### ISSUE TITLE
Considerable amount of GRPC error details can trigger ingress response header limit

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#11284]
**Description**

In cases, like an invalid bpmn model, a considerable number of errors can occur. These are passed back to the client via the `grpc-status-details-bin` HTTP header, [see](https://groups.google.com/g/grpc-io/c/ZA2i0lhCBO4).
In cases where Zeebe is accessed through a reverse proxy/ingress like nginx, this behavior can exceed response header limits of the proxy, resulting in error logs as:
```
[error] 2243#2243: *1868588 upstream sent too big header while reading response header from upstream
```
leading to a 502 response to the client by the proxy.

We may consider limiting the amount of error details returned to e.g. a limit of 5 entries, followed by a summary error entry if there are more errors "and N more errors". This would allow to still enforce a response header limit on any client facing proxy while making sure the client still gets back useful information to actually fix the model errors, no matter how much errors they provoked.

[SUPPORT-15410](https://jira.camunda.com/browse/SUPPORT-15410)

```[tasklist]
### Task List
- [ ] https://github.com/camunda/camunda-bpm-platform/issues/4443
- [ ] https://github.com/camunda/camunda/issues/19595
- [ ] https://github.com/camunda/camunda/issues/19591
- [ ] https://github.com/camunda/camunda/issues/19829
```

**Comment by Zelldon** [comment]
See related discussion and investigation in slack https://camunda.slack.com/archives/CT702EPFH/p1671124412586789

**Comment by korthout** [comment]
@megglos Can you clarify for us what the chances are of running into this situation? And what is the impact? Does the user receive a response at all?

**Comment by megglos** [comment]
@jfriedenstab 300 out of how many total deployment requests? 🤓 

Would you consider a truncated error like suggested here
> We may consider limiting the amount of error details returned to e.g. a limit of 5 entries, followed by a summary error entry if there are more errors "and N more errors"
would be a good solution to educate the user about the modeling errors in the model?

The user may at least be aware of some specific errors and once resolved may learn about the next remaining ones. On the other hand wouldn't it be better to raise those issues directly in the modeler via validation to provide more helpful errors direct in the modeler (e.g on the affected elements)? If I'm no mistaken we have such validation already and I wonder how users can deploy invalid models from the modeler still 🤔

**Comment by jfriedenstab** [comment]
Thanks a lot for your quick reply, @megglos!

> 300 out of how many total deployment requests? 🤓

I can't tell you the total number of requests in the 90-day period, but in the last 24 hours alone there were ~1200 deployment requests. Ok, so the ratio of requests that failed with the `502` error is pretty small 😊.

> Would you consider a truncated error like suggested here would be a good solution?

Yes, I'd say it's a good solution 👍🏻.

> Wouldn't it be better to raise those issues directly in the modeler via validation to provide more helpful errors directly in the modeler (e.g on the affected elements)?

I agree that, ideally, we would already show the user all the model errors before they try to deploy. However, I think the linting/validation rules that are in place are not able to catch all the possible error cases. So, some errors would only be detected when the model is actually deployed.

> I wonder how users can deploy invalid models from the modeler still 🤔

True, we could prevent deployments if the linting detects errors. If I remember correctly though, we took a conscious decision a while ago to allow deployments anyway (sorry, I don't recall the details).

Anyway, models can also be deployed from outside the Web Modeler (via `zbctl`, etc.). So it would probably make sense to return a more helpful error message for these scenarios, too.

**Comment by jfriedenstab** [comment]
Hi @megglos,
Just a friendly reminder about this issue 🙂.
FYI: It might occur more often in Web Modeler when we release [process applications](https://github.com/camunda/product-hub/issues/1983) (if there are are multiple invalid files in a deployment bundle).

**Comment by korthout** [comment]
Thanks @jfriedenstab. I've moved it back into our inbox for triage. 

As I understand, the problem leads to errors in the reverse proxy **and** the client not receiving the error response. That sounds like a bug to me. It's also high severity as there is no workaround available. 

I find it difficult to specify a likelihood for this.

**Comment by jfriedenstab** [comment]
Thank you @korthout!

FYI: The Zeebe Java client will receive the following error response:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 502
invalid content-type: text/html
headers: Metadata(:status=502,date=Wed, 28 Feb 2024 23:11:02 GMT,content-type=text/html,strict-transport-security=max-age=63072000; includeSubDomains,content-length=150)
DATA-----------------------------
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Regarding the likelihood: The problem seems to occur regularly. Sentry (that we use for error tracking in Web Modeler) recorded 433 events from 75 different users over the last 90 days.

**Comment by jfriedenstab** [comment]
> would be worth to check if there is some other way to transmission the error but we can consider that out of scope

Maybe something to consider for the future when you add a deploy endpoint to the C8/Zeebe REST API (getting the errors back in a more structured format would also be nice) 🙃.

**Comment by mustafadagher** [comment]
Just to be sure, for this bug fix, do we want to only truncate BPMN Model validation errors (since I see this was the main cause for this bug), or do we need to truncate all grpc errors in general?

**Comment by korthout** [comment]
>do we want to only truncate BPMN Model validation errors [..] or do we need to truncate all grpc errors in general?

@mustafadagher I'd prefer a general solution over a specific one.

However, it's not entirely clear to me whether the validation errors are stored as separate grpc errors, or formatted as a single string which just becomes too long. I was thinking the prior when reading the issue description, but don't know how that's supposed to work. As far as I know, we simply format a string.

If possible, let's find a way to limit all grpc errors to a max of 5 + `and N more errors`. If not, let's just truncate the string at the validators

**Comment by mustafadagher** [comment]
> However, it's not entirely clear to me whether the validation errors are stored as separate grpc errors, or formatted as a single string which just becomes too long. I was thinking the prior when reading the issue description, but don't know how that's supposed to work. As far as I know, we simply format a string.

According to my investigation so far:
In the `BpmnValidator.validate()`, we walk what we call `designTimeAspectValidator` and `runtimeAspectValidator` over a `modelInstance`.  Each returns some `ValidationResults` which basically contains a Map of [Model Element, List Of validation errors]. The `ValidationResults` instances also contain the total error count.

We then use a formatter `ValidationErrorFormatter` to write these results into one string error.

So if we are only concerned about the validation errors, we could limit it there and then (when writing it to a the single string).


> If possible, let's find a way to limit all grpc errors to a max of 5 + and N more errors. If not, let's just truncate the string at the validators

I think the generic grpc error handling happens in `GrpcErrorMapper.mapErrorToStatus()`, if that's right. Then we have a problem there, that the error message is already a `string`, it appears right now difficult how to determine where to make the cut, and how many errors did we omit without creating a convoluted error-prone logic.

**Comment by mustafadagher** [comment]
As a followup question, if we are going to go ahead and solve it at `BpmnValidator.validate()` as I suggested:

As I mentioned in the comment above, there are two types of validators there: `designTimeAspectValidator`, and `runtimeAspectValidator`. Each returns it's own list of errors.

If we have to limit the errors to 5 only (or another configurable number). Which one do we truncate? or basically, which one has a higher value/priority and we should try to send it back complete.

If I use my intuition, I notice that we print the `Design Time` errors before the `Runtime` ones. So I'd assume we should give higher priority to the design time errors.

@korthout I'd appreciate your input on the this comment and the one above! 🫶

**Comment by mustafadagher** [comment]
I was looking into what could be a systematic way to solve this issue, I looked into different solutions and several different direction, from `moving the errors to the headers to the response body`, `compressing server responses and decompressing at the client`, `truncating all error messages to a fixed configurable length`, and others. 

But I think the best, and the most effective solution for this problem is actually at the `NGINX configuration`. I believe the best way to address this issue is to increase the NGINX `proxy_buffer_size` and the buffer number at `proxy_buffers`, and optionally also the `proxy_busy_buffers_size`. 

Here is a reference on how to find and set the correct buffer values at the end of [this article](https://www.cyberciti.biz/faq/nginx-upstream-sent-too-big-header-while-reading-response-header-from-upstream/). If we use NGINX as an ingress controller in k8s, here's [a reference](https://ambidextrous-dev.medium.com/nginx-error-upstream-sent-too-big-header-2e16c34e08) on where to change these configs there too .

**Comment by korthout** [comment]
> But I think the best, and the most effective solution for this problem is actually at the `NGINX configuration`. I believe the best way to address this issue is to increase the NGINX `proxy_buffer_size` and the buffer number at `proxy_buffers`, and optionally also the `proxy_busy_buffers_size`.

That's a good solution for Self-Managed users that encounter this problem in the future. Do note that it does not come for free. It requires more memory for NGINX, and I imagine it could also introduce some performance drawbacks for NGINX (although that's probably negligible for Zeebe).

I still think that truncating the our error message to a maximum of 5 errors makes sense. @mustafadagher What do you think?

**Comment by mustafadagher** [comment]
> That's a good solution for Self-Managed users that encounter this problem in the future. Do note that it does not come for free. It requires more memory for NGINX, and I imagine it could also introduce some performance drawbacks for NGINX (although that's probably negligible for Zeebe).

@korthout I think the possible drawbacks from increasing these buffers are higher memory usage and the potential for resource contention if we are not careful with them. It can also impact latency in some cases if they were **too large**. That's why I referred to an article on how to find out the correct sizes to set, and we should also use proper monitoring for memory usage and performance metrics for our servers to ensure the changes are beneficial.

But to the contrary, increasing them can actually lead to performance improvements, especially for handling large responses, and reduced disk i/o.

**Comment by mustafadagher** [comment]
I was looking into implementing the solution to resolve the symptom originating from validation errors, I checked out [camunda-bpm-platform](https://github.com/camunda/camunda-bpm-platform) and started looking into possible changes there to extend the `ValidationResults.write()` with an option to limit the printed output, and I have a couple of observations and open questions.
1. In `ValidationResults.write()`: it doesn't only write the **errors** to the output writer, but it also writes **warnings**
2. The initial intuition was to limit the output to a certain number of errors, but on a second thought 5 error messages in some case could be larger than 15 in another. So limiting by the number of errors is not deterministic, but rather with a `max size (bytes)`.
3. If we extend (or overload) the current `write` method with a max size, we would also need to know how many errors did it write before reaching this max size, so we might need to return this number in the return value. which is not too bad, but not too fluent either.
4. I iterated over this before, but again in the `BpmnValidator` we first write the `designTimeAspectValidator` **errors** (and **warnings**) then the `runtimeAspectValidator`'s. In a case where we are limiting the output, I'd say all **errors** have more priority than all **warnings**. Should we then provide a constructor that would take two validation results and combine them? Should we also then pass a `sorting` (or priority) flag too to resort the collected results?
5. if we agreed on all the above suggestions, and we adopted that implementation, then remains the question of what would be a good value for `maxSize`? we should definitely make it configurable then, but we should also come up with a good default value. any suggestions?

CC: @korthout

**Comment by korthout** [comment]
@mustafadagher Let's avoid expanding scope with priority sorting of errors and warnings. Instead:
- allow specifying a max validation results size in bytes by overloading the `ValidationResultsCollectorImpl` constructor, by default it's not set and unused
- if set, only allow adding errors and warnings up to the max validation results size
- keep track of the number of errors and warning that don't fit anymore
- add something like `and N more errors and/or warnings` at the end

We should try to stay pragmatic for defaults. Let's look at some online resources:

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md:
>Clients may limit the size of Response-Headers, Trailers, and Trailers-Only, with a default of 8 KiB each suggested.

https://stackoverflow.com/a/8623061/3442860:
> As vartec says above, the HTTP spec does not define a limit, however many servers do by default. This means, **practically speaking, the lower limit is 8K**. For most servers, this limit applies to the sum of the request line and ALL header fields (so keep your cookies short).
>
> - Apache [2.0](http://httpd.apache.org/docs/2.0/mod/core.html#limitrequestfieldsize), [2.2](http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestfieldsize): 8K
> - [nginx](http://nginx.org/r/large_client_header_buffers): 4K - 8K
> - IIS: [varies by version](https://stackoverflow.com/a/6160643/92629), 8K - 16K
> - Tomcat: [varies by version](https://stackoverflow.com/a/6160643/92629), 8K - 48K (?!)
> 
> It's worth noting that **nginx uses the system page size by default, which is 4K on most systems**. [..]

- Let's just consider that the most common lower limit is 4K.
- Let's simply take half of this as the max validation results size: 2K.
- Let's try it out and see what happens when using the example process model to see if that default makes sense
- If the default makes sense in general, let's postpone making it configurable until users request it

**Comment by mustafadagher** [comment]
> I was looking into what could be a systematic way to solve this issue, I looked into different solutions and several different direction, from `moving the errors to the headers to the response body`, `compressing server responses and decompressing at the client`, `truncating all error messages to a fixed configurable length`, and others.
> 
> But I think the best, and the most effective solution for this problem is actually at the `NGINX configuration`. I believe the best way to address this issue is to increase the NGINX `proxy_buffer_size` and the buffer number at `proxy_buffers`, and optionally also the `proxy_busy_buffers_size`.
> 
> Here is a reference on how to find and set the correct buffer values at the end of [this article](https://www.cyberciti.biz/faq/nginx-upstream-sent-too-big-header-while-reading-response-header-from-upstream/). If we use NGINX as an ingress controller in k8s, here's [a reference](https://ambidextrous-dev.medium.com/nginx-error-upstream-sent-too-big-header-2e16c34e08) on where to change these configs there too .

Regarding the suggestion to change the `nginx proxy buffer size`, @aabouzaid has guided me that in SM the configuration is set to `128k` [here](https://github.com/camunda/camunda-platform-helm/blob/fc79bdbc70475e19a22d9f7b24e11c036cea6be8/charts/camunda-platform-latest/values.yaml#L1120).

@camunda/sre @camunda/web-modeler-cawemo-backend @camunda/connectors-dev would you guys know where do we configure the same value for SaaS and Web Modeler? And Could we maybe match the same value we have for SM there too?

Thanks!

**Comment by wollefitz** [comment]
@mustafadagher The ingress configuration for Web Modeler SaaS is located here: 
* https://github.com/camunda/web-modeler/blob/809855747b89e28865bcd986855eb80ddac9c5a8/.ci/deploy/base/modeler/webapp/ingress.yml
* https://github.com/camunda-cloud/ingress-nginx-deployment/blob/9ce98e2e2f9a86e9243c6e92385cec4763c3af55/ingress-nginx/helm-values.yaml#L136

**Comment by thomas-polnik** [comment]
@wollefitz 
> * [camunda/web-modeler@`8098557`/.ci/deploy/base/modeler/webapp/ingress.yml](https://github.com/camunda/web-modeler/blob/809855747b89e28865bcd986855eb80ddac9c5a8/.ci/deploy/base/modeler/webapp/ingress.yml)
> * [camunda-cloud/ingress-nginx-deployment@`9ce98e2`/ingress-nginx/helm-values.yaml#L136](https://github.com/camunda-cloud/ingress-nginx-deployment/blob/9ce98e2e2f9a86e9243c6e92385cec4763c3af55/ingress-nginx/helm-values.yaml#L136)

I would not set the default value `proxy-buffer-size: 128k` because, as I said, it can have an effect on the memory consumption of nginx. So I would only set this higher `proxy-buffer-size` for services that need it.

@wollefitz will you change it for modeler? (In the past your team and and @camunda/sre worked together to setup k8s resources for modeler.)

**Comment by wollefitz** [comment]
> @wollefitz will you change it for modeler? (In the past your team and and @camunda/sre worked together to setup k8s resources for modeler.)

Deployments from Web Modeler are done via an outgoing request from the `restapi` pod to Zeebe directly without any ingress involved on the Web Modeler side - thus I don't think it is necessary to adjust anything in Web Modeler, but please do double-check and correct me if I'm wrong.

**Comment by mustafadagher** [comment]
> > @wollefitz will you change it for modeler? (In the past your team and and @camunda/sre worked together to setup k8s resources for modeler.)
> 
> Deployments from Web Modeler are done via an outgoing request from the `restapi` pod to Zeebe directly without any ingress involved on the Web Modeler side - thus I don't think it is necessary to adjust anything in Web Modeler, but please do double-check and correct me if I'm wrong.

Hi @wollefitz I was thinking the same too actually on Friday, and that's why I opened a PR to adjust zeebe's configs on camunda-operator but not for web-modeler. I think we don't need to change anything for web-modeler for now!

Thank you 🙏

**Comment by koevskinikola** [comment]
Blocked until the C7 team releases the fixed code.

**Comment by mustafadagher** [comment]
@jfriedenstab @wollefitz Zeebe's `proxy-buffer-size` change to `128k` (https://github.com/camunda-cloud/camunda-operator/pull/3011) has been deployed on dev. 

@jfriedenstab let us know if you can test the same use case on dev, and if you can still see failures.

Deployments of the change on other environments will follow, and is managed by `controller` team.

**Comment by mustafadagher** [comment]
During testing the changes from https://github.com/camunda-cloud/camunda-operator/pull/3011, we figured out they don't work as expected. 

After a live troubleshooting session with @thomas-polnik and @jfriedenstab, we found out that 
[Based on this documentation](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource), changing proxy-buffer-size will set grpc_buffer_size to the same size, but it is not done.

[Based on this issue](https://github.com/kubernetes/ingress-nginx/issues/9363), we have to set a dedicated value for grpc_buffer_size.

@thomas-polnik opened a PR with the changes here https://github.com/camunda-cloud/camunda-operator/pull/3025

Yet during testing, we found out that when we increased the number of errors in the model even more, we started to see a different error `http2 exception` thrown from zeebe-client.

With more investigation, it turns out that `zeebe-client` doesn't set a value for `maxInboundMetadataSize` when building the channel ([here](https://github.com/camunda/camunda/blob/a5a1003acfbe210482b38eea445d880f3f0023f6/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientImpl.java#L185)).
The default value for this config is `8kb`

I'm looking making this value configurable too for zeebe's java client
