### ISSUE TITLE
[EPIC] Start new process instances for top-level conditional start events

### ISSUE THREAD

**Issue by lzgabel** [camunda/camunda#11341]
This is stage 1 of the umbrella epic:

* #11217

## Introduction
It will be possible for users to evaluate start conditions using the gRPC API, starting new process instances for the processes that have top-level conditional start events.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/24605947/209554901-89535de7-1ef4-4acd-a6c1-620263f0dfd9.png">

`Condition Evaluation` arriving in the gateway must be written to a partition leader. The partition leader needs to start instances for each top-level conditional start event if a given condition is evaluated to `true`. 

A process is subscribed to a condition using a new `ConditionalSubscription` record

## Concept

A `conditional start event` can be used to start a process by evaluating some condition. One process can have one or more conditional start events. The condition expression of a `conditional start event` must refer to the static variables provide by the client (as the process instance has not yet been created). 

If more than one conditions are satisfied, the respective number of processes will be triggered.

When deploying a process definition with conditional start events, the following considerations apply:

* The condition of a conditional start event must be unique within a given process definition, i.e. a process definition cannot have multiple conditional start events with the same condition. If two or more conditional start events contain the same condition, the engine will reject the deployment process definition.
* Process versioning: Upon deployment of a new version of a process definition, the conditional subscriptions of the previous version are cancelled. This is also the case for conditional events that are not present in the new version.

### Broker
* [ ] Create `ConditionalSubscription` and `ConditionalSubscriptionIntent`
  *  Introduce new `ConditionalSubscription` records, with intents: `CREATED`, `DELETED`
      The conditional subscription record value should consist of:
      * `bpmnProcessId` - The id of the process in the bpmn model
      * `processDefinitionKey` - The key of the deployed process
      * `catchEventId` - The id of the conditional catch event
      * `catchEventInstanceKey` - The key of the conditional catch event instance (optional)
      * `condition` - The condition of the conditional catch event

* [ ] Subscribe processes with top-level conditional start events
   * Adjust the `DeploymentCreateProcessor` to subscribe to new top-level conditional start events
      * If the deployed process contains a top-level conditional start event:
          * Write `ConditionalSubscription:CREATED`
             * Event applier for `ConditionalSubscription:CREATED` puts subscription in `DbConditionalSubscriptionState`
             * `DbConditionalSubscriptionState` should have methods:
                *  `visitStartEventSubscriptions` (only visits all the subscriptions for top-level start events)
                * `visitStartEventSubscriptionsByProcessDefinitionKey` (only visits the subscriptions for top-level start events)
                * `visitByElementInstanceKey` (only visits the subscriptions for catch events existing in process instances) 
   * Don't allow top-level conditional start events to act as none start event
      * Change `ExecutableCatchEvent.isNone()` implementation
         * Requires adjustment of `CatchEventTransformer` to transform conditional catch events

* [ ] Unsubscribe older versions of processes when a new version is deployed
   * Adjust the `DeploymentCreateProcessor` to unsubscribe for conditional of the previous version of the deployed process
      * uses `DbConditionalSubscriptionState.visitStartEventSubscriptionsByProcessDefinitionKey`  to find these subscriptions (only the ones for top-level start events should be used)
      * Write `ConditionalSubscription:DELETED` 
         * Event applier for ConditionalSubscription:DELETED removes the subscription from DbConditionalSubscriptionState

### Gateway API

* [ ] Create `ConditionEvaluationRecord` and `ConditionEvaluationIntent`
   * Introduce new `ConditionEvaluationRecord` records, with intents: `Evaluate`, `Failed`, `Evaluated`
     * The record value should consist of:
        * optionally `processDefinitionKey`: The key of the process definition to correlate on.
        * optionally variables: Pass variables to the condition.
* [ ] Introduce new `ConditionEvaluation:Evaluate` command processor
   * Writes a `ConditionEvaluation:Evaluate` event indicating that the command was processed successfully, otherwise the command is rejected.
   * If the specified `processDefinitionKey` is provided, For each `ConditionalSubscription` matching the `processDefinitionKey`, uses `DbConditionalSubscriptionState.visitStartEventSubscriptionsByProcessDefinitionKey`
     * If related catch event is a top-level start event and the condition is evaluated to `true`:
        * Start an instance of the latest version of the process defined by `bpmnProcessId`, at start event `catchEventId`
   * If no `processDefinitionKey` is provided, for each `ConditionalSubscription`, uses `DbConditionalSubscriptionState.visitStartEventSubscriptions`
     * If related catch event is a top-level start event and the condition is evaluated to `true`:
        * Start an instance of the latest version of the process defined by `bpmnProcessId`, at start event `catchEventId`

* [ ] Condition Evaluation using the gRPC API
   * The RPC takes a message containing:
      * optionally `processDefinitionKey`: The key of the process definition to correlate on.
      * optionally variables: Pass variables to the condition.
   * Implementation should write a `ConditionEvaluation:Evaluate` command to the deployment partition leader

### Exporters and Metrics

* [ ] Export `ConditionalSubscription` records to ElasticSearch

### Zeebe Process Test
* [ ] New value type logger defined for value type `CONDITIONAL_SUBSCRIPTION`

### Documentation

* [ ] Document top-level conditional start events

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links
- Camunda 7 documentation: [conditional-start-event](https://docs.camunda.org/manual/7.18/reference/bpmn20/events/conditional-events/#conditional-start-event)

- Product Hub (internal):

**Comment by remcowesterhoud** [comment]
Hi @lzgabel! Thanks for your patience. I will have a look at this next week 🙂

**Comment by remcowesterhoud** [comment]
Thanks @lzgabel 🚀 Here is my first round of feedback.

 I suppose my first question is why you decided to start with the top-level start event. I feel like it's the more complex part of the epic, yet also provides the least value. Maybe I misunderstand the use case but from my understanding:

1. User has some set of variables
2. User sends a command with these variables
3. Zeebe decides whether or not it has to create a process instance

Whereas without this it would be:
1. User has some set of variables
2. User uses these variables to decide whether or not it should send a create process instance command
3. Zeebe doesn't have to do any processing if the condition doesn't match

Both ways have pros and cons of course and I do think it's nice to support this event. But I can't help but feel user problems could be solved with the regular catch events.

---------------------------

I think your breakdown is pretty good so far. I would like to see it more broken down as atomic issues as opposed to how it is currently. For example you currently have `Subscribe processes with top-level conditional start events` as a single item. Looking at all the sub-items this could easily be split in a bunch of separate issues such as:
- Create the state
- Handle the created event
- etc.

Maybe this is what you were planning but it wasn't clear to me so I wanted to write it down to be sure. Having these things as separate issues makes for smaller PRs which will be easier to review.

-----------------------------

> Create ConditionEvaluationRecord and ConditionEvaluationIntent

I think we should carefully consider the naming we use here. This is the record for the subscription of the top-level start event. I believe the other conditional events will also require subscriptions, but they don't need the same data. It's a very similar scenario to message subscriptions. How are you planning to name the other record?

-------------------------------

> DbConditionalSubscriptionState should have methods:
> - visitStartEventSubscriptions (only visits all the subscriptions for top-level start events)
> - visitStartEventSubscriptionsByProcessDefinitionKey (only visits the subscriptions for top-level start events)
> - visitByElementInstanceKey (only visits the subscriptions for catch events existing in process instances)

Why do we need these methods? In what scenario we need to visit all the start event subscriptions? From your explanation I understand that we always have the process definition key available. Is there any reason to have the methods other than the one to visit the subscriptions by process definition key?

---------------------------------

> Introduce new ConditionEvaluationRecord records, with intents: Evaluate, Failed, Evaluated
> The record value should consist of:
> - optionally processDefinitionKey: The key of the process definition to correlate on.
> - optionally variables: Pass variables to the condition.

You mention the `processDefinitionKey` is optional. Why is this? If we don't have this available how do we know which conditional events we must evaluate? Did you consider using the process id instead of the definition key?

💭 Just some random thoughts here. With create process instance we have a way to start instances of a previous version. Did you consider allowing this here? This would be difficult with the subscriptions. I'm not sure how we do this with message start events currently.

You mention variables are optional. I don't see a case where can evaluate an expression without passing variables, unless the expression only contains static values. This doesn't seem sensible to me and I feel we shouldn't allow this.

-----------------------------------

> Implementation should write a ConditionEvaluation:Evaluate command to the deployment partition leader

Could you explain how this would work with multiple partitions? The evaluate command is written on the partition leader. Is this required or could we also distribute these fairly amongst the partitions? Where will the subscriptions be created? On all partitions, or just the deployment partition?

**Comment by lzgabel** [comment]
Hi @remcowesterhoud. Thanks a lot for the feedback. :heart:

> I suppose my first question is why you decided to start with the top-level start event. I feel like it's the more complex part of the epic, yet also provides the least value.

Yes. Due to recent work reasons, it was not possible to completely disassemble this epic. Just done the `conditional start event part` so far, so I may not realize it's more complex than the other events and provides the least value.

---
> >Create ConditionEvaluationRecord and ConditionEvaluationIntent
>
> I think we should carefully consider the naming we use here. This is the record for the subscription of the top-level start event. I believe the other conditional events will also require subscriptions, but they don't need the same data. It's a very similar scenario to message subscriptions. How are you planning to name the other record?

❓ Let's rename it to `ConditionalStartEventEvaluationRecord` and `ConditionalStartEventEvaluationIntent`. 

WDYT?

---

> > DbConditionalSubscriptionState should have methods:
          visitStartEventSubscriptions (only visits all the subscriptions for top-level start events)
          visitStartEventSubscriptionsByProcessDefinitionKey (only visits the subscriptions for top-level start events)
          visitByElementInstanceKey (only visits the subscriptions for catch events existing in process instances)
>
> Why do we need these methods? In what scenario we need to visit all the start event subscriptions? From your explanation I understand that we always have the process definition key available. Is there any reason to have the methods other than the one to visit the subscriptions by process definition key?

Let me explain the usage scenarios of the respective methods：

* `visitStartEventSubscriptions` (only visits all the subscriptions for top-level start events)
  * When I deploy multiple process definitions with conditional start events, I hope to create corresponding process instances according to the evaluation variables. There may be one process definition evaluation result that is true, or there may be multiple. Of course, this behavior is more consistent with C7. For details, see: [#conditional-start-event](https://docs.camunda.org/manual/7.18/reference/bpmn20/events/conditional-events/#conditional-start-event)
 
* `visitStartEventSubscriptionsByProcessDefinitionKey`
   * After your explanation, I realized that currently it is supported to get the last process definition by process id to create an instance, so I thought to rename it to `visitStartEventSubscriptionsByBpmnProcessId`. WDYT?
   
*  `visitByElementInstanceKey`
   *  This method will not be used for now, let's exclude it from this scope


---
> > Introduce new ConditionEvaluationRecord records, with intents: Evaluate, Failed, Evaluated
  The record value should consist of:
  optionally processDefinitionKey: The key of the process definition to correlate on.
  optionally variables: Pass variables to the condition.
>
> You mention the processDefinitionKey is optional. Why is this? If we don't have this available how do we know which conditional events we must evaluate? Did you consider using the process id instead of the definition key?

As described above:
> When I deploy multiple process definitions with conditional start events, I hope to create corresponding process instances according to the evaluation variables. There may be one process definition evaluation result that is true, or there may be multiple. Of course, this behavior is more consistent with C7. For details, see: [#conditional-start-event](https://docs.camunda.org/manual/7.18/reference/bpmn20/events/conditional-events/#conditional-start-event)


> I don't see a case where can evaluate an expression without passing variables, unless the expression only contains static values. This doesn't seem sensible to me and I feel we shouldn't allow this.

Yes. At first, I envisioned allowing some static expression to be provided, e.g. : `= true`. 
For now, it doesn't make much sense, let's make it required.


Based on the above information, modify it as follows:

Introduce new `ConditionalStartEventEvaluationRecord` records, with intents: `Evaluate`, `Failed`, `Evaluated`
  * The record value should consist of:
    * optionally bpmnProcessId: The ID of the process definition to correlate on.
    * variables: Pass variables to the condition.

----

> > Implementation should write a ConditionEvaluation:Evaluate command to the deployment partition leader
>
> Could you explain how this would work with multiple partitions? The evaluate command is written on the partition leader. Is this required or could we also distribute these fairly amongst the partitions? Where will the subscriptions be created? On all partitions, or just the deployment partition?

After writing the evaluation command on the partition leader, I think we can distribute it as a generic record on top of this epic([Generalized record distribution](https://github.com/camunda/zeebe/issues/11456)). @korthout Please correct me if I understand it wrong.

**Comment by remcowesterhoud** [comment]
Hey @lzgabel, thanks for answering my questions!

> Let's rename it to ConditionalStartEventEvaluationRecord and ConditionalStartEventEvaluationIntent.

Sounds good 👍 

> visitStartEventSubscriptions (only visits all the subscriptions for top-level start events)
>
> When I deploy multiple process definitions with conditional start events, I hope to create corresponding process instances according to the evaluation variables. There may be one process definition evaluation result that is true, or there may be multiple. Of course, this behavior is more consistent with C7. For details, see: [#conditional-start-event](https://docs.camunda.org/manual/7.18/reference/bpmn20/events/conditional-events/#conditional-start-event)

I'm still a bit confused here. Could you explain the flow to me? The way I understand it now:

1. User sends command to gateway
2. Command is mapped to a `ConditionalStartEventEvaluationRecord` with the intent `EVALUATE`
3. What does this command processor do? Will it visit all the start event subscriptions and evaluate them? Writing another `ConditionalStartEventEvaluationRecord` where the `processDefinitionKey` is filled with the `EVALUATED/FAILED` intent?

I have some concerns about step 3 if that's the way it's supposed to work. First of all it takes a `processDefinitionKey`, but a single definition could contain multiple conditional start events. How will it work in this case? We don't know which start event is the one that should be triggered.
Another one is that I feel like it might have a significant performance impact to evaluate all of the conditional start events available. I don't have a better solution for this yet, because I think this is how conditional start events are supposed to work.

> Yes. At first, I envisioned allowing some static expression to be provided, e.g. : = true.
For now, it doesn't make much sense, let's make it required.

👍 

> Currently, I see that all process instance creation commands are created on the partition leader, so I might be more inclined to write commands to the partition leader. Of course, I believe your opinion is more professional.

Ignore this one, this was a stupid question from my side 🤦  It of course must be on the partition leader. For some reason I was thinking it would always go to the same partition instead of being distributed fairly amongst them. But it does get fairly distributed amongst all partition leaders.

--------------------------

Great work so far @lzgabel! We really appreciate your contributions.

This being said I do want to make you aware that we are not prioritising this feature at this moment. Release 8.2 is coming up and we have a bunch of topics that we still need to finish (e.g. generalised record distribution, resource deletion, performance increases). We need to focus on these topics to prevent having to release partly-completed functionalities. We want to prevent adding this one, because we don't see this being completed on time for the 8.2 release, and to allow the team to focus on the topics we have going on already.

I saw that you already proposed working on the signal events as @skayliu doesn't have the time for this currently. Since this is currently also a partly done feature it would be great if you'd shift your focus to that topic instead of this one!

Let me know if you have any questions about this 🙂

**Comment by lzgabel** [comment]
> Since this is currently also a partly done feature it would be great if you'd shift your focus to that topic instead of this one!

@remcowesterhoud. Thanks for your reply, since the breakdown of conditional events is not ready yet, and release 8.2 is coming up, I will shift the focus to the singal events, let's put this epic on hold for now. ❤️
