### ISSUE TITLE
[EPIC]: Run dry releases as medic

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#11361]
<sup>split of https://github.com/camunda/zeebe/issues/10651</sup>

blocked by https://github.com/camunda/zeebe/issues/10992

- [ ] Run dry releases as medic (may require changes, thus depends on GHA migration)
  - [ ] Every week when the medic set ups a benchmark he can use the release workflow to build the related images etc. This makes sure that the pipeline still works.
    - [ ] Release are not public available, just for internal usage
    - [ ] Release to gcr.io
    - [ ] Close maven artifacts
  - [ ] Use the built images as medic benchmarks
  - [ ] Run E2E tests against "pre-releases"
