### ISSUE TITLE
[EPIC] Rewrite zbctl in JVM-language

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#12523]
## Introduction

`zbctl` is a command-line tool to interact with Zeebe from a shell easily. It is often used by the teams developing Zeebe to try out new features or to set up scenarios for manual testing. It is written in Go using the Zeebe Go Client, but the team members maintaining it are not experts in Go. This is visible in the [number of open issues](https://github.com/camunda/zeebe/issues?q=is%3Aopen+is%3Aissue+label%3Ascope%2Fclients-go) for the Go client.

To improve our ability to maintain this tool and continue to enhance it, we propose to rewrite it in a language that the team is more familiar with. The team is experienced in Java, Scala, and Kotlin. Several mechanisms are available to produce native binaries using such languages, e.g. GraalVM or Kotlin Native.

## Concept

TBD

## Task Breakdown

TBD

### Main Tasks

TBD

### Testing

TBD

### Documentation

TBD

### Out of scope

TBD

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

### GraalVM, Kotlin Native, or other

> **Note** This discussion is still open.

We need to decide what we could support best.

- If we were to go for GraalVM, it would require us to make the Zeebe Java Client compatible with GraalVM. This could enable other users to embed this client into their GraalVM projects.
- ..

### Performance

> **Note** This discussion is still open.

There is likely a performance reduction in a JVM-language native binary compared to a native binary produced from Go. We must consider whether this is relevant for `zbctl`'s use cases.

## Links

- Product Hub (internal): ..

**Comment by npepinpe** [comment]
Is this happening? :O

Just asking, because I have a branch already with a native image of zbctl which can only do Topology requests, but still :eyes:

**Comment by korthout** [comment]
We were planning to work on this first:
- https://github.com/camunda/zeebe/issues/12524

But I do think we want to explore this. So if you want to share your work so far, then that could be helpful 🙇
