### ISSUE TITLE
[EPIC] Complex Process Definition Deletion

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#13979]
## Concept

**Running process instances**
As of now users cannot delete process definitions when there are running process instances. In order to support we must add a way to asynchronously terminate process instances. We must also add a callback to finalise the deletion once all running instance have completed/terminated.

<img width="1316" alt="image" src="https://github.com/camunda/zeebe/assets/5787702/425067d3-d524-43fe-a6ef-fb00f4e67d56">

The image above shows how this would work. It all starts when a `Resource.DELETE` command is received. The `ResourceDeletionProcessor` will process this command. At the moment it will check for running instances. If there is any it reject the command. This needs to be changed.

When a users makes the request we should give them an option what they want to do with running instances:

- Wait for completion
    - Upon receiving the command we won't do anything with the running instances. We will mark the process definition as `PENDING_DELETION`. The terminate/complete callbacks will detect when the last running instance reached an end state and delete the process definition.
- Terminate them
    - Upon receiving the command we will find running instances and send a `TERMINATE` command for each of them. This has to be happen in a batch-like manner, similar to termination of child instances of a process instance. Similar to waiting for completion the callbacks will detect when the last running instance has reached an end state and delete the process definition.
- Abort the delete
    - We reject the command like we already do.

**Reactivation of timers/messages/signals**
As of now when deleting the latest version of a process definition, the previous known version becomes the new latest. This means we reactivate timer/message/signal start events. We should consider allowing users to set a flag if they want to reactivate the previous version. Why is this relevant?

One of the use-cases to delete a process definition is to stop timer start events. It's not unlikely that previous versions of the same process also contain a timer start event. Reactivating this version might not be the intended behaviour for the user, as the timers for this process definition start triggering. By allowing users to specify if they want reactivation we can prevent this from happening.

### Broker

> [!NOTE]
>  This task breakdown is not complete. The tasks that exist are tasks that were out of scope for #9576 

### Broker
- [ ] #13587
- [ ] #9795
- [ ] #9797 
- [ ] #13352 
- [ ] #13353 
- [ ] #13355 

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1504
- Resource definition deletion : https://github.com/camunda/zeebe/issues/9576
