### ISSUE TITLE
[EPIC] Enable Zeebe to support 2-region deployment with disaster recovery

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#16126]
Product hub Epic: https://github.com/camunda/product-hub/issues/1963 

# Description

By default Zeebe can support 3 or more regions (assuming partition distribution ensures each partition has replica in 3 regions). When one regions is down, Zeebe can work with the other two regions because Raft needs 2 replicas as the quorum. However, we have customers who want to deploy Zeebe (and Camunda 8 cluster) in **two regions** because they have only two data centers available. Adding one more region is not feasible due to cost or organizational policies. However, they still want to ensure that if one regions fails, they can work with the surviving region, with no loss of data. High availability is not possible like in 3 regions, but with manual intervention and with a bit of down time the surviving region should be equipped to continue processing with out any dataloss. 

Our proposal for Zeebe deployment is as follows:
* Set replication factor to 4
* Use a multiple of 4 as the clusterSize
* Deploy brokers with odd brokerIds in one region, and deploy brokers with even brokerIds in the other region. (Support for this will be added to our helm chart).
* When following the above scheme, the default round-robin scheme ensures that for each region has two replicas of each partition. Thus the quorum (3 out of 4) should always contains atleast one broker from each region ensuring that when one region is lost, the other region has atleast one replica (for each partition) with the latest data.

Given the above conditions, we want to provide a way to resume processing with only the surviving region. 

### Goals:
* Recovery Point Objective (RPO) = 0. No data is lost due to the disaster of one region.
* Recovery Time Objective (RTO) >= 0. Zero disruption is not feasible, but the cluster should be available with in a reasonable period of time after the failure is detected manually.
* Adding necessary features to support this in Camunda 8 cluster with all other components. 

### Out of scope
* Automatic detection of region failure and failover to surviving region.
* Performance improvements to work with higher latency between regions.

More details about the proposed solution for C8 
* [Proposed architecture (internal)](https://docs.google.com/document/d/1wa84HrUxYZ087klgy8iJYIU-sjmrimyfeuz8ox2iWdc/edit#bookmark=id.vse2tbk0smdc)
* [Operational procedure during disaster recovery (internal)](https://docs.google.com/spreadsheets/d/1UVBe2vpYyQUUZFK8QZKolt7HZekMNd3hT_H4j-Dk6Bk/edit#gid=0) 

# Tasks
```[tasklist]
### To support disaster recovery in Zeebe
- [ ] https://github.com/camunda/zeebe/issues/16145
- [ ] https://github.com/camunda/zeebe/issues/16673
- [ ] https://github.com/camunda/zeebe-e2e-test/issues/421
- [ ] https://github.com/camunda/zeebe/issues/16954
```

```[tasklist]
### To support disaster recovery of other components in C8
- [ ] https://github.com/camunda/zeebe/issues/17260
- [ ] https://github.com/camunda/zeebe/issues/18030
- [ ] https://github.com/camunda/zeebe/issues/18752
- [ ] https://github.com/camunda/camunda/issues/19023
- [ ] https://github.com/camunda/camunda/issues/18296
```
For the above APIs, it is important that the information (such as an exporter is paused/disabled/enabled) is persisted across restarts and distributed to all brokers (also the ones that are not currently available, but will be joined later).

```[tasklist]
### Impact of high network latency between regions
- [ ] https://github.com/camunda/zeebe/issues/16768
- [ ] https://github.com/camunda/zeebe/issues/11496
```

```[tasklist]
### Documentation
- [x] Document all new APIs in docs.camunda.io
- [x] Update OpenAPI spec
```

**Comment by deepthidevaki** [comment]
I'm removing https://github.com/camunda/camunda/issues/16767 from the scope. I think it is useful to do, but not necessary to do it immediately.

Also adding a followup https://github.com/camunda/camunda/issues/19565

**Comment by npepinpe** [comment]
Is the documentation still missing? We would need it for 8.6, correct?

**Comment by deepthidevaki** [comment]
The docs for overall procedure for dual-region was added this week. I'm planning to add the missing API docs this week. I will close this epic after that.
