### ISSUE TITLE
[EPIC] Middleware parity of REST API to gRPC

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#16185]
## Introduction

This increment aims to achieve feature parity between the REST and gRPC APIs regarding middleware support.

## Task Breakdown

```[tasklist]
### Preparation
- [ ] https://github.com/camunda/zeebe/issues/18446
```

```[tasklist]
### Gateway API
- [ ] https://github.com/camunda/camunda/issues/19291
```

```[tasklist]
### Java client
- [ ] https://github.com/camunda/camunda/issues/19293
- [x] Add support for custom middleware in the Camunda Spring SDK
```

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/4108
- [ ] https://github.com/camunda/camunda-docs/issues/4109
```

## Other Teams

- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub (internal)
](https://github.com/camunda/product-hub/issues/2040)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1r_PRe6xgAH-IcN3OPGUiee4ey93BKWF5iH_hy3cH-5o/edit#heading=h.sq0mg44yd28a)

## Additional context

Blocked by https://github.com/camunda/zeebe/issues/16167

**Comment by aleksander-dytko** [comment]
@koevskinikola I propose renaming it to: `Middleware parity of REST API to gRPC` to avoid confusion that REST is already providing the same as gRPC

**Comment by koevskinikola** [comment]
I'm closing this issue, as all the sub-tasks have been completed. 🎉
