### ISSUE TITLE
[EPIC] Add support for BPMN compensation event subprocesses

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#16247]
## Introduction

After adding BPMN compensation events in the [previous epic](https://github.com/camunda/zeebe/issues/14920), this epic focuses on **BPMN compensation event subprocesses**. It will enable two main use cases:
- Compensate activities in a given order
- Access process variables from a completed subprocess (i.e. snapshot data that contain relevant context)

![image](https://github.com/camunda/zeebe/assets/4305769/65d5ddec-8aea-4132-8587-c837f8659904)

## Concept

The implementation will be based on compensation subscriptions that were introduced in the previous epic. Read more the details [here](https://github.com/camunda/zeebe/issues/14920).

### Broker

- [x] #15459 
- [x] #15334 
- [x] #15349 
- [x] #15451 
- [x] #15458 
- [x] #15464 

### Gateway API

None.

### Exporters and Metrics

- [ ] https://github.com/camunda/zeebe-analytics/issues/23

### Testing

- [ ] #16807

### Zeebe Process Test

None.

### Documentation

- [ ] https://github.com/camunda/camunda-docs/issues/3291

### Out of scope

- Support compensation event subprocess on process level

## Other Teams

- [x] [Operate](https://github.com/camunda/operate/issues)
- [x] [Tasklist](https://github.com/camunda/tasklist/issues)
- [x] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [x] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2081
- Previous epic: https://github.com/camunda/zeebe/issues/14920
