### ISSUE TITLE
[EPIC] Correlate message with result

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#16304]
<h3>Is your feature request related to a problem? Please describe.</h3>
When publishing a message, users need to know immediately if the publication was successful to take further action. There is currently no possibility of getting the information if the correlation was successful.

Currently, the only response for a published message is the message key ([ref](https://docs.camunda.io/docs/8.3/apis-tools/grpc/#output-publishmessageresponse)) which doesn't provide enough information to take appropriate action.

When the message is published, we need to know what was the result of this operation.

<h3>Describe the solution you'd like</h3>
Provide an API that returns:
- if the message was correlated to a process instance 
- the process instance key if the message was correlated

If the message is correlated to multiple process instances, the API returns one of the process instance keys. 

Message buffering (i.e. message TTL > 0) doesn't fit well with returning a correlation result. If there is no open message subscription during the message publication then we could return a result only within the given request timeout. Usually, the request timeout is lower than the message TTL (i.e. default is 1 hour in the Java client). To provide consistent and simple usage, we can exclude message buffering from the API.   

To separate the new API from the existing publish message API, we can use a different name. The name should reflect the intention to correlate a message to a specific process instance. This goes more in the direction of Camunda 7's message API ([ref](https://docs.camunda.org/manual/7.20/reference/bpmn20/events/message-events/#message-api)).

<details><summary><h3>Rest API</h3></summary>

<h4>Endpoint</h4>

POST `/v2/messages/correlation`

<h4>Request body</h4>

Parameter name | Type | Required | Description
-- | -- | -- | --
name | string | true | Name of the message
correlationKey | string | false | Correlation key of the message
variables | object | false | JSON object representing the variables to pass along with the message
tenantId | String | false | The tenant of the message sender

</div></b>

<h4>Response</h4>

HTTP status|Description|Response schema
--|--|--
200|The message is correlated to one or more process instances|{</br>  "key": int64, //unique ID of the published message</br>  "tenantId": string, //the tenant ID of the message</br>  "processInstanceKey": int64 //the process instance key the message was correlated to</br>}
400|The provided data is not valid.|[Problem details](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.o06ulmu7sbls)
403|Multi-tenancy is enabled and an unauthorized tenant ID is provided|[Problem details](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.o06ulmu7sbls)
404|One of:<ul><li>We didn’t find a message subscription to correlate with</li><li>Multi-tenancy is enabled and the tenantId is blank</li><li>Multi-tenancy is enabled and an invalid tenant ID is provided</li><li>Multi-tenancy is disabled and the tenantId is not blank</li><ul>|[Problem details](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.o06ulmu7sbls)
409|A message with the same ID was previously published and is still alive.|[Problem details](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.o06ulmu7sbls)
500|An internal error occurred while processing the request.|[Problem details](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.o06ulmu7sbls)

<h4>Example</h4>

```json

-- Request
{
  "name": "exampleMessage",
  "correlationKey": "exampleCorrelationKey",
  "variables": {"foo": "bar"},
  "tenantId": "exampleTenant"
}

-- Response
{
  "key": 1234567890,
  "tenantId": "exampleTenant",
  "processInstanceKey": 0987654321
}


```

</details>

<details><summary><h3>gRPC API (out of scope)</h3></summary>

⚠️ As the gRPC design will get deprecated and we don’t expect this to be required for high-performance use-cases we won’t support this API in gRPC.

The gRPC API could be defined as:

```
message CorrelateMessageRequest {
  // the name of the message
  string name = 1;
  // the correlation key of the message
  string correlationKey = 2;
  // the message variables as a JSON document; to be valid, the root of the document must be an
  // object, e.g. { "a": "foo" }. [ "foo" ] would not be valid.
  string variables = 3;
  // the tenant ID of the message
  string tenantId = 4;
}

message CorrelateMessageResponse {
  // the unique ID of the message that was published
  int64 key = 1;
  // the tenant ID of the message
  string tenantId = 2;
  // the process instance key the message was correlated to 
  int64 processInstanceKey = 4;
}
```

</details>  

<h3>Describe alternatives you've considered</h3>
Consume Zeebe's event stream by using an exporter and collect the information about the message correlation. Only available for self-managed. Requires an additional/custom application.  

<h3>Additional context</h3>

- Related product hub issue (internal): https://github.com/camunda/product-hub/issues/1818
- Related PoC: https://github.com/camunda/zeebe/pull/15633

<h3>Task Breakdown</h3>

```[tasklist]
### Protocol
- [ ] https://github.com/camunda/camunda/issues/20164
- [ ] https://github.com/camunda/camunda/issues/20167
```

```[tasklist]
### Gateway
- [ ] https://github.com/camunda/camunda/issues/20477
```

```[tasklist]
### Engine
- [ ] https://github.com/camunda/camunda/issues/20173
- [ ] https://github.com/camunda/camunda/issues/20174
- [ ] https://github.com/camunda/camunda/issues/20175
- [ ] https://github.com/camunda/camunda/issues/20176
- [ ] https://github.com/camunda/camunda/issues/20568
```

```[tasklist]
### Client
- [ ] https://github.com/camunda/camunda/issues/20478
```

```[tasklist]
### Exporters
- [ ] https://github.com/camunda/camunda/issues/20186
- [ ] https://github.com/camunda/camunda/issues/20187
```

```[tasklist]
### Others
- [ ] https://github.com/camunda/camunda/issues/20189
- [ ] https://github.com/camunda/camunda/issues/20190
```

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/4164
```

**Comment by saig0** [comment]
## Implementation notes

- Protocol: 
  - Add new gRPC API `PublishMessageWithResult` ([ref](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-extend-the-gateway-protocol))
    - The request contains an additional request timeout 
    - The response contains a boolean if the message was correlated
    - The response may contain a process instance key 
  - Add new `PUBLISH_WITH_AWAITING_RESULT` to `MessageIntent`
  - Extend message record: ([ref](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-extend-an-existing-record))
    - Add new property for process instance key
  - Extend message subscription record: ([ref](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-extend-an-existing-record))
    - Add new property for request id
    - Add new property for request stream id
- Gateway
  - Add request and response mapping for new API 
  - Handle request timeout in `EndpointManager`
- Engine
  - Adjust `MessagePublishProcessor`:
    - Set the request data to the subscription record 
    - Send the API response without process instance key if there are no message subscriptions 
    - Send the API response with process instance key if there is a message start event subscriptions 
  - Adjust `DbMessageSubscriptionState` to store the request data in the a message subscription
  - Adjust `MessageSubscriptionCorrelateProcessor` to send the API response with the process instance key if the request data is set for the subscription
  - Adjust `MessageSubscriptionRejectProcessor` to set the request data to the next message subscription record
- Java client
  - Add `withResult()` to publish message API 
  - Handle request timeout similar to `CreateProcessInstanceWithResultCommandImpl`
- Exporters:
  - Adjust ES + OS templates for message record ([ref](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-extend-an-existing-record)) 
- QA:
  - Add integration test for new command 

### Questions:
- How does the request timeout behave?
- Do we support TTL > 0 with result?
- Do we send a response if TTL > 0 && TTL < request timeout?

**Comment by korthout** [comment]
@aleksander-dytko I've assigned you to provide information about the priority

**Comment by aleksander-dytko** [comment]
Thanks! 
Let's add this to the next iteration to estimate the size of the effort to support that

**Comment by ingorichtsmeier** [comment]
Taking a look at the Camunda 7 implementation (https://docs.camunda.org/rest/camunda-bpm-platform/7.20/#tag/Message/operation/deliverMessage), they provide process variables in the response as well (if requested).

Would that be feasible for Zeebe as well? 

It will close another feature gap, as some customers use this API in Camunda 7.

**Comment by korthout** [comment]
@saig0 I believe it's possible what @ingorichtsmeier requests. 

It looks to me that there are variables on the `ProcessMessageSubscription:Correlate` command that could be passed along to the `MessageSubscription:Correlate` command. I guess that's not the case right now to reduce data, but for `withResult` we could fill the `variables` property. What do you think?

Variables are on the record before acknowledging
https://github.com/camunda/zeebe/blob/c781bae6512504bd04c7f6f879d5d87ece303ee6/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java#L118-L120

Acknowledging is the act of sending the `MessageSubscription:CORRELATE` command, but variables are not passed along
https://github.com/camunda/zeebe/blob/c781bae6512504bd04c7f6f879d5d87ece303ee6/engine/src/main/java/io/camunda/zeebe/engine/processing/message/ProcessMessageSubscriptionCorrelateProcessor.java#L151-L159

There is already a `variables` property on `MessageSubscription`
https://github.com/camunda/zeebe/blob/c781bae6512504bd04c7f6f879d5d87ece303ee6/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageSubscriptionRecord.java#L48

**Comment by ingorichtsmeier** [comment]
Sidenote: Another wish to close a product gap: synchronous signal sending.

Camunda 7 returns an empty payload: https://docs.camunda.org/rest/camunda-bpm-platform/7.20/#tag/Signal.

I could create a new gap/epic/feature request, if you tell that it is implementation wise related to the synchronous message correlation.

**Comment by saig0** [comment]
> Taking a look at the Camunda 7 [implementation](https://docs.camunda.org/rest/camunda-bpm-platform/7.20/#tag/Message/operation/deliverMessage), they provide process variables in the response as well (if requested).
>
> Would that be feasible for Zeebe as well?
>
> It will close another feature gap, as some customers use this API in Camunda 7.

@ingorichtsmeier no. I would consider the return of process variables as out of scope for this issue. It doesn't fit the current or new API. 

Zeebe processes commands asynchronously. When you publish a message using the new `PublishMessageWithResult` API, Zeebe will return the response immediately after the message is correlated to the process instance (i.e. activated/completed the message catch event).

Camunda 7 processes commands synchronously. When you correlate a message in Camunda 7, the engine will return the response after reaching all wait states (i.e. no more processing - when entering the next BPMN element after the message catch event).  

In Camunda 7, the response variables will contain values processed or modified by the BPMN elements after the message catch event. For example, a return/result variable that is produced by a task after the message catch event. To have the same behavior in Camunda 8, we would need to monitor the wait states of the process instance before sending the response. Returning the process instance variables directly after correlating the message would return the current process instance variables without a return/result variable. It would be different and I guess that it doesn't solve the use case.

**Comment by korthout** [comment]
> Sidenote: Another wish to close a product gap: synchronous signal sending.
> 
> Camunda 7 returns an empty payload: https://docs.camunda.org/rest/camunda-bpm-platform/7.20/#tag/Signal.
> 
> I could create a new gap/epic/feature request, if you tell that it is implementation wise related to the synchronous message correlation.

@ingorichtsmeier Let's keep that out of scope, signals work quite differently from messages in Zeeb

**Comment by korthout** [comment]
@saig0 Looking at the defined behavior above, what about the following case:


Open message subscription (1) | Message TTL (2) | Response
-- | -- | --
❌ | >0 | Message is correlated before request times out

**Comment by ingorichtsmeier** [comment]
> signals work quite differently from messages in Zeebe

Thank you for the confirmation

**Comment by saig0** [comment]
@korthout and I agreed on the following design:
- Message buffering is out of scope. It is not required by the customer who requested this feature. It would lead to less consistent behavior because the buffering interferes with the request timeout. If the timeout is exceeded before the message is correlated then the caller doesn't get a response. 
- The new API is called `CorrelateMessage`. The name should differ from the existing `PublishMessage` API. Why?
  - Different feature set: correlation result vs. message buffer + message id  
  - Different intent: correlate a message to a specific target (i.e. process instance) vs. publish/ingest a message without a target (i.e. fire and forget)
  - More close to Camunda 7's message API ([ref](https://docs.camunda.org/manual/7.20/reference/bpmn20/events/message-events/#message-api))
- The name of the new API doesn't have the postfix `withResult` like the `CreateProcessInstanceWithResult`. The correlation result will be sent directly after the message is correlated. It doesn't wait until the process instance is completed or has reached a certain wait state.
- With the new API, we would have the option in the future to refine the correlation by supporting:
  - Correlation to a given process instance key
  - Correlation to a given process key / BPMN process id (i.e. for start events)

I adjusted the solution design based on the discussion.

**Comment by aleksander-dytko** [comment]
Awesome, thank you @saig0 and @korthout  🚀 

@korthout how would you estimate the t-shirt size of this epic?

**Comment by megglos** [comment]
removing from upcoming, this is handled and planned via PDP https://github.com/camunda/product-hub/issues/1818

**Comment by remcowesterhoud** [comment]
After discussion with @aleksander-dytko we've decided we won't support this endpoint in the gRPC API, but only in the REST API. The reasoning is explained in the [kickoff document (internal)](https://docs.google.com/document/d/1MFONEYUcMYW2uZMUe4IfCw7owpnpxAa07dOL-7n_OFU/edit#heading=h.aha4etj4ibfa).

**Comment by falko** [comment]
@remcowesterhoud cross-posting my comment from the GDoc for visibility:
> The feature request comes from GLS, which is currently our SaaS customer with the highest load, and it has been requested specifically for a high-performance use case.
Which impact will the use of the REST API have in comparison to gRPC? I imagine GLS will have to use gRPC for job streaming and REST for messaging? Will this mix be possible with the Java client?

**Comment by yT0n1** [comment]
@jwulf Is there any chance this would make its way into the node SDK before 8.6? This would be very helpful for Play to provide better feedback to users.

**Comment by jwulf** [comment]
> @jwulf Is there any chance this would make its way into the node SDK before 8.6? This would be very helpful for Play to provide better feedback to users.

 @yT0n1 - theoretically possible. The devil is in the details: https://github.com/camunda/product-hub/issues/1818#issuecomment-2260099816

**Comment by remcowesterhoud** [comment]
There is a small change in the original design:

Our plan was to store the request data on the Message Subscription. This means we would have it available to use when the subscription gets correlated, and we can use it to send a response. This doesn't work in all cases. Mainly, when the correlation of a subscription fails, we don't always have access to this subscription. No access to the subscription means we don't have access to the request data and we can't give a response to the client.

I have now decided to introduce a new `ColumnFamily` to store this request. It'll be stored using the message key, which as I said previously is available everywhere. It's a bit more work, but I believe it is generally a cleaner solution. It keeps the entire request/response isolated to the new `ValueType`. I will store the request data to the state using a `MessageCorrelation.CORRELATING` event. The data will be removed using the `MessageCorrelation.CORRELATED` or `MessageCorrelation.NOT_CORRELATED` events.

**Comment by remcowesterhoud** [comment]
Closing this as all tasks are implemented and the feature is complete.
