### ISSUE TITLE
Clients can provide a reference to a command that can be observed in the resulting event

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16916]
**Is your feature request related to a problem? Please describe.**

* Operate batch operations are a set of so-called single operations (one for each element of entities the operation is applied to). For each single operation, Operate makes commands against Zeebe (e.g. cancel a process instance). When the effect of that operation is imported into Operate, we want to mark the corresponding single operation as completed, so that the user can understand to which degree a batch operation is complete.
* Today, this is solved by querying the Operate indexes during import, i.e. searching for single operations that match the observed process instance key. This would be a performance problem in the new exporter design, where we want to avoid any queries to Elasticsearch on the hot data path.
* While Operate makes these requests synchronously, i.e. it can immediately observe the result, it must wait until the event is observed in the exporter before it can mark the single operation as completed. Otherwise, the operation will appear completed for the user while the effect is not yet visible.
* [Product hub epic](https://github.com/camunda/product-hub/issues/2128)

**Describe the solution you'd like**

* When sending a command to Zeebe, it should be possible to add a reference, e.g. a `long` value
* This reference is then propagated to the events resulting from the command, so that an exporter can pick up the reference again and match the event efficiently with its data store.
  * Specifically, Operate would send the single operation's ID so that the Elasticsearch exporter can just make a direct update statement against Elasticsearch with it
* Optional: Add a reference category field to distinguish different parties that might submit references (e.g. without this, another client could send the same reference and the exporter couldn't detect that). This may not strictly be a problem.

**Describe alternatives you've considered**

* See the [design document](https://docs.google.com/document/d/1Z-3jykjuTn5egjLEaOJZUbnvg1YIyPyjT474dPYnM2s/edit#heading=h.kgatlqtvc1an)

**Additional context**

```[tasklist]
### Task Breakdown
- [x] introduce operationReference in the commands operate uses within zeebe-client
- [x] include the operationReference in the exported records resulting from the command
- [ ] https://github.com/camunda/camunda/issues/19080
```

```[tasklist]
### Nice to have
- [ ] introduce operationReference to the rest of the commands in zeebe client to have a consistent ux everywhere
- [ ] introduce the operationReference in the REST command endpoints too
- [ ] Do we want to include an operation category?
- [ ] Do we want to include the operationReference in responses?
```

**Comment by mustafadagher** [comment]
I started looking into this issue and the related epics/docs, and I have a few initial (unorganized) thoughts and open questions.

Initially, we can break the feature down into the following tasks:
- [ ] Generating the (operation) reference value
- [ ] Update zeebe client to accept operation reference in command calls
- [ ] Zeebe should propagate operation references to the resulting events
- [ ] ❓ Update zeebe exporters to write the operation reference to elastic search (and open search)
- [ ] ❓ Operate to properly use the operation reference to match operations to zeebe events

### Generating the (operation) reference value
Regarding the first part `Generating the (operation) reference value`, I have a few open questions

- ❓ Should this be the responsibility of `operate` to generate it when sending the operation to `zeebe`? or should `zeebe` be responsible for this and communicate the operation reference back to the task execution `future`?
  - Why does that matter? 
    - Having it in `zeebe` makes no need to change the clients APIs, we will need to change the usages to get it from the future responses though (❓  is that possible in the current design?). It could be useful for other usecases too (not just for operate) to have a traceId for every zeebe request/response, but that's out of the scope of this task.
    - Having it in `operate` is simpler, closer to the scope of this task, and adds the ability to add more operate specific context to it in the future.
- ❓ Does it need to be sequential? Or can it be random?
- ❓ I assume it should be unique within an installation, yet for SaaS, how big could it get? Is `long` enough?
- ❓ How to ensure the uniqueness amongst clusters/partitions?
  - 💭 can it be generated from a combination that could be matched to a cluster/pod/etc? 
  - ❓ do we have a common practice in zeebe for such matters?
- 💭 Operate’s `OperationEntity` already has a random generated `id`, isn’t that sufficient to be sent?

### Operate to properly use the operation reference to match operations to zeebe events
- ❓ What needs to change in operate for this to be properly used? 
- ❓ Should this replace the `ImportJob` notifying the `ImportListeners` with `finish` or `failure`? where should it be placed then?
- Who should own this task? operate team or zeebe? I assume operate?

CC: @ThorbenLindhauer, I appreciate to hear your thoughts on the above

**Comment by mustafadagher** [comment]
I had a fruitful alignment call with @sdorokhova this morning, and below are a few takeaways:

- **Operate** shall figure out how to generate the operation reference key (and send a caller/origin key/category, to avoid having duplicate references if another client would call zeebe with the same value)
- A `long` reference should be sufficient. The value doesn't need to be sequential, relaying on something like timestamp and other known variables could be an idea, but that's for operate team to figure out and decide.
- **Zeebe** needs to accept these values in the zeebe client, and write them back in the zeebe `Record`s
- [_Optional_] **Zeebe** can send the operation reference key in the client response

The **scope** of this issue then starts from **accepting the new reference key and the callerID** (e.g. `OPERATE` in this case), and ends at **writing it back to the Zeebe Protocol `Record`**.
Sending the reference back in the zeebe client response is a **_nice to have_**, and we shall address it later if we see the need for it going further.

**A possible trade-off:**
I still think that generating such reference in Zeebe and communicating it back can have more value for other use cases and can also ensure uniqueness around clients out of the box for them, but I choose to postpone this for later, to limit the scope of this task to what's just needed and we can always revisit it again in the future if we find evidence for value. I shall create a **_SPIKE_** to come back to it later in the future.

I'll have a deeper look at the complete flow again and will post another update at a later point outlining the solution and listing the possible task breakdown from Zeebe's perspective.

**Comment by mustafadagher** [comment]
After having a catchup with @oleschoenburg and on a second thought about this:
In Zeebe, we already generate a `requestId` for every incoming request (check [here](https://github.com/camunda/zeebe/blob/1c145ffee7cf8772e289ee5ef368c52e7da622cd/zeebe/transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java#L117)). So far, we only use this id internally. We don't propagate it to responses and we don't also export it in the events.

The request is now kept as part of the `TypedRecord` interface. If we move it to the `Record` interface, and updated the elasticsearch templates to have it, **we could already have it as part of the exported events**.

Now the missing part would be propagating this `requestId` back to every client response. For that we would need to introduce a few changes to the `Protocol`, `Broker` and the `Gateway`. From there, we wouldn't need much change in the `zeebe-client` and **Operate** will only need to pick the `requestId` up from the future response and store it somewhere to use it for queries later.

A draft task breakdown shall be as follows:

```[tasklist]
- [ ] [zeebe- protocol] Zeebe should write the requestId in the exported events/records ( Move `requestId` to `record` interface and update the `zeebe-record-template` to have it.)
- [ ] [zeebe- protocol] protocol to include `requestId` in `ExecuteCommandResponse` (in SBE scheme and encoder)
- [ ] [zeebe-broker] Broker to include `requestId` in `CommandResponseWriter` (and probably in `BrokerResponse`?)
- [ ] [gateway-protocol] response messages to include `requestId`
- [ ] [zeebe-gateway] Gateway `ResponseMapper`s to include the `requestId` in the mapped responses
```

I'm probably missing some _links_ along the way in the flow above, but I shall update it when needed.

CC: @sdorokhova

**Comment by mustafadagher** [comment]
From the [comments on the PR](https://github.com/camunda/zeebe/pull/17877#issuecomment-2082915980) for #17637 , @oleschoenburg, @Zelldon and @deepthidevaki brought to my attention that 
> the generated `requestId` might be unique across partitions, although this was not the intention. Please check [here](https://github.com/camunda/zeebe/blob/main/zeebe/transport/src/main/java/io/camunda/zeebe/transport/impl/AtomixServerTransport.java#L45). But it is easy to break this assumption if we run this code per partition. Right now it is per broker. If we are relying on this guarantee, we should take measures to ensure this is not accidentally broken.

I'll copy my response here too for transparency, to keep the decision reasoning clear after the PR is closed:

> I see indeed for the current design it should be unique still across nodes, since the nodeId is passed to the generator and it occupies a few bits from the generated sequence.
>
> As @deepthidevaki mentioned indeed this only relies on the guarantee of having this run only on the broker. 
>
>To avoid this breaking the assumptions from Operate's perspective, we could do one of two solutions:
>1. refrain from using this requestId totally, and revert back to the original solution by asking operate to provide this reference in the request.
>2. to include the partitionId/requestStreamId in the exported records and the client responses too. As a matter of fact, `partitionId` is already part of the exported records, so it would be up to us to also pass it back in the client responses, and inform operate to rely on both values together for their queries. Not sure if this would impact the performance on their side by any means (@sdorokhova  could maybe share her thoughts.) 
>
>For now, I'm leaning towards solution number 2. But I appreciate hearing your thoughts further, and also letting me know if there are any extra points I've missed or wrong assumptions I could have made.

**Comment by mustafadagher** [comment]
For trasnparency:

However the implementation in https://github.com/camunda/camunda/pull/17877 was finalized and the PR was approved to have a unique requestId from exported with the records, after discussions with @korthout, we agreed that there are edge cases where there might be network partition, and an operation from operate (or other clients) would complete successfully but a response wouldn't be sent. This would result in a missing requestId for these operations. Even though the edge case would be rare to happen. 
I decided that it would be better to address it, and thought it would be best for the clients to provide their own operation reference, then they would have better transparency on what is happening within zeebe for their own operation.


I opened another [PR](https://github.com/camunda/camunda/pull/18669) for the operation reference approach, and it's waiting to be reviewed and merged.



CC: @sdorokhova
