### ISSUE TITLE
Assess and track exporter performance and act on problems

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16920]
### Description

* With creating an [exporter that writes directly to the Operate indexes](https://github.com/camunda/product-hub/issues/2128), we are moving logic from the Operate importer into Zeebe. Within Zeebe, we have higher performance requirements for the code, as it competes with other critical Zeebe features (e.g. stream processing) for CPU and memory resources. Once we have rolled the new exporter out, we need to ensure that it can reliably keep up with our target workloads and does not negatively impact other Zeebe components.
* [Product hub epic](https://github.com/camunda/product-hub/issues/2128)

### TODO

* Define a workload we want to sustain
* Define a corresponding benchmark (using the benchmark project); agree on the pod resource specs we want to cover (for example, could be the minimum and maximum SaaS cluster sizing)
* Establish/extend a procedure in the Operate team to monitor the benchmark metrics, identify and act on problems

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

```[tasklist]
### Tasks
- [ ] Release new Benchmark helm chart - as soon alpha1 has been release
- [ ] Add additional metrics as replacment for missing import missing (to see how quick data is injected into ES
```

**Comment by ThorbenLindhauer** [comment]
Moving to backlog because we need to finish preliminary work first.

**Comment by Zelldon** [comment]
We have introduced new realistic benchmarks https://github.com/camunda/camunda/issues/21462
We have them made part of our weekly benchmarks https://github.com/camunda/camunda/pull/24109

**Comment by Zelldon** [comment]
New weekly Zeebe benchmarks will contain exporter. 

First glimpse can be seen here https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=ck-main-exporter&var-pod=All&var-partition=All

As there is not more actionable from this ticket I will close it. We will react on issues, performance issues, when observing.
