### ISSUE TITLE
[EPIC] Support Spring Zeebe SDK

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#17338]
## Introduction

Complete the migration of Spring Zeebe SDK (for more information about the migration see https://github.com/camunda/zeebe/issues/16816), refactor the codebase and extend test coverage.

Project channel: [#prj-spring-zeebe-sdk](https://camunda.slack.com/archives/C06MPP9DQ21)

## Concept

- Review latest changes to the community-project (https://github.com/camunda-community-hub/spring-zeebe/pull/690) and decide if we should migrate them
- ~~Migrate test support ([@ZeebeSpringTest](https://github.com/camunda-community-hub/spring-zeebe/tree/main/test))~~
- Remove leftovers from other components/Remove unused code
- Review and address TODOs -> refactor the code where needed, simplify and make maintainable
- Add tests coverage
- Merge sdk and client for more maintainability of the code, will not affect users

### Client

```[tasklist]
### Spring starter & Spring client
- [ ] https://github.com/camunda/zeebe/issues/17339
```

```[tasklist]
### Spring zeebe SDK
- [ ] https://github.com/camunda/zeebe/issues/17341
- [ ] https://github.com/camunda/zeebe/issues/17340
- [ ] https://github.com/camunda/zeebe/issues/17342
- [ ] https://github.com/camunda/zeebe/issues/17343
- [ ] https://github.com/camunda/zeebe/issues/17344
- [ ] https://github.com/camunda/zeebe/issues/17767
- [ ] https://github.com/camunda/zeebe/issues/17884
- [ ] https://github.com/camunda/zeebe/issues/17885
- [ ] https://github.com/camunda/zeebe/issues/17886
- [ ] https://github.com/camunda/zeebe/issues/18355
- [ ] https://github.com/camunda/zeebe/issues/18528
- [ ] https://github.com/camunda/zeebe/issues/18656
```

```[tasklist]
### Stretch goal
- [ ] https://github.com/camunda/zeebe/issues/17345
```

### Documentation

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/3699
- [ ] https://github.com/camunda/camunda-docs/issues/3709
- [ ] https://github.com/camunda/camunda-docs/issues/3748
```

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2148
- Migration EPIC: https://github.com/camunda/zeebe/issues/16816
