### ISSUE TITLE
[EPIC] Process Instance Migration Phase 3: Nesting and common events

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#17349]
## Introduction

Third phase of the [Process Instance Migration](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/) concept.

This phase expands the concept introduced in https://github.com/camunda/zeebe/issues/14907 and expanded by https://github.com/camunda/zeebe/issues/17346 by increasing the coverage of processes that can be migrated, focussing on commonly used elements.

## Concept

This phase focuses on:
- expanding support for the migration of nested elements like those nested in an event-subprocess and child-process instances called from a call activity
- horizontally expanding support for more types of message event subscriptions like intermediate message catch event and elements subscribed to message event-subprocess
- and vertically expanding support for events to timers like intermediate timer catch event and elements subscribed to timer boundary event or timer event-subprocess

## Task Breakdown

Work in progress

### Phase 3 - nesting, messages, and timers
- [ ] https://github.com/camunda/zeebe-analytics/issues/131
- [ ] https://github.com/camunda/zeebe/issues/15921
- [ ] https://github.com/camunda/zeebe/issues/15922
- [ ] https://github.com/camunda/zeebe/issues/16386
- [ ] https://github.com/camunda/camunda/issues/19527
- [ ] https://github.com/camunda/camunda/issues/19640
- [ ] https://github.com/camunda/zeebe/issues/15918
- [ ] https://github.com/camunda/camunda/issues/19716
- [ ] https://github.com/camunda/camunda/issues/20911
- [ ] https://github.com/camunda/camunda/issues/20938
- [ ] https://github.com/camunda/zeebe/issues/17419
- [ ] https://github.com/camunda/camunda/issues/21218
- [ ] https://github.com/camunda/camunda/issues/20906
- [ ] https://github.com/camunda/camunda/issues/21969
- [ ] https://github.com/camunda/camunda/issues/22146
- [ ] https://github.com/camunda/camunda/issues/22680

## Later phases
- https://github.com/camunda/camunda/issues/22346
- https://github.com/camunda/camunda/issues/22797
- https://github.com/camunda/camunda/issues/22799

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Discussions and Decisions

- https://github.com/camunda/zeebe/issues/16999

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2172

**Comment by aleksander-dytko** [comment]
For message events we still need:
* Migration of the subscription - prerequisite 
* Intermediate Catch event
* Event subprocess start event 
* Mapping instructions for subscriptions - API (you can pass the mapping instruction) and UI (support this element)


💡 mapping instructions with flag to unsubscribe/subscribe - this is advanced feature (as it expands on the basic feature - use the same subscription) and workaround exists (process instance modification)
   - this shouldn't have the high prior

❓ `Intermediate message catch event`: Migrate message subscription vs unsubscribe and subscribe to the message subscription 
* the difference is on the record log 
* migrate message subscription is significantly more difficult 

TODO:
- [ ] summarize two options and share this in the prj channel - to make a decision 
   - ask Roman and Phillipp about the opinion

**Comment by aleksander-dytko** [comment]
@berkaycanbc for visibility - I divided phase 5 into 2 sections

**Comment by npepinpe** [comment]
@berkaycanbc - can we close this? It looks like the epics in general were not closed, but probably we can close them? 🤔
