### ISSUE TITLE
Migrate message event subprocess

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#17419]
Similar to [migrating active embedded subprocesses](https://github.com/camunda/zeebe/issues/15923), we also want to support migrating active event subprocesses. This is useful when we want to change the flow inside an event subprocess that has been triggered at least once and one or more elements nested inside the event subprocess are active.

Like other migrations, users must provide mapping instructions for the active event subprocess element because all active elements require mapping instructions. 

> [!IMPORTANT]
> The mapping instruction is for the event subprocess element itself, not its start event. Mapping the start event of the event subprocess will be used to deal with the event subscription of the event subprocess, not for migrating an active event subprocess.

Note that an event subprocess may be active multiple times if it is non-interrupting. We must migrate all instances of the event subprocess. This should happen automatically when we allow migrating active event subprocesses in the `MIGRATE` command processor.

In the example below, an error event subprocess is active. Nested inside is an active service task `B`. When migrating, we provided mapping instructions for both the event subprocess and the service task. As a result, the migrated process instance awaits at the same service task, but the active service task `B` now flows to service task `C` instead of to an end event.

<img width="875" alt="Screenshot 2024-04-10 at 13 43 39" src="https://github.com/camunda/zeebe/assets/3511026/55803d84-86cd-499e-ae95-86095cb64274">

## Migration of elements subscribed/subscribing to event subprocess is out of scope <a href="#limitation" id="limitation">#</a>

An interrupting event subprocess terminates the main process flow when it triggers. On the other hand, the main process flow may still be active for non-interrupting event subprocesses, and the event subprocess may trigger again. We must deal with these subscriptions like active elements subscribed to a boundary event. We'll do that in other issues, but until then, we should reject migrations that attempt to migrate element instances that are subscribed to an event subprocess in the source process or that will subscribe to an event subprocess in the target process.

We should consider rejecting such migrations in the same way as we do with boundary events. We could already support a subset of allowed event types, like in the example below. This will help us to build the unsubscribing and subscribing behaviors for unmapped start events of event subprocesses incrementally. As the type of an event subprocess depends on the type of the start event of the event subprocess, we'll need to use that information somehow.

https://github.com/camunda/zeebe/blob/422a2b5a209a856c1ee00fdc526c9f85c357b3a8/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditionChecker.java#L435-L446

For now, it is okay if the type of the event subprocess changes (i.e. the type of the start event of the event subprocess), as we will only add support for migrating the subscription later. So, we do not need to add a rejection for this case right now.

## Cross-team efforts

Process instance migration is a topic that both Zeebe and Operate build together. For active event subprocess migrations, Operate must be able to:
- update the active state and history through `PROCESS_INSTANCE:ELEMENT_MIGRATED` events for the migrated event subprocess instances
- provide mappings for event subprocesses

## Breakdown

```[tasklist]
### Tasks
- [ ] Allow migration of process instance with active event subprocess, i.e. remove rejection
- [ ] Migrate all active event subprocess instances
- [ ] Migrate existing message event subprocesses
- [ ] Subscribe to message event subprocesses
- [ ] Unsubscribe from message event subprocesses
- [ ] Update documentation about supported migration of active event subprocesses
- [ ] Inform Operate that active event subprocess migration is supported
```
