### ISSUE TITLE
Import `jobKind` from Zeebe `JobRecordValue` into flow node instance and event

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#17469]
### Description

In order to support the handling of `JobKind` from Zeebe `JobRecordValue` Operate needs to add a field to `FlowNodeInstanceForListViewEntity` and `EventMetadataEntity`

This field can later be used to process `TaskListener` and `ExecutionListener` events.

### TODO

- [ ] Evaluate different approaches:
    - Create new index for Job (and refactor job related fields?)
    - Add as additional fields?
    - What dependencies will be introduced by using `jobKind` field?
- [ ] Add field `jobKind` to `list-view` index 
- [ ] Add field `jobKind` to `event` index 
- [ ] Store value of `JobRecordValue::getJobKind` in fields

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
