### ISSUE TITLE
Unified flow control for Zeebe

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#17547]
## Problem
Currently, Zeebes main flow control mechanism are:
1. Backpressure on user commands
2. Rate limiting log storage writes

The first check is supposed to protect the entire system by (some!) user commands when they cannot be processed fast enough. By default we have a target of 200ms response times.

The second check is supposed to protect the raft thread. All log storage writes have to go through the raft thread responsible for the partition. We must avoid overwhelming this thread with for example a burst of writes. Otherwise we could end up missing heartbeats, forcing unnecessary leader changes and just in general destabilizing the system.

However, we have two components that are _not_ protected by flow control. The processing queue and the exporting queue.
When internal processing results in a high workload, for example with large multi-instances or with looping script tasks, the processing queue can grow unbounded. Backpressure for user commands increases because their processing becomes delayed but the internal processing continues at full speed.
This often results in the exporting queue being overwhelmed too. Internal processing is often much faster than the rate at which we can export, especially to ElasticSearch.

Because these two components are not protected by flow control, we often encounter incidents where we observe high disk usage (lot's of unprocessed and not yet exported records in the journal) and a high delay until data shows up in the webapps.

## Solution

We want to introduce a third mechanism that rate limits _all writes_ based on the exporting rate. Basically, if exporting slows down, writing of new records becomes slower too. For user commands this will show up as increased backpressure. Internal processing will slow down because the stream processor needs to wait longer for writing of processing results to complete.

To achieve this, we will first refactor the existing flow control mechanisms. We've already explored this in a spike with promising results: https://github.com/camunda/zeebe/issues/10087#issuecomment-1802371153

In a second step, we will add the third mechanism. Every record that is written will have to pass three checks:
1. Can we write it without overwhelming the raft thread?
2. Can we process it fast enough?
3. Can we export it?

Depending on the _source_ of the record, some checks can be ignored. For example, internal commands (unlike user commands) don't have to be processed within a target latency range.

## Breakdown

```[tasklist]
### Refactoring flow control
- [ ] https://github.com/camunda/zeebe/issues/17548
- [ ] https://github.com/camunda/zeebe/issues/17669
- [ ] https://github.com/camunda/zeebe/issues/18116
- [ ] https://github.com/camunda/zeebe/issues/18120
- [x] `LogStreamImpl` should not be async
- [ ] https://github.com/camunda/zeebe/issues/18731
```

```[tasklist]
### Limit overall write rate
- [ ] https://github.com/camunda/camunda/issues/19680
- [ ] https://github.com/camunda/camunda/issues/19681
- [ ] https://github.com/camunda/camunda/issues/20215
- [ ] https://github.com/camunda/camunda/issues/20274
- [ ] https://github.com/camunda/camunda/issues/20275
```

```[tasklist]
### Evaluation
- [ ] https://github.com/camunda/camunda/issues/20267
- [ ] https://github.com/camunda/camunda/issues/20269
- [ ] https://github.com/camunda/camunda-docs/issues/4087
```

```[tasklist]
### Visualization
- [ ] https://github.com/camunda/camunda/issues/20944
- [ ] https://github.com/camunda/camunda/issues/21324
```

```[tasklist]
### Zeebe talk
- [ ] https://github.com/camunda/camunda/issues/21305
```

## Related Issues

[PDP Epic](https://github.com/camunda/product-hub/issues/1426)

closes https://github.com/camunda/zeebe/issues/6723
closes https://github.com/camunda/camunda/issues/14688
relates to https://github.com/camunda/zeebe/issues/14316
relates to https://github.com/camunda/zeebe/issues/10087

**Comment by oleschoenburg** [comment]
My initial goal (and what's mostly implemented now) was to have three different limits, for commits, processing and exporting.

Commit and processing limits would match our existing append limit and user-command backpressure while the exporting limit would be new.

Having implemented most of this, I'm having second thoughts. Each limit on its own is difficult to understand already. Just try to understand the`gradient2` limit for example and predict how it would behave for Zeebe.
This complexity explodes once we have three limits that each and every write has to go through.

So what would happen if we just have one limit and we can configure when we consider an in-flight entry as "done" instead?
Then we could configure just one limit (e.g. our usual AIMD 200ms) and choose where we want to allow a backlog to grow:
1. Nowhere: we can build up a long queue of unwritten and uncommitted entries, potentially overwhelming the raft thread
2. Committing: we protect the raft thread but processing queue can grow unbounded and we have no control over response times
3. Processing: We control the processing queue and can target a certain response time but accept that we can have a long exporting queue
4. Exporting: All queues are bounded and we have control over how long it takes to export something.

**Comment by deepthidevaki** [comment]
Have you looked into the priority based limits? If I remember correctly, the current library that we use supports it. That is there is only one queue, but we can set priority to different types of requests. For example, we have one queue for both user commands and followup records from processing. But we can set priority - 40% user requests, 60% internal load.

**Comment by deepthidevaki** [comment]
Also, I think when we have limits everywhere, especially in processing, we might not need a limit for committing. It will be automatically bounded because all components that generate new events will be bounded.

**Comment by lenaschoenburg** [comment]
I discussed this with @deepthidevaki and @npepinpe and we ended up with the following design that we think would cover all use cases and still be easy to implement, understand and observe:

1. We keep a limit on unprocessed entries, probably the already existing 200ms AIMD limit. Either all entries or just new user commands (not yet clear which is better) have to acquire from this limit and release on processing.
2. As a second layer, we introduce a write rate limit. In it's simplest form this can be a fixed rate. To control exporting backlog, we could adjust the rate dynamically.

With this, we prevent:
1. Slow response times. Everything needs to be processed within 200ms
2. Long processing queue. With a long queue, response times would not be achievable
3. Continuous overload of ES. The write rate limit should match ES resources.
4. Long exporting queue. We reduce the write rate limit based on queue length.

The behavior is relatively easy to understand and easy to observe. All rejected writes know which limit is exceeded and we can visualize how many are rejected per limit. We can also derive a utilization metric (number of writes / maximum write limit) and mark time ranges where we needed to reduce the write limit to reduce exporting backlog. We can also make it observable when utilization is low because processing latency (i.e. response times) are too high.

**Comment by deepthidevaki** [comment]
> 1. We keep a limit on unprocessed entries, probably the already existing 200ms AIMD limit. Either all entries or just new user commands (not yet clear which is better) have to acquire from this limit and release on processing.

If we want to prevent long processing queue due to internal load or fork bombs, internal events/commands may have to also go though this limit. Right?

**Comment by lenaschoenburg** [comment]
In theory, fork bombs are also mitigated because of the write rate limit. But I think having everything go through the processing limit (AIMD) would be simpler and more effective mitigation :+1:

**Comment by lenaschoenburg** [comment]
There's a problem with limiting the writing of processing results. When we have exhausted our in-flight spots and thus can't write processing results, processing itself is blocked, thus not freeing up any in-flight spots. So this is a deadlock.

**Comment by npepinpe** [comment]
Regarding the exporting queue, can we put that behind a feature flag or a config? This would help support users who may be using non-critical exporters and want to prioritize processing speed over exporters.

**Comment by saig0** [comment]
> The main concern was internal load due to fork bombs or something similar. (messages and timer expiry should be ok because we are already throttling it)

I'm not sure about this. During the last game day, we overloaded the broker with timer events. We run a bunch of process instances with a multi-instance subprocess and inside a non-interrupting event subprocess that triggers every minute. At some time, the backpressure was at 100% and the partitions were unhealthy (most of the time).

From a user perspective, I would like to continue processing the tasks or repair the process instance by a modification or a version migration command. But this was not possible anymore.

Can we consider the case that timers should not overwhelm the system?

**Comment by lenaschoenburg** [comment]
> Can we consider the case that timers should not overwhelm the system?

If I understand correctly, this boils down to a prioritizing certain writers over others. This is not something we can address with the flow control as it is implemented now. 

In my opinion, we need to solve this issue differently:
1. Why was the command caching not effective?
2. Cancellation of process instances already ignores the request limit. Perhaps we should add process instance modification.
3. Flow control settings can be changed dynamically now so we can always unblock us if needed
