### ISSUE TITLE
[EPIC] Tasklist is included to Single Jar/distribution

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda#17577]
## Introduction

Based on #17062, Tasklist will become part of the Single Jar (that already includes Zeebe and Operate).

## Breakdown
* Preparete Tasklist dependencies to align with Zeebe's
  * Clean-up Tasklist maven dependencies: enable dependencies analyse and convergence plugins
  * Bump java version to 21
  * Integrate Tasklist into maven multi module structure
* Add Tasklist to current Zeebe distro
  * Add tasklist.sh script to start only Tasklist
  * Resolve conflict with Operate's `migrate.sh` script
  * Remove obsolete `tasklist-distro` folder
  * Ensure that the correct index.html is served (because the Single Jar bundles multiple webjars containing an index.html)
  * use different webapp application configuration files per component 
  * logs mount for unpriviliged user in `tasklist.Dockerfile`
*  Include Tasklist in the unified release workflow
* Update helm and camunda-operator with configuration files changes

## Tasks
```[tasklist]
- [ ] https://github.com/camunda/zeebe/pull/17526
- [ ] https://github.com/camunda/zeebe/pull/17550
- [ ] https://github.com/camunda/zeebe/pull/17587
- [ ] https://github.com/camunda/zeebe/pull/17649
- [ ] <https://github.com/camunda/zeebe/pull/17702>
- [ ] https://github.com/camunda/zeebe/pull/17691
- [ ] https://github.com/camunda/zeebe/pull/18029
- [x] https://github.com/camunda-cloud/camunda-operator/pull/2770
- [ ] https://github.com/camunda-cloud/camunda-operator/pull/2775
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1709
```

related to https://github.com/camunda/product-hub/issues/2278

**Comment by romansmirnov** [comment]
@houssain-barouni, in Tasklist we should do the same as in Operate with creating the `logs` folder: https://github.com/camunda/zeebe/pull/17686

**Comment by marcosgvieira** [comment]
@houssain-barouni should we move this to Completed on HTO Board, can you please move it or update what is pending?

**Comment by houssain-barouni** [comment]
remaining changes in the helm chart, but they are released only in the next minor
