### ISSUE TITLE
Operate backend IT overhaul and CI optimization

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/camunda#17658]
### Description

Relevant documents: 
https://docs.google.com/document/d/1rDDokhd5XAY2JKdgaZynU8b0E2PoZR8E8Rk9BllfcNU/edit
https://docs.google.com/spreadsheets/d/1r-vgeNDEKKyLHAi6vE32E1OZFTSrwJFZwKI1y-3tN4k/edit#gid=0

Phase 2:

- [x] Move Importer integration tests to nightly job: https://github.com/camunda/camunda/issues/19186
- [x] Refactor stage 2 integration tests: https://github.com/camunda/operate/issues/6268
- [x] Refactor several stage 1 integration tests: https://github.com/camunda/zeebe/issues/17650

Phase 3:

- [x] Create workflow for ITs with Opensearch configuration: https://github.com/camunda/zeebe/issues/17651
- [x] Create workflow for Java code checks: https://github.com/camunda/zeebe/issues/17652
- [x] Create workflow for unit tests: https://github.com/camunda/zeebe/issues/17653
- [ ] Add updated Operate CI to mono-repo merge check: https://github.com/camunda/camunda/issues/18600

Continuous improvement work:
- [ ] Investigate splitting out frontend build from maven: https://github.com/camunda/zeebe/issues/17926#issue-2266193800
- [ ] Cleanup remaining ITs and convert to Junit 5: https://github.com/camunda/zeebe/issues/17655
- [x] Research docker dependency pool strategy for zeebe containers: https://github.com/camunda/zeebe/issues/17656
- [x] Research converting search-only Operate ITs to create their own indices: https://github.com/camunda/zeebe/issues/17657
- [ ] Clean up Operate import/Stage2 ITS: https://github.com/camunda/zeebe/issues/17659

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | NEEDS_INFO |
| **Severity** | N/A |
| **Likelihood** | N/A |
| **Confidence** | 0.94 |

---

### 📝 Rationale

The issue lists related CI/test work but lacks a clear problem statement, affected stakeholders, intended outcome, and testable acceptance criteria; therefore task impact and timing cannot be assigned reliably under the triage rules. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
