### ISSUE TITLE
[EPIC] Resource and Process API migration to REST

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#17674]
## Introduction

This increment aims to provide REST API endpoints for deploying resources, deleting resources, and starting process instances. Message correlation is included here as it may also start process instances.

### Gateway

- [x] camunda/camunda#21054
- [x] camunda/camunda#21055
- [x] camunda/camunda#21056
- [x] camunda/camunda#21057

### Java client

- [x] camunda/camunda#22191
- [x] camunda/camunda#22192
- [x] camunda/camunda#22193
- [x] camunda/camunda#22194

### Documentation

- [x] camunda/camunda-docs#4442

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub (internal)](https://github.com/camunda/product-hub/issues/2040)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1r_PRe6xgAH-IcN3OPGUiee4ey93BKWF5iH_hy3cH-5o/edit#heading=h.s3ld46mi140)

**Comment by tmetzke** [comment]
All endpoints have been defined in our internal overview.

**Comment by tmetzke** [comment]
@nicpuppa, I added a placeholder item for `Document file size Spring configuration for "deploy resources" endpoint`
