### ISSUE TITLE
[EPIC] Job API migration to REST

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#17672]
## Introduction

This increment migrates existing gRPC Job APIs to the REST API.

### Gateway

- [x] #17676
- [x] #20080
- [x] #20081
- [x] #20082
- [x] #20083
- [x] #20085
- [x] https://github.com/camunda/camunda/issues/20897

### Java client

- [x] #18256
- [x] #21167
- [x] #21377
- [x] #21412
- [x] #21523
- [x] #21430

### Documentation

- [x] https://github.com/camunda/camunda-docs/issues/3918
- [x] Complete Job REST API is documented (done with https://github.com/camunda/camunda-docs/pull/4098)
- [x] Fail Job REST API is documented (done with https://github.com/camunda/camunda-docs/pull/4098)
- [x] Throw error REST API is documented (done with https://github.com/camunda/camunda-docs/pull/4098)
- [x] Update job retries and timeout REST API is documented
- [x] Resolve incident REST API is documented (done with https://github.com/camunda/camunda-docs/pull/4098)

### Out of scope

- Job streaming will not be migrated to the REST API and will stay on gRPC only.

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub (internal)](https://github.com/camunda/product-hub/issues/2040)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1r_PRe6xgAH-IcN3OPGUiee4ey93BKWF5iH_hy3cH-5o/edit#heading=h.3y5soesyr478)

**Comment by tmetzke** [comment]
## REST Endpoint design

### Considerations

* For the Zeebe user tasks, we discussed how to tackle multiple operations as well and (internally) [decided for separate endpoints](https://docs.google.com/document/d/1W4XA74hmD8mpRucIBeupBe3KoTfAYR2iQ57n_Pf43U8/edit#bookmark=id.wabgstnbvybe) per action and one PATCH endpoint to adjust all "simple" values.

### Options

#### Separate endpoints for actions, patch endpoint for "simple" values

* Complete, fail, error, and resolve incident are separate POST endpoints, e.g. `POST /v2/jobs/{jobKey}/completion`, `POST /v2/jobs/{jobKey}/failure`.
* Updating `retries` and `timeout` can be done via a PATCH endpoint (both or one of them).

##### Pros

* Design is close to what we have in gRPC: each action has an endpoint.
* Separation of concerns: each endpoint has exactly one functionality to cover.
* Self-explanatory: choosing good naming gives away the endpoints' functionality without much (or any) documentation.
* Simplicity: each endpoint is easy to grasp and stable (only minimal changes to expect for each endpoint).
* Consistency: experience aligned with user tasks, with POST endpoints for actions and one general PATCH endpoint for simple updates.

##### Cons

* Design is not super RESTful with POST endpoints for actions. We're updating the `status` of a job resource and could provide an endpoint that does that.
* Users have to discover multiple endpoints to achieve their goals.

#### One PATCH endpoint to rule them all

* All operations can be executed via a single PATCH endpoint with different `status` values and attributes that are only viable for specific values of the `status`.

##### Pros

* Design is very RESTful as we're updating the `status` of a job resource and providing an endpoint that does exactly that.
* Users only need to discover one endpoint to update a job.

##### Cons

* Error-prone: only specific attributes of the endpoint can be used based on the chosen value of the `status`. Using the wrong attributes or missing the required ones is more likely.
* Complex endpoint: the endpoint triggers very different actions in the engine based on the value of the `status` attribute and others. Grasping all implications of the endpoint is complex.
* Documentation-heavy: without documentation, it is almost impossible to understand what attributes to use in combination.
* Inconsistent: the user task endpoints are structured in a way, providing separate endpoints for actions and one update endpoint for simple values.

### Decisions

**_TBD_**

**Comment by korthout** [comment]
Regarding https://github.com/camunda/camunda/issues/17672#issuecomment-2172546574, I'd like to share my learnings from building https://github.com/korthout/camunda-platform-rest-api. This project applies the second approach 'One PATCH endpoint to rule them all' to job actions. You can find it here: https://korthout.github.io/camunda-platform-rest-api/docs/api/update-job

You've already expressed all the pros and cons that I would raise myself. I'd like to add that the cons become exceedingly bad when expanding the number of actions aggregated by a single PATCH endpoint.

IMO, 'Separate endpoints for actions, patch endpoint for "simple" values' leads to simpler, easier to maintain, and easier to understand endpoints. IMO, this trumps the purist-REST argument and trumps the endpoint discovery argument.

Note that endpoint discovery can be made easier through well-designed documentation and documentation navigation, and postman templates.

Lastly, this approach is in line with previously made decisions regarding the `/user-tasks` endpoints. For example, [assigning a user task](https://docs.camunda.io/docs/next/apis-tools/zeebe-api-rest/specifications/assign-a-user-task/), and [unassigning a user task](https://docs.camunda.io/docs/next/apis-tools/zeebe-api-rest/specifications/unassign-a-user-task/) are separate endpoints. I'm all in favor of a unified API that applies the same approaches everywhere. A unified experience helps existing users to use other parts of the API without additional instructions.

So, I would not take the 'One PATCH endpoint to rule them all' approach again for our project.

**Comment by tmetzke** [comment]
Thanks a lot, @korthout, I totally agree with your viewpoint. I'm also in favor of the direction of separate endpoints per action 👍

**Comment by berkaycanbc** [comment]
@tmetzke I agree with Nico's comment https://github.com/camunda/camunda/issues/17672#issuecomment-2173669698. While the first option is not RESTful it is more intuitive and also used in public APIs (e.g. [GitHub star a gist](https://github.com/camunda/camunda/issues/17672#issuecomment-2173669698)). 

I still have a followup question: I saw we implemented an action using nouns `POST /user-tasks/:userTaskKey/completion` as we do for entities of the user task `POST /user-tasks/:userTaskKey/assignment`. Why did we choose to make actions as nouns instead of using verbs for actions e.g. `/complete`? IMO, using verbs for actions would clarify the distinction between altering an entity that belongs to a resource and performing action on an entity.

**Comment by tmetzke** [comment]
All REST endpoints have been defined and added to the [C8 REST API endpoint overview](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.t4xwt6arefiz) (links to the first of the job endpoints, the others follow it directly).
