### ISSUE TITLE
[EPIC] Process Instance and Decision API migration to REST

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#17675]
## Introduction

This increment is focused on expanding the support of process instance operations through the REST API.

### Gateway

- [x] #21212
- [x] #21209
- [x] #21207
- [x] #21208
- [x] #21210
- [x] #21211

### Java client

- [x] #22400
- [x] #22401
- [x] #22402
- [x] #22403
- [x] #22404
- [x] #22405

### Documentation

_Automatically done through the OpenAPI specification_

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- [Product Hub (internal)](https://github.com/camunda/product-hub/issues/2040)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1r_PRe6xgAH-IcN3OPGUiee4ey93BKWF5iH_hy3cH-5o/edit#heading=h.esj39lt8395z)

**Comment by tmetzke** [comment]
All endpoints have been defined in our internal overview.

**Comment by tmetzke** [comment]
All endpoints migrated to REST, closing this
