### ISSUE TITLE
🎯 Persistable Personal Task Filters

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#17689]
### Description

- [ ] https://github.com/camunda/product-hub/issues/2086
- [ ] https://github.com/camunda/product-design/issues/1415

#### Backend

 * [ ] ~~https://github.com/camunda/zeebe/issues/17713~~ (Won't be delivered on this iteration due to problems in the architecture of the endpoint)

#### Frontend

 * [ ] https://github.com/camunda/zeebe/issues/17714
 * [ ] https://github.com/camunda/zeebe/issues/17715
 * [ ] ~~https://github.com/camunda/zeebe/issues/17716~~ (Won't be delivered on this iteration due to problems in the architecture of the endpoint)
 * [x] https://github.com/camunda/camunda/issues/18823
 * [ ] Add tracking to new persistable filters: https://github.com/camunda/team-hto/issues/624
 * [ ] Update docs

### Definition of Ready - Checklist

- [ ] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] Edge cases and limitations are clear

### Acceptance Criteria

- [ ] All the TODO issues are done

**Comment by volodymyr-melnykc** [comment]
Event tracking for persistable task filters will be handled in https://github.com/camunda/team-hto/issues/624

**Comment by volodymyr-melnykc** [comment]
The documentation will be updated in https://github.com/camunda/camunda-docs/issues/3871
