### ISSUE TITLE
Provide dates of last successful operations

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#17704]
### Description
As part of the [automapping epic](https://github.com/camunda/zeebe/issues/17701), the backend API needs to provide the date of the last successful process instance migration. To achieve this, the backend API will return the date for each completed operation for a process instance.

### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in process instance details view
    Then I can get the date of the last migration from internal Operate API
```

### Acceptance Criteria

- [x] The `GET /api/process-instances/<instanceKey>` is extended and contains the field `completedDate` for each object in the `operations` list

### API

`GET /api/process-instances/<instanceKey>`

Response:

```
{
  "id": <String>,
  ...
  "operations": [
    {
      "id": <String>,
      ...
     "completedDate": <String | null>
    }
  ],
}

```

### Todo

- [x] `OperationDto` (API object) needs a new field `completedDate`
- [x] `OperationEntity` (database storage) needs a new field `completedDate`
- [x] `OperationTemplate` needs a new field `completedDate` (also schema json file)
- [x] [`OperationsManager::completeOperation`](https://github.com/camunda/zeebe/blob/c3110d98798853f0b471a7a6bcc22a66f70e4d71/operate/schema/src/main/java/io/camunda/operate/util/OperationsManager.java#L85-L85 ) needs to store date in `OperationEntity` (operation index)
     - [x] Check if method needs new `date` parameter 
     - [x] Update other usages of method
-  ~~[ ] Use `Record<ProcessInstanceRecordValue>::getTimestamp` to retrieve date like https://github.com/camunda/zeebe/blob/c3110d98798853f0b471a7a6bcc22a66f70e4d71/operate/importer-8_5/src/main/java/io/camunda/operate/zeebeimport/v8_5/processors/ListViewZeebeRecordProcessor.java#L502-L502~~

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [x] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [x] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [x] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [x] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)
