### ISSUE TITLE
🎯 Version Migration: Automapping for process activities during migration

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#17701]
### Description

This feature includes

- Automatic mapping of process activities in the mapping step in process instance migration mode. Activities with the same flow node id in the source and target process will be mapped automatically to speed up creating the migration plan.
- A tag in process instance details view which shows the date of the last successful migration (if there is any).

Links
- Product Hub: https://github.com/camunda/product-hub/issues/1831
- Designs: [Figma](https://www.figma.com/file/tnqak7ht4Hb4VCGygvLNFU/Version-Migration-HFW?type=design&node-id=1970-161194&mode=design&t=I7E1Eufl0D5NYFuy-0)
- Slack channel for updates and discussions: [#prj-operate-process-instance-migration](https://camunda.slack.com/archives/C061QD0H6DS)

### Iteration 1: core features, target: 8.6.0-alpha2

Each issue is an incremental improvement on it's own, so it's not necessary to introduce a feature flag.

#### Frontend

- [x] https://github.com/camunda/zeebe/issues/18538
- [x] https://github.com/camunda/zeebe/issues/18571
- [x] https://github.com/camunda/zeebe/issues/18573
- [x] https://github.com/camunda/camunda/issues/18761

#### Backend
- [x] https://github.com/camunda/zeebe/issues/17704

#### Frontend

- [x] https://github.com/camunda/zeebe/issues/18576
- [x] https://github.com/camunda/operate/issues/5799
- [x] https://github.com/camunda/operate/issues/6419
- [x] https://github.com/camunda/zeebe/issues/18574
- [x] https://github.com/camunda/zeebe/issues/18577
- [x] https://github.com/camunda/zeebe/issues/18541

### Definition of Ready - Checklist

- [x] The epic is broken down into backend and frontend tasks/features - if applicable
- [x] It is clear what will be delivered in each increment/alpha release
- [x] Edge cases and limitations are clear
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [x] Cross-team dependencies have been considered

### Acceptance Criteria

- [x] All the TODO issues are done
