### ISSUE TITLE
Update custom filters modal to support persistable filters

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#17715]
### Description

Witht he persistable filter we need to add an option for the users to save the filters in the custom filters modal.
We need to add a save button and second dialog to give a name to the filters

### TODO

- [ ] [Mocks](https://www.figma.com/file/vHwXlQ9noa0N3f4ECjQBqV/Tasklist-Filters?type=design&node-id=493-32839&mode=design&t=6inAL6IS9LpuyBfs-0)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by volodymyr-melnykc** [comment]
@vsgoulart This one already seems to be done. Can we close it?
