### ISSUE TITLE
Refactor tasks filters UI

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#17714]
### Description

Our current UI does not have enough space to add the persistable custom filters and Carbon does not have any built-in components that fulfills our needs.

### TODO

- [ ] [Adapt the UI to support a left collapsible bar like in the mocks](https://www.figma.com/file/vHwXlQ9noa0N3f4ECjQBqV/Tasklist-Filters?type=design&node-id=493-32839&mode=design&t=6inAL6IS9LpuyBfs-0)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
