### ISSUE TITLE
🎯 Listener Visibility in Operate

### ISSUE THREAD

**Issue by johanwelgemoed** [camunda/camunda#18026]
### Description

Check execution and incident data of Execution Listeners to understand process execution history.
For the first iteration the focus will be on execution listeners (the designs done for task listeners will still be relevant since the concepts remain the same).

Links
- Product Hub: https://github.com/camunda/product-hub/issues/2103
- Final Designs: [Figma HFW & Prototype](https://www.figma.com/file/zfOVIMNthZneqFiyUhWTP2/Listeners?type=design&node-id=1331%3A59443&mode=design&t=IJJpqnewzp4PDhrN-1) 
- Specifications: [Figma specifications](https://www.figma.com/file/zfOVIMNthZneqFiyUhWTP2/Listeners?type=design&node-id=1331%3A59466&mode=design&t=IJJpqnewzp4PDhrN-1)
- Resizable panels designs: [HFW & prototypes](https://www.figma.com/file/zfOVIMNthZneqFiyUhWTP2/Listeners?type=design&node-id=1331%3A51584&mode=design&t=IJJpqnewzp4PDhrN-1)
- [Design handover doc](https://docs.google.com/document/d/1oNPuZ1YQ6Dd96G_B0dLpyMcMyopJImrf5_dh0T7oc00/edit)
- [Design handover recording](https://camunda.zoom.us/rec/share/kahcfJSqw0V54qD0S8zmEzX4aMNm3zdoyUhrXW2CCLIllBXwmkAhNsqrFrVI5IN3.cY-vKhqkFQPB8JZy) Pass: s8SqNEr&
- Project Channel: https://camunda.slack.com/archives/C06CNGWTBAS

#### Backend

- [x] https://github.com/camunda/camunda/issues/17469
- [x] https://github.com/camunda/camunda/issues/18549
- [x] https://github.com/camunda/camunda/issues/19556
- [x] https://github.com/camunda/camunda/issues/21512
- [x] https://github.com/camunda/camunda/issues/21540

#### Frontend

- [x] https://github.com/camunda/zeebe/issues/18545
- [x] https://github.com/camunda/camunda/issues/20110

### Definition of Ready - Checklist

- [x] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] It is clear what will be delivered in each increment/alpha release
- [ ] Edge cases and limitations are clear
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [x] Cross-team dependencies have been considered

### Acceptance Criteria

- [ ] All the TODO issues are done
