### ISSUE TITLE
Operate backup retries on recoverable exceptions

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#18118]
### Description

Part of #17878 Topic 2:Retry on recoverable exceptions

Currently exceptions will acknowledged. In case of failed backup attempts witch recoverable exceptions Operate should retry a backup.
For example, if the database cluster is not available for a moment, then retry to create a backup.

### TODO

- [ ] Identify exceptions and classify into recoverable and non-recoverable exceptions
- [ ] Add a retry strategy for recoverable exceptions
- [ ] Make retry mechanism configurable

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | 🔥 High |
| **When** | ⚠️ Soon |
| **Confidence** | 0.91 |

---

### 📝 Rationale

Implementation work improving reliability of existing Operate backups through configurable retries, classified as Core Features operational/reliability work rather than a specific released-version defect.  

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
