### ISSUE TITLE
[EPIC] Complete Zeebe REST API infrastructure

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#18254]
**Introduction**

With https://github.com/camunda/product-hub/issues/2039, we introduced the core infrastructure for the Zeebe REST API.
As a follow-up, the infrastructure needs extensions for convenient testing, metrics tracking, reliable startup, and ease of REST controller building.

## Task Breakdown

```[tasklist]
### Gateway API
- [ ] https://github.com/camunda/zeebe/issues/17492
- [ ] https://github.com/camunda/camunda/issues/19524
- [ ] https://github.com/camunda/camunda/issues/19977
- [ ] https://github.com/camunda/camunda/issues/19986
- [ ] https://github.com/camunda/zeebe/issues/17441
- [ ] https://github.com/camunda/camunda/issues/22540
```

```[tasklist]
### Java client
- [ ] https://github.com/camunda/zeebe/issues/16643
- [ ] https://github.com/camunda/zeebe/issues/16677
- [ ] https://github.com/camunda/camunda/issues/19374
- [ ] https://github.com/camunda/zeebe/issues/16557
- [ ] https://github.com/camunda/camunda/issues/21173
- [ ] https://github.com/camunda/camunda/issues/19883
```

```[tasklist]
### Metrics
- [ ] https://github.com/camunda/zeebe/issues/17442
```

## Links

- [Product Hub (internal)
](https://github.com/camunda/product-hub/issues/2040)
- [Zeebe breakdown document (internal)](https://docs.google.com/document/d/1r_PRe6xgAH-IcN3OPGUiee4ey93BKWF5iH_hy3cH-5o/edit#heading=h.g6vkdo5j5lxo)
