### ISSUE TITLE
Operate NPE in FlowNodeInstanceReader::searchForIncidents  

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#18322]
### Description

Found in Stackdriver errors version `8.5.0`:

NPE in `FlowNodeInstanceReader::searchForIncidents`

Stacktrace:
```
java.lang.NullPointerException: Cannot invoke "io.camunda.operate.entities.FlowNodeType.equals(Object)" because "flowNodeType" is null

at io.camunda.operate.webapp.elasticsearch.reader.FlowNodeInstanceReader.searchForIncidents ( io/camunda.operate.webapp.elasticsearch.reader/FlowNodeInstanceReader.java:712 )
at io.camunda.operate.webapp.elasticsearch.reader.FlowNodeInstanceReader.getMetadataByFlowNodeId ( io/camunda.operate.webapp.elasticsearch.reader/FlowNodeInstanceReader.java:919 )
at io.camunda.operate.webapp.elasticsearch.reader.FlowNodeInstanceReader.getFlowNodeMetadata ( io/camunda.operate.webapp.elasticsearch.reader/FlowNodeInstanceReader.java:136 )
at io.camunda.operate.webapp.rest.ProcessInstanceRestService.getFlowNodeMetadata ( io/camunda.operate.webapp.rest/ProcessInstanceRestService.java:267 )
at io.camunda.operate.webapp.rest.ProcessInstanceRestService$$SpringCGLIB$$0.getFlowNodeMetadata
```
### TODO

- [ ] Add null guard

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | 🔥 High |
| **Confidence** | 0.86 |

---

### 📝 Rationale

Concrete NPE in released Operate 8.5.0 when flowNodeType is null. Operate web applications are within Core Features scope. The failure indicates production request/UI impact without evidence of data loss; occurrence scope is unknown, so likelihood is HIGH per the triage rules.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
