### ISSUE TITLE
Camunda exporter: propagate an `OperationReference` along with Zeebe commands, and use it to mark operations as completed

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#18372]
### Description

Currently when importing some of Zeebe records we need to complete corresponding operations (e.g. [when process instance is cancelled](https://github.com/camunda/zeebe/blob/main/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java#L261)). For that we first [find operations to update](https://github.com/camunda/zeebe/blob/main/operate/schema/src/main/java/io/camunda/operate/util/OperationsManager.java#L94) and then send an update request. Since we must avoid any queries from Elasticsearch when performing Operate export we need to rework this logic and update operations based on an `operationReference` that operations should pass along with zeebe commands and expect it back in the exported records.
 
Depends on [#16916](https://github.com/camunda/zeebe/issues/16916).

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/24027
- [ ] https://github.com/camunda/camunda/issues/24028
- [ ] https://github.com/camunda/camunda/issues/24255
- [ ] https://github.com/camunda/camunda/issues/24029
- [ ] https://github.com/camunda/camunda/issues/24030
```

**Comment by mustafadagher** [comment]
I had a look at this issue partly yesterday and today, and I have a few observations:
1. The ticket title and description are outdated. As per https://github.com/camunda/camunda/pull/18669, we allowed zeebe clients/users to provide an `operationReference` to commands.
2. We do not care then about `requestId`s or `partitionId`, and we should not expect zeebe responses to contain them.

The task breakdown should now be:
1. We need to find a way to create a unique id (long), use it as a reference to send to with commands to zeebe.
2. We need to store this reference somewhere (probably in operation entity)
3. use that operation reference to co-relate between commands and records handled

The open questions here would be, 
- where (or at which point) to generate this unique key? 
- and is the operation entity the best place to store it? is it actually stored somewhere? or only in the runtime?
- When we say `mark operation as completed`, what do we actually mean? just setting the `operationEntity.state` or should we add it to a batch again? what does that entail? I'm confused because I had a quick look at the `OperationStore` in operate, and I noticed that it uses es/os. Are this going to stay the same?

CC: @Zelldon @sdorokhova

**Comment by sdorokhova** [comment]
Hey @mustafadagher , sorry I did not adjust the issue description based on how Zeebe part was implemented. I remember there were some back and forth on how we should proceed, looks like I did not check the final decision.

>where (or at which point) to generate this unique key? (I noticed that the operation entity has a generated id of type UUID, if we had known this fact during implementing the operation reference in zeebe, we could have accustomed to it)

I think we discussed that long value is preferable over UUID due to performance reasons 🤔 Anyway, I don't see any problems in just start writing the new operations with new long ids. They won't ever collide with older UUID. Or do you see the problem here?

>and is the operation entity the best place to store it? is it actually stored somewhere? or only in the runtime?

I'm not sure that I got this question. Operation are stored in operation index, as we execute operations asynchronously. 
I imaging that the workflow will be:
1. Create unique id and store the operation with this id in Elastic. This must happen when the user calls REST API to schedule some operation(s).
2. Send this id as `operationReference` when executing the operation (this will be in `OperationHandler` subclasses)
3. Update the operation as completed in export handler (correlate by `operationReference`)

> When we say mark operation as completed, what do we actually mean? 

Currently completion means [this](https://github.com/camunda/camunda/blob/670c89efbbc170af7ddf11ed694241ca8f64b721/operate/schema/src/main/java/io/camunda/operate/util/OperationsManager.java#L151).
But I don't think that we will be able to update batch operation without performing the search query. I need to refresh my knowledge what was our idea about it 🤔  For now I would say that it's enough to update single operation (`OperationEntity`) the same way it's done in referenced code. What is confusing you about ES/OS thing? We will need to do in "exporter style".

**Comment by mustafadagher** [comment]
> I think we discussed that long value is preferable over UUID due to performance reasons

Yes, that's true. I just didn't know we have already and id we use that is UUID. I would have argued with the `performance-advocates` at zeebe with this argument (just kidding 😄 ). 

>they won't ever collide with older UUID. Or do you see the problem here?
it's not a problem, no. we can definitely create and use long ids, but we should find a new field to store this id/reference(I think, because if we try to query an old one that has a uuid, the casting will fail). 
And we need to agree on a way to generate this number and ensure its uniqueness. (In zeebe we use SnowflakeIdGenerator, but I'm not sure that would work here)

>What is confusing you about ES/OS thing?
what is confusing me is that this OperationsManager/OperationStore has direct access to ES/OS, and I wasn't sure if that should still exist. 
And to do it through the `ExportHandler`s is going to be tricky because we don't have access to the batch request except for during `flush`. So I guess we will have to port this `OperationEntity` to the webapps-schema, and create a special handler for it. But I also can't imagine how will that work.

If my explanation above is not clears, that shows exactly how confused I am 😄

**Comment by mustafadagher** [comment]
I just had a sync meeting with @sdorokhova about this issue, and here are some points and decisions we came up with:

- **Where to get the `operation reference` when sending it to zeebe client?**

_We can rely on [OperationEntity](https://github.com/camunda/camunda/blob/main/operate/schema/src/main/java/io/camunda/operate/entities/OperationEntity.java) `id` right now and change [generateId()](https://github.com/camunda/camunda/blob/a60cdd2579ff109fa19632536eb64ad1f97ec2a1/operate/schema/src/main/java/io/camunda/operate/entities/OperationEntity.java#L215-L217) to generate a long value instead of a `UUID`._

- **How to generate this operation reference and ensure its uniqueness?**

_We can rely on `uuid.getMostSignificantBits()` for now. 100% uniqueness is not a great deal for operate, specially when it comes to operation, and the rare chance of collision using  `uuid.getMostSignificantBits()` can/shall be tolerated._

- **Now that we are changing the id to become a long instead a UUID, what happens if an operation gets schedule before updating to the new version, and then parsing the wrong format `Id` fails?**

_We can ignore the operations we fail to parse their Ids. It's a rare case and will happen only for a temporary period during migration_

- **In operate, we also updated [BatchOperationEntity](https://github.com/camunda/camunda/blob/main/operate/schema/src/main/java/io/camunda/operate/entities/BatchOperationEntity.java) by decrementing total operations counts when completing an operation related to this batch, this won't be possible in the exporter since we have no knowledge about the batch operation id available during exporting, what should happen to that logic?**

_This could either be combined with post-importer actions, or handled separately in the operate webapp_

- **There’s still an open question regarding variable modifications, we update several variables from the same modification operation entities. Should we send the same reference, it could happen that we update the operation as completed when there still some variable being processed**


For now, this would be the next steps, unless something else appears up along the way:

- [ ] Move [OperationEntity](https://github.com/camunda/camunda/blob/main/operate/schema/src/main/java/io/camunda/operate/entities/OperationEntity.java) to the `Webapps-schema` module, and update the `generateId()` to use the `uuid.getMostSignificantBits()`
- [ ] Update all operate's OperationHandlers to send the `operationReference` along with the underlying zeebe commands
- [ ] Create an `ExporterHandler` for each operation handler record type, and that should mark the operation as `completed`
- [ ] Get rid of the current operation completion logic in operate
- [ ] Create an issue to handle BatchOperation modification and completion in post-importer or operate

I'll create sub-tasks for the breakdown above tomorrow, and will collaborate with @sdorokhova to add more context to the tickets

**Comment by mustafadagher** [comment]
I also updated the title and the description, and added a basic task breakdown to the ticket.
