### ISSUE TITLE
[Root task] Dynamic Schema Update

### ISSUE THREAD

**Issue by nathansandi** [camunda/camunda#18484]
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/18486
- [ ] https://github.com/camunda/zeebe/issues/18487
- [ ] https://github.com/camunda/zeebe/issues/18488
- [ ] https://github.com/camunda/camunda/issues/18853
```
