### ISSUE TITLE
Create new Listeners tab on node details panel

### ISSUE THREAD

**Issue by vitorwtavares** [camunda/camunda#18545]
### Description

This issue is part of #18026 Listener Visibility in Operate epic.

On the process instance page, when a flow node is selected there is a panel with different tabs.
We need to create a new Listeners tab with a list of the Listener jobs for a specific node, as well as incident indicators.

### TODO

- [ ] Mock new endpoint response
- [ ] Show Listeners tab conditionally based on if there are any listeners attached to selected node
- [ ] Add incident icon on the tab conditionally if any Listener job has an incident
- [ ] Create dropdown to select type of Listener
- [ ] Create new type for Listener job instance
- [ ] Display Listeners jobs list on table
- [ ] Consume new endpoint to get Listeners jobs list for each node

### Additional Information

- Epic link: https://github.com/camunda/zeebe/issues/18026

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
