### ISSUE TITLE
Remove source/target dropdown header in confirm step of instance migration mode

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#18577]
### Description

The source/target dropdown header can be removed in the confirm step of instance migration mode, because all information is already shown in the notification banner.

![image](https://github.com/camunda/operate/assets/2543743/3c56ab5d-7ab9-45ff-bbd9-4a4eae7a6ccb)

### TODO

- [x] Remove source/target dropdown header in confirm step
- [x] Keep the dropdown in mapping step

### Additional Information

Design issue: https://www.figma.com/design/tnqak7ht4Hb4VCGygvLNFU/Version-Migration-HFW?node-id=2808%3A328364&t=EpWVp0Rz3Aw2Hajq-1

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
