### ISSUE TITLE
Allow adding an exporter via an API

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#18752]
I can enable an exporter via an API and specify another exporterId to initialize the metadata from.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/18757
- [ ] https://github.com/camunda/camunda/issues/18808
- [ ] https://github.com/camunda/camunda/issues/18854
- [ ] https://github.com/camunda/camunda/issues/18962
- [ ] https://github.com/camunda/camunda/issues/18855
- [ ] https://github.com/camunda/camunda/issues/19022
```

**Comment by npepinpe** [comment]
I've amended the title to avoid confusion - you can't _add_ exporters, just enable them :smile:
