### ISSUE TITLE
Set `routing` to particular request instead to `BulkRequest`

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#18760]
### Description

`Routing` parameter is set in wrong place. Instead of setting `routing` in `BulkRequest` it should be set on the each particular request. See below

Related to #https://github.com/camunda/operate/issues/6149

### TODO

- [x] Backport `.routing` changes to 
    - [x] `8.4`  https://github.com/camunda/operate/pull/6752
    - [x] `8.3`  https://github.com/camunda/operate/pull/6753
    ~~- [ ] `8.2`~~ Affected component does not exists here

https://github.com/camunda/camunda/pull/17057:

https://github.com/camunda/zeebe/blob/7e3c2a0584da09258ae4fd56008e75dbbc70a2d6/operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchBatchRequest.java#L89-L89

```java
    .routing(routing));
```

 - [x] Check for other occurrences where routing is used on `BulkRequest`
 
### Additional Information

This was fixed in [main](https://github.com/camunda/zeebe) by [camunda/zeebe#17057](https://github.com/camunda/zeebe/pull/17057/files#diff-8edd6c0fbbeeb0546671f6fa01c1e312ad6e3f9ecd6f1f163ecdc1b202cdafdc) and in [8.5](https://github.com/camunda/zeebe/tree/stable/operate-8.5) by [camunda/zeebe#18270](https://github.com/camunda/zeebe/pull/18270/files#diff-8edd6c0fbbeeb0546671f6fa01c1e312ad6e3f9ecd6f1f163ecdc1b202cdafdc).

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [x] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description and testable acceptance criteria
- [x] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [x] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [x] Potential Security risks have been considered
- [x] Cross-team dependencies have been considered
