### ISSUE TITLE
Investigate and fix multi tenancy dropdown test failures

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#18791]
### Description
The following tests started to fail after a dependency upgrade of @carbon/react from [v1.57.0 to v1.58.0](https://github.com/camunda/camunda/pull/18734).

`FAIL src/App/Processes/ListView/Filters/tests/multiTenancy.test.tsx`
`<Filters /> › should clear decision name and version field when tenant filter is changed`

`FAIL src/App/Decisions/Filters/tests/multiTenancy.test.tsx`
`Filters › should clear process and version field when tenant filter is changed`

### TODO
- [ ] unskip the two mentioned tests
- [ ] investigate and fix the problem

### Additional Information

```
 FAIL src/App/Processes/ListView/Filters/tests/multiTenancy.test.tsx
  ● Filters › should clear process and version field when tenant filter is changed

    expect(element).toHaveValue()

    Expected the element to have value:

    Received:
      Big variable process

      232 |     await waitFor(() => expect(processesStore.state.status).toBe('fetched'));
      233 |
    > 234 |     expect(screen.getByLabelText('Name')).toHaveValue('');
          |                                           ^
      235 |     expect(
      236 |       screen.getByLabelText('Version', {selector: 'button'}),
      237 |     ).toHaveTextContent(/select a process version/i);

      at Object.<anonymous> (src/App/Processes/ListView/Filters/tests/multiTenancy.test.tsx:234:43)

FAIL src/App/Decisions/Filters/tests/multiTenancy.test.tsx
  ● <Filters /> › should clear decision name and version field when tenant filter is changed

    expect(element).toHaveValue()

    Expected the element to have value:

    Received:
      Assign Approver Group

      246 |     );
      247 |
    > 248 |     expect(screen.getByLabelText('Name')).toHaveValue('');
          |                                           ^
      249 |     expect(
      250 |       screen.getByLabelText('Version', {selector: 'button'}),
      251 |     ).toHaveTextContent(/select a decision version/i);

      at Object.<anonymous> (src/App/Decisions/Filters/tests/multiTenancy.test.tsx:248:43)


```

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by pedesen** [comment]
Outcome: The test failures are related to the Carbon ComboBox component, which introduced bugs with the v1.58.0 dependency upgrade. There is currently no workaround available so the dependency update gets reverted.
