### ISSUE TITLE
Persist custom filters via `localStorage`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#18823]
### Description

Instead of https://github.com/camunda/camunda/issues/17716 we'll persist the custom filters via `localStorage`

### TODO

- [ ] Add option of setting a name to a filter
- [ ] Persist it via `localStorage`

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
