### ISSUE TITLE
Update @carbon/react dependency once bugfix was provided for Carbon

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#18851]
Depends on https://github.com/carbon-design-system/carbon/issues/16565

### Description

Upgrade @carbon/react dependency once bug fix was provided for the ComboBox component in Carbon (see: https://github.com/carbon-design-system/carbon/issues/16565)

### TODO

- [ ]  bump @carbon/react dependency
- [ ] remove @carbon/react from the excluded list of dependencies in `.git/renovate.json`

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by pedesen** [comment]
This has been fixed with `@carbon/react` v11.68.0

**Comment by pedesen** [comment]
:heavy_check_mark: The [bug](https://github.com/carbon-design-system/carbon/issues/16565) where the value was not updated properly was fixed

:x: But there is now another bug: the onChange callback is called twice when clearing the input field. I opened an issue here: https://github.com/carbon-design-system/carbon/issues/18137.

This again prevents us from upgrading the `@carbon/react` dependency, because it causes unexpected behavior in the Operate UI.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.
