### ISSUE TITLE
Camunda exporter creates and updates Operate schema

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#19006]
### Description

Since Operate exporter is filling the Operate indices with data, exporter will also be responsible for creating and updating Operare indices. 

### TODO

- [x] create new Maven module that will store entities and index descriptor classes for all web apps #22274
- [x] move Operate entities to the new module: #22310
- [ ] move index and template descriptors as well as schema mapping JSONs to the new module: https://github.com/camunda/camunda/pull/22802
- [ ] ~~make sure that exporter creates proper schema on startup~~ -> another issue #22804
---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by RomanJRW** [comment]
@sdorokhova - bumping here in case you missed the above in your absence

**Comment by sdorokhova** [comment]
Hi @RomanJRW , sorry, missed your question (two times 🙈 )

We're implementing the same functionality that we have in Operate right now, which will include configuring shards and replica counts (one for all indices, or per index) and ILM.

**Comment by RomanJRW** [comment]
@sdorokhova - all good, thanks for the response! 👍

**Comment by sdorokhova** [comment]
One note or retry logic. In Operate we executed both schema creation and update with retry logic so that if Elastic is not available Operate won't fail to startup but rather will wait for some time for Elastic to come back.
In Camunda exporter we're not doing this in schema manager logic, but instead `CamundaExporter#open` method will be retried in case of failure (see https://github.com/camunda/camunda/issues/20728).
