### ISSUE TITLE
[EPIC] Support `deployment` version binding for linked resources

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda#19384]
## Introduction
The goal of this epic is to add support for `deployment` version binding for linked resources to Zeebe, similar to what already exists in Camunda 7. This should give users a simple and safe way to reference resources that belong together in a process solution.

Currently, when a sub process, decision or form is linked from a BPMN process, Zeebe will always resolve this link to the latest known version of the target resource which might lead to unexpected behavior. With this epic, it will be possible instead to make Zeebe resolve a link reliably within the same "deployment unit".

## Task Breakdown

```[tasklist]
### BPMN Model API
- [ ] https://github.com/camunda/camunda/issues/19461
- [ ] https://github.com/camunda/camunda/issues/20054
``` 

```[tasklist]
### Engine
- [ ] https://github.com/camunda/camunda/issues/19859
- [ ] https://github.com/camunda/camunda/issues/19709
- [ ] https://github.com/camunda/camunda/issues/19710
- [ ] https://github.com/camunda/camunda/issues/19712
```

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/4124
```

```[tasklist]
### Misc
- [ ] https://github.com/camunda/web-modeler/issues/10093
```

### Out of scope
- https://github.com/camunda/camunda/issues/20067

## Other Teams

- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues):
  - https://github.com/camunda/camunda-modeler/issues/4385
  - https://github.com/camunda/camunda-modeler/issues/4386

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/1920

**Comment by tmetzke** [comment]
Hey @jfriedenstab, I was looking at this feature in the context of the C8 REST API and I was wondering:
Is there a specific reason we don't support this for start event forms as well? We support this for user task forms but not for start events.
