### ISSUE TITLE
Does not always respect scope of local variable when completing job

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#19441]
**Describe the bug**

Zeebe does not respect the scope of a local variable when completing a job with that same variable (name and value). Instead, it produces a new global variable with that name and value.

**To Reproduce**

- deploy a process with:
  - an embedded subprocess with an input mapping creating a local variable `x=1`
  - a nested service task inside the subprocess
- create an instance of this process
- complete the job with a variable `x=1`
- note that the variable is created both locally and globally 

A full reproducing test case can be found here: https://github.com/camunda/camunda/compare/stable/8.2...korthout-8.2-reproducing-reported-variable-scope-bug

**Expected behavior**

No global variable is created. The variable is only created locally. The variable at the local scope does not have to be updated because it's value stays the same.

**Environment:**
- Zeebe Version: 8.2 (and potentially others)

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | ⚠️ Mid |
| **Confidence** | 0.95 |

---

### 📝 Rationale

The issue describes a clear bug in Zeebe where completing a job with a local variable results in an unintended global variable, violating expected variable scoping. The report includes a clear problem statement, expected vs actual behavior, and reproduction steps. According to Core Features Bug Triage, this is a 'BUG'. Severity is 'MID' because it causes a noticeable impact on production usage (incorrect variable scoping) but does not result in data loss or critical system failure, and a workaround may exist. Likelihood is 'MID' as it is likely to affect some users or environments but is not described as universal or rare. The issue is in scope for Core Features per Team Boundaries.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.

**Comment by koevskinikola** [comment]
# Fix: job completion creates a spurious global variable when an unchanged value already exists in an intermediate scope (#19441)

## Summary

When a job is completed with a variable whose name **and value** already match a **local** variable in an
intermediate (non-root) scope — e.g. a variable created by an embedded subprocess input mapping — the engine
incorrectly **also** creates that variable at the process-instance (root) scope. The variable ends up
duplicated: once locally (correct) and once globally (the bug).

Expected: no global variable is created. The existing local variable is left untouched (its value is unchanged).

## Root cause

The defect is in `VariableBehavior.mergeDocument(...)`, file
`zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/variable/VariableBehavior.java`.

`mergeDocument` propagates a document of variables from the starting scope up the scope hierarchy. For each
scope it visits, it checks whether each variable already exists *locally* in that scope. When it finds a match
it is supposed to stop propagating that variable further up (it has found its home). The current condition only
does this when the value **differs**:

```java
// VariableBehavior.java (inside the while loop over parent scopes)
final VariableInstance variableInstance =
    variableState.getVariableInstanceLocal(currentScope, entry.getName());

if (variableInstance != null && !variableInstance.getValue().equals(entry.getValue())) {
  applyEntryToRecord(entry);
  stateWriter.appendFollowUpEvent(
      variableInstance.getKey(), VariableIntent.UPDATED, variableRecord);
  variableEvents.add(
      new VariableEvent(
          currentScope, VariableIntent.UPDATED, getVariableRecordCopy(variableRecord)));
  entryIterator.remove(); // <-- only removed when the value changed
}
```

When the variable exists in the current scope **with the same value**, the condition is `false`, so
`entryIterator.remove()` never runs. The entry stays in the document and keeps propagating upward until it
reaches the root scope, where the final block of the method creates it via `setLocalVariable` → a spurious
global `Variable.CREATED`.

### Why the existing tests miss it

Two tests in `VariableBehaviorTest` look related but do not cover this case:

- `shouldMergeDocumentWithoutUpdatingUnmodifiedVariable` places the unmodified variable at the **root** scope.
  There the final `setLocalVariable` block de-dupes it correctly, so the leak never appears.
- `shouldMergeDocumentWithoutPropagatingExistingVariables` only covers the **value-differs** case, where
  `entryIterator.remove()` does fire.

The bug requires the unmodified variable to live in an **intermediate** scope (the subprocess), which neither
test exercises.

## The fix

Remove the entry from the in-flight document whenever it already exists in the current scope, regardless of
whether the value changed. Emit a `Variable.UPDATED` follow-up event only when the value actually differs.

This matches the issue's expected behavior: "The variable at the local scope does not have to be updated because
its value stays the same."

**Side effect on conditional events (intended):** suppressing the spurious root `CREATED` also stops a phantom
`VariableEvent` from being fed into `conditionalBehavior.evaluateConditionals(...)` at the end of `mergeDocument`.
This is correct — a conditional/event-subprocess interrupt should not fire for a variable "change" that never
actually happened. No change to `evaluateConditionals` is needed.

---

## Implementation (TDD — write the failing tests first)

### Task 1: Unit test reproducing the leak in `mergeDocument`

**File (modify):**
`zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/VariableBehaviorTest.java`

Add the test below next to `shouldMergeDocumentWithoutPropagatingExistingVariables`. It sets `x` in an
**intermediate** scope with the **same** value as the document, starts the merge from a child scope, and asserts
that **no** variable event is produced at all — in particular, nothing is created at the root scope.

> Encoding note: the existing `setVariable(...)` helper packs the value as a MessagePack **string**. To exercise
> the "value unchanged" branch, the document must encode `x` to the *same* MessagePack bytes — so the document
> uses `Map.of("x", "1")` (string `"1"`), matching `setVariable(..., "x", "1")`. If the document used the integer
> `Map.of("x", 1)` instead, the bytes would differ, the merge would take the value-differs branch, and the bug
> would not reproduce.

- [ ] **Step 1 — Add the failing test:**

```java
@Test
void shouldNotPropagateUnmodifiedVariableExistingInIntermediateScope() {
  // given
  final long processDefinitionKey = 1;
  final long rootScopeKey = 1;
  final long subprocessScopeKey = 2;
  final long taskScopeKey = 3;
  final long subprocessVariableKey = 4;
  final String tenantId = TenantOwned.DEFAULT_TENANT_IDENTIFIER;
  final DirectBuffer bpmnProcessId = BufferUtil.wrapString("process");
  // String "1" on both sides so the MessagePack encodings match (see encoding note above)
  final Map<String, Object> document = Map.of("x", "1");
  state.createScope(rootScopeKey, VariableState.NO_PARENT);
  state.createScope(subprocessScopeKey, rootScopeKey);
  state.createScope(taskScopeKey, subprocessScopeKey);
  // 'x' already exists locally in the intermediate (subprocess) scope with the same value
  setVariable(subprocessVariableKey, subprocessScopeKey, processDefinitionKey, "x", "1");

  // when
  behavior.mergeDocument(
      taskScopeKey,
      processDefinitionKey,
      rootScopeKey,
      rootScopeKey,
      bpmnProcessId,
      tenantId,
      MsgPackUtil.asMsgPack(document));

  // then – no global variable is created and the unchanged local variable is not updated
  assertThat(getFollowUpEvents()).isEmpty();
}
```

- [ ] **Step 2 — Run it and confirm it FAILS** (on `main`, before the fix):

```bash
./mvnw verify -pl zeebe/engine \
  -Dtest=VariableBehaviorTest#shouldNotPropagateUnmodifiedVariableExistingInIntermediateScope \
  -DskipTests=false -DskipITs -Dquickly
```

Expected: FAIL — on `main` the loop visits the subprocess scope, finds `x` with an equal value, does **not**
remove it from the document, so it propagates to the root scope where it is created. `getFollowUpEvents()`
contains exactly one event: a `Variable.CREATED` for `x` at `scopeKey = rootScopeKey (1)`. The assertion
`isEmpty()` therefore fails. (If instead the test passes on `main`, the value encodings don't match — re-check
the encoding note.)

### Task 2: Apply the fix in `VariableBehavior.mergeDocument`

**File (modify):**
`zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/variable/VariableBehavior.java`

- [ ] **Step 1 — Replace the inner loop body** in `mergeDocument`. Change this block:

```java
        if (variableInstance != null && !variableInstance.getValue().equals(entry.getValue())) {
          applyEntryToRecord(entry);
          stateWriter.appendFollowUpEvent(
              variableInstance.getKey(), VariableIntent.UPDATED, variableRecord);
          variableEvents.add(
              new VariableEvent(
                  currentScope, VariableIntent.UPDATED, getVariableRecordCopy(variableRecord)));
          entryIterator.remove();
        }
```

to:

```java
        if (variableInstance != null) {
          if (!variableInstance.getValue().equals(entry.getValue())) {
            applyEntryToRecord(entry);
            stateWriter.appendFollowUpEvent(
                variableInstance.getKey(), VariableIntent.UPDATED, variableRecord);
            variableEvents.add(
                new VariableEvent(
                    currentScope, VariableIntent.UPDATED, getVariableRecordCopy(variableRecord)));
          }
          // The variable already lives in this scope; stop propagating it further up so it is not
          // re-created at the root scope. Only emit an UPDATED event when the value actually changed.
          entryIterator.remove();
        }
```

- [ ] **Step 2 — Run the Task 1 unit test and confirm it PASSES:**

```bash
./mvnw verify -pl zeebe/engine \
  -Dtest=VariableBehaviorTest#shouldNotPropagateUnmodifiedVariableExistingInIntermediateScope \
  -DskipTests=false -DskipITs -Dquickly
```

Expected: PASS.

- [ ] **Step 3 — Run the full `VariableBehaviorTest`** to confirm no regression in the existing merge/update/
  propagation cases (e.g. `shouldMergeDocumentWithoutPropagatingExistingVariables`,
  `shouldMergeDocumentPropagatingToRoot`, `shouldMergeDocumentWithoutUpdatingUnmodifiedVariable`):

```bash
./mvnw verify -pl zeebe/engine -Dtest=VariableBehaviorTest -DskipTests=false -DskipITs -Dquickly
```

Expected: PASS (all tests green).

### Task 3: Engine-level reproducer matching the issue exactly

Create a focused, non-parameterized engine test that reproduces the reported scenario end-to-end: an embedded
subprocess whose input mapping creates a local `x=1`, a nested service task, and completing that task's job with
`{"x": 1}`. Assert that `x` is created **once**, at the subprocess scope, and **never** at the process-instance
(root) scope.

> Here both the input mapping (`zeebeInputExpression("1", "x")`) and the job variables (`{'x': 1}`) produce the
> integer MessagePack `1`, so the values match naturally — no string workaround is needed (unlike the unit test,
> which uses string `"1"` only because its `setVariable` helper packs a string).

**File (create):**
`zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/JobCompletionVariableScopeTest.java`

- [ ] **Step 1 — Add the test class and failing test:**

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.engine.processing.variable.mapping;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;

import io.camunda.zeebe.engine.util.EngineRule;
import io.camunda.zeebe.model.bpmn.Bpmn;
import io.camunda.zeebe.protocol.record.Record;
import io.camunda.zeebe.protocol.record.intent.ProcessInstanceIntent;
import io.camunda.zeebe.protocol.record.intent.VariableIntent;
import io.camunda.zeebe.test.util.MsgPackUtil;
import io.camunda.zeebe.test.util.record.RecordingExporter;
import io.camunda.zeebe.test.util.record.RecordingExporterTestWatcher;
import java.util.UUID;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;

/** Reproduces https://github.com/camunda/camunda/issues/19441. */
public final class JobCompletionVariableScopeTest {

  @ClassRule public static final EngineRule ENGINE = EngineRule.singlePartition();

  private static final String PROCESS_ID = "process";
  private static final String SUBPROCESS_ID = "subprocess";
  private static final String TASK_ID = "task";

  @Rule
  public final RecordingExporterTestWatcher recordingExporterTestWatcher =
      new RecordingExporterTestWatcher();

  private String jobType;

  @Before
  public void init() {
    jobType = UUID.randomUUID().toString();
  }

  @Test
  public void shouldNotCreateGlobalVariableWhenCompletingJobWithLocalScopedVariable() {
    // given – a subprocess whose input mapping creates a local variable x=1, with a nested task
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(PROCESS_ID)
                .startEvent()
                .subProcess(
                    SUBPROCESS_ID,
                    s ->
                        s.zeebeInputExpression("1", "x")
                            .embeddedSubProcess()
                            .startEvent()
                            .serviceTask(TASK_ID, t -> t.zeebeJobType(jobType))
                            .endEvent())
                .endEvent()
                .done())
        .deploy();

    final long processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    final long subprocessScopeKey =
        RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
            .withProcessInstanceKey(processInstanceKey)
            .withElementId(SUBPROCESS_ID)
            .getFirst()
            .getKey();

    // when – the job is completed with the same variable name and value that already exists locally
    ENGINE
        .job()
        .ofInstance(processInstanceKey)
        .withType(jobType)
        .withVariables(MsgPackUtil.asMsgPack("{'x': 1}"))
        .complete();

    // then – `x` appears exactly once: a single CREATED at the subprocess scope.
    // No CREATED at the process-instance (root) scope, and no spurious UPDATED.
    // `limitToProcessInstance` terminates the stream once the instance completes, so the
    // assertion sees every variable record the instance produced.
    assertThat(
            RecordingExporter.records()
                .limitToProcessInstance(processInstanceKey)
                .variableRecords()
                .withName("x"))
        .extracting(Record::getIntent, r -> r.getValue().getScopeKey())
        .containsExactly(tuple(VariableIntent.CREATED, subprocessScopeKey));
  }
}
```

- [ ] **Step 2 — Run it and confirm it FAILS** (on `main`, before the fix):

```bash
./mvnw verify -pl zeebe/engine \
  -Dtest=JobCompletionVariableScopeTest -DskipTests=false -DskipITs -Dquickly
```

Expected: FAIL — the stream contains two `x` records:
`tuple(CREATED, subprocessScopeKey)` **and** `tuple(CREATED, processInstanceKey)` (the spurious global
variable) — so `containsExactly` fails on the unexpected second element.

- [ ] **Step 3 — With the Task 2 fix in place, run it and confirm it PASSES:**

```bash
./mvnw verify -pl zeebe/engine \
  -Dtest=JobCompletionVariableScopeTest -DskipTests=false -DskipITs -Dquickly
```

Expected: PASS.

### Task 4: Format, regression-check, commit

- [ ] **Step 1 — Format (mandatory before commit):**

```bash
./mvnw license:format spotless:apply -T1C
```

- [ ] **Step 2 — Run the broader job/variable test scope** to catch any propagation regressions:

```bash
./mvnw verify -pl zeebe/engine \
  -Dtest='VariableBehaviorTest,JobOutputMappingTest,ActivityOutputMappingTest,JobCompletionVariableScopeTest' \
  -DskipTests=false -DskipITs -Dquickly
```

Expected: PASS.

- [ ] **Step 3 — Verify the repo still compiles:**

```bash
./mvnw install -Dquickly -T1C
```

- [ ] **Step 4 — Commit** (keep the behavioral fix and its tests together; conventional commit):

```bash
git add zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/variable/VariableBehavior.java \
        zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/VariableBehaviorTest.java \
        zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/JobCompletionVariableScopeTest.java
git commit -m "fix: do not create global variable when completing job with unchanged local-scoped variable

mergeDocument kept propagating a variable up the scope hierarchy when it
already existed in an intermediate scope with an unchanged value, causing a
spurious global variable to be created at the root scope. Stop propagation
whenever the variable exists in the current scope; only emit UPDATED when the
value actually changed.

Closes #19441"
```

---

## Acceptance criteria

- Completing a job with a variable whose name and value already exist as a local variable in an intermediate
  scope produces **no** `Variable.CREATED` at the root/process-instance scope.
- The existing local variable is **not** updated when its value is unchanged (no `Variable.UPDATED` either).
- When the value **does** differ, the existing behavior is preserved: a single `Variable.UPDATED` at the scope
  where the variable lives, no propagation past it.
- `VariableBehaviorTest`, `JobOutputMappingTest`, `ActivityOutputMappingTest`, and the new
  `JobCompletionVariableScopeTest` all pass.

## Scope / non-goals

- Only the upward-propagation branch of `mergeDocument` changes. `mergeLocalDocument` (local-only, no
  propagation) and `setLocalVariable` are unaffected and must not be touched.
- No change to public APIs, records, or protocol.

## Backporting

The bug has existed since 8.2. Add backport labels for all currently-supported stable branches when opening the
PR: `backport stable/8.9`, `backport stable/8.8`, `backport stable/8.7`. (Confirm the active support window at PR
time and adjust if the set has changed.)

**Comment by koevskinikola** [comment]
This issue has been moved as a sub-task of https://github.com/camunda/camunda/issues/54335 to be resolved in a more general way. Initially, I resolved it with the following PR: https://github.com/camunda/camunda/pull/56197
