### ISSUE TITLE
🎯 Better visual indication of the executed path / steps in the process

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#19554]
### Description

This epic adds several improvements to the Operate instance detail user interface related to the visibility of executed paths:

- Highlighting executed/completed elements in the process diagram
- Adding badges to the process diagram to show the number of executed times for each element
- Accessibility improvements

PDP Epic: [Product Hub](https://github.com/camunda/product-hub/issues/274)
Designs: [Figma](https://www.figma.com/design/2iYV26UW5TwEhU4LooOCMF/Better-visualization-of-the-executed-path?node-id=1154-63379&t=MgdB8QPfonRNRNaw-0)
#### Backend

No backend work needed.

#### Frontend

* [x] https://github.com/camunda/camunda/issues/19555
* [x] https://github.com/camunda/camunda/issues/19558
* [x] https://github.com/camunda/camunda/issues/19562
* [x] https://github.com/camunda/camunda/issues/19567
* [x] https://github.com/camunda/camunda/issues/19615

### Definition of Ready - Checklist

- [x] The epic is broken down into backend and frontend tasks/features - if applicable
- [x] It is clear what will be delivered in each increment/alpha release
- [x] Edge cases and limitations are clear
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

### Acceptance Criteria

- [ ] All the TODO issues are done
