### ISSUE TITLE
Handle edge cases of message boundary event subscription migration 

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#19640]
## Description
After implementing message subscription migration with PR #18822, there are a few edge cases that are left uncovered. Currently these lead to unexpected rejections (the user sees a processing error and the error is logged in the broker). We need to add rejections/testcases for these:
- Map a message boundary event that is attached to a different element in the target as it was in the source.
- Map two message boundary events in the source to the same message boundary event in the target.
- A source has two message boundary events attached to an element. Map one to the other only. I think this is supposed to unsubscribe a message first, migrate one, and subscribe again. I'm not sure whether we can support this case right now.
- A source has two message boundary events attached to an element. In the target there is only one of those two left. Map the removed boundary event to the remaining boundary event, and don't provide a mapping from the other.

In some of these cases, I've seen the following exception, which we should also protect against:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "interrupting" is null
io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.lambda$handleCatchEvents$4(ProcessInstanceMigrationMigrateProcessor.java:436)
at java.base/java.util.ArrayList.forEach(Unknown Source
at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.handleCatchEvents(ProcessInstanceMigrationMigrateProcessor.java:424)
```
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/19956
- [ ] https://github.com/camunda/camunda/issues/19960
- [x] Verify special message boundary event removal cases
- [ ] https://github.com/camunda/camunda-docs/issues/4186
```

**Comment by korthout** [comment]
>A source has two message boundary events attached to an element. Map one to the other only. I think this is supposed to unsubscribe a message first, migrate one, and subscribe again. I'm not sure whether we can support this case right now.

✅ This case is currently limited by:
> Expected to migrate process instance '2251799813685252' but active element with id 'A' attempts to subscribe to a message it is already subscribed to with name 'msg1'. Migrating active elements that subscribe to a message they are already subscribed to is not possible yet. Please provide a mapping instruction to message catch event with id 'boundary1' to migrate the respective message subscription.

<details><summary>Test case</summary>
<p>

```java
@Test
public void shouldRejectCommandWhenSubscribingToMessageEventThatIsAlsoMapped() {
  final String processId = helper.getBpmnProcessId();
  final String targetProcessId = helper.getBpmnProcessId() + "2";

  final var deployment =
      ENGINE
          .deployment()
          .withXmlResource(
              Bpmn.createExecutableProcess(processId)
                  .startEvent("start")
                  .serviceTask("A", t -> t.zeebeJobType("A"))
                  .boundaryEvent(
                      "boundary1",
                      b ->
                          b.message(m -> m.name("msg1").zeebeCorrelationKeyExpression("key"))
                              .endEvent())
                  .moveToActivity("A")
                  .boundaryEvent(
                      "boundary2",
                      b ->
                          b.message(m -> m.name("msg2").zeebeCorrelationKeyExpression("key"))
                              .endEvent())
                  .moveToActivity("A")
                  .endEvent("end")
                  .done())
          .withXmlResource(
              Bpmn.createExecutableProcess(targetProcessId)
                  .startEvent("start")
                  .serviceTask("A", t -> t.zeebeJobType("A"))
                  .boundaryEvent(
                      "boundary1",
                      b ->
                          b.message(m -> m.name("msg1").zeebeCorrelationKeyExpression("key"))
                              .endEvent())
                  .moveToActivity("A")
                  .boundaryEvent(
                      "boundary2",
                      b ->
                          b.message(m -> m.name("msg2").zeebeCorrelationKeyExpression("key"))
                              .endEvent())
                  .moveToActivity("A")
                  .endEvent()
                  .done())
          .deploy();

  final long targetProcessDefinitionKey =
      extractProcessDefinitionKeyByProcessId(deployment, targetProcessId);
  final var processInstanceKey =
      ENGINE.processInstance().ofBpmnProcessId(processId).withVariable("key", "key").create();

  RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
      .withElementId("A")
      .await();

  // when
  final var rejection =
      ENGINE
          .processInstance()
          .withInstanceKey(processInstanceKey)
          .migration()
          .withTargetProcessDefinitionKey(targetProcessDefinitionKey)
          .addMappingInstruction("A", "A")
          .addMappingInstruction("boundary1", "boundary2")
          .expectRejection()
          .migrate();
```

</p>
</details>

**Comment by korthout** [comment]
>A source has two message boundary events attached to an element. In the target there is only one of those two left. Map the removed boundary event to the remaining boundary event, and don't provide a mapping from the other.

✅ This is already covered. It simply unsubscribes from one and migrates the other. This works as expected.
