### ISSUE TITLE
🎯 Execution Layer Identity exists as part of single-application

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda#19669]
### Description

https://github.com/camunda/product-hub/issues/2222

Identity as an application is integrated into Camunda Single-Application. It allows to manage authorizations for Camunda. This epic serves as an entrypoint

### TODO

```[tasklist]
### Epic breakdown
- [ ] https://github.com/camunda-cloud/identity/issues/2796
- [ ] https://github.com/camunda/camunda/issues/19734
- [ ] https://github.com/camunda/camunda/issues/19670
- [ ] https://github.com/camunda/camunda/issues/19671
- [ ] https://github.com/camunda/camunda/issues/19672
- [ ] https://github.com/camunda/camunda/issues/19673
- [ ] https://github.com/camunda/camunda/issues/19674
- [ ] https://github.com/camunda/camunda/issues/19675
- [ ] Identity supports PostgresQL, H2 and Aurora AWS databases
- [ ] https://github.com/camunda/camunda/issues/20400
- [ ] https://github.com/camunda/camunda/issues/22570
- [ ] https://github.com/camunda/camunda/issues/23810
```

### Definition of Ready - Checklist

- [ ] The epic is broken down
- [ ] It is clear what will be delivered in each increment/alpha release
- [ ] Edge cases and limitations are clear
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

**Comment by npepinpe** [comment]
Closing, as new issues replace this I think.
