### ISSUE TITLE
Camunda supports authentication with an external OIDC provider

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda#19672]
```[tasklist]
### In scope
- [ ] https://github.com/camunda/camunda/issues/19741
- [ ] https://github.com/camunda/camunda/issues/19742
- [ ] https://github.com/camunda/camunda/issues/19743
- [ ] https://github.com/camunda/camunda/issues/19771
- [ ] https://github.com/camunda/camunda/issues/19772
- [ ] Camunda should be able to fetch aggregated authorizations for a OIDC Authentication
- [ ] User should be able to Single Sign Out in all components when OIDC profile is active.
```

```[tasklist]
### Potentially out of scope
- [ ] Users can logout from Camunda if they are logged in via their own IDP (Single Sign Out)
- [ ] User sync on login (configurable)
- [ ] User group sync on login (configurable)
```

**Comment by npepinpe** [comment]
I'm pretty sure this is done, or at least, all parts we wanted to do.
