### ISSUE TITLE
Camunda supports granting authorizations for specific resources

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda#19674]
### Description
Authorization is a concept to define access permissions to a specific resource type and key. Conceptually the resource type can be every thing like bpmnProcessId, process definition id, process instance id, user task id and so on, but practically and mostly because of performance concerns we are limiting the resource type.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/20433
- [ ] https://github.com/camunda/camunda/issues/20442
- [ ] https://github.com/camunda/camunda/issues/20451
- [ ] https://github.com/camunda/camunda/issues/20454
- [ ] https://github.com/camunda/camunda/issues/20461
- [ ] https://github.com/camunda/camunda/issues/21794
- [ ] https://github.com/camunda/camunda/issues/21782
- [ ] https://github.com/camunda/camunda/issues/21778
- [ ] https://github.com/camunda/camunda/issues/21791
- [ ] https://github.com/camunda/camunda/issues/21792
- [ ] https://github.com/camunda/camunda/issues/21858
- [ ] https://github.com/camunda/camunda/issues/22064
- [ ] https://github.com/camunda/camunda/issues/22147
- [ ] https://github.com/camunda/camunda/issues/22626
- [ ] https://github.com/camunda/camunda/issues/22627
- [ ] https://github.com/camunda/camunda/issues/22625
- [ ] https://github.com/camunda/camunda/issues/20460
- [ ] Authorization services provide a boolean `hasPermission` for a given resource type, user, permission
- [ ] Authorization services provide a method to get all resource IDs for a given resource type, user, permission
- [ ] Role/Permission/Role membership migration to Authorization is documented
- [ ] Authorization management is documented
- [ ] https://github.com/camunda/camunda/issues/23797
- [ ] https://github.com/camunda/camunda/issues/25652
- [ ] https://github.com/camunda/camunda/issues/26594
```

**Comment by remcowesterhoud** [comment]
@remcowesterhoud Note to self. When implementing authentication validation refer to [this slack thread](https://camunda.slack.com/archives/C037W9NMATG/p1725976817780089)
