### ISSUE TITLE
Camunda supports local user management and authentication

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda#19734]
### Description
Camunda supports the ability to perform user management and authentication checks using basic auth.

### User management
- [x] https://github.com/camunda/camunda/issues/20398
- [x] https://github.com/camunda/camunda/issues/21672
- [x] https://github.com/camunda/camunda/issues/21673
- [x] https://github.com/camunda/camunda/issues/21695
- [x] Identity webapp supports user creation
- [ ] https://github.com/camunda/camunda/issues/20402
- [ ] Identity webapp supports user editing
- [ ] https://github.com/camunda/camunda/issues/20403
- [ ] Identity webapp supports deleting a user
- [x] https://github.com/camunda/camunda/issues/20405
- [x] Identity webapp supports viewing users
- [ ] User management is documented
- [ ] https://github.com/camunda/camunda/issues/21560
- [x] https://github.com/camunda/camunda/issues/21830
- [x] https://github.com/camunda/camunda/issues/22659
- [x] https://github.com/camunda/camunda/issues/24594
- [x] https://github.com/camunda/camunda/issues/25700

### Authentication
- [x] https://github.com/camunda/camunda/issues/20409
- [x] https://github.com/camunda/camunda/issues/22452
- [x] https://github.com/camunda/camunda/issues/22728
- [x] https://github.com/camunda/camunda/issues/22732
- [x] https://github.com/camunda/camunda/issues/22729
- [x] https://github.com/camunda/camunda/issues/22730
- [x] https://github.com/camunda/camunda/issues/22731
- [ ] https://github.com/camunda/camunda/issues/24595
- [x] https://github.com/camunda/camunda/issues/23093
- [x] https://github.com/camunda/camunda/issues/23907
- [ ] Basic authentication and session management are documented
- [x] https://github.com/camunda/camunda/issues/25416
- [x] https://github.com/camunda/camunda/issues/25542

**Comment by npepinpe** [comment]
Marking as done, please correct and re-open if not.
