### ISSUE TITLE
Camunda supports Token Mappings to grant Roles/Groups/Authorizations/Tenants based on access token data

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda#19743]
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/22633
- [ ] rest endpoint for create mapping rules
- [ ] ui for mapping rule creation
- [ ] backend for search mapping rules
- [ ] rest endpoint for search mapping rules
- [ ] ui for search mapping rules
- [ ] backend for retreive a mapping rule
- [ ] rest endpoint for retrieving a mapping rule
- [ ] ui to show the details of a mapping rule
- [ ] backend update a mapping rule
- [ ] rest endpoint for update a mapping rule
- [ ] ui supports update a mapping rule
- [ ] backend delete a mapping rule
- [ ] rest endpoint to delete a mapping rule
- [ ] ui supports deleting a mapping rule
```

**Comment by maryarm** [comment]
I have a proposal to instead of mapping rules/groups/tenants based on a token just map a token to special kind of user (I called it mappedUser and each token can be mapped to several of them) and then use the standard flow of assigning roles/groups and tenants to user. In [my conceptual code](https://github.com/camunda/camunda/pull/19796), it's some how reflected. I'd like to know your ideas about it and if it makes sense at all.

**Comment by dlavrenuek** [comment]
Token mapping should allow managing access without having actual users (the identity) on our side. Additionally mapping jwt to users would mean the identity is lost in it's process. For example
- a service account makes an api call to complete a service task with `{"sub": "serviceaccountA@teamA"}`
- a user access Tasklist with `{"sub":"some.user@teamA"}`

Both of these could have the same permissions allocated through a role (current implementation) or via a user (your proposal). When the requests are mapped to a user "teamA", then we can not log the actual identity (Use case: access logging, audit logs) and it will not work in case where customers don't want or can't store user data in our database (use case is not exactly clear to me since it would be a "fake user" but this could still lead to conceptual misunderstandings).

Also one reason to not change current implementation: it works and I don't know of customers' feedback that the concept should be changed

**Comment by Ben-Sheppard** [comment]
Closing this as its superseded by https://github.com/camunda/camunda/issues/23810
