### ISSUE TITLE
[EPIC] Support `version tag` binding for linked resources

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda#19812]
## Introduction
The goal of this epic is to add support for `version tag` binding for linked resources to Zeebe, similar to what already exists in Camunda 7.

Currently, when a sub process, decision or form is linked from a BPMN process, Zeebe will always resolve this link to the latest known version of the target resource – which is not always the intended behavior. With this epic, it will be possible to assign a custom version tag (like `v1.3.4`) to a resource and use this tag to bind a linked resource to this exact version (instead of the latest).

## Task Breakdown

```[tasklist]
### BPMN Model API
- [ ] https://github.com/camunda/camunda/issues/21124
- [ ] #21034
- [ ] https://github.com/camunda/camunda/issues/21161
```

```[tasklist]
### Engine
- [ ] #21035
- [ ] #21036
- [ ] #21037
- [ ] #21038
- [ ] #21040
- [ ] #21041
```

```[tasklist]
### Operate
- [ ] https://github.com/camunda/camunda/issues/21061
- [ ] https://github.com/camunda/camunda/issues/21062
``` 

```[tasklist]
### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/4221
```

## Other Teams
- [x] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues/4489)
  - [x] https://github.com/camunda/zeebe-bpmn-moddle/issues/59
  - [x] https://github.com/camunda/camunda-modeler/issues/4453
  - [x] https://github.com/camunda/camunda-modeler/issues/4454
  - [x] https://github.com/camunda/camunda-modeler/issues/4463
  - [x] https://github.com/camunda/camunda-modeler/issues/4460
  - [x] https://github.com/camunda/camunda-modeler/issues/4461
  - [x] https://github.com/camunda/camunda-modeler/issues/4462
  - [x] https://github.com/camunda/camunda-modeler/issues/4480
  - [x] https://github.com/camunda/camunda-modeler/issues/4481

## Links
- Product Hub (internal): https://github.com/camunda/product-hub/issues/435
- related epic: https://github.com/camunda/camunda/issues/19384

**Comment by nikku** [comment]
Integration PR (Desktop Modeler) - https://github.com/camunda/camunda-modeler/issues/4489.

**Comment by jfriedenstab** [comment]
Closing this epic, as everything has been completed except https://github.com/camunda/camunda/issues/21062 which will be tackled as a follow-up task.
