### ISSUE TITLE
Update spring-boot to a version >= 3.2.7

### ISSUE THREAD

**Issue by johanwelgemoed** [camunda/camunda#19820]
### Context

* Updating Spring Boot to 3.2.7 or higher updates
  * Spring Framework to 6.1.10 or higher
  * Tomcat to 10.1.25 or higher

### TODO
Update spring-boot to version `3.2.7` (or higher) for the following supported C8 versions
- 8.5.x
- 8.4.x
- 8.3.x
- 8.2.x

### Additional context
* https://jira.camunda.com/browse/SEC-1040
* https://jira.camunda.com/browse/SEC-1046

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):
