### ISSUE TITLE
REST API: Allow for tracking subscriptions

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda#19925]
### Description

Event correlation is an important factor of process execution. This is why it should be visible. I would like to be able to track:
* messages (including their correlation to element instances)
* signals (including their correlation to element instances)
* timers (with their due date, they are bound to an element instance, so I want to see the relation here)

### User Story

```Gherkin
Scenario: As an REST API consumer
    Given I have selected the flownode instance of an intermediate catch event
    When I want to see the event that has been correlated to it and I know which type of event it was
    Then I am able to load this item from the api to retrieve correlation details
```
### Acceptance Criteria

- [ ]

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by ThorbenLindhauer** [comment]
Has been picked up by Aleksander for planning. Will move to backlog.

**Comment by saig0** [comment]
With 8.8, we added new APIs for:
- Message subscriptions: https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/search-message-subscriptions/
- Correlated messages: https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/search-correlated-message-subscriptions/

@jonathanlukas I recomment to close this issue in favor of more fine granular issues.

**Comment by jonathanlukas** [comment]
@saig0 you are right, for messages this is done.

For signals and timers, I created new issues:

https://github.com/camunda/camunda/issues/44239

https://github.com/camunda/camunda/issues/44240
