### ISSUE TITLE
Avoid performing a lookup twice for `treePathCache`

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20027]
### Description

In `FlowNodeInstanceZeebeRecordProcessor` a cache is used to retrieve tree path for a flow node
This cache is used every time when process instance is processed.
A lookup in the cache involves usage of a lock. 

`FlowNodeInstanceZeebeRecordProcessor` calls twice the retrieving of the value.
This can be avoided.

### TODO

- [x] Retrieve only once the value for a key to avoid unnecessary locks.

### Additional Information

Related to [Support 22328](https://camunda.slack.com/archives/C077P3F763X)
Needs to be back ported to 8.6, 8.4, 8.3, 8.2

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
@ralfpuchert can we close this ticket?
