### ISSUE TITLE
Use one `treePathCache` per partition in `FlowNodeInstanceZeebeRecordProcessor` 

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20076]
### Description

In processing of process instances flow node instances will be updated in database.
To avoid searching for parents for each flow node instance a cache (treePathCache) is used.
To avoid conflicts by accessing the cache from different threads the cache should exist for each partition. Currently one cache is used for all.

### TODO

- [ ] Use one cache per partition in `FlowNodeInstanceZeebeRecordProcessor`
- [ ] Initialize the cache early not lazy in `FlowNodeInstanceZeebeRecordProcessor`

### Additional Information

- Related to [Support 22328](https://camunda.slack.com/archives/C077P3F763X)
- Needs to be backported into `8.2`, `8.3`, `8.4`, `8.5`, `8.6`

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
@ralfpuchert is there still open work here?
