### ISSUE TITLE
Camunda supports role management

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#20453]
### Description
Camunda supports role management

### Storage
- [ ] https://github.com/camunda/camunda/issues/22912
- [ ] https://github.com/camunda/camunda/issues/22913
- [ ] https://github.com/camunda/camunda/issues/22916
- [ ] https://github.com/camunda/camunda/issues/22927
- [ ] https://github.com/camunda/camunda/issues/22917
- [ ] https://github.com/camunda/camunda/issues/22930
- [ ] https://github.com/camunda/camunda/issues/22923
- [ ] https://github.com/camunda/camunda/issues/22938
- [ ] https://github.com/camunda/camunda/issues/22926
- [ ] https://github.com/camunda/camunda/issues/22940
- [ ] https://github.com/camunda/camunda/issues/22920
- [ ] https://github.com/camunda/camunda/issues/22934

### Exporters
- [ ] https://github.com/camunda/camunda/issues/23185
- [ ] https://github.com/camunda/camunda/issues/24459
- [ ] https://github.com/camunda/camunda/issues/24581
- [ ] https://github.com/camunda/camunda/issues/24582

### Service
- [ ] https://github.com/camunda/camunda/issues/23647
- [ ] https://github.com/camunda/camunda/issues/24402
- [ ] https://github.com/camunda/camunda/issues/24578
- [x] Camunda services support retrieving role(s)
- [ ] https://github.com/camunda/camunda/issues/24579
- [x] https://github.com/camunda/camunda/issues/24584
- [ ] https://github.com/camunda/camunda/issues/24583
- [x] Camunda services support assigning authorizations to a role
- [x] Camunda services support retrieving authorizations assigned to a role
- [x] Camunda services support removing authorizations from a role

### Webapp
- [x] Identity webapp supports role creation
- [x] Identity webapp supports role editing
- [x] Identity webapp supports role deletion
- [x] Identity webapp supports assigning users to a role
- [ ] Identity webapp supports assigning authorizations to a role

### API
- [ ] https://github.com/camunda/camunda/issues/22389

### Java client
- [ ] https://github.com/camunda/camunda/issues/25297
- [ ] Java client supports role editing
- [ ] Java client supports role deletion
- [ ] Java client supports updating users assigned to a role
- [x] Java client supports updating authorizations assigned to a role

### Migration app
- [ ] Migration service supports migration of old roles/permissions/roles memberships to new authorizations.

### Operational
- [ ] https://github.com/camunda/camunda/issues/25751

### Documentation
- [ ] Role management is documented
- [ ] Role migration is documented

**Comment by npepinpe** [comment]
Marking as done, please re-open if incorrect.
