### ISSUE TITLE
Camunda supports tenant management

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#20455]
### Description
Camunda supports functionality related to tenant management

### Storage
- [ ] https://github.com/camunda/camunda/issues/22840
- [ ] https://github.com/camunda/camunda/issues/22841
- [ ] https://github.com/camunda/camunda/issues/23104
- [ ] https://github.com/camunda/camunda/issues/23105
- [ ] https://github.com/camunda/camunda/issues/23106
- [ ] https://github.com/camunda/camunda/issues/23108
- [ ] https://github.com/camunda/camunda/issues/23112
- [ ] https://github.com/camunda/camunda/issues/23113
- [ ] https://github.com/camunda/camunda/issues/23115
- [ ] https://github.com/camunda/camunda/issues/23116
- [ ] https://github.com/camunda/camunda/issues/23118
- [ ] https://github.com/camunda/camunda/issues/23119
- [ ] https://github.com/camunda/camunda/issues/26110

### Exporters
- [ ] https://github.com/camunda/camunda/issues/23135
- [ ] https://github.com/camunda/camunda/issues/24590
- [ ] https://github.com/camunda/camunda/issues/24591
- [ ] https://github.com/camunda/camunda/issues/24589

### Service
- [ ] https://github.com/camunda/camunda/issues/23137
- [ ] https://github.com/camunda/camunda/issues/23138
- [ ] https://github.com/camunda/camunda/issues/23139
- [ ] https://github.com/camunda/camunda/issues/23149
- [ ] https://github.com/camunda/camunda/issues/23171
- [ ] https://github.com/camunda/camunda/issues/24877
- [ ] https://github.com/camunda/camunda/issues/25694

### API
- [x] https://github.com/camunda/camunda/issues/22390

### Webapp
- [ ] https://github.com/camunda/camunda/issues/23204
- [ ] https://github.com/camunda/camunda/issues/24934
- [ ] https://github.com/camunda/camunda/issues/25020
- [ ] https://github.com/camunda/camunda/issues/25021
- [ ] https://github.com/camunda/camunda/issues/25693

### Java client
- [ ] https://github.com/camunda/camunda/issues/24896
- [ ] https://github.com/camunda/camunda/issues/25018
- [ ] https://github.com/camunda/camunda/issues/25019
- [ ] https://github.com/camunda/camunda/issues/25721
- [ ] https://github.com/camunda/camunda/issues/25784
- [ ] https://github.com/camunda/camunda/issues/25591

### Migration app
- [ ] https://github.com/camunda/camunda/issues/25130
- [ ] https://github.com/camunda/camunda/issues/25133

### Operational
- [ ] https://github.com/camunda/camunda/issues/24639
- [ ] https://github.com/camunda/camunda/issues/24959
- [ ] https://github.com/camunda/camunda/issues/22842
- [ ] https://github.com/camunda/camunda/issues/25715
- [ ] https://github.com/camunda/camunda/issues/25718
- [ ] https://github.com/camunda/camunda/issues/25719
- [ ] https://github.com/camunda/camunda/issues/25720
- [ ] https://github.com/camunda/camunda/issues/25795
- [ ] https://github.com/camunda/camunda/issues/25982
- [x] https://github.com/camunda/camunda/issues/26502
- [ ] https://github.com/camunda/camunda/issues/26694

### Documentation
- [ ] Tenant managment is documented
- [ ] Tenant migration is documented
