### ISSUE TITLE
[EPIC] Handle C8 REST Query API availability

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#20579]
## Introduction

The Camunda 8 REST API features a partially introduced Query API with 8.6 that is (planned to be) completed with 8.7.
This part of the REST API has to be disabled by default with 8.6 and enabled with 8.7.
Before it is completed, its availability has to be configurable, i.e. it can be enabled via a configuration property.
When it is completed, its availability is not configurable any more.

## Concept

With 8.6, a new configuration property exists to enable the C8 REST Query API (e.g. search for user tasks and process instances). With the property being enabled, the respective REST controller beans are created in the REST gateway. Otherwise, the beans are not created and search paths are not accessible.

Since the Java client for Camunda 8 also contains parts of the Query API, the related commands are marked as `@ExperimentalApi` until the endpoints are enabled by default.

The REST API explorers in the public documentation as well as the OpenAPI specification of the C8 API declare the Query API endpoints with 8.6 already. The endpoints are however clearly marked as experimental and disabled by default.

### Before Query API is completed (8.6)

```[tasklist]
#### Gateway API
- [x] camunda/camunda#20580
- [x] camunda/camunda#22224
```

```[tasklist]
#### Java client
- [x] camunda/camunda#20596
```

```[tasklist]
#### Testing
- [x] camunda/camunda#20645
```

```[tasklist]
#### Documentation
- [x] camunda/camunda-docs#4097
- [x] camunda/camunda#20619
- [x] camunda/camunda-docs#4121
```

```[tasklist]
#### Console
- [x] ~Make Query API an activatable alpha feature~
```

### After Query API is completed (planned for 8.7)

```[tasklist]
#### Gateway API
- [ ] https://github.com/camunda/camunda/issues/25993
```

```[tasklist]
#### Java client
- [ ] https://github.com/camunda/camunda/issues/26009
```

```[tasklist]
#### Testing
- [x] Adjust automated tests for REST API configuration properties
```

```[tasklist]
#### Documentation
- [ ] https://github.com/camunda/camunda-docs/issues/4761
- [ ] https://github.com/camunda/camunda/issues/26022
```

## Discussions and Decisions

* Instead of marking Query API as "experimental", we'll make it an [alpha feature](https://docs.camunda.io/docs/reference/alpha-features/).

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2243
