### ISSUE TITLE
[EPIC] Implement `Process definition` endpoints 

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20652]
### Description

Process definition endpoints provides searching for process definitions and the BPMN description as XML.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `processDefinitionKey`
* Process definitions objects are defined in
  * [Process definition](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.32uloox6n1z6) 

### Endpoints

- [x] https://github.com/camunda/camunda/issues/22643
- [x] https://github.com/camunda/camunda/issues/22645
- [x] https://github.com/camunda/camunda/issues/22646 
- [x] https://github.com/camunda/camunda/issues/22733

**Comment by tmetzke** [comment]
I added `Get process definition by key` to the list of endpoints to build

**Comment by kristinkomschow** [comment]
Added `processVersionTag` to Search Process Definitions body to support filtering by versionTag, which was implemented for the V1 API.

I'm unsure what to do to ensure the C8 API returns the version tag field as well, since the definition of the Response types is global (for all components) from what I see (?)

Context: https://github.com/camunda/camunda/issues/22070

**Comment by tmetzke** [comment]
> I'm unsure what to do to ensure the C8 API returns the version tag field as well, since the definition of the Response types is global (for all components) from what I see (?)

Each search endpoint defines its item type, i.e. the type of the items returned by the general search response.
The process definition item type can be found [here](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.32uloox6n1z6). I guess this is where you'd add the new property.

**Comment by kristinkomschow** [comment]
Thanks! I'll add it then.
I was mostly unsure if I should just do that because it is already marked as "Defined", so I didn't know if I should just change it or need to inform someone about it.

**Comment by ralfpuchert** [comment]
@kristinkomschow you can inform me for any changes regarding Operate related C8 API endpoints.
