### ISSUE TITLE
[EPIC] Implement `Decision instance` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20655]
### Description

Decision instance endpoints provides searching for decision instances.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `decisionInstanceId`
* Decision definitions objects are defined in
  * [Decision instance](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.9ds4r2ra5n5l) 
  * [Decision requirements](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.pe9vw4ocuyy8)
 

### Endpoints

- [x] https://github.com/camunda/camunda/issues/22654
- [x] https://github.com/camunda/camunda/issues/22656

### Acceptance Criteria

- [ ] Unit tests
- [ ] Integration tests

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by tmetzke** [comment]
Added `Get decision instance by key` endpoint

**Comment by ralfpuchert** [comment]
Set endpoint `Get Decision requirements data` to obsolete. Can be calculated by using existing endpoints.
