### ISSUE TITLE
[EPIC] Implement `Process instance` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20660]
### Description

Process instance endpoints provides searching for process instances.

[Issue for statistic part of process-instance endpoint](https://github.com/camunda/camunda/issues/21716)

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* {place-holder} is the placeholder for parameters like `processInstanceKey`
* Process instance objects are defined in
  * [Process instance](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ohvt3i3y6syj) 
 
### Endpoints

- [x] Search Process instances - `POST /v2/process-instances/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.i7nt9g66bj81)
  - response format: [ProcessInstance](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ohvt3i3y6syj) 
- [x] Get process instance by key - `GET /v2/process-instances/{processInstanceKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.y4y1at1esns5)

### Subtasks

- [x] https://github.com/camunda/camunda/issues/21837
- [x] https://github.com/camunda/camunda/issues/21836
- [x] https://github.com/camunda/camunda/issues/21943
- [x] ~~https://github.com/camunda/camunda/issues/21944~~
- [x] ~~https://github.com/camunda/camunda/issues/21945~~ moved to https://github.com/camunda/camunda/issues/22812 as a follow-up
- [x] ~~https://github.com/camunda/camunda/issues/21948~~
- [x] https://github.com/camunda/camunda/issues/22600
- [x] https://github.com/camunda/camunda/issues/22739

**Comment by mihail-ca** [comment]
Hello @ralfpuchert @ThorbenLindhauer I am trying to understand the requirements for the endpoint **/v2/process-instances/search**, however I cannot find the corresponding schema:

- My understanding so far, is that we need two schema models, one for the request, and one for the response.
- In the documentation however, none of the endpoints mention the **response** format. For example, in search process instances: https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.i7nt9g66bj81
It does not mention the response format (which fields to return).
- Secondly, the request is used as filter, so the fields in the request should be a **subset** of the fields in the response, right ?
- However, the endpoint mentions this object as request filter for process instance search: https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.wnbb83yfz5ut
but looking at the schema, it does not seem the match the fields of a process instance.

So please explain, what are the correct models expected, both for response and the request, for the endpoint /**v2/process-instances/search** ? Thank you.

**Comment by ThorbenLindhauer** [comment]
Hi @mihail-ca,

>  It does not mention the response body format (which fields to return).

I left a comment in the doc tagging you where this is.

> Secondly, the request is used as filter, so the fields in the request should be a subset of the fields in the response, right ?

No, this doesn't have to be. So the request can have parameters (or names) that you won't find in the response. E.g. the `boolean running` property. Do we specify that anywhere?

Ralf can answer questions about specific properties, as he created the definition.

**Comment by ralfpuchert** [comment]
Hello @mihail-ca, the process instance request is defined after the internal API in [ProcessInstanceRestService::queryProcessInstances](https://github.com/camunda/camunda/blob/2ec16f62882f477842d8f736ea39563e61ac45f1/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/ProcessInstanceRestService.java#L111-L111). There we have a request object [ListViewRequestDto](https://github.com/camunda/camunda/blob/2ec16f62882f477842d8f736ea39563e61ac45f1/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/listview/ListViewRequestDto.java#L18-L18) with embedded [ListViewQueryDto](https://github.com/camunda/camunda/blob/2ec16f62882f477842d8f736ea39563e61ac45f1/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/listview/ListViewQueryDto.java#L16-L16).

The goal was to have one search request for process instance that can deliver the data in public API and internal API.

**Comment by felix-mueller** [comment]
Quick question: Will we also return rootProcessInstanceKey for a processInstance like in C7?

**Comment by mihail-ca** [comment]
> Quick question: Will we also return rootProcessInstanceKey for a processInstance like in C7?

This is tracked in subtask https://github.com/camunda/camunda/issues/21945 (`rootInstanceId`)

**Comment by tmetzke** [comment]
I added the `Get process instance by key` endpoint to the list

**Comment by kristinkomschow** [comment]
I added version tags to the `list-view` entities that should be returned with the process instance API calls now (https://github.com/camunda/camunda/pull/22282/commits/1b5ae43f57d87b6df8481aae4c0d9264a4f85ef4).

@mihail-ca Could you check if there are any other modifications to the process instance V2 API necessary to support the version tags?

**Comment by ralfpuchert** [comment]
> Get process instance core statistics, and Get flow node statistics of process instance key endpoints to the list

Hello @tmetzke , statistic endpoints are already covered in https://github.com/camunda/camunda/issues/2171.

**Comment by tmetzke** [comment]
> > Get process instance core statistics, and Get flow node statistics of process instance key endpoints to the list
> 
> Hello @tmetzke , statistic endpoints are already covered in #21716

Thank you, @ralfpuchert, I have somehow completely overlooked and never opened that issue 😄

**Comment by tmetzke** [comment]
@ralfpuchert, I have moved https://github.com/camunda/camunda/issues/21945 to https://github.com/camunda/camunda/issues/22812 so this EPIC focuses on the "easy to achieve" attributes.

Is this EPIC done then?

**Comment by ralfpuchert** [comment]
Close due to tracking of minor changes in #22812

**Comment by tmetzke** [comment]
Added https://github.com/camunda/camunda/issues/24103
