### ISSUE TITLE
Remove magic strings ProcessSaasIT

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#20700]
### Description
The test cases in `io.camunda.tasklist.graphql.ProcessSaasIT` refer to magic strings set during the deployment of the processes. A recent CI issue was caused due to this [change](https://github.com/camunda/camunda/pull/20699) and was not easy to trace the root cause.

### TODO
We should either: 
- [ ] Remove the magic strings specified on the issue above and the test case and retrieve them via the Zeebe CLI
- [ ] Document the peculiarity of these test cases

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
