### ISSUE TITLE
Refactor `<team>-labeled.yml` workflows to remove duplication

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#20768]
## Description

Problem: 99% redundant workflows (running on same trigger with same logic, just different GH label and GH project id)

* https://github.com/camunda/camunda/blob/main/.github/workflows/operate-labeled.yml
* https://github.com/camunda/camunda/blob/main/.github/workflows/tasklist-labeled.yml
* Optimize is also introducing one in https://github.com/camunda/camunda/pull/20516

Solution:

* composite GH action in this repository having 2 parameters (GH label, GH project id) and assigns issues matching the label to the project if the issue has no project yet
* 1 GH workflow `issues-labeled` calling this composite GH action for each `operate`, `tasklist` (, `optimize` when merged)
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/pull/21135
- [ ] https://github.com/camunda/camunda/pull/21176
- [ ] https://github.com/camunda/camunda/pull/21179
```

**Comment by misiekhardcore** [comment]
@cmur2 when you decide this can be worked on, you can assign this task to me

**Comment by cmur2** [comment]
> @cmur2 when you decide this can be worked on, you can assign this task to me

There is no dependency to other tasks so feel free to start work on this 👍🏼

**Comment by misiekhardcore** [comment]
Do we reassign the issue to the reviewer when we move it to review?

**Comment by cmur2** [comment]
> Do we reassign the issue to the reviewer when we move it to review?

Yes we can, I have no hard preference.

**Comment by misiekhardcore** [comment]
@cmur2 can this be closed now?

**Comment by cmur2** [comment]
> @cmur2 can this be closed now?

Can you please do a test if its working if you didn't already?

**Comment by misiekhardcore** [comment]
it looks like I used the name of the action I had before changing it later :/ opened #21176 to fix it

**Comment by cmur2** [comment]
Thanks for fixing that, can you do another (final) test to see if it works?

**Comment by misiekhardcore** [comment]
I did and it seems to still be broken. I think I need to add `checkout` action to the workflow now

**Comment by misiekhardcore** [comment]
It is still broken, it cant find the action and it suggests that we need to do checkout, so I opened #21179 to add it

**Comment by misiekhardcore** [comment]
It finally worked https://github.com/camunda/camunda/actions/runs/10402715844/job/28807751709
