### ISSUE TITLE
Operate OpenSearch AWS config can't be disabled.

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20939]
### Describe the bug

If Operate is configured to use OpenSearch as database it [looks for AWS configuration](https://github.com/camunda/camunda/blob/7d215585cdb269029f5c9f8cfd33e9e391c41f47/operate/common/src/main/java/io/camunda/operate/connect/OpensearchConnector.java#L181-L181). If a configuration is found it tries to setup AWS. This prevents using other mechanisms such as basic authentication (via the `operate.opensearch.username/password` properties; see also the [corresponding docs](https://docs.camunda.io/docs/self-managed/setup/guides/using-existing-opensearch/#connecting-to-amazon-opensearch-service-with-basic-auth)).

In order to disable AWS setup even if AWS configuration exists Operate needs a configuration like Zeebe:
`camunda.operate.opensearch.awsEnabled=[true|false]` (default false).

Additionally helm charts must be updated to use this configuration for helm chart config: `global.opensearch.aws.enabled` .

Related to [Support issue 23119](https://jira.camunda.com/browse/SUPPORT-23119)

#### Tasks

- [x] Add configuration `awsEnabled` in [OpenSearchProperties](https://github.com/camunda/camunda/blob/7d215585cdb269029f5c9f8cfd33e9e391c41f47/tasklist/common/src/main/java/io/camunda/tasklist/property/OpenSearchProperties.java#L17-L17)
- [x] Use the configuration above in [OpenSearchConnector::isAWS](https://github.com/camunda/camunda/blob/7d215585cdb269029f5c9f8cfd33e9e391c41f47/operate/common/src/main/java/io/camunda/operate/connect/OpensearchConnector.java#L181-L181) to setup an AWS configuration according to `awsEnabled`
- [x] Create an issue/PR in distribution for updating helm charts => https://github.com/camunda/camunda-platform-helm/issues/2215
- [x] Backport to 8.5

### To Reproduce

1. Use Operate with OpenSearch on AWS
2. Try to use without AWS with basic authentication for example
3. Look for exceptions with messages related to security, permissions like
```
[security_exception] no permissions for ...
```

### Current behavior

Operate can't connect to OpenSearch on AWS if an AWS configuration exists in the environment.

### Expected behavior

Operate can be used with OpenSearch on AWS even if a AWS configuration exists in the environment.

### Environment

* Operate with OpenSearch configured in AWS

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [x] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [x] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by ThorbenLindhauer** [comment]
Added to September patches
