### ISSUE TITLE
Tasklist OpenSearch AWS config can't be disabled

### ISSUE THREAD

**Issue by nathansandi** [camunda/camunda#21070]
### Describe the bug

If Tasklist is configured to use OpenSearch as database it (like the operate)[looks for AWS configuration](https://github.com/camunda/camunda/blob/7d215585cdb269029f5c9f8cfd33e9e391c41f47/operate/common/src/main/java/io/camunda/operate/connect/OpensearchConnector.java#L181-L181). If a configuration is found it tries to setup AWS. This prevents using other mechanisms such as basic authentication (via the `tasklist.opensearch.username/password` properties; see also the [corresponding docs](https://docs.camunda.io/docs/self-managed/setup/guides/using-existing-opensearch/#connecting-to-amazon-opensearch-service-with-basic-auth)).

In order to disable AWS setup even if AWS configuration exists Tasklist needs a configuration like Zeebe:
`camunda.tasklist.opensearch.awsEnabled=[true|false]` (default false).

Additionally helm charts must be updated to use this configuration for helm chart config: `global.opensearch.aws.enabled` .

Related to [Support issue 23119](https://jira.camunda.com/browse/SUPPORT-23119) and [Support issue 23157](https://jira.camunda.com/browse/SUPPORT-23157)

#### Tasks

- [ ] Add configuration `awsEnabled` in [TasklistSearchProperties]
- [ ] Use the configuration above in [OpenSearchConnector::isAWS] to setup an AWS configuration according to `awsEnabled`
- [x] Create an issue/PR in distribution for updating helm charts => https://github.com/camunda/camunda-platform-helm/issues/2215
- [ ] Bacport to 8.5

### To Reproduce

1. Use Tasklist with OpenSearch on AWS
2. Try to use without AWS with basic authentication for example
3. Look for exceptions with messages related to security, permissions like
```
[security_exception] no permissions for ...
```

### Current behavior

Tasklist can't connect to OpenSearch on AWS if an AWS configuration exists in the environment.

### Expected behavior

Tasklist can be used with OpenSearch on AWS even if a AWS configuration exists in the environment.

### Environment

* Tasklist with OpenSearch configured in AWS

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

Version : **_8.4, 8.5 and 8.6-alpha._**

- Release version ( in which version this fixed/feature will be released):
