### ISSUE TITLE
Fix Optimize issues with dependencies updates

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#21072]
Engineering DRI: @misiekhardcore 

### Context

Currently there are no Optimize checks required for a PR to be automerge. Due to that renovate updated some dependencies in Optimize which broke it. This caused issues with Optimize workflows failing on every single PR in the monorepo now.

To fix the problem, two things need to be done:
1. renovate config is updated to contain some dependencies exclusions in Optimize
2. Optimize unit tests workflow is added to [unified CI](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) workflow so at least any Optimize checks are required before a PR is automerged

### Testing Notes

- [x] optimize unit tests are running in the [CI workflow](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml)
- [x] no breaking updates we excluded from renovate are merged to Optimize

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/21063
- [ ] https://github.com/camunda/camunda/pull/21060
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Review Resources

- Feature PR: {Link to PR targeting the main branch}
- Preview environments: {Link(s) to preview environments}

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and maintenance branches
- [x] The correct version labels are applied to the issue
