### ISSUE TITLE
🎯 Support version tag

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#21075]
### Description

PDP item:
- [ ] https://github.com/camunda/product-hub/issues/435

#### Backend

- [ ] Extend `POST api/processes/grouped` API endpoint to support version tags

Proposal for API response extension:

```
[
  {
    "bpmnProcessId": string,
     ...
    "processes": [
      {
        "id": string,
        "name": string,
        "version": number,
        "bpmnProcessId": string,
        "versionTag": string       // <-- new field
      }
    ]
  }
]
```

- [ ] Extend `GET api/process-instances/<key>` API endpoint to support version tag

Proposal for API response extension:

```
{
  "id": string,
  "processId": string,
  "processName": string,
  "processVersion": number,
  "processVersionTag": string             // <- new field
  ...
}
```
- [ ] Extend the V1 API endpoints for process definitions: [Search process definitions](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/search-2/), [Get process definition by key](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/by-key-2/)
- [ ] Extend the V1 API endpoints for process instances: [Search process instances](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/search-1/), [Get process instance by key](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/by-key-1/)
- [ ] Ensure these changes are covered by the [V2 API epic](https://github.com/camunda/product-hub/issues/2244) (e.g. by extending the scope of the corresponding endpoinst, or adding an extra ticket)

#### Frontend

- [ ] Add version tag to process instance details view
- [ ] Add version tag to process instances list view

### Definition of Ready - Checklist

- [ ] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] It is clear what will be delivered in each increment/alpha release
- [ ] Edge cases and limitations are clear
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

### Acceptance Criteria

- [ ] All the TODO issues are done

**Comment by pedesen** [comment]
Duplicate to https://github.com/camunda/camunda/issues/21061
