### ISSUE TITLE
Fix Optimize command workflows

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#21071]
Engineering DRI: @misiekhardcore

### Context

Due to the token generation error in the [`optimize-command-dispatch.yml`](https://github.com/camunda/camunda/blob/main/.github/workflows/optimize-commands-dispatch.yml) workflow, this workflow is adding error messages to every comment in monorepo.
For now the problem is solved by [disabling the workflow](https://github.com/camunda/camunda/actions/workflows/optimize-commands-dispatch.yml) entirely, but it has to be fixed, so it can be used.

### Acceptance Criteria

- [x] optimize commands do not update every single command then the main workflow encounters an error
- [x] all the commands tokens are generated properly
- [x] all the commands work as they were intended to

### Testing Notes

- [ ] play with commands to see if they work as intended

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/21578
- [ ] https://github.com/camunda/camunda/pull/21625
- [ ] https://github.com/camunda/camunda/pull/23462
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Review Resources

- Feature PR: {Link to PR targeting the main branch}
- Preview environments: {Link(s) to preview environments}

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and maintenance branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
The token issues were finally resolved by adding the optimize app we were using for GH token generation to the monorepo, so the token can be generated from there with access to everything the workflow needs

**Comment by misiekhardcore** [comment]
I found out one other issue. There is new PR added to fix it

**Comment by RomanJRW** [comment]
@OmranAbazid - shall we go ahead and close this then?

**Comment by RobertDorlan** [comment]
Hey @misiekhardcore also this one seems to not be working. 

I tried on the following issue --> https://github.com/camunda/camunda/issues/25200
and is not working, I got the following error: 
![image](https://github.com/user-attachments/assets/078dbd81-d1fa-4699-a9b5-462c649fa9bf)
