### ISSUE TITLE
fix optimize issue templates

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#21168]
### Acceptance Criteria

- [x] optimize task, epic and bug report issue templates are listed when creating new issue

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/21169
- [ ] https://github.com/camunda/camunda/pull/21181
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Review Resources

When trying to create new issue, none of the optimize templates is listed
The reason is, those files are formatted and have to be repaired 

- Feature PR: {Link to PR targeting the main branch}
- Preview environments: {Link(s) to preview environments}

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue
