### ISSUE TITLE
Add a common schema management for camunda exporter

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#21177]
- [x] Identify/Add common interfaces #21527 
    * IndexDescriptor
        * Concrete implementations of this will be provided by the webapps
    * TemplateDescriptor
        * Concrete implementations of this will be provided by the webapps
    * The interfaces for creation of indices and templates should be implementation agnostic between Elasticsearch and Opensearch
    * Should provide an initial implementation of a client which creates indices and templates for Elasticsearch
- [x] Implement SchemaManager that can create new schema #21528 
    * Support only ElasticSearch in the first version, but abstract common logic and interfaces so that support for OpenSearch can be easily added.
    * SchemaManager can create schema for provided list of indices and templates
    * If failed, should throw error with good error message. No need to retry as the exporter.open() will be retried until success.
    * Configuration: 
      * Can configure a default number of shards and replicas
      * Can configure per index/template number of shards and replicas
    * Add tests for verifying above behaviors.
- [x] Schema source files also support a settings field. https://github.com/camunda/camunda/pull/22848
- [x] SchemaManager can update schema on version updates https://github.com/camunda/camunda/issues/21762
    * Ignore rolling updates for now 
    * When new fields are added to the schema, schema manager can update existing schema with the new fields
    * Add tests for verifying above behaviors
- [x] Provide a way for webapps to register/add the list of indices/templates to create schemas https://github.com/camunda/camunda/issues/21980
- [x] Integrate SchemaManager with the exporter https://github.com/camunda/camunda/issues/21956
    * On exporter open, schema manager is invoked to create or update the schema
    * Provide configuration to enable/disable schema creation on startup
- [x] SchemaManager can validate schemas for existing indices/templates https://github.com/camunda/camunda/issues/21831
    * An existing schema in ES is valid if
      * It is the same as the provided one
      * The provided one is a new version (with newly added fields)
      * Schema validation fails if an existing schema is not valid.
      * Ignore rolling updates for now
- [x] SchemaManager can create/update ILM policies https://github.com/camunda/camunda/issues/22597
    * First version can have a common policy for all indices
    * To consider whether it should be configurable per webapp
- [x] Handle rolling updates https://github.com/camunda/camunda/issues/22758
    *  What should happen when schema manager on old version and new version tries to update the schema at the same time? This can happen during a rolling update when one partition leader is on new version and another is on old version.
    * Also consider schema validation during rolling updates

**Comment by deepthidevaki** [comment]
Check the discussions related to how to handle schema update during rolling update https://camunda.slack.com/archives/C06F0GLJNFM/p1723713532572709

**Comment by deepthidevaki** [comment]
@EuroLew Can this issue be closed?

**Comment by EuroLew** [comment]
> @EuroLew Can this issue be closed?

Yep it's finished
