### ISSUE TITLE
fix optimize c8 health status action

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#21187]
### Context

Updated health status action is failing due to ArgoCD misconfiguration. We are passing the Argo CD token but then there is no Argo config provided and `infra-report-action` throws an error. We do n't want ArgoCD at all so we need to remove any trace of it from the workflow

### Acceptance Criteria

- [ ] remove argo from optimize health status action

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/21188
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Review Resources

- Feature PR: {Link to PR targeting the main branch}
- Preview environments: {Link(s) to preview environments}

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue
