### ISSUE TITLE
A skeleton Spring boot based Migration app exists for Identity in the monorepo

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#21282]
## Description
Migration app will be deployed on each execution cluster and have a connection to management identity and execution identity. The goal of this application is migrating the existing data on Postgres to the new architecture.

## Tasks

- [x] Create a spring module called migration in camunda/camunda repo.
- [x] Active profile for the migration app's beans is **migration**.
- [x] root package name is: io.camunda.identity.migration
- [x] Create an spring boot application in dist called MigrationApplication.
- [x] Migration application implements CommandLineRunner to get the args and pass it to the Migration management bean that reside in migration module. These args can be: 
   - mode: resume or restart (default to resume)
   - entities: tenant, user, .. (default to all)
   - command: migrate: do the migration or status: to print the latest statistics and status
- [x] Add dependency to camunda-service so then migration app can use identity related services from zeebe.
- [x] Add dependency to WebClient so then migration app can call management identity migration endpoints.
