### ISSUE TITLE
Resource authorization migration is supported

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#21332]
## Description
As we have a new structure for Authorisations in standalone application, we have to migrate the existing Resource Authorizations to this new structure.

## Technical Details
New structure for Authorizations is: `(resourceType string, resourceKey string, ownerType string, ownerKey string, permissions list<string>)`.

Existing Resource Authorizations has the following structure: `(id UUID, entityId string, entityType string, organizationId string, resource (id UUID, key string, type string, organizationId string), permission string)`

To map the existing authorizations to the new authorization:

- Execution cluster is mapped to the `organizationId`, it means each cluster only queries for authorizations and resources that matches the organization assigned to the cluster.
- Group all the authorizations in the batch with same **`entityId`, `entityType`,`resourceId`** to get a union of the permissions.
- attribute associations are: 
      **`RA.entityId` -> Key in Zeeb side -> `A.ownerKey`
      `RA.entityType` -> `A.ownerType`
      `RA.resource.key` -> `A.resourceKey`
      `RA.resource.type` -> `A.resourceType`
      `union of permissions` -> `A.permissions`**
- if an Authorization with same `resourceType , resourceKey, ownerType , ownerKey `already exist, then add the new permissions to existing ones.

##Tasks
### Management identity

- [ ] Add a column `migration_status` to `resource_authorizations` and the `Authorization` entity class.
- [ ] Add a method `findAuthorizationsForMigration` to the AuthorizationRepository to fetch authorizations filtered by `organizationId` and `migration_status`, ordered by `entityId`, `entityType`,`resourceId` and with limit and offset.
- [ ] Add `/authorizations/migration` get endpoint to use the AuthorizationRepository#findAuthorizationsForMigration. This endpoint should be annotated with `@PreAuthorize("hasReadAccess() or canViewAuthorizationsInOrganization(#organizationId)")`. It should also returns the detail for entity.
- [ ] Add `/authorizations/migration` put endpoint to update `migration_status` for a list of `Authorization`. The security annotation is `@PreAuthorize("hasWriteAccess() or canManageAuthorizationsInOrganization(#request.organizationId())")`

### Migration App

- [x] Create ResourceAuthorizationMigrator to manage the resource authorization migration.
- [x] call `/authorizations/migration` to get a batch for migration
- [x] group Resource Authorizations by `entityId`, `entityType`,`resourceId` to collect permissions
- [ ]  for each group:
      - find the owner (like by username, group id, role name) or create the owner if not exist.
      - create/update Authorization
      - call /authorizations/migration` to update migration_status

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/21284
- [ ] https://github.com/camunda/camunda/issues/19743
- [ ] https://github.com/camunda/camunda/issues/22295
- [ ] https://github.com/camunda/camunda/issues/25129
- [ ] https://github.com/camunda/camunda/issues/26071
```
