### ISSUE TITLE
Collapsing dynamic lists affects the output data in tasklist

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda#21348]
### Describe the bug

When collapsing a dynamic list, the contents which are hidden are not submitted with the form

https://app.incident.io/camunda/incidents/1631
https://jira.camunda.com/browse/SUPPORT-23067

### To Reproduce

1. Go to the modeler preview or tasklist
2. Have a form ready with a dynamic list
3. Add a bunch of entries into the dynamic list
4. Collapse the dynamic list
5. Look at the submitted data

### Actual behavior

6. No data beyond the point of collapse is submitted

### Expected behavior

6. Collapsing shouldn't affect the outputted data

### TODO

* [x] https://github.com/bpmn-io/form-js/issues/1230
* [x] release new version of form-js
* [x] integrate new version into tasklist

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?
