### ISSUE TITLE
Fix issue with simple dates in negative offset timezones behave erratically

### ISSUE THREAD

**Issue by Skaiir** [camunda/camunda#21346]
### Describe the bug

https://jira.camunda.com/browse/SUPPORT-23165?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D

Negative timezones lead to the date component cycling down infinitely or until a random date

### To Reproduce

1. Set up your environment with an American timezone for example
2. Create a form with a simple date (date only, no time)
3. Attach it to a process
4. Run that process
5. Access the form in tasklist and try to use the date component

### Actual behavior

6. The date cycles down

### Expected behavior

6. The date should not

### Environment

All

### TODO

* update form-js@1.9.1 in tasklist

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?
