### ISSUE TITLE
Update Operate docs screenshots

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#21387]
### Description

With https://github.com/camunda/camunda/issues/19554 we have changed how the executed path is visualized. This affects a lot of docs screenshots of Operate. Let's update them with [our automation](https://github.com/camunda/camunda/actions/workflows/operate-update-docs-screenshots.yml).

### TODO

* [x] Fix the screenshot workflow
* [x] Run it so that all Operate screenshots in the docs are updated for 8.6

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
Once the workflow is fixed, let's share the PR with @christinaausley so that she can take it as an example on how to work with the automation.

**Comment by pedesen** [comment]
@ThorbenLindhauer @christinaausley I merged the PR and run the screenshot generator on the main branch. It works! The screenshots can be downloaded as part of the playwright report here: https://github.com/camunda/camunda/actions/runs/11292047862

**Comment by christinaausley** [comment]
Wahoo! Great news. I'll launch a docs PR. Thank you!
