### ISSUE TITLE
[EPIC] Integrate permissions with REST API queries

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#21393]
## Description
When authorizations are enabled on the orchestration cluster, a principal (user/M2M) has access assigned to specific resources, this allows a customer to restrict what a given principal can see/access.

To be able to ensure that the results returned from ElasticSearch are compliant with the authorizations assigned, the authorizations for the principle on the request should be retrieved and applied to the search queries.

A POC for this exists [here](https://github.com/camunda/camunda/pull/22212).

## Acceptance Criteria

- There is a generalized concept for permissions in the search layer (data store-independent)
- There are transformers for the search layer implementations, applying the permissions to queries
- Permissions are integrated for all entities in the search layer
- Permission handling is updated in V1 application code if necessary
 
```[tasklist]
- [ ] https://github.com/camunda/camunda/issues/23174
- [ ] https://github.com/camunda/camunda/issues/23127
- [ ] https://github.com/camunda/camunda/issues/23179
- [ ] https://github.com/camunda/camunda/issues/23180
- [ ] https://github.com/camunda/camunda/issues/23352
```

**Comment by tmetzke** [comment]
@houssain-barouni, `Update authorization implementation for Operate V1/internal endpoints` is in the scope of this epic but it doesn't have to be you to act on it. Depending on assessment, we could also start work on it in parallel to your work on the V2 API if that makes sense.

**Comment by houssain-barouni** [comment]
Kickoff meeting [Miro board](https://miro.com/app/board/uXjVIshWsds=/)

**Comment by houssain-barouni** [comment]
This EPIC covered basic authentication
OIDC implementation will be covered in https://github.com/camunda/camunda/issues/25992
