### ISSUE TITLE
[EPIC]: Extend benchmarking approach to measure Operate import performance

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#21462]
## Description

As part of https://github.com/camunda/camunda/issues/16912, we want to tackle an ultimate user problem, reducing the Operate import delay. This means the time until the user sees data in Operate.

The current idea, which is followed in #16912, is to reduce the import latency, by moving the importing logic into the exporting, reducing additional index hops and unnecessary data conversions. 

As this is an important performance topic, we want to make sure that we are on the right track and guide the implementation phase with benchmarks, which are realistic and which include Operate measurements (especially import latency measurements and other measures).

This topic is divided into the following sub-topics:

1. improve benchmarks in general
2. make the benchmarking more realistic
3. improve measurements (via adding more metrics and dashboards)
4. execute benchmarks

### Improved benchmarks

We need to revamp the benchmarks, especially our [Helm charts](https://github.com/zeebe-io/benchmark-helm), upgrading to the newest versions and making them more extensible.

```[tasklist]
### Benchmark improvements
- [x] https://github.com/zeebe-io/benchmark-helm/pull/171 - Migrate to the last helm chart version (`10.2.1`)
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2183
- [ ] https://github.com/camunda/camunda-platform-helm/issues/2197
- [x] https://github.com/camunda/camunda/pull/20937 - Fix issues in benchmark workflows, for new chart version
- [x] https://github.com/camunda/camunda-platform-helm/pull/2223 - To fix configuration for Operate/Tasklist
- [x] https://github.com/zeebe-io/benchmark-helm/pull/176 - Alpha version already contained cfg fixes
- [x] https://github.com/zeebe-io/benchmark-helm/pull/173
- [ ] https://github.com/camunda/camunda/pull/21031
- [ ] https://github.com/camunda/camunda/pull/21129
- [x] Make starter extensible https://github.com/zeebe-io/benchmark-helm/pull/184
- [x] Make worker extensible https://github.com/zeebe-io/benchmark-helm/pull/183
```

### Realistic benchmarks

As of now, we use quite simple processes with only one service task. We normally just increase the load by increasing the process instance creation/completion per second (PI/s).

In the past, we discussed several times to improve our coverage and use different process models. What we did is to run on a weekly basis a benchmark with a higher load, with still the one task process, but also a mixed benchmark which has a process with a message start event and a task, plus a process with a timer. Of course likely not really covering the reality, but at least covering some more symbols.

We want to further improve and make the benchmarks more realistic, by using a process model that covers the average process orchestration use case and a payload that reflects the reality.

This is not only useful for this EPIC or topic, but also in general to improve our benchmarking approach and to cover more components in the future (the ultimate target is to cover the Camunda Platform as a whole). Results will be more understandable for Customers/Users and will help in Consulting to point to different results. 

```[tasklist]
### Realistic benchmarks
- [x] [Reached out to consulting](https://app.slack.com/client/T0PM0P1SA/C01Q05D6YUU) for input to model a more realistic (Avg) process model
- [x] [Modeled more realistic model](https://camunda.slack.com/archives/C01Q05D6YUU/p1724306840107089?thread_ts=1724138721.573489&cid=C01Q05D6YUU)
- [x] [Found a good payload for the process instance](https://camunda.slack.com/archives/C01Q05D6YUU/p1724312774772399?thread_ts=1724138721.573489&cid=C01Q05D6YUU)
- [ ] https://github.com/camunda/camunda/issues/21472
```

### Improved measurements

We included Operate in the past already into our weekly benchmarks, but since then no more metrics have been added nor improved. 

The current Operate metrics dashboard is not meaningful or useful to be used for a planned performance benchmark, that covers several different latencies and duration to understand how the system performs and where time is spent.

We need in several components additional metrics in exporter, importer, etc. to better measure our performance. Additional we need a revamped dashboard to be used for our performance testing, which allows us to see a) on high level that system works, is healthy and performaning b) we can directly compare and see different aspects of the system. Meaning latencies and throughput in different components which are playing together.

```[tasklist]
### Improved measures
- [x] [Created new dashboard](https://grafana.dev.zeebe.io/d/eb6b38cb-3ac3-49fa-9c6c-c66d3eeebb1c/camunda-benchmarks-ck?orgId=1&from=now-1h&to=now&var-DS_PROMETHEUS=prometheus&var-namespace=All&var-pod=All&var-partition=All) https://github.com/camunda/camunda/pull/22021
- [ ] https://github.com/camunda/camunda/pull/21297
- [ ] https://github.com/camunda/camunda/pull/21445
- [ ] Operate latency measure improvements (duration of import, make latency measurement an histogram to measure p99, etc.)
- [x] Make dashboard public available
```

### Execute Benchmarks

We want to run benchmarks on a regular basis, with the improvements we made during this EPIC. This should allow us to track progress and improvements, and additionally to detect potential issues. Furthermore, it allows us to understand what might be missing from the benchmark execution or measurement side.

```[tasklist]
### Execute benchmarks
- [x] Created [a results sheet](https://docs.google.com/spreadsheets/d/1qzcrqI88uMSwzTjcc1CPY4DvGoeN6q7vLGQs0AjFoy8/edit?gid=0#gid=0) to collect benchmark data
- [x] Run first benchmarks to understand what we have, what are we missing in terms of measurements
- [x] https://zeebe-io.github.io/zeebe-chaos/2024/08/16/Operate-load-handling/
- [x] https://zeebe-io.github.io/zeebe-chaos/2024/08/19/Operate-improve-import-latency
- [ ] https://github.com/camunda/camunda/issues/21376
- [x] Run first benchmarks with more realistic process models and data
- [ ] https://github.com/camunda/camunda/pull/24109
```

**Comment by Zelldon** [comment]
We have realistic benchmarks. We used them already for measure performance for new SaaS offerings. We integrated them into our weekly benchmarks now. I will close this (over 90% is done). Left overs can be done separately, or are unrelated like config adjustments in helm.
