### ISSUE TITLE
Make benchmarks more realistic

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#21472]
## Description

> As of now, we use quite simple processes with only one service task. We normally just increase the  load by increasing the process instance creation/completion per second (PI/s).
> 
> In the past, we discussed several times to improve our coverage and use different process models. What we did is to run on a weekly basis a benchmark with a higher load, with still the one task process, but also a mixed benchmark which has a process with a message start event and a task, plus a process with a timer. Of course likely not really covering the reality, but at least covering some more symbols.
> 
> We want to further improve and make the benchmarks more realistic, by using a process model that covers the average process orchestration use case and a payload that reflects the reality.
> 
> This is not only useful for this EPIC or topic, but also in general to improve our benchmarking approach and to cover more components in the future (the ultimate target is to cover the Camunda Platform as a whole). Results will be more understandable for Customers/Users and will help in Consulting to point to different results

related to https://github.com/camunda/camunda/issues/21462

### Break down

```[tasklist]
### Pre-requisites
- [x] [Reached out to consulting](https://app.slack.com/client/T0PM0P1SA/C01Q05D6YUU) for input to model a more realistic (Avg) process model
- [x] [Modeled more realistic model](https://camunda.slack.com/archives/C01Q05D6YUU/p1724306840107089?thread_ts=1724138721.573489&cid=C01Q05D6YUU)
- [x] [Found a good enough payload for the process instance](https://camunda.slack.com/archives/C01Q05D6YUU/p1724312774772399?thread_ts=1724138721.573489&cid=C01Q05D6YUU)
```

```[tasklist]
### Todo's
- [x] https://github.com/camunda/camunda/pull/21501
- [x] Add complex process model to benchmark application https://github.com/camunda/camunda/pull/21501
- [x] Add suitable payload to benchmark application, generate a payload that allows a multi-instance [of around 50 elements] (https://camunda.slack.com/archives/C01Q05D6YUU/p1724312774772399?thread_ts=1724138721.573489&cid=C01Q05D6YUU) https://github.com/camunda/camunda/pull/21501
- [x] Extend starter to generate business key, if configured (variable name should be configurable to be used as `customerId`) https://github.com/camunda/camunda/pull/21501
- [x] Extend starter to deploy extra process models, extending to be backwards compatible https://github.com/camunda/camunda/pull/21501
- [ ] <Optional> (Not clear yet) Extend starter to generate different payload?
- [x] Helm charts: Extend starter configuration (ex. to allow to start and create instances of complex process model) https://github.com/zeebe-io/benchmark-helm/pull/184
- [x] Helm charts: Extend worker configuration (allow to define array of worker configs, to deploy different workers for different name, job types, etc.) https://github.com/zeebe-io/benchmark-helm/pull/183
- [x] Extend worker application: Allow to publish a message from a job worker, the message must send a message with a specific correlation key, which is based on the job variables (customerId in our case). https://github.com/camunda/camunda/pull/21905
- [ ] https://github.com/zeebe-io/benchmark-helm/pull/185
- [x] Workers are overloading system on message publish failure https://github.com/camunda/camunda/pull/22244
- [ ] Use workers config in Mono repo CI benchmarks https://github.com/camunda/camunda/pull/22361
```
