### ISSUE TITLE
Update Tasklist translations based on the feedback from native speakers

### ISSUE THREAD

**Issue by volodymyr-melnykc** [camunda/camunda#21473]
Product hub epic: https://github.com/camunda/product-hub/issues/2378

### Description

Update Tasklist translations to DE, FR, and ES based on the feedback from native speakers.

### TODO

- [x] Update translations for German
- [x] Update translations for Spanish
- [x] Update translations for French
- [x] Fix issue with truncated labels in task sorting popover
