### ISSUE TITLE
Integrate aggregation into Search API

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#21724]
### Description

Operate defines endpoints which involve aggregations on database:
* https://github.com/camunda/camunda/issues/21716 
* https://github.com/camunda/camunda/issues/21720
* https://github.com/camunda/camunda/issues/21717
* https://github.com/camunda/camunda/issues/21719
* https://github.com/camunda/camunda/issues/21721

The current search API does not support aggregations in [SearchRequest](https://github.com/camunda/camunda/blob/e9afa1edb0e498d11e0907f09803368665ba337c/search/search-client/src/main/java/io/camunda/search/clients/core/SearchQueryRequest.java#L23-L23)
and [SearchResponse](https://github.com/camunda/camunda/blob/e9afa1edb0e498d11e0907f09803368665ba337c/search/search-client/src/main/java/io/camunda/search/clients/core/SearchQueryResponse.java#L16-L16)

In order to support aggregations an aggregation framework which integrates in `SearchRequest` and `SearchResponse` is needed. This includes `Aggregation` (request/specification) and `Aggregate` (response/result) components with corresponding `Transformer` and `Builder`. Also different types of aggregations and aggregates are needed.

The following aggregations are needed to implement Operate statistic endpoints:

* [CardinalityAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html) 
* [FiltersAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filter-aggregation.html)
* [TermsAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) 
* [TopHitsAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html)
* [ChildrenAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-children-aggregation.html)

### Documentation

* [OpenSearch](https://opensearch.org/docs/latest/aggregations/)
* [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html)

### Tasks

- [ ] Create Aggregation and Aggregate components for C8 API
- [ ] Integrate them in SearchRequest and SearchResponse
- [ ] Create aggregation and aggregate framework (Transformer, Builder, etc)
- [ ] Add an implementation of an aggregation and aggregate as use case

### PR'S

* Aggregation framework proposal: https://github.com/camunda/camunda/pull/21533
* Sub aggregations proposal: https://github.com/camunda/camunda/pull/21585

### Acceptance Criteria

- [ ] Unit tests
- [ ] Integration tests

**Comment by pedesen** [comment]
Leaving this as information source, but not for tracking. Proposed approach is to implement this with one specific endpoint, and refine and abstract with specific endpoints.
