### ISSUE TITLE
Avoid downloading CSV several times in parallel

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda#21784]
Engineering DRI: @misiekhardcore

### Context

Several (business-) users click the “Download CSV-Export” button multiple times

### Acceptance Criteria

- Downloading CSV several times is avoided by disabling the button for the time of downloading
- Feature is available in C7 and C8

### Links

Customer [request](https://jira.camunda.com/browse/SUPPORT-22741).  

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/13972
- [ ] https://github.com/camunda/camunda/pull/21812
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by toco-cam** [comment]
@RomanJRW task created as discussed.

**Comment by misiekhardcore** [comment]
@toco-cam @RomanJRW does it have to be backported to older versions?

**Comment by RomanJRW** [comment]
Given that this is a task rather than a bug, I would say no backporting necessary here

**Comment by RobertDorlan** [comment]
Tested agains C8 8.6.0-SNAPSHOT


Button is disabled for the time of downloading as expected ✅ 

![image](https://github.com/user-attachments/assets/0ca3fbb3-dbce-4393-b9ac-b820c9333785)
