### ISSUE TITLE
Migrate to react 18

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#21816]
### Context

We are still using outdated react 17 so we need to upgrade to v18.

### Acceptance Criteria

- [ ] Upgrade `react` and `react-dom` to v18
- [ ] use enzyme react 18 adapter to be able to run all unit tests wi

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and maintenance branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8 - 8.7.0-SNAPSHOT and 3.15.0-SNAPSHOT


I did some exploratory testing and working fine ✅ 
Also this will be confirmed by Regression during release
