### ISSUE TITLE
[EPIC] Deprecate and migrate zbctl and GO Client to community project

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#21817]
## Introduction

This epic is about executing the deprecation of the go client and zbctl as planned with this PDP epic https://github.com/camunda/product-hub/issues/2438.

## Concept

With 8.6 and the availability of the full featured [Zeebe REST API](https://github.com/camunda/product-hub/issues/2040) the go client and zbctl will get deprecated. Effectively migrated to a community project and not officially supported nor maintained with Camunda 8.6+.

**This doesn't mean the go-client or zbctl is gone** as for all supported minor releases the go-client and zbctl will still be available and maintained. Also as there are no changes planned to the Zeebe GRPC API from 8.6 on, zbctl 8.5 should stay forwards compatible for some period of time while the GRPC API is avilable. In doubt it can be maintained further via the community repository and adopted to the REST API.

## Task Breakdown

```[tasklist]
### Phase 0 - Prerequisities/Announcement/Communication
- [x] announce deprecation on repository with 8.6.0-alpha5 - https://github.com/camunda/camunda/pull/21760 @aleksander-dytko
- [x] [Blog Post on the deprecation](https://docs.google.com/document/d/12i2yQSPnjOB4l1qxO5-no9qGDWlHc3BKvyc5WdD97tU/edit#heading=h.b2kkidhk4gox) will be published with alpha5 @aleksander-dytko
- [x] https://github.com/camunda/camunda-docs/pull/4264
- [x] check-in with @Sijoma on impact of the deprecation for controller team - outcome see [here](https://github.com/camunda/camunda/issues/21817#issuecomment-2333889659)
```

### Phase 1 - The Move (Code)
```[tasklist]
### Create Go client and zbctl project on Community Hub based on last `main` branch state
- [x] Create `zeebe-client-go` repo (naming alignment with [zeebe-client-csharp](https://github.com/camunda-community-hub/zeebe-client-csharp)) - https://github.com/zeebe-io/zeebe-client-go
- [x] [Migrate repo to community hub](https://github.com/camunda-community-hub/community/issues/159)
- [x] migrate state of [go client](https://github.com/camunda/camunda/tree/main/clients/go) from main to the new repo (preserving history)
- [x] https://github.com/zeebe-io/zeebe-client-go/pull/1
- [ ] https://github.com/camunda/camunda/issues/22613
- [ ] (Nice to have) setup protoc [gateway protocol generation](https://github.com/camunda/camunda/blob/main/clients/go/pkg/pb/gateway.pb.go) on new repo
```

### Phase 2 - The Removal
```[tasklist]
### Remove go client from camunda/camunda
- [x] validate that removal of go client from main is not breaking `go-mod` referencing <=8.5.x releases [see](https://github.com/camunda/product-hub/issues/2438#issuecomment-2315322662)
- [ ] https://github.com/camunda/camunda/issues/22504
- [ ] https://github.com/camunda/camunda/issues/22511
- [ ] https://github.com/camunda/camunda/issues/22537
- [x] [Adopt docs to move go client to community section](https://github.com/camunda/camunda-docs/pull/4228)
- [ ] https://github.com/camunda/camunda/issues/22665
- [ ] https://github.com/camunda/camunda/issues/23188
- [ ] https://github.com/camunda/camunda/issues/22536
```

```[tasklist]
### Phase 3 - The Move no 2 (open issues)
- [ ] https://github.com/camunda/camunda/issues/23447
```

```[tasklist]
### Follow-ups (Out of scope)
- [ ] clarify whether and when we migrate zeebe-chaos to java client
```

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2438
- Slack channel: [#prj-zeebe-go-client-zbctl-deprecation](https://camunda.slack.com/archives/C07L66RECJZ)

**Comment by akeller** [comment]
Added this to the DevEx board so we have visibility. Thanks for adding the docs POC! 

The biggest gotcha here is our reliance on zbctl for checking if the connection to Zeebe is good.

**Comment by megglos** [comment]
> check-in with @Sijoma on impact of the deprecation for controller team

Not used by production code of the controller team, thus no impact.

**Comment by Zelldon** [comment]
@megglos fyi some from QA are using Zbctl the question was raised (again) what would be the alternative

\cc @mschoe @Szik

**Comment by megglos** [comment]
>@megglos fyi some from QA are using Zbctl the question was raised (again) what would be the alternative
>
> \cc @mschoe @Szik

From my understanding zbctl 8.5 should work for 8.6+ still while the GRPC API is present. Can you confirm @Zelldon ?

Going forward it will eventually not and then you can either use the bare REST API or if CLIO convenience is needed we need to prioritize a new zbctl-java component. @aleksander-dytko do we already have a FR for a CLI client?

**Comment by aleksander-dytko** [comment]
Not yet - I'll create that in ProductBoard so that we can gather feedback and link it in the blogpost

**Comment by akeller** [comment]
Adding @mesellings as the docs DRI for this project.

**Comment by megglos** [comment]
First community repo release of the go client and zbctl is here
https://github.com/camunda-community-hub/zeebe-client-go/releases/tag/v8.6.0-RC1

**Comment by akeller** [comment]
Removing @mesellings so he can focus on higher priority items. 

I've been tackling most of the remaining docs work on a best effort basis with @christinaausley assisting with backporting:

* https://github.com/camunda/camunda-docs/pull/5026
* https://github.com/camunda/camunda-docs/pull/5131
* https://github.com/camunda/camunda-docs/pull/5135

If you want something beyond what we have there, you'll probably want to keep this open.

**Comment by akeller** [comment]
Does anything else still remain here? Or can we close this out?
