### ISSUE TITLE
[EPIC] Task Listeners

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#21974]
## Introduction

Currently, Tasklist doesn’t provide any events describing what is happening in tasks. 

This blocks technical use cases that require visibility into task state changes, such as managing tasks in a custom task list, assigning users based on custom logic or notifying users about new tasks.
Working with user tasks produces multiple lifecycle events, where each of them might be important to react to. With the current solution, customers need to consume lifecycle events (available only in Self-Managed) in their systems and react to events in a specific way. This is a problem as to satisfy this need customers have to provide additional infrastructure (to consume and store events), filter Zeebe events and react to specific ones. This approach might work only in self-managed installations with a custom Tasklist application.
The lack of this functionality prevents satisfying some HTO use cases where customers need to react to lifecycle events.
This epic addresses the need to unlock multiple human task orchestration use cases.

## Task breakdown

```[tasklist]
### Iteration 1 - Blocking Complete Listener E2E increment - Target End of September
- [ ] https://github.com/camunda/camunda/issues/21491
- [ ] https://github.com/camunda/camunda/issues/21975
- [ ] https://github.com/camunda/camunda/issues/21976
- [ ] https://github.com/camunda/camunda/issues/21977
```

```[tasklist]
### Iteration 2 - Iterate on the complete listener - Target 8.7.0-alpha1
- [ ] https://github.com/camunda/camunda/issues/22398
- [ ] https://github.com/camunda/camunda/issues/23925
- [ ] https://github.com/camunda/camunda/issues/24101
- [ ] https://github.com/camunda/camunda/issues/24056

```

```[tasklist]
### Iteration 3 - Assignment listener + listener abilities - Target 8.7.0-alpha2
- [ ] https://github.com/camunda/camunda/issues/24232
- [ ] https://github.com/camunda/camunda/issues/23709
- [x] #23383 (bugfix for Execution Listeners that will be worked as part of this epic)
- [ ] #23942
- [ ] #23944
- [ ] #23945
- [ ] #23941
- [ ] https://github.com/camunda/camunda/issues/24234
- [ ] https://github.com/camunda/camunda-modeler/issues/4590
```

```[tasklist]
### Iteration 4 - Feature wrap up - Target 8.7.0-alpha3
- [ ] https://github.com/camunda/camunda/issues/24556
- [ ] https://github.com/camunda/camunda/issues/24197
- [ ] https://github.com/camunda/camunda/issues/25408
- [ ] https://github.com/camunda/camunda/issues/24607
- [ ] https://github.com/camunda/camunda/issues/22717
- [ ] https://github.com/camunda/camunda/issues/24102
- [ ] #23946
- [ ] https://github.com/camunda/camunda/issues/23492
- [ ] #23943
- [ ] https://github.com/camunda/camunda/issues/23708
- [ ] https://github.com/camunda/camunda/issues/25607
- [ ] #23728
- [ ] https://github.com/camunda/camunda/issues/25419
- [ ] https://github.com/camunda/camunda/issues/25541
- [ ] https://github.com/camunda/camunda/issues/25543
- [ ] https://github.com/camunda/camunda/issues/25502
- [ ] https://github.com/camunda/camunda/issues/25451
```

```[tasklist]
### Out of scope (stretch goals)
- [ ] https://github.com/camunda/camunda/issues/23702
- [ ] https://github.com/camunda/camunda/issues/25421
- [ ] https://github.com/camunda/camunda/issues/25890
- [ ] Allow throwing BPMN error on task listener job or prevent it
- [ ] https://github.com/camunda/camunda/issues/26934
- [ ] Task Listener for `creating` event
- [ ] Task Listener for `canceling` event
- [ ] https://github.com/camunda/camunda/issues/24107
- [ ] Global user task listeners
- [ ] https://github.com/camunda/camunda/issues/27140
- [ ] Pass task headers to task listeners
- [ ] Task listeners implemented as FEEL expression
- [ ] Connectors as task listeners
- [ ] https://github.com/camunda/camunda/issues/27141
- [ ] Allow task listener to provide reason to correct data
```

## Links
- Issue: https://github.com/camunda/product-hub/issues/1822
- Root epic: https://github.com/camunda/product-hub/issues/1316
- Operate design: [Figma](https://www.figma.com/proto/zfOVIMNthZneqFiyUhWTP2/Listeners?page-id=925%3A34385&node-id=856-29596&node-type=frame&viewport=-986%2C-1810%2C0.08&t=MXwMMnjHSWn6Jqq6-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=856%3A29596)

**Comment by korthout** [comment]
The feature was released in `8.7.0-alpha3`. Since then the following bugs were discovered:

- https://github.com/camunda/camunda/issues/25387
- https://github.com/camunda/camunda/issues/26614 
- https://github.com/camunda/camunda/issues/26701
- https://github.com/camunda/camunda/issues/26786
- https://github.com/camunda/camunda/issues/26787
- https://github.com/camunda/camunda/issues/26791
- https://github.com/camunda/camunda/issues/26809
- https://github.com/camunda/camunda/issues/26828
- Possible to throw BPMN error on task listener job (undefined behavior)

**Comment by korthout** [comment]
I'm re-opening this issue, to help track the scope we plan to deliver with 8.8

**Comment by bruderj15** [comment]
Are there any updates on the out-of-scope _Global user task listeners_?
I'd highly endorse it.

**Comment by korthout** [comment]
@bruderj15 It won't make it to 8.8, but [it's currently in 'considering' on the roadmap](https://roadmap.camunda.com/c/300-global-user-task-listeners?&utm_medium=social&utm_source=share). Please let the product-management team know how important this is to you at the bottom of that page 🙇

**Comment by korthout** [comment]
Given that this feature is set to be fully released with the upcoming `8.8` release, I believe we can close this issue as completed. For follow-ups, please considering using the referenced issues in the description, or open new issues where they are still missing. Thanks to everyone that contributed to this feature.

For a full overview of the feature, please check [the documentation](https://docs.camunda.io/docs/next/components/concepts/user-task-listeners/), or try out [the example user task listener](https://docs.camunda.io/docs/next/components/concepts/listen-to-user-tasks/) guide.
