### ISSUE TITLE
[EPIC] Deprecate zbctl and GO Client

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#22015]
## Introduction

This epic is focused on the execution of deprecation the Zeebe Go client and zbctl, migrating them to a community project.

### Phase 1 - The Move
```[tasklist]
### Create Go client and zbctl project on Community Hub 
- [ ] Create `zeebe-client-go` repo (naming alignment with [zeebe-client-csharp](https://github.com/camunda-community-hub/zeebe-client-cshar))
- [ ] migrate state of [go client](https://github.com/camunda/camunda/tree/main/clients/go) from main to the new repo (preserving history)
- [ ] (Should Have) migrate ci of [go client](https://github.com/camunda/camunda/tree/main/clients/go) - [build](https://github.com/camunda/camunda/blob/main/.github/actions/build-zeebe/action.yml#L31), 
- [ ] [Adopt docs to move go client to community section](https://github.com/camunda/camunda-docs/pull/4228) 
```

### Phase 2 - The Removal
```[tasklist]
### Remove go client from camunda/camunda
- [ ] validate that removal of go client from main is not breaking `go-mod` [see](https://github.com/orgs/camunda/projects/9/views/45?filterQuery=go+client&pane=issue&itemId=74429664) 
- [ ] Remove go client ci
- [ ] Remove go client from release workflow
- [ ] Remove go client module
```

## Links

- Product Hub (internal):

**Comment by megglos** [comment]
duplicate https://github.com/camunda/camunda/issues/21817
