### ISSUE TITLE
Extend internal API to return version tag

### ISSUE THREAD

**Issue by kristinkomschow** [camunda/camunda#22069]
### Description

Internal "processes" search endpoints need to return the `versionTag` field to display it in the frontend.

### TODO

- [x] Extend `POST api/processes/grouped` API endpoint to support version tags

Proposal for API response extension:

```
[
  {
    "bpmnProcessId": string,
     ...
    "processes": [
      {
        "id": string,
        "name": string,
        "version": number,
        "bpmnProcessId": string,
        "versionTag": string | null       // <-- new field
      }
    ]
  }
]
```

- [x] Extend `GET /api/processes/<id>` API endpoint to support version tag

Proposal for API response extension:

```
{
  "id": string,
  "name": string | null,
  "version": number,
  "bpmnProcessId": string,
  "versionTag": string | null         // <- new field
}
```
### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
