### ISSUE TITLE
Extend external API to return version tag

### ISSUE THREAD

**Issue by kristinkomschow** [camunda/camunda#22070]
### Description

The external operate API should support the display of version tags.

### TODO

- [x] Extend the V1 API endpoints for process definitions: [Search process definitions](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/search-2/), [Get process definition by key](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/by-key-2/)
- [x] Extend the V1 API endpoints for process instances: [Search process instances](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/search-1/), [Get process instance by key](https://docs.camunda.io/docs/apis-tools/operate-api/specifications/by-key-1/)
- [x] Ensure these changes are covered by the [V2 API epic](https://github.com/camunda/product-hub/issues/2244) (e.g. by extending the scope of the corresponding endpoints, or adding an extra ticket)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by kristinkomschow** [comment]
Checked the V2 Epic and brought the changes to the attention of the DRIs for the Process Instance and Process Definition Endpoints:
https://github.com/camunda/camunda/issues/20652#issuecomment-2348677005
https://github.com/camunda/camunda/issues/20660#issuecomment-2348519729
