### ISSUE TITLE
Support OS in Optimzie FE scripts

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22188]
Engineering DRI: @misiekhardcore

### Context

Currently there is no easy way of running Optimize development with OS database and this is needed from time to time

### Acceptance Criteria

- [ ] FE development scripts support running optimize in all modes with OS database

### Testing Notes

- start optimize in every mode and make sure they all work

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14179
- [ ] https://github.com/camunda/camunda/pull/22197
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue
