### ISSUE TITLE
Publish Optimize release notes to a publicly available space

### ISSUE THREAD

**Issue by RomanJRW** [camunda/camunda#22258]
Engineering DRI: @OmranAbazid

### Context

Now that Optimize is in the mono repo, we must ensure that release notes for each distribution are handled in the correct way, enabling customers from C7 and C8 to independently access release notes, that are visible to the public.

Hints:
- For fetching commits from the Optimize repo for patches of older Optimize releases, we could consider modifying the script used by other components: https://github.com/camunda/camunda-platform/blob/5931f81e5ce9523754404660b043c9f83362aade/release-notes-fetcher/fetch.go

### Acceptance Criteria

- Optimize 8.6+ release notes, using mono repo commits, are available as part of the shared release notes [here](https://github.com/camunda/camunda-platform)
- Optimize <8.6 patch release notes, using commits from the Optimize repo, are available as part of the shared release notes [here](https://github.com/camunda/camunda-platform)
- Optimize 3.14+ release notes, using commits from the Optimize repo, are available in a public repository. For example, here: https://github.com/camunda/camunda-optimize-examples
- The Optimize 8 release guide is modified in such a way that ensures that the above criteria are consistently respected
- The Optimize 7 release guide is modified in such a way that ensures that the above criteria are consistently respected

### Links

- [convo on how to integrate Optimize into the `camunda-platform-release` process](https://camunda.slack.com/archives/C06UWQNCU7M/p1728912335344289) 

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-bpm-platform/issues/4599
- [ ] https://github.com/camunda/camunda-platform/pull/957
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
@RomanJRW I cannot think of any good way of generating release notes for optimize only in the monorepo. for the last C8 releases we used changelog generateg in C7 repo, but moving forward we should find a different way I believe. Any ideas?

**Comment by RomanJRW** [comment]
@misiekhardcore - Can we not use the changelog in the mono repo? And I assume this is already what other teams there are doing? My hope was that it would be something that needs to be (re)configured rather than built

**Comment by misiekhardcore** [comment]
@RomanJRW do I understand correctly that we don't want C8 release notes at all? We just want to publish the C7 release notes to the examples repo?

**Comment by RomanJRW** [comment]
I think we should have C8 release notes and that they should exist here: https://github.com/camunda/camunda-platform/releases

Perhaps this is already automated from the mono repo and just needs to start including Optimize

**Comment by misiekhardcore** [comment]
but as I mentioned above, it is not really possible to get release notes for Optimize only from the shared repository I believe. Let's see if in the current release, the monorepo release notes will include also Optimize, if so then we are good, otherwise I will investigate this further

**Comment by misiekhardcore** [comment]
@RomanJRW there is a point saying **Optimize 3.14+ release notes, using commits from the Optimize repo, are available in a public repository.** shouldn't it be Optimize 7 in general? if not then what about versions <3.14?

**Comment by misiekhardcore** [comment]
I unassigned myself from this issue cause I switch teams

**Comment by RomanJRW** [comment]
@misiekhardcore - can you ensure that this is in a state where another Engineer could pick it up? At the moment, it is still "In Progress" and does not look resumable from that state. Does it make sense for it to go back to "Ready"?

**Comment by misiekhardcore** [comment]
## Update 24.10.2024

The only part Ive done so far is modifying C7 release workflow to push tags and create GH releases in examples repo for minor and patch releases.

Regarding C8, the release notes generation is being looked into in general in monorepo so I couldn't make any progress. I tried to modify the script used in `camunda/camunda-platform` and opened a [PR](https://github.com/camunda/camunda-platform/pull/957), but it was pushed back, so I closed it taking into consideration the overall changes to the release notes generation.

See also the linked convo in the issue description

**Comment by RomanJRW** [comment]
@OmranAbazid - this could possibly be in scope of the upcoming work on the release process

**Comment by OmranAbazid** [comment]
Since there is not plan to work on this anymore and due to the team switch. I will move this to the global backlog
