### ISSUE TITLE
Implement AuthorizationMigrationHandler to handle the migration logic

### ISSUE THREAD

**Issue by maryarm** [camunda/camunda#22295]
### Description 
As we have a new structure for Authorisations in standalone application, we have to migrate the existing Resource Authorizations to this new structure.

### Tasks
- [x] call management identity client to get a batch of resource auhtorization for migration
- [x] group by authorizations and convert values
- [x]  create/update Authorization
- [x] call management identity client to update status of migrated items
