### ISSUE TITLE
Investigate the need for the reports endpoint

### ISSUE THREAD

**Issue by OmranAbazid** [camunda/camunda#22309]
### Context

See [slack convo](https://camunda.slack.com/archives/CUZUYDMMG/p1726232582069749)

### Acceptance Criteria

- Try to use the entities endpoint instead of the loadReports endpoint
- If successful, remove the use of the loadReports from the front-end and create an issue to remove it in the backend.

### Links

https://jira.camunda.com/browse/SUPPORT-23399

### Breakdown

```[tasklist]
### Issues
- [ ] https://github.com/camunda/camunda/issues/22689
- [ ] https://github.com/camunda/camunda/issues/22694
- [ ] https://github.com/camunda/camunda/issues/22796
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
@OmranAbazid can you give some more info of what this is about? which endpoint do you want to replace with which one exactly?

**Comment by OmranAbazid** [comment]
@misiekhardcore Take a look at the slack conversation linked for more info.
The `api/reports` endpoint seems to be redundant as we can just filter the `api/entities` result to get the reports

**Comment by misiekhardcore** [comment]
and why do we want to remove this endpoint?

**Comment by misiekhardcore** [comment]
I compared the data from `entities` and `reports` endpoints, and the first one has only basic information about the entity
```ts
{
    "id": string,
    "name": string,
    "description": string,
    "lastModified": string,
    "created": string,
    "owner": string,
    "lastModifier": string,
    "collectionId": string,
    "data": {
      "subEntityCounts": {},
      "roleCounts": {}
    },
    "combined": boolean,
    "reportType": string,
    "currentUserRole": string
  }
```
and I checked if this is enough for the alerts list, but for example to format the `description` that is used in alerts table, we need to determine if report is a duration report, and to do that we need `report.data.view.properties`. Quickly looking at other components that are getting this reports data, there is one other place which needs `report.data.view.properties`.
There is also `isAlertCompatibleReport` check being performed which needs `report.data.vizualization`, `report.data.view.properties` and `report.data.configuration.aggregationType`.
If we are not planning to extend the `entities` endpoint than we have to keep the `reports` request

**Comment by RomanJRW** [comment]
Thanks @misiekhardcore - that is probably enough of an investigation for now then to understand that this endpoint can't easily be replaced/removed.

As a next step, we could still consider redesigning this endpoint to serve only the information actually required, potentially even merging this with the `entities` endpoint. @misiekhardcore - do I understand correctly then that the only properties we need from the `report` endpoint are the following?
- `description`
- `report.data.view.properties`
- `report.data.vizualization`
- `report.data.configuration.aggregationType`

**Comment by misiekhardcore** [comment]
@RomanJRW the `description` is not needed, is is generated based on `report.data.view.properties` but apart from that, the properties you've listed are the ones we would need. Maybe we should just return the whole `report.data` if its easy? I am not sure what is the best approach in this situation

**Comment by misiekhardcore** [comment]
We are also using it to:
- get a list of collection reports for the modal that adds tiles to dashboard, but this one I believe can be replaced by `entities` endpoint as we are only using `report.name` and `report.id` properties.
- get the reports for the alerts dropdown on dashboard page and what it needs a bunch of report properties like `report.data.groupBy`, `report.data.distributedBy`, `report.data.view`.

The other uses are related to alerts on collection page and I described those in the previous message. And probably I still miss something

**Comment by RomanJRW** [comment]
> get a list of collection reports for the modal that adds tiles to dashboard, but this one I believe can be replaced by entities endpoint as we are only using report.name and report.id properties.

This is interesting. Would it already be possible to start using the entities endpoint in collections? The originally reported issue (see linked Support ticket) was that there was slowness when loading a collection and this was one suspected cause. I would see this already as a benefit if we can implement that as a quick win

**Comment by misiekhardcore** [comment]
@RomanJRW I think we can try it out and see how it goes

**Comment by misiekhardcore** [comment]
@RomanJRW I already opened two issues and replace the reports endpoint in two components, where no BE changes were required for it to work

**Comment by misiekhardcore** [comment]
One of those issues after looking into, I had to close, because:
I figured out that this cannot be replace, cause in `AlertsDropdown` component, we are using `isAlertCompatibleReport` function which needs `data.visualization`, `data.view` and `data.configuration` properties, which are not returned by the `entities` endpoint

**Comment by RomanJRW** [comment]
@misiekhardcore - to confirm, this means we can already stop using the reports endpoint on the collections view? But we cannot stop using it for the alerts view?

**Comment by misiekhardcore** [comment]
As we discussed yesterday, the reports endpoint is still called when user opens a collection page, because even though the  "Dashboards & reports" tab is opened by default, all the other tabs are also loaded and the "Alerts" tab is making the call to `/reports`. And as the alerts need properties from the report which are not available in `/entities` response, it can't be replaced

**Comment by misiekhardcore** [comment]
I think one solution is to modify the Tabs component we use, so it does not render and fetch anything for the tabs that were not yet opened. I will open a PR and discuss my solution with @OmranAbazid when he's back.
[Here](https://github.com/camunda/camunda/issues/22796) is the issue - I already implemented the changes and PRs are in review

**Comment by misiekhardcore** [comment]
## Update on 25.10.2024

After investigating the issue, the problem we were facing was related to fetch from multiple endpoints when opening a collection page. One of this endpoints is `/reports` endpoint which is expensive in some cases.
The initial solution to replace that endpoint call with `/entities` cannot be done due to missing properties in `/entities` response.
After analyzing the situation, the `/report` call is done from **Alerts** tab, what means that anytime a page uses **Tabs** component, all the tabs are loaded, not only the currently opened one. The solution I came up with is to make **Tabs** component load only the current tab.
