### ISSUE TITLE
Enable version tag feature in Operate UI

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#22301]
### Description

Enable the version tag feature in the Operate UI.

### TODO

- [x] Remove feature flag
- [x] Remove mocks

### Additional Information

Depends on https://github.com/camunda/camunda/issues/22069

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
