### ISSUE TITLE
Flow node instances should only show the listeners relevant to the specific instance

### ISSUE THREAD

**Issue by vitorwtavares** [camunda/camunda#22320]
### Describe the bug

Currently, when selecting a flow node instance from the Instance History panel, on a process instance page, the Listeners tab shows all listeners attached to that flow node.

We now want the listeners listed to be only the ones relevant to that specific flow node instance.

We should still be able to get all the listeners for a given flow node for the scenario where a flow node is clicked on the diagram - in which all its instances will be selected, and the listeners listing should reflect that.

### To Reproduce

1. Go to the process instance page of a process that has an Execution Listener
2. Add another token so that the task with the listener has 2 different instances on the Instance History
3. Click one of the instances on the Instance History panel
4. Check 2 listeners appear on the list (one for each instance)

### Current behavior

When clicking either a flow node instance on the Instance History panel OR a flow node on the diagram, the Listeners tab panel displays all listeners attached to that flow node.

### Expected behavior

 - Selecting a flow node instance in the Instance History panel will show only listeners on that instance in the Listeners tab panel.
 - Selecting a flow node on the diagram will show listeners on all instances of that flow node in the Listeners tab panel.

### TODO

Backend:
- [x] https://github.com/camunda/camunda/issues/22323

Frontend:
- [ ] https://github.com/camunda/camunda/issues/22325

### Additional context

Will be worked on as part of product epic [#1821](https://github.com/camunda/product-hub/issues/1821)

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by vitorwtavares** [comment]
Closing issue as it is a duplicate of #23941
