### ISSUE TITLE
[EPIC] Process Instance Migration Phase 4: Remaining Common Elements

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#22346]
## Introduction

Fourth phase of the [Process Instance Migration](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/) concept.

This phase expands the concept introduced in https://github.com/camunda/camunda/issues/17349 by increasing the coverage of processes that can be migrated, focussing on tasks, events and gateways.

## Concept

This phase focuses on:
- expanding support for more event subscriptions and its BPMN implementations such as intermediate catch events, elements subscribed to event-subprocess and boundary events
- expanding support for more tasks
- supporting some gateway types

## Task Breakdown

Work in progress

### Process Instance Migration Phase 4 - remaining common elements
- [ ] https://github.com/camunda/camunda/issues/21588
- [ ] https://github.com/camunda/camunda/issues/21671
- [ ] https://github.com/camunda/camunda/issues/21538
- [ ] https://github.com/camunda/camunda/issues/21580
- [ ] https://github.com/camunda/camunda/issues/21593
- [ ] https://github.com/camunda/camunda/issues/21862
- [ ] https://github.com/camunda/camunda/issues/21924
- [ ] https://github.com/camunda/camunda/issues/21863
- [ ] https://github.com/camunda/camunda/issues/21864
- [ ] https://github.com/camunda/camunda/issues/21866
- [ ] https://github.com/camunda/camunda/issues/22032
- [ ] https://github.com/camunda/camunda/issues/22129
- [ ] https://github.com/camunda/camunda/issues/22184
- [ ] https://github.com/camunda/camunda/issues/22680

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Discussions and Decisions

- Support for parallel gateway instances are moved to Phase 5 due to its complexity. See comments on the issue https://github.com/camunda/camunda/issues/22067

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2338
