### ISSUE TITLE
Implement `group` endpoints

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#22387]
### Description

Group endpoints provides CRUD options for groups combined with assigning of additional resources i.e. users or roles.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `key`

### Endpoints

- [x] Create group - `POST /v2/groups` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.qc7j844hp0au)
- [x] Search groups - `POST /v2/groups/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.3r5lq4sb0tyu)
- [x] Get a single group - `GET /v2/groups/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.vsmunaey9342)
- [x] Update a group - `PATCH /v2/groups/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.27d3ji9wuci5)
- [x] Assign a user to a group - `POST /v2/groups/{key}/users/{userKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.7d4q4ehhqx7d)
- [x] Search users in a group - `POST /v2/groups/{key}/users/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.1425quaqoc48)
- [x] Remove a user from a group - `DELETE /v2/groups/{key}/users/{userKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.f2cf41s0545d)
- [x] Delete a group - `DELETE /v2/groups/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.oa81iyqm7b8)

### Acceptance Criteria

- [ ] Unit tests
- [ ] Integration tests

**Comment by koevskinikola** [comment]
The following sub-tasks have been completed:
- Group create endpoint
- Group update endpoint

**Comment by koevskinikola** [comment]
Scope update - the following sub-tasks were added by mistake and have been removed:
- Assign a role to a group - `POST /v2/groups/{key}/roles/{roleKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ip3r9nmiwwoa)
- Search roles in a group - `POST /v2/groups/{key}/roles/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.yyti6z8hn52y)
- Remove a role from a group - `DELETE /v2/groups/{key}/roles/{roleKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.mw38y5jrppds)
