### ISSUE TITLE
Implement `mapping-rule` endpoints

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#22392]
### Description

Mapping rule endpoints provide CRUD options for mapping rules.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `key`

### Endpoints

- [x] Create mapping rule - `POST /v2/mapping-rules` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.9ula0nupgc8f)
- [x] Search mapping rules - `POST /v2/mapping-rules/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ac4uy4iju5se)
- [ ] Get a single mapping rule - `GET /v2/mapping-rules/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.xeantwy19aio)
- [ ] Update a mapping rule - `PATCH /v2/mapping-rules/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.d4udhz79t2ne)
- [x] Delete a mapping rule - `DELETE /v2/mapping-rules/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.pzdfgevzrw6o)s

### Acceptance Criteria

- [ ] Unit tests
- [ ] Integration tests
