### ISSUE TITLE
Implement `tenant` endpoints

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#22390]
### Description

Tenant endpoints provide CRUD options for tenants combined with assigning of additional resources i.e. users or groups.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `key`

### Endpoints

- [x] Create tenant - `POST /v2/tenants` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.sfk9yx9h4die)
- [x] Search tenants - `POST /v2/tenants/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.r0skv1hpjiwv)
- [x] Get a single tenant - `GET /v2/tenants/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.q6y918i7mvfs)
- [ ] Get tenants for token - `GET /v2/tenants/for-token` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.zi50tr7feopw)
- [x] Update a tenant - `PATCH /v2/tenants/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.xrlfeo4gwxx0)
- [x] Assign a users to a tenant - `POST /v2/tenants/{key}/users` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.a9ktiwwmxjw0)
- [x] Search users in a tenant - `POST /v2/tenants/{key}/users/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.cp741nljmz7g)
- [x] Remove a user from a tenant - `DELETE /v2/tenants/{key}/users/{userKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ticig9ov38b7)
- [x] Assign groups to a tenant - `POST /v2/tenants/{key}/groups` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.cgs2q24ehr3e)
- [x] Search groups in a tenant - `POST /v2/tenants/{key}/groups/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.fsk1vlt1faxy)
- [x] Remove a group from a tenant - `DELETE /v2/tenants/{key}/groups/{groupKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.izqggkukx82v)
- [x] Delete a tenant - `DELETE /v2/tenants/{key}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.gizl9vh5ut2k)
- [x] Remove a mapping from a tenant - `DELETE /v2/tenants/{tenantKey}/mapping-rules/{mappingKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ticig9ov38b7)
- [x] Assign mapping to a tenant - `POST /v2/tenants/{tenantKey}/mapping-rules/{mappingKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.cgs2q24ehr3e)

### Tasks
- [ ] https://github.com/camunda/camunda/pull/24876
- [ ] https://github.com/camunda/camunda/pull/24933
- [ ] https://github.com/camunda/camunda/pull/25521
- [ ] https://github.com/camunda/camunda/pull/25522
- [ ] https://github.com/camunda/camunda/pull/25697

### Acceptance Criteria

- [ ] Unit tests
- [ ] Integration tests

**Comment by verma-kartik** [comment]
@Ben-Sheppard if no one else is working on it, I can pick this up.

**Comment by npepinpe** [comment]
The only thing not done was `GET /v2/tenants/for-token`. Can we just close this? Please re-open if still important.
