### ISSUE TITLE
Remove remaining C7 Optimize logic from the camunda repo

### ISSUE THREAD

**Issue by OmranAbazid** [camunda/camunda#22461]
### Context

In https://github.com/camunda/camunda-optimize/issues/12594, we start removing C7 Optimize logic from the camunda repo, since there are still stuff to removed, this issue is needed to track those leftovers.

### Acceptance Criteria

- Any C7 Optimize logic is removed  from the camunda repo

### Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-optimize/issues/13379
- [ ] https://github.com/camunda/camunda-optimize/issues/13439
- [ ] https://github.com/camunda/camunda/issues/33560
- [ ] https://github.com/camunda/camunda-optimize/issues/13375
- [ ] https://github.com/camunda/camunda-optimize/issues/13382
- [ ] https://github.com/camunda/camunda-optimize/issues/13980
- [ ] https://github.com/camunda/camunda-optimize/issues/13981
- [ ] https://github.com/camunda/camunda-optimize/issues/13405
- [ ] https://github.com/camunda/camunda-optimize/issues/14105
- [ ] https://github.com/camunda/camunda/issues/28877
- [ ] Remove CandidateGroupRestService
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RomanJRW** [comment]
@abremard - do you feel brave enough to take this? It might require some digging around and asking questions to understand some of the scope

**Comment by RomanJRW** [comment]
Unassigning because Alex is working on a P0 topic, and the remaining work here is lower priority. We will schedule again in future when there is capacity
