### ISSUE TITLE
I can migrate business rule, script and send tasks

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#22506]
### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in instance migration view
    Then I'm able to map business rule, script and send tasks
    When I start the migration
    Then all elements are getting migrated to the new process definition version
```

### Acceptance Criteria

- [x] I can map and migrate business rule tasks (see https://github.com/camunda/camunda/issues/21588)
- [x] I can map and migrate script tasks (see https://github.com/camunda/camunda/issues/21671)
- [x] I can map and migrate send (see https://github.com/camunda/camunda/issues/21538)

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)
