### ISSUE TITLE
Remove final dependency on ElasticSearch RestClient 7 from Schema integrity tests

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#22518]
### Context

The Schema integrity tests are still using ElasticSearch RestClient 7, this should be removed. It is being used in `optimize/qa/schema-integrity-tests/src/test/java/io/camunda/optimize/test/upgrade/client/ElasticsearchSchemaTestClient.java` (and accordingly referenced in the `pom.xml)`

### Acceptance Criteria

- ElasticSearch RestClient 7 is no longer used
- Schema Integrity tests are still executed as usual

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24469
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by RomanJRW** [comment]
@grlimacan - is this the case in the mono repo? This would be a blocker to ES9

Would it make sense for @KarpovIvan to pick this up given his experience?

**Comment by grlimacan** [comment]
> @grlimacan - is this the case in the mono repo? This would be a blocker to ES9
> 
> Would it make sense for @KarpovIvan to pick this up given his experience?

@RomanJRW Yes, this is the case in the mono-repo. Sure, he could do it.
