### ISSUE TITLE
Zeebe can verify permissions

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#22570]
<h2>Description</h2>

Zeebe can check the permissions of a user for the specified commands, and will reject the command if a user has insufficient permissions.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/22585
- [ ] https://github.com/camunda/camunda/issues/22587
- [ ] https://github.com/camunda/camunda/issues/22589
- [ ] https://github.com/camunda/camunda/issues/22590
- [ ] https://github.com/camunda/camunda/issues/22591
- [ ] https://github.com/camunda/camunda/issues/22592
- [ ] https://github.com/camunda/camunda/issues/22593
- [ ] https://github.com/camunda/camunda/issues/22601
- [ ] https://github.com/camunda/camunda/issues/22602
- [ ] https://github.com/camunda/camunda/issues/22603
- [ ] https://github.com/camunda/camunda/issues/22604
- [ ] https://github.com/camunda/camunda/issues/22605
- [ ] https://github.com/camunda/camunda/issues/22885
- [ ] https://github.com/camunda/camunda/issues/22886
- [ ] https://github.com/camunda/camunda/issues/22887
- [ ] https://github.com/camunda/camunda/issues/22888
- [ ] https://github.com/camunda/camunda/issues/22889
- [ ] https://github.com/camunda/camunda/issues/22891
- [ ] https://github.com/camunda/camunda/issues/22892
- [ ] https://github.com/camunda/camunda/issues/22893
- [ ] https://github.com/camunda/camunda/issues/22894
- [ ] https://github.com/camunda/camunda/issues/22895
- [ ] https://github.com/camunda/camunda/issues/22858
- [ ] https://github.com/camunda/camunda/issues/22902
- [ ] https://github.com/camunda/camunda/issues/22594
- [ ] https://github.com/camunda/camunda/issues/22595
- [ ] https://github.com/camunda/camunda/issues/22596
- [ ] https://github.com/camunda/camunda/issues/22890
- [ ] https://github.com/camunda/camunda/issues/22896
- [ ] https://github.com/camunda/camunda/issues/22898
- [ ] https://github.com/camunda/camunda/issues/24176
- [ ] https://github.com/camunda/camunda/issues/24403
- [ ] https://github.com/camunda/camunda/issues/24404
- [ ] https://github.com/camunda/camunda/issues/24060
- [ ] https://github.com/camunda/camunda/issues/24611
- [ ] https://github.com/camunda/camunda/issues/24612
- [ ] https://github.com/camunda/camunda/issues/24613
- [ ] https://github.com/camunda/camunda/issues/26015
```
