### ISSUE TITLE
Add more detailed error handling in OpenSearchConnector

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#22586]
### Description

If connecting to OpenSearch failed due to [missing permissions](https://github.com/camunda/camunda-docs/issues/4316) the logging messages are not clear enough:
```
2024-09-12 11:51:03.792 DEBUG 7 --- [           main] i.c.o.c.OpensearchConnector              : Creating OpenSearch connection...
2024-09-12 11:51:03.793  INFO 7 --- [           main] i.c.o.c.OpensearchConnector              : AWS Credentials are disabled. Using basic auth.
2024-09-12 11:51:04.792  WARN 7 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.camunda.operate.management.ModelMetricProvider': Unsatisfied dependency expressed through field 'processStore': Error creating bean with name 'io.camunda.operate.store.opensearch.OpensearchProcessStore': Unsatisfied dependency expressed through field 'richOpenSearchClient': Error creating bean with name 'io.camunda.operate.store.opensearch.client.sync.RichOpenSearchClient' defined in URL [jar:nested:/usr/local/operate/lib/operate-webapp-8.5.6-exec.jar/!BOOT-INF/lib/operate-schema-8.5.6.jar!/io/camunda/operate/store/opensearch/client/sync/RichOpenSearchClient.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'openSearchClient' defined in class path resource [io/camunda/operate/connect/OpensearchConnector.class]: Failed to instantiate [org.opensearch.client.opensearch.OpenSearchClient]: Factory method 'openSearchClient' threw exception with message: Jackson exception: Unrecognized token 'Unauthorized': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 13]
2024-09-12 11:51:04.806  INFO 7 --- [           main] o.a.c.c.StandardService                  : Stopping service [Tomcat]
```

* Related to [Support case](https://jira.camunda.com/browse/SUPPORT-23578)

### TODO

- [ ] Add info log message in `OpenSearchConnector` for each step in constructing and connection to OpenSearch.
- [ ] Add more fine-grained exception handling in order to catch the root causing error.

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
Moving to backlog for capacity reasons.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ⚠️ Mid |
| **When** | ⚠️ Soon |
| **Confidence** | 0.84 |

---

### 📝 Rationale

Requests clearer OpenSearch permission-failure logging and exception handling, a quality-of-life/reliability improvement rather than a new capability. The affected Operate/OpenSearch area is within Core Features ownership.   

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
