### ISSUE TITLE
Replace reports endpoint with entities in alerts dropdown component

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22694]
Engineering DRI: @misiekhardcore

### Context

To improve performance we want to replace expensive call to collection reports API with the one fetching basic entities info

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/22695
- [ ] https://github.com/camunda/camunda-optimize/pull/14342
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
I figured out that this cannot be replace, cause in `AlertsDropdown` component, we are using `isAlertCompatibleReport` function which needs `data.visualization`, `data.view` and `data.configuration` properties, which are not returned by the `entities` endpoint
