### ISSUE TITLE
[C8 API] Align field names according to naming conventions

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#22716]
### Description

In order to have align with the [naming convention](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit) fields needs to be renamed.
Please link the appropriate PR for each todo item.

### TODO

- [ ] Process instance: key -> processInstanceKey
- [ ] ...

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
