### ISSUE TITLE
Bring importer 8.6/8.7 changes to exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#22747]
### Description

After we copied importer business logic to exporter we continued adjusting importer when implementing bug fixes or new features.
We need to copy all this changes as a last step before we remove importer 8.6.

### TODO

Commits to migrate:

- [x] FNITransformer (double-check whether there are some meaningful changes): ccaf688 - all the changes are related with caches refactoring, which is not relevant for exporter. Nothinh to do here.
- [x] versionTag: b763d69, 53368f1, e77d2c4
- [ ] job and listeners related: 5686484, 916aef2, f92a942, 8c014ce, 1ff4ae3, 51a049b, 2250c4b
- [x] message subscription migration: 17689f4 (done within https://github.com/camunda/camunda/pull/25246)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by sdorokhova** [comment]
For the record I analyzed the following range of commits:
de2c8bc7997be0387a7fe49c73724c6e35671b27 90e79816b66eb3b57dc43dbac9939da9113b1a1a 8bc849a735404a61846156ee464c3e7baa89f5d7 bb8a664e82cea6720bbc0dda47206930c4b1bdb1 cd43577bf75af7fb746ca772bb50d8e3bbd0a631 fbfbc4f47d55ebc5bbaf0edc9ed84ac9c144602e 2250c4bc0b06782c10d867bedf1dc85979fce614 2af4f3d8c411f09c28d7d6bfd2cbd5d197535af1 ebdbdefc897e473be9918d3d71be975f1d1e6af6 51a049b91490b34bfef0b67d3072df64c4e6a477 1ff4ae372c6dbb759174fef69d01ffe7429395f9 8c014cea94fa74cfdfc4c34280e3233a39d4699e c60e6a1ac905fc612cd056733de271f6633d5b38 17689f4036ec97841d79fdcc0dfd597012c63eb1 f92a942ca33e1442854afd21316aa5505c94db8b 916aef2c1f606f3ba1595f79249c8b7315dde1f1 56864842d0aef47b2b06171bbc85a6d0afed7348 b763d697cc9c2cf9b7d9423c729702e7d7ae7fd4 53368f14c0e9d8cf19a82e8f03be7055a82d177f e77d2c44856feac22f55f404fcf7c4510c15cd9d ccaf688b53a82186d1bea04fc618f28f646871b7 421941e87b7618a8e6fbda6841ac067ec9d2b2ab a6f64d7b77de7e39ed36aaef49492a367c3bb627 e21d328bad11db5d9e3ab2fd99d8cf9d8ad38f61 ba920d23fb1b5fa44f0e80d19c897f9c2747df55 818bfe498a6c7671e8e9a7008bbf54e4b3e577e2 0dc1ae839e880d7bc6f32ff7c1b8509d4a8518b4 6684601d95061678c582bb973fa28a2fc7386a2b 9e59e4a41445be80d884f932b54b9843f0917d2c 3fe9eb1a7c15f85ce974ca834b27cc0813f5c1f4 ee874de9672afd3c991f55026453373dbe38a321 c50e2396604fde363bae7e5dbdc062e2b784ed0c e376379d9949bac018418eaef1a6c8f3a154f9f8 95bc79364deeddbd4c66f99f6436fdb2526eeea7 973ec55df87c67e0b9ef7bb3a563bacdf783432d df4bbf8eb916d87897783cc507fdbb6fe742ee60 1cd44d942858d1989e2342f5337b0c3ad20d8fa7 a39378f36f336346522d85e11e7b4a6c135a4846 932977e44fa5bef5c2d8fa13cb738fdc71b2c364 49b86c467022dceab72c0ad592272750779aa9dc deef490c7aba0160c77212635580c0ee9428d916 81f401efdf6da3bdf391aedf3d18afc721aabf7e 2fb6c5501d9bd379eaca8cba2919878bad845fcc fe3ee0ee792d20018dda26886c04e7dfcdf23d2c 43b649525c959bbd7402243dbb01307490a5de04 0346f06361ce856653ef73c38b3ad1c19d7a846b d55ed2503f0da1e0eea47576ac055d13719f7010 c42dc51abf618c11e860eeef83eb51a2a6933477 76dbe470c7117805a421d178de82acf22f8054b6 0d2ceb7a2846968541e4928c1246bd8127476f4a 0018c72e3e0f3e15287ac23706d732943eee54c2 25a89e4f9fcd1f834cb21c892d36c264db60a82a a18e0e0b77b61c9e1570f358d7956d78fdf950ad c3dc6229f337df4ed41c995cb3c1bf95f85527ec 61c23c09e02e40d6feb8978d9350e828a7623697 24cd7b4132190ce32be838190acb4621c5266b6d 5a82ed64268e9ffdf0567ec906227d194bca47e0 0c2d668f158e052b1401708adbac22f1a784f3f3 958ed9ae7929b7d34699822d79cc9745c4189557 102a3105dc2bd61f793b7e4691ce377248ec0b36 373ce26c899f3f0dc13dca07b3a22e69e6bbc5f8 1fdf190516468001fc957812a7b0e18571ae678f 9438e044cf2d5e51fdb9fcff3d65173d2ec7eae3
