### ISSUE TITLE
Do not load all tabs on initial render

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22796]
Engineering DRI: @misiekhardcore

### Context

Currently when we are displaying Tabs on a page, all the tabs, even those not visible are loaded and that means also all API requests those tabs needed are made. To improve performance, we want to not load tabs that haven't been explicitly opened.

### Acceptance Criteria

- [x] API requests for not opened tabs aren't made until the tab is open
- [x] Tabs are working properly

### Testing Notes

- [ ] pages like Collections, event based processes and analysis which are using Tabs, should work as expected

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14363
- [ ] https://github.com/camunda/camunda/pull/22816
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by OmranAbazid** [comment]
This issue require a bit more work from my side. Since it is alow priority, i will keep it open until i am back from my leave.

**Comment by RomanJRW** [comment]
@OmranAbazid - are the PRs linked here mergeable?

**Comment by OmranAbazid** [comment]
I closed them. I will reopen when i am back

**Comment by OmranAbazid** [comment]
This needs a bit more work and value is currently quite low as it does not really address the support issue mentioned [#22309](https://github.com/camunda/camunda/issues/22309). I will move it to an open state.
