### ISSUE TITLE
[EPIC]  Process Instance Migration Phase 5: compensation, escalation, advanced gateways

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#22797]
## Task Breakdown

```[tasklist]
### Process Instance Migration Phase 5
- [ ] https://github.com/camunda/camunda/issues/24374
- [ ] https://github.com/camunda/camunda/issues/24385
- [ ] https://github.com/camunda/camunda/issues/24377
- [ ] https://github.com/camunda/camunda/issues/24487
- [ ] https://github.com/camunda/camunda/issues/22067
- [ ] https://github.com/camunda/camunda/issues/25672
- [ ] https://github.com/camunda/camunda/issues/26944
- [ ] https://github.com/camunda/camunda/issues/28458
```

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal):
