### ISSUE TITLE
[EPIC] Process Instance Migration Phase 6: re-evaluate expressions

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#22799]
## Task Breakdown

```[tasklist]
### Process Instance Migration Phase 6 - reevaluate
- [ ] Reevaluate job expressions
- [ ] Reevaluate input mappings expressions
- [ ] Reevaluate user tasks expressions
- [ ] Reevaluate message expressions
- [ ] Reevaluate other event's expressions
- [ ] Migrate active elements to elements with the same ID without explicit mapping
```

## Other Teams

- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

## Links

- Product Hub (internal):
