### ISSUE TITLE
[EPIC] Implement `User task` endpoints

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#22839]
### Description

User task endpoints provide searching for user tasks.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
 
### Endpoints

- [x] https://github.com/camunda/camunda/issues/19211
- [x] https://github.com/camunda/camunda/issues/22481
- [x] https://github.com/camunda/camunda/issues/22449
- [x] #22903

**Comment by tmetzke** [comment]
Let's also implement a `GET /v2/user-tasks/{userTaskKey}/variables` endpoint to fetch all variables visible from a user task.

**Comment by tmetzke** [comment]
Added #22903 here
