### ISSUE TITLE
Replace Optimize APIs with unified APIs where possible

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22906]
Engineering DRI: @misiekhardcore

### Context

When Optimize becomes part of camunda single jar, we gain access to the unified API.
This API already offers many performant endpoints which can replace existing ones from Optimize API

### Acceptance Criteria

- [ ] identify which APIs can be replaced
- [ ] replace APIs
- [ ] deprecate unused Optimize APIs

### Links

- related to https://github.com/camunda/product-hub/issues/2289

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/issues/22908
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
After syncing with @RomanJRW we think this is not necessarily a direction we want to go, so closing for now
