### ISSUE TITLE
Implement `Get Variable for User Task`

### ISSUE THREAD

**Issue by nathansandi** [camunda/camunda#22903]
### Description

Variables endpoint providing search for variables.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* Variable objects are defined in
  * [Variable](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.i5jd4xzabhje) 
 
### Endpoint

* `GET /v2/user-tasks/{userTaskKey}/variables`
* [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.sc4u7eavwp5g)

### Acceptance Criteria

- [ ] REST API endpoint incl. OpenAPI spec
- [ ] Java client support
- [ ] Integration tests

```[tasklist]
### Subtasks
- [ ] https://github.com/camunda/camunda/issues/23558
```

**Comment by nathansandi** [comment]
This is "on hold" for now until we have a decision from exporters team and how data migration will work.

**Comment by nathansandi** [comment]
The exporter team has decide use the taskliost-task exporter,
and this endpoint will retrieve variables from `operate-variables`

**Comment by paskal98** [comment]
Hi, i will be glad if i can take this issue

**Comment by tmetzke** [comment]
> Hi, i will be glad if i can take this issue

Hey @paskal98, thanks a lot for the interest in contributing here, appreciated!
We are already on it internally already, so there is no need for additional effort from you here.
However, we always look for early feedback and validation, so feel free to investigate any related code changes and the release this will be featured in to test this!

**Comment by nathansandi** [comment]
Summary to the decision related to the development of this endpoint: 
Use case: There are the use case on Tasklist OOTB where tasks needs to brings all variables related to the task, this case is when a task has no forms. This would bring the need relate the scopeKey from the task, to the variables, as well as the process variables (considering the behaviour of V1)

The need from this endpoint, this will avoid to bring extra development over Front-end on API developers, to relate the scopKey (from task and process) with the respective variables. So at the end we use the tree path from operate to retrieve the respective variables.

**Comment by tmetzke** [comment]
> Summary to the decision related to the development of this endpoint: Use case: There are the use case on Tasklist OOTB where tasks needs to brings all variables related to the task, this case is when a task has no forms. This would bring the need relate the scopeKey from the task, to the variables, as well as the process variables (considering the behaviour of V1)
> 
> The need from this endpoint, this will avoid to bring extra development over Front-end on API developers, to relate the scopKey (from task and process) with the respective variables. So at the end we use the tree path from operate to retrieve the respective variables.

Thanks, @nathansandi 👍 
Can you please also update the endpoint description itself as it's not a GET anymore but a POST search endpoint?
