### ISSUE TITLE
🎯 Tasklist V2 API migration

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22911]
### Description

-  [Product hub issue](https://github.com/camunda/product-hub/issues/2516)
- [Figma mocks](https://www.figma.com/board/yrBf25ou306NCjDoD2altz/Migration-of-OOTB-Tasklist-to-V2-API?node-id=0-1&node-type=canvas)

### TODO

Migrate Tasklist to C8 unified API

#### Backend

- [ ] Migration of active tasks
- [ ] Changes in the importer/exporter
- [ ] Changes in the data types after index migration ([Docs link](https://docs.google.com/spreadsheets/d/1Pc3ZFPhcsGld8ebUaYWcTWrHo8FJQ-NxCDP9YfOCZB0/edit?gid=230650532#gid=230650532))
- [ ] Investigate possibility of using special auth settings in Identity for public start forms
  - [ ] If we can't do this we need to disable/add a linting rule in the modelers that we won't support this feature in 8.7

#### Frontend
- [ ] https://github.com/camunda/camunda/issues/22924
- [ ] https://github.com/camunda/camunda/issues/22925
- [ ] https://github.com/camunda/camunda/issues/22933
- [ ] https://github.com/camunda/camunda/issues/22935
- [ ] https://github.com/camunda/camunda/issues/22936
- [ ] https://github.com/camunda/camunda/issues/22937
- [ ] https://github.com/camunda/camunda/issues/22939
- [ ] https://github.com/camunda/camunda/issues/22941
- [ ] https://github.com/camunda/camunda/issues/22947
- [ ] https://github.com/camunda/camunda/issues/23007
- [ ] https://github.com/camunda/camunda/issues/23009
- [ ] Investigate resource based auth on processes page
- [ ] Remove public start form

#### Externals dependencies changes
- [ ] https://github.com/camunda/camunda/issues/23017

### Definition of Ready - Checklist

- [x] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] Edge cases and limitations are clear

### Acceptance Criteria

- [ ] All the TODO issues are done

**Comment by vsgoulart** [comment]
Closing it favor of https://github.com/camunda/camunda/issues/28691
