### ISSUE TITLE
Replace `/v1/internal/processes/:processDefinitionKey` with `/v2/process-definitions/:processDefinitionKey`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22925]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate get process definition endpoint to C8 unified API

### TODO

- [ ] Replace `/v1/internal/processes/:processDefinitionKey` with `/v2/process-definitions/:processDefinitionKey`

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
