### ISSUE TITLE
Replace `/v1/internal/users/current` with `/v2/me`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22924]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate current user endpoint to C8 unified API

### TODO

- [ ] Replace `/v1/internal/users/current` with `/v2/me`

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by vsgoulart** [comment]
Done via https://github.com/camunda/camunda/pull/28134
