### ISSUE TITLE
Replace `/v1/tasks/search` with `/v2/user-tasks/search`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22936]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate tasks search endpoint to C8 unified API

### TODO

- [ ] Replace `/v1/tasks/search` with `/v2/user-tasks/search`
- [ ] Remove search by follow-up date
- [ ] Remove search by due date
- [ ] Remove sort by follow-up date
- [ ] Remove sort by due-date
- [ ] Remove search by variables
- [ ] Remove search by candidate groups
- [ ] Remove search by candidate users
- [ ] Remove search by task definition id

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
