### ISSUE TITLE
Replace `/v1/tasks/:taskId/unassign` with `/v2/user-tasks/:userTaskKey/assignee`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22939]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate unassignment endpoint to C8 unified API

### TODO

- [ ] Replace `/v1/tasks/:taskId/unassign` with `/v2/user-tasks/:userTaskKey/assignee`

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
