### ISSUE TITLE
Replace `/v1/tasks/:taskId/variables/search` with ` /v2/variables/search`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22933]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate search variables endpoint to C8 unified API

### TODO

- [ ] Replace `/v1/tasks/:taskId/variables/search` with ` /v2/variables/search`
- [ ] Remove draft variables function

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
