### ISSUE TITLE
Replace `/v1/internal/processes/:bpmnProcessId/start` with `/v2/public/process-definitions/:processKey/start`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#22947]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate start process endpoint to C8 unified API

### TODO

- [ ] Replace `/v1/internal/processes/:bpmnProcessId/start` with `/v2/public/process-definitions/:processKey/start`

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
