### ISSUE TITLE
API/metric to check if the Operate importer has caught up and can be deactivated

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#22953]
### Description

* Part of https://github.com/camunda/product-hub/issues/2128
* There should be an endpoint so that users can determine if the Operate importer still has to import pending Zeebe records to import from a prior minor release
* As soon as this endpoint indicates that the importer has caught up, users can deactivate the importer

### TODO

- [ ] How can we determine that the importer has caught up
- [ ] Make this a metric
- [ ] Expose this metric

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
