### ISSUE TITLE
Add Optimize labels for workflow automation

### ISSUE THREAD

**Issue by RomanJRW** [camunda/camunda#22955]
Engineering DRI: @misiekhardcore

### Context

Optimize workflow automation with slashes depends on a number of labels to manage QA state. In the mono repo, these labels do not exist. We should add them to the mono repo, to allow us to correct apply the verification lifecycle for new reported bugs in Optimize.

Note that we might need to use slightly different labels to respect mono repo convention of `/` vs `:`. If this is the case, the Optimize workflows will also need to be adjusted accordingly

### Acceptance Criteria

- [ ] QA labels added to repository labels
- [ ] Command workflows updated to use labels with `/` instead of `:` in label name

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/22983
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
