### ISSUE TITLE
Remove slack notifications from Optimize GH actions

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22982]
Engineering DRI: @misiekhardcore

### Context

Many of Optimize GH workflows use `notify-on-slack` action to post an error summary when workflow fails. However, all the workflows which have that action added, are also part of the `health report`. To remove redundant duplication in messaging and as `notify-on-slack` action does not bring any additional value, we are removing it from all the Optimize workflows.

### Acceptance Criteria

- [ ] `notify-on-slack` action and all its occurrences are removed

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
I created this issue assuming that in C8 we still have the same problem with `notify-on-slack` action being used, but then I checked and its not there so I close this issue
