### ISSUE TITLE
Remove processes tab search and filter

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23009]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

On the migration to the unified API the process definition search endpoint won't support search and filter by start forms. This feature is planned to be released on 8.8 so we have to remove this feature until then.

### TODO

- [ ] Remove search and filter in the processes tab

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
