### ISSUE TITLE
Remove or rework draft variables

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23007]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Draft variables are not planned to be released until 8.8. Currently we have this feature implemented in the UI for the variable view in the task details.
We could possibly replace this with local Zeebe variables. If it's not possible we should simply remove this feature from the UI

### TODO

- [ ] Investigate possibility of using local Zeebe variables instead of draft variables
  - [ ] Remove or rework draft variables in the UI

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
