### ISSUE TITLE
Disable `Enforce user task restrictions` on 8.7 clusters

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23017]
### Description

Root issue https://github.com/camunda/camunda/issues/22911

Migrate current user endpoint to C8 unified API

When migrating to the unified API we won't have candidate groups and users restrictions. We need to disable this feature in clusters that use 8.7

<img src="https://github.com/user-attachments/assets/a5e805f0-5bf1-40bf-ba6c-f33b8c77bd76" alt="image" width="300" />

### TODO

- [ ] Disable UI items in 8.7 clusters

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
