### ISSUE TITLE
Move Tasklist entities to the webapps-schemas

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#23040]
### Description
Migrate the existing `tasklist-form` and adapt existing UserTask indices to accomodate Variables from Tasklist's schema defintion to the common WebApps schema module .

### TODO
- [x] `tasklist-task`
- [x] `tasklist-form`
- [x] `tasklist-metric`

### Additional Information

The `tasklist-form` index has properties related to, now retired, Job Worker User Tasks. The fields `processDefintiionId` and `isEmbedded` are irrelevant for Zeebe User Tasks.

The current `tasklist-task` index will be enhanced in the following structure, similar to the previous `tasklist-list-view` and it will also include _processVariables, taskVariables_ and _process_ information.

<b style="font-weight:normal;" id="docs-internal-guid-076c12db-7fff-1443-d6ae-86ecf7c2d64b"><div dir="ltr" style="margin-left:0pt;" align="center">
 New | Field | Data Type | Meta | Notes
-- | -- | -- | -- | --
No | formId | keyword |  |  Maintained from tasklist-task (deprecated)
No | formVersion | integer |  |  Maintained from tasklist-task (deprecated)
No | isFormEmbedded | boolean |  |  Maintained from tasklist-task (deprecated)
 :heavy_check_mark:   | action | keyword |   | Will not migrate data  from operate-user-task
No | assignee | keyword |   |  
No | bpmnProcessId | keyword |   |  
No | candidateGroups | keyword |   |  
No | candidateUsers | keyword |   |  
:heavy_check_mark: | changedAttributes | text |   | Will not migrate data  from operate-user-task
No | dueDate | date | "format": "date_time \|\| epoch_millis" |  
No | flowNodeBpmnId | keyword |   |  
No | flowNodeInstanceId | keyword |   |  
No | externalFormReference | keyword |   |  
No | followUpDate | date | "format": "date_time \|\| epoch_millis" |  
No | formKey | keyword |   |  
No | id | keyword |   | Same as flowNodeInstanceId
No | key | long |   | Refers to variableKey, userTaskKey, processKey
No | partitionId | integer |   |  
No | position | long |   |  
No | priority | integer |   |  
No | processDefinitionId | keyword |   |  
No | processDefinitionVersion | integer |   |  
No | processInstanceId | keyword |   |  
No | tenantId | keyword |   |  
:heavy_check_mark:  | name | keyword |   | variables
:heavy_check_mark:  | value | keyword | "ignore_above": 8191 | variables
:heavy_check_mark:  | fullValue | keyword | "ignore_above": 8191 | variables
:heavy_check_mark:  | scopeKey | keyword |   |  
:heavy_check_mark:  | isTruncated | boolean |   | variables
No | completionTime | date | "format": "date_time \|\| epoch_millis" |  
No | creationTime | date | "format": "date_time \|\| epoch_millis" |  
No | customHeaders | object | dynamic: true |  
No | state | keyword |   |  
:heavy_check_mark:  | join | join | {"eager_global_ordinals":true,"relations":{"task":["taskVariable"],"process":["processVariable","task"]}} | Not actually a field in the Index, it’s used for Elasticsearch to perform the parent/child joins to retrieve relevant data.

</div></b>

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Ensure that in case the index don't exist, they are properly created when starting the application
- [ ] Ensure that Camunda 8 Rest APIs are not affected by this implementation

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by Zelldon** [comment]
@panagiotisgts is this done? Can we close this?

**Comment by panagiotisgts** [comment]
For the `tasklist-metric` index entity a common one with Operate's is used.
