### ISSUE TITLE
Use the new exporter handlers to populate tasklist-task index

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#23042]
### Description
Make use of the new `CamundaExporter` functionality to populate the existing User Task indice joined index from Zeebe events.

### TODO
This joined index contains data from all the bellow events, essentially wrapping `tasklist-task`, `tasklist-process` and `tasklist-variable` into one Index.
- [ ] Zeebe User Task events
- [ ] Process Variable events
- [ ] Process Events

### Additional Information
All records in that index referring to a User Task/Process ID should be on the same partition of ES/OS for perfromant execution of the relationship joins in the index. 

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Ensure that Tasklist's  is not affected by these changes
- [ ] Migrate existing ITs to the `CamundaExporter` module
- [ ] When a Camunda User Task (Zeebe User Task) is created on Zeebe, UserTask index should have the corresponding `User Task` information inserted on User Task index
- [ ] When a Camunda User Task (Zeebe User Task) is created on Zeebe, User Task index should have the corresponding `Variable` information inserted on User Task index as part of the User Task index record
- [ ] When a Camunda User Task (Zeebe User Task) is migrated (Process Instance Migration) on Zeebe, User Task index should have the corresponding `User Task` information inserted on User Task index
- [ ] When a variable is updated on Zeebe related to the UserTask, User Task index should reflect those changes
- [ ] Whan a variable is updated on Zeebe and it's not related with a UserTask, this variable should not be stored in the user task index

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
