### ISSUE TITLE
Migrate/Remove Tasklist Tests

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#23045]
### Description
Currently Tasklist relies on entities present only on Tasklist, since we are now removing Importer from Tasklist, we need to evaluate if the existing tests should be removed, or if it makes sense for any of them to stay active (in this case, migrate to use the correct indice)

### TODO
- [ ] Decide what part of test cases should we maintain
- [ ] Decide whether test cases are included in Operate and/or enrich Operate with additional cases for Tasklist specific operations

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Ensure that Tasklist's feature test coverage is maintained and extended

### Definition of Ready - Checklist
- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by Zelldon** [comment]
Related to #24441

**Comment by ChrisKujawa** [comment]
Closing as duplicate of https://github.com/camunda/camunda/issues/25798
