### ISSUE TITLE
Bootstrap frontend monorepo and Remix project

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23059]
### Description

In order to streamline the frontend projects we will start a frontend specific monorepo which will have a common entrypoint through a [Remix framework project](https://remix.run/)

### TODO

- [ ] Bootstrap frontend monorepo
- [ ] Bootstrap Remix project with SSR disabled

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
