### ISSUE TITLE
Remove `styled-components` from `@camunda/camunda-composite-components`

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23054]
### Description

Currently C3 uses `styled-components`. Unfortunately there are some compatibility issues with Remix and also because of the library's implementation we need a less strict CSP config in our projects (`style-src 'unsafe-inline'`).
Besides these issues `styled-components` is also less performant than vanilla CSS

Because of the issues above we should migrate away from `styled-components` to SASS. We're moving to SASS because then we can better use Carbon styling utilities and because of SASS outputs vanilla CSS. 

### TODO
- [ ] Migrate `@camunda/camunda-composite-components` from `styled-components` to SASS

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
