### ISSUE TITLE
Move `@camunda/camunda-composite-components` to the monorepo

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23051]
### Description

In order to continue streamlining and further increasing collaboration between teams we should integrate the C3 repo into the monorepo.

### TODO

- [ ] Move the codebase to this repo
- [ ] Keep all their automations working here

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
