### ISSUE TITLE
Extract tracking into its own package

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23062]
### Description

When consolidating the frontend projects we will be able to share and reuse more code between projects. To kick start we need to extract the tracking functionality from Tasklist into a reusable package

### TODO

- [ ] Extract tracking into its own package

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
