### ISSUE TITLE
Extract i18n into its own package

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23063]
### Description

When consolidating the frontend projects we will be able to share and reuse more code between projects. To kick start we need to extract the i18n functionality from Tasklist as package in the monorepo that can be reused

### TODO

- [ ] Extract i18n into its own package

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
