### ISSUE TITLE
Implement endpoints not covered by the C8 unified API

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23069]
### Description

With the consolidation of the frontends in a single project this new backend project will have to implement endpoints that exist today only to support the frontends. e.g: `client-config.js`, side bar links, token refresh endpoint for global notifications

### TODO

- [ ] Identify which endpoints must be implemented that are not covered by the C8 unified API
- [ ] Implement them

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
