### ISSUE TITLE
Implement caching for consolidate frontend

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23068]
### Description

After https://github.com/camunda/camunda/issues/23066 we must implement a proper caching approach for the frontend static assets. Currently in SaaS we configure caching via env vars in the controller with Spring env vars. This approach is bad because it doesn't cover self-managed

### TODO

- [ ] Handle caching for frontend static assets

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
