### ISSUE TITLE
Bootstrap backend project for unified frontend

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23066]
### Description

With the frontend streamlining we will need a backend that will server as a BFF (backend for frontend). We will keep using Spring instead of a Node server because it betters fits our broader architecture goals and because we can reuse existing code in our apps.

### TODO

- [ ] Bootstrap a Spring project similar to existing backend for Operate/Tasklist/Optimize/Identity
  - [ ] This new backend must have a minimal API to support the frontend
  - [ ] This new backend must handle all our different auth modes that exist today in our components

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
