### ISSUE TITLE
Introduce Sentry into the frontend monorepo

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23065]
### Description

Currently in the C8 components we have no frontend logs or tracking. We already use Sentry in other Camunda projects so we should introduce it into this new project

### TODO

- [ ] Introduce Sentry in the frontend unified entrypoint

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
