### ISSUE TITLE
Move the Tasklist frontend project to the frontend monorepo

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23060]
### Description

To integrate the frontend projects we will have a common entrypoint through a Remix project. For that we will move the Tasklist frontend code to the frontend monorepo

### TODO

- [ ] Move Tasklist frontend code to the new monorepo
- [ ] Prepare project for importing the routes and configuring it on the main entrypoint

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
