### ISSUE TITLE
Prepare authentication and authorisation for unified frontend

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23067]
### Description

After https://github.com/camunda/camunda/issues/23066 we must implement all the auth modes we currently support in our components. These modes are: Identity, SSO-Auth0, Basic-auth

The new auth approach must use the new Identity API

### TODO

- [ ] Implement basic auth integration
- [ ] Implement SSO-Auth0 integration
- [ ] Implement Identity integration

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
