### ISSUE TITLE
Extract login and error pages into its own package

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#23061]
### Description

When consolidating the frontend projects we will be able to share and reuse more code between projects. To kick start we need to extract the login and errors pages from Tasklist as package in the monorepo that can be reused

### TODO

- [ ] Extract login page
- [ ] Extract/create error pages

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
