### ISSUE TITLE
Harmonize `Process` and `ProcessDefinition` interfaces in `io.camunda.zeebe.client.api.response`

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#23120]
### Description

[Process](https://github.com/camunda/camunda/blob/53af5bb30977b0939a2ca27971e10273c3f0b136/clients/java/src/main/java/io/camunda/zeebe/client/api/response/Process.java#L18-L18) and `ProcessDefinition` interfaces in `io.camunda.zeebe.client.api.response` describe the same entity but with slightly different fields.  

### TODO

- [ ] Use only one interface in client 

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by tmetzke** [comment]
Interesting case. Well, the `ProcessDefinition` interface (the new search response interface) is basically extending the existing `Process` interface by a `versionTag`, a `name`, and a `processDefinitionId` (replacing the `bpmnProcessId`). The implementing `ProcessDefinitionImpl` should only implement the `ProcessDefinition` interface, not both.

If the `ProcessDefinition` extends the `Process`, it will have a `getBpmnProcessId` which is probably OK. We can remove it later, e.g. with the Camunda Client which we want to create with 8.7 as well at some point from the Zeebe Client.

**Comment by mihail-ca** [comment]
Closing this as out of scope.
