### ISSUE TITLE
Implement `ProcessQueryTest::waitForProcessesToBeDeployed` by using process definition query

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#23121]
### Description

Implement [ProcessQueryTest::waitForProcessesToBeDeployed](https://github.com/camunda/camunda/blob/53af5bb30977b0939a2ca27971e10273c3f0b136/qa/integration-tests/src/test/java/io/camunda/it/client/ProcessQueryTest.java#L497-L497) in terms of process definition query in `ZeebeClient`

### TODO

- [x] Implement the method by lookup for deployed processes with help of process definition query.

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
