### ISSUE TITLE
Package 6: Documentation changes for OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23155]
### Context

This is a parent task to group all documentation tasks that are required for the Optimize OpenSearch implementation

### Acceptance Criteria

All sub-tasks are closed

### Testing Notes

No testing required, as it's just a parent task

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/issues/14043
- [ ] https://github.com/camunda/camunda/issues/23087
- [ ] https://github.com/camunda/camunda/issues/23615
- [ ] https://github.com/camunda/camunda/issues/24083
- [ ] https://github.com/camunda/camunda/issues/23766
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
