### ISSUE TITLE
[CPT] Assert that a process instance completed the given elements in order

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#23191]
## Description

I want to assert that a process instance has completed the given elements in order.

The assertion is an equivalent for the assertions in: 
- C7: [hasPassedInOrder()](https://docs.camunda.org/manual/7.21/user-guide/testing/assert-examples/#instance-haspassedinorder)
- ZPT: [hasPassedElementsInOrder()](https://github.com/camunda/zeebe-process-test/blob/ae9b96c848ca1bf3d8efdbf43bf6b1003ac1536a/assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java#L236)

## Tasks

- [x] The assertion passes if the process instance has completed all elements in the given order
- [x] The assertion passes if the process instance has completed other elements in between
- [x] The assertion passes if the process instance has completed an element multiple times in the given order (e.g. `A,B,A`)
- [x] The assertion fails if the process instance has not completed one of the given elements
- [x] The assertion fails if the process instance has completed an element in a different order
- [x] The assertion fails if the process instance has not completed an element multiple times or in a different order (e.g. `A,B,A` != `A,A,B`)
- [x] The assertion waits until all elements are completed in the given order

For example:

```java
assertThat(processInstance).hasCompletedElementsInOrder("A", "B", "C");
```

**Comment by srsp** [comment]
@saig0 , quick question: If the process completed with elements `A, B, A` and we assert `CamundaAssert.assertThat(processInstanceEvent).hasCompletedElementsInOrder("B", "A")`. What is the expected outcome?

**Comment by saig0** [comment]
> What is the expected outcome?
The expected outcome is: pass. 

Why?
- C7 works in this way [docs](https://docs.camunda.org/manual/7.21/user-guide/testing/assert-examples/#instance-haspassedinorder)
- Assertj: containsSequence/containsSubsequence works this way

```
assertThat(Arrays.asList(1, 2, 1)).containsSequence(2, 1);       // pass
assertThat(Arrays.asList(1, 2, 1)).containsSubsequence(2, 1); // pass
```

> Is this a realistic use case?
Yes, multi-instance. Assumption: a parallel multi-instance subprocess with `A -> B -> C`. We want to verify the sequence `A -> B -> C`. Since the other instances run in parallel, there could be other instances of `A`, `B`, `C` in between.
