### ISSUE TITLE
[CPT] Assert that a process instance has any incident

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#23250]
## Description

I want to assert that a process instance has an active/open incident.

The assertion is an equivalent for the assertions in:
- ZPT: [hasAnyIncidents()](https://github.com/camunda/zeebe-process-test/blob/b3bcfa95682e8e9d790d646ea42394429949af89/assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java#L527)

## Tasks

- [ ] The assertion passes if the process instance has an active incident
- [ ] The assertion fails if the process instance has no active incidents
- [ ] The assertion waits until an incident is active

For example:

```java
assertThat(processInstance).hasActiveIncidents();
```
