### ISSUE TITLE
Implement Exporter and SearchClient for Zeebe UserTask

### ISSUE THREAD

**Issue by stoerti** [camunda/camunda#23272]
The RDBMS Camunda 8 REST API V2 should support querying for Zeebe UserTask.

```[tasklist]
### Tasks
- [x] Export Zeebe User Tasks
- [ ] Export Task Variables
- [x] Search for Zeebe User Tasks with Task Filters
- [ ] Search for Zeebe User Tasks with Task Variable Filters
```

**AcceptanceCriteria:**
- the RDBMS module fully implements the UserTaskSearchClient with all filters and fields
- the RDBMS module can process all relevant Zeebe records for the UserTask
