### ISSUE TITLE
Update authorization implementation for Operate internal endpoints

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda#23352]
## Overview

Operate uses `PermissionService` to check permissions on `process definitions` and `decision definitions`. `PermissionService` uses Identity SDK for retrieving authorizations.
In current implementation all authorizations are retrieved and then filtered by application logic.

From 8.7 on the Identity SDK is not available anymore. 
`PermissionService` needs to retrieve authorizations from `AuthorizationService`.

Retrieving a list of `AuthorizationEntity` can be done for example:
```java
 final List<AuthorizationEntity> authorizationEntities =
        authorizationServices
            .search(
                AuthorizationQuery.of(
                    q ->
                        q.filter(
                            f ->
                                f.resourceKey(processDefinitionId)
                                    .resourceType(RESOURCE_TYPE_PROCESS_DEFINITION))))
            .items();
```

### Notes from PMs:

- The Operate V1 Public API should work as it did for customers, including permissions. We don’t want to introduce any breaking changes with the V1 API. If no permission was used in an endpoint, we must not introduce it.
- For Operate internal API - old permissions should be mapped to new permissions so that nothing changes for customers.
- As a user, if I had “write” permissions per process definition, I should still have “write” permissions per process definition with 8.7
- As a user, if I had “read” permissions per process definition, I should still have “read” permissions per process definition with 8.7
- As a user, if I had “read+write” permissions per process definition, I should still have “read+write” permissions per process definition with 8.7

### Components for permissions:

- [Permission](https://github.com/camunda/camunda/blob/a1ed2210f98726ce8a1e8efac9b39d68e0471d86/security/security-core/src/main/java/io/camunda/security/entity/Permission.java#L13-L13)
- [PermissionType](https://github.com/camunda/camunda/blob/a1ed2210f98726ce8a1e8efac9b39d68e0471d86/security/security-core/src/main/java/io/camunda/zeebe/protocol/record/value/PermissionType.java#L10-L10)
- [AuthorizationEntity](https://github.com/camunda/camunda/blob/a1ed2210f98726ce8a1e8efac9b39d68e0471d86/search/search-domain/src/main/java/io/camunda/search/entities/AuthorizationEntity.java#L16-L16)
- [AuthorizationServices](https://github.com/camunda/camunda/blob/a1ed2210f98726ce8a1e8efac9b39d68e0471d86/service/src/main/java/io/camunda/service/AuthorizationServices.java#L32-L32)

## Proposal

- `PermissionService` implements its methods in terms of components mentioned above
- No usage of Identity SDK (Identity object as main entry) anymore
- The permissions shouldn't be stored in session or some other cache-like objects. They need to be retrieved in every call.
- The retrieval should be specific as possible. Use the query filter.
- Replace `IdentityPermission` with `PermissionType` 
- v1 API checks also permissions

## Tasks

Adjust types and mapping of types:
- [ ] Adjust permission types or map them to the ones that are used in Operate
     - [ ] IdentityPermission -> PermissionType 

The following queries needs to be rewritten:
- [ ] Retrieve process definition permissions by process definition id (bpmnProcessId)      
- [ ] Retrieve decision definition permissions by decision id
- [ ] Retrieve process definitions keys by permission 
- [ ] Retrieve decision definitions keys by permission 
- [ ] Has permission for process definition id
- [ ] Has permission for decision id

Add missing checks:
- [ ] Add permissions check in v1 API

**Comment by romansmirnov** [comment]
@ralfpuchert, just a few questions/notes:

With
> Add permissions check in v1 API

Do I assume correctly that the `@PreAuthorize("hasPermission(...)")` is meant?

> The following queries needs to be rewritten:

This refers to the `PermissionService, right?

https://github.com/camunda/camunda/blob/622f2cd835abe17412b0523941b3ef11d3819c53/operate/webapp/src/main/java/io/camunda/operate/webapp/security/identity/PermissionsService.java

... and by that, the permissions won't retrieved anymore from the session/authentication?

Additionally, to make sure, what about checking access to the Operate UI? Will this be covered by the Identity stream (@Ben-Sheppard)?

**Comment by Ben-Sheppard** [comment]
Good question @romansmirnov - my expectation is that yes the access to the UI is something that we will be handling in our stream. We will need to handle some changes there as you are aware due to the new application access permissions but I hope this can be achieved in a way that is complimentary to the current approaches (maybe as a v1)
