### ISSUE TITLE
Add client integration tests for API endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#23365]
### Description

Some API endpoints need client integration tests.

### TODO

- [x] Process definition: search, get: https://github.com/camunda/camunda/pull/23461
- [x] Flow node instance: search, get: 
      https://github.com/camunda/camunda/pull/23525
      https://github.com/camunda/camunda/pull/23488
- [x] Incident: search, get: https://github.com/camunda/camunda/pull/23567
- [x] User task: search, get
