### ISSUE TITLE
Racing condition causes deploy pipeline to fail

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23455]
Engineering DRI: @grlimacan

### Context

Similar as the issue resolved with https://github.com/camunda/camunda/issues/23389, however on the deployment stage, see [deploy_stage_log.txt](https://github.com/user-attachments/files/17362167/deploy_stage_log.txt)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23456
- [ ] https://github.com/camunda/camunda/pull/23458
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue
