### ISSUE TITLE
Create single user selection and use it for selecting process owner

### ISSUE THREAD

**Issue by OmranAbazid** [camunda/camunda#23483]
Engineering DRI: @misiekhardcore

### Context

We currently use the multi-user selection for selecting a single owner. We prevent the owner from selecting additional owners by closing the selection after selecting an owner. This is confusing to the customer, and instead we should implement a single user selection input.

### Acceptance Criteria

- Implement a single user selection input
- Use the new single user selection input for the process owner selection.

### Testing Notes

1. go to Dashboards page
2. on the processes list click the settings icon to open process owner modal
3. the user selector should allow to select one user only

![Screenshot from 2024-10-24 16-06-07](https://github.com/user-attachments/assets/cd170806-4bca-44bf-a53c-91db5f4863a8)

![Screenshot from 2024-10-24 16-06-18](https://github.com/user-attachments/assets/198cf18c-8e89-4d0d-8f97-7e7dfd3e5e17)

### Links

related to https://jira.camunda.com/browse/SUPPORT-23995

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23827
- [ ] https://github.com/camunda/camunda-optimize/pull/14645
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by OmranAbazid** [comment]
@misiekhardcore from looking at this i imagine that we could build a SingleUserInput component that uses the carbon combo box component.
Feel free to do something else if you see a better solution though.

**Comment by misiekhardcore** [comment]
@OmranAbazid should this be done in both C7 and C8? should it be backported?

**Comment by OmranAbazid** [comment]
@misiekhardcore can you take a look at the support ticket and figure out the version we need to have this.
Since this is a support issue, it is important that customers do not face the issue again.
Feel free to fix it where you see is necessary.

**Comment by RomanJRW** [comment]
@misiekhardcore 

The failed workflow says "Issue can be moved to In Progress only from 'Global Backlog', 'Ready', 'On Hold' or 'Inbox' status". Should this not also allow a transition for rejected Eng reviews, like in this case?

**Comment by misiekhardcore** [comment]
@RomanJRW maybe there is an error in the validation step

**Comment by misiekhardcore** [comment]
@OmranAbazid should this go to QA now?

**Comment by OmranAbazid** [comment]
@misiekhardcore do we want to backport this to C7 optimize?
 If not, feel free to move it to QA

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT

the user selector should allow to select one user only ✅ 
https://github.com/user-attachments/assets/88c13ead-58d7-4bfa-9c15-04324b9a08e2
