### ISSUE TITLE
Replace legacy icon in NoDataNotice component

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23529]
Engineering DRI: @misiekhardcore

### Context

We want to replace legacy icon component with carbon ones in `NoDataNotice` component

### Acceptance Criteria

- [x] `NoDataNotice` component uses carbon icons

### Testing Notes

This can be tested if there is an error in report and the error message with icon is shown
![Screenshot from 2024-10-16 12-36-51](https://github.com/user-attachments/assets/fec99642-e747-4b95-b956-3020b8acfdce)
![Screenshot from 2024-10-16 12-36-29](https://github.com/user-attachments/assets/83444dfc-d540-4c23-ae77-b24b69927cfe)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23534
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
I could not reproduce it. 
@misiekhardcore tested forcing the error state in the code. 
as is an small change I'm approving and moving forward.
