### ISSUE TITLE
Create and use custom optimize icons

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23550]
Engineering DRI: @misiekhardcore

### Context

There are two custom Optimize icons that we need to keep as they can't be replaced with carbon. For those we need to import SVG files as components (vite allows that)

### Acceptance Criteria

- [x] optimize custom icons are handled by importing svg files the way vite is allowing to

### Testing Notes

There are two places affected and both should look and work exactly the same as they did before:
- Create new empty state component (Collections and Collection pages)

![Screenshot from 2024-10-16 12-29-45](https://github.com/user-attachments/assets/e257fa85-0998-4876-b50f-9fc9ea9e9050)

- Embedded dashboard/report (icon in bottom-left corner)

![Screenshot from 2024-10-16 12-30-29](https://github.com/user-attachments/assets/829da714-ef21-4c95-a544-2b22a1cd0fc7)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23557
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains C8- 8.7.0-SNAPSHOT**


Embedded dashboard/report (icon in bottom-left corner) ✅ 
<img width="898" alt="image" src="https://github.com/user-attachments/assets/288d443c-462d-4293-87d2-fd6d743ba4c7">
