### ISSUE TITLE
Implement branch analysis for OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23561]
Engineering DRI: @grlimacan

### Context

Implement BranchAnalysis for OpenSearch, this mostly consists of the implementation of BranchAnalysisReaderOS. This needs to be backported to C7 as well

### Acceptance Criteria
BranchAnalysisQueryIT, BranchAnalysisRestServiceIT are passing
The feature is working properly in the Optimize UI

### Testing Notes

Branch Analysis is working in the Optimize UI

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14516
- [ ] https://github.com/camunda/camunda/pull/23723
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Tested agains C7 3.15.0-SNAPSHOT**


Branch Analysis without filter ✅ 
![image](https://github.com/user-attachments/assets/97b145ad-43e6-492d-babf-d2c3025fc21b)



Branch Analysis with filters ✅ 
Instance state = Running 
![image](https://github.com/user-attachments/assets/d64e4a22-14af-43c9-ba10-2896996d3855)


Branch Analysis with filters ✅ 
Instance date = this month
![image](https://github.com/user-attachments/assets/0ded2870-5102-41cc-85dc-6cf9f71bacd1)


Branch Analysis with filters ✅  
flow node date = this month
![image](https://github.com/user-attachments/assets/6c04611d-a025-497b-b942-a6855193c0b1)



Branch Analysis with filters ✅ 
Instance duration = less than 7 days
![image](https://github.com/user-attachments/assets/024f3e58-80c5-4302-879d-5c7d702789ef)


Branch Analysis with filters ✅ 
Flow node execution = Running, canceled, or completed
![image](https://github.com/user-attachments/assets/28b25c85-a7bd-4871-b24d-3275bef2d0a9)
 

Branch Analysis with filters ✅ 
Incident = No incident 
![image](https://github.com/user-attachments/assets/d1a07050-ac55-4921-aa57-bab914147a01)


Branch Analysis with filters ✅ 
Assignee = Demo demo
![image](https://github.com/user-attachments/assets/ecd91a1c-24da-406b-9d23-99d571c87a03)


Branch Analysis with filters ✅ 
Candidate group = is Sales
![image](https://github.com/user-attachments/assets/73604cab-a83a-48c1-9cf1-bc1ae6cb04cc)


Branch Analysis with filters ✅ 
Variable
![image](https://github.com/user-attachments/assets/399d9808-1f89-4bf0-b3cd-1ce2f6f1b3af)





**Tested agains C8 8.7.0-SNAPSHOT**


Branch Analysis without filter ✅ 
![image](https://github.com/user-attachments/assets/39247b9e-068f-44a6-bda7-ae3eec5820ad)



Branch Analysis with filters ✅ 
Instance state = Running 
![image](https://github.com/user-attachments/assets/6579e7f3-e19a-449b-aebb-92d537c4ba34)


Branch Analysis with filters ✅ 
Instance date = this month
![image](https://github.com/user-attachments/assets/db1f38f6-01c2-407c-8c74-5d9d6f6c8fc8)



Branch Analysis with filters ✅  
flow node date = this month
![image](https://github.com/user-attachments/assets/60ced879-4ff7-491b-8fd1-389c55180eef)


Branch Analysis with filters ✅ 
Instance duration = less than 7 days
![image](https://github.com/user-attachments/assets/da5bddae-60a3-488c-9282-ef68c674adf4)



Branch Analysis with filters ✅ 
Flow node execution = Running, canceled, or completed
![image](https://github.com/user-attachments/assets/bb803b6b-19a4-4080-92b2-74f9eb2c21a5)

 

Branch Analysis with filters ✅ 
Incident = No incident 
![image](https://github.com/user-attachments/assets/79fe94b7-2222-4915-8aa3-e51c0f27491f)


Branch Analysis with filters ✅ 
Assignee = unassigned
![image](https://github.com/user-attachments/assets/b3989ea4-31e1-464e-8043-c0cadb784c22)


Branch Analysis with filters ✅ 
Variable
