### ISSUE TITLE
Fix ExternalEventTraceStateImportIT

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23571]
Engineering DRI: @grlimacan

### Context

ExternalEventTraceStateImportIT is failing with 
`java.lang.AssertionError: 
Expecting actual:
  [EventSequenceCountDto(id=null:ketchup:signup-event%backend:ketchup:register-event, sourceEvent=EventTypeDto(group=null, source=ketchup, eventName=signup-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:register-event%backend:ketchup:onboarded-event, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:onboarded-event%backend:ketchup:complained-event, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=complained-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:register-event%null:null:null, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), targetEvent=null, count=1),
    EventSequenceCountDto(id=backend:ketchup:complained-event%backend:ketchup:register-event, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=complained-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:onboarded-event%null:null:null, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), targetEvent=null, count=-1)]
to contain exactly in any order:
  [EventSequenceCountDto(id=null:ketchup:signup-event%backend:ketchup:register-event, sourceEvent=EventTypeDto(group=null, source=ketchup, eventName=signup-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:register-event%backend:ketchup:onboarded-event, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:onboarded-event%backend:ketchup:complained-event, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=complained-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:complained-event%backend:ketchup:register-event, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=complained-event, eventLabel=null), targetEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), count=1),
    EventSequenceCountDto(id=backend:ketchup:register-event%null:null:null, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=register-event, eventLabel=null), targetEvent=null, count=1),
    EventSequenceCountDto(id=backend:ketchup:onboarded-event%null:null:null, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), targetEvent=null, count=0)]
elements not found:
  [EventSequenceCountDto(id=backend:ketchup:onboarded-event%null:null:null, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), targetEvent=null, count=0)]
and elements not expected:
  [EventSequenceCountDto(id=backend:ketchup:onboarded-event%null:null:null, sourceEvent=EventTypeDto(group=backend, source=ketchup, eventName=onboarded-event, eventLabel=null), targetEvent=null, count=-1)]
`

### Acceptance Criteria

ExternalEventTraceStateImportIT is passing

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14595
- [ ] https://github.com/camunda/camunda-optimize/pull/14596
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
