### ISSUE TITLE
Fix false error message in the logs when starting Optimize

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23578]
Engineering DRI: @grlimacan

### Context

When starting Optimize with an empty OpenSearch database, the following error message is logged because no process instance indexes exist yet:

```
17:55:27.726 [PlatformUserTaskIdentityCache-1] ERROR o.c.o.s.d.o.e.OpenSearchOperation - An exception has occurred when trying to execute an OpenSearch operation 
org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [index_not_found_exception] no such index [optimize-process-instance]
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport.extractAndWrapCause(ApacheHttpClient5Transport.java:1153)
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport.performRequest(ApacheHttpClient5Transport.java:158)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1386)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.unsafeSearch(OpenSearchDocumentOperations.java:269)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.lambda$search$6(OpenSearchDocumentOperations.java:289)
	at org.camunda.optimize.service.db.os.externalcode.OpenSearchOperation.safe(OpenSearchOperation.java:92)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:289)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:278)
	at org.camunda.optimize.service.db.os.OptimizeOpenSearchClient.search(OptimizeOpenSearchClient.java:579)
	at org.camunda.optimize.service.db.os.OpenSearchCompositeAggregationScroller.getNextPage(OpenSearchCompositeAggregationScroller.java:99)
	at org.camunda.optimize.service.db.os.OpenSearchCompositeAggregationScroller.consumePage(OpenSearchCompositeAggregationScroller.java:81)
	at org.camunda.optimize.service.db.os.reader.AssigneeAndCandidateGroupsReaderOS.consumeUserTaskFieldTermsInBatches(AssigneeAndCandidateGroupsReaderOS.java:129)
	at org.camunda.optimize.service.db.os.reader.AssigneeAndCandidateGroupsReaderOS.consumeUserTaskFieldTermsInBatches(AssigneeAndCandidateGroupsReaderOS.java:73)
	at org.camunda.optimize.service.db.reader.AssigneeAndCandidateGroupsReader.consumeUserTaskFieldTermsInBatches(AssigneeAndCandidateGroupsReader.java:71)
	at org.camunda.optimize.service.db.reader.AssigneeAndCandidateGroupsReader.consumeAssigneesInBatches(AssigneeAndCandidateGroupsReader.java:32)
	at org.camunda.optimize.service.identity.PlatformUserTaskIdentityCache.lambda$populateCache$2(PlatformUserTaskIdentityCache.java:61)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
	at org.camunda.optimize.service.identity.PlatformUserTaskIdentityCache.populateCache(PlatformUserTaskIdentityCache.java:58)
	at org.camunda.optimize.service.identity.AbstractPlatformIdentityCache.synchronizeIdentities(AbstractPlatformIdentityCache.java:152)
	at org.camunda.optimize.service.identity.AbstractPlatformIdentityCache.syncIdentitiesWithRetry(AbstractPlatformIdentityCache.java:118)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [index_not_found_exception] no such index [optimize-process-instance]
	at org.opensearch.client.transport.Endpoint.exceptionConverter(Endpoint.java:102)
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport.prepareResponse(ApacheHttpClient5Transport.java:547)
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport.lambda$performRequestAsync$0(ApacheHttpClient5Transport.java:191)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport$1.completed(ApacheHttpClient5Transport.java:236)
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport$1.completed(ApacheHttpClient5Transport.java:225)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:148)
	at org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:72)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$2$1.completed(InternalAbstractHttpAsyncClient.java:304)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer$1.completed(AbstractAsyncResponseConsumer.java:101)
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:87)
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:83)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:142)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:251)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:276)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:366)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:338)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:143)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:176)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:125)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:92)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	... 1 common frames omitted
17:55:27.729 [PlatformUserTaskIdentityCache-1] INFO  o.c.o.s.d.o.OpenSearchCompositeAggregationScroller - Was not able to get next page of composite aggregation because at least one instance from [process-instance] does not exist. 
17:55:27.732 [PlatformUserTaskIdentityCache-1] ERROR o.c.o.s.d.o.e.OpenSearchOperation - An exception has occurred when trying to execute an OpenSearch operation 
org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [index_not_found_exception] no such index [optimize-process-instance]
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport.extractAndWrapCause(ApacheHttpClient5Transport.java:1153)
	at org.opensearch.client.transport.httpclient5.ApacheHttpClient5Transport.performRequest(ApacheHttpClient5Transport.java:158)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1386)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.unsafeSearch(OpenSearchDocumentOperations.java:269)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.lambda$search$6(OpenSearchDocumentOperations.java:289)
	at org.camunda.optimize.service.db.os.externalcode.OpenSearchOperation.safe(OpenSearchOperation.java:92)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:289)
	at org.camunda.optimize.service.db.os.externalcode.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:278)
	at org.camunda.optimize.service.db.os.OptimizeOpenSearchClient.search(OptimizeOpenSearchClient.java:579)
	at org.camunda.optimize.service.db.os.OpenSearchCompositeAggregationScroller.getNextPage(OpenSearchCompositeAggregationScroller.java:99)
	at org.camunda.optimize.service.db.os.OpenSearchCompositeAggregationScroller.consumePage(OpenSearchCompositeAggregationScroller.java:81)
	at org.camunda.optimize.service.db.os.reader.AssigneeAndCandidateGroupsReaderOS.consumeUserTaskFieldTermsInBatches(AssigneeAndCandidateGroupsReaderOS.java:129)
	at org.camunda.optimize.service.db.os.reader.AssigneeAndCandidateGroupsReaderOS.consumeUserTaskFieldTermsInBatches(AssigneeAndCandidateGroupsReaderOS.java:73)
	at org.camunda.optimize.service.db.reader.AssigneeAndCandidateGroupsReader.consumeUserTaskFieldTermsInBatches(AssigneeAndCandidateGroupsReader.java:71)
	at org.camunda.optimize.service.db.reader.AssigneeAndCandidateGroupsReader.consumeCandidateGroupsInBatches(AssigneeAndCandidateGroupsReader.java:45)
	at org.camunda.optimize.service.identity.PlatformUserTaskIdentityCache.lambda$populateCache$2(PlatformUserTaskIdentityCache.java:66)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
	at org.camunda.optimize.service.identity.PlatformUserTaskIdentityCache.populateCache(PlatformUserTaskIdentityCache.java:58)
	at org.camunda.optimize.service.identity.AbstractPlatformIdentityCache.synchronizeIdentities(AbstractPlatformIdentityCache.java:152)
	at org.camunda.optimize.service.identity.AbstractPlatformIdentityCache.syncIdentitiesWithRetry(AbstractPlatformIdentityCache.java:118)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Acceptance Criteria

This is not a real error, make sure this log message is not displaying on a fresh Optimize start

### Testing Notes

When doing a fresh start of Optimize, this error message is not displayed

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14576
- [ ] https://github.com/camunda/camunda/pull/24087
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains C7 - 3.15.0-SNAPSHOT**

When doing a fresh start of Optimize, this error message is not displayed as expected ✅ 

![image](https://github.com/user-attachments/assets/28835b6a-6ad1-4263-960a-c33518d7b98a)
![image](https://github.com/user-attachments/assets/afac6f5e-46a7-4af2-b94d-4b926d7e5e0c)
![image](https://github.com/user-attachments/assets/a3b821f5-e09a-4f04-aa2a-5eeddaa67520)
![image](https://github.com/user-attachments/assets/48952683-058c-4a9a-ad91-361528521f35)


** Successfully tested agains C8- 8.7.0-SNAPSHOT**
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/9d64f716-39f7-4730-9e48-c5daf37c0924">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/d2d4cbda-4192-4e14-ad75-05ab9e13c89a">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/7d60e812-71ae-4814-aa73-6927ca0b70a0">
