### ISSUE TITLE
Implement UserDigestReports for OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23579]
Engineering DRI: @grlimacan

### Context

Verify that the [User Digest functionality](https://docs.camunda.io/optimize/components/userguide/process-dashboards/#configuring-process-owner-and-digests) is working properly with Optimize in C7 and C8

### Acceptance Criteria

User Digest is working as intended with OpenSearch

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT


User Digest is working as intended with OpenSearch ✅ 


<img width="1717" alt="image" src="https://github.com/user-attachments/assets/6a2cdeae-ab91-4ff0-b4c1-27168ca051c4">
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/0eaf2d49-4d49-4a6f-8b83-9787aa936215">


Successfully tested agains C7-3.15.0-SNAPSHOT


User Digest is working as intended with OpenSearch ✅ 

<img width="862" alt="image" src="https://github.com/user-attachments/assets/385ee0a2-f606-4944-996e-99f2150091af">

**Comment by grlimacan** [comment]
@RobertDorlan For testing this, could you please use a scenario where KPIs are actually present in the email?

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT


User Digest is working as intended with OpenSearch ✅ 


<img width="1717" alt="image" src="https://github.com/user-attachments/assets/6a2cdeae-ab91-4ff0-b4c1-27168ca051c4">

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/9616c89b-b578-47f7-9e3b-4e7e87eabc13">





Successfully tested agains C7-3.15.0-SNAPSHOT

**Comment by RobertDorlan** [comment]
Hey @grlimacan 

Testing has been completed with the KPIs present on the email

https://github.com/camunda/camunda/issues/23579#issuecomment-2483300468
