### ISSUE TITLE
Instant process dashboards are working with OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23582]
Engineering DRI: @grlimacan

### Context

There are currently 6 failing tests in InstantPreviewDashboardIT and their failure are all related to missing features from reporting. Once reporting is completed, make sure that the Instant Preview Dashboard feature is working. At the current moment, there doesn't seem to be any implementation task directly related to this, so we expect that once the reporting functionality is completed, this will also complete

### Acceptance Criteria

[Instant process dashboards](https://docs.camunda.io/optimize/components/userguide/instant-process-dashboards/) are working with OpenSearch

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains C8-SNAPSHOT**

Instant process dashboards working as expected ✅ 
- Importing and displaying data as expected ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/d1e7c3b1-a858-4e54-9382-ec00a31527c5">

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/97c3e5fb-3fbf-40aa-beda-b50c16e1a948">



Copy of instant process dashboard ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/d0b282e2-2aa1-4f65-ad03-e528339cc1f4">



---------------------------------------------------------------------------------------------------------------------------



**Successfully tested agains C7-3.15.0-SNAPSHOT**

Instant process dashboards working as expected ✅ 
- Importing and displaying data as expected ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/204e7b9f-679e-42c4-9216-0ab878e51f7b">

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/4a7d4c0f-fb4d-4181-b637-d0011b32b6cf">



Copy of instant process dashboard ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/a7cd73bb-63db-4b54-b75b-1835f6341a89">
