### ISSUE TITLE
Finalize OpenSearch Front-end for minor

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23588]
Engineering DRI: @OmranAbazid

### Context

~~This task is to be executed immediately after our alpha 2 release, once we have assessed whether we can deliver all OpenSearch features as planned with the upcoming minor. If the assessment results into the need of having to hide some features, we need to hide them in the same way we did with https://github.com/camunda/camunda-optimize/issues/14180~~ 
All features are implemented for OpenSearch. Therefore now we need to remove the OpenSearch warning on the top-right corner.

### Acceptance Criteria

- There is no difference in the UI for OpenSearch and ElasticSearch for C7 and C8

### Testing Notes

- Please make sure that everything that is displayed in ElasticSearch is also displayed in OpenSearch and vice-versa for C7 and C8

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/25049
- [ ] https://github.com/camunda/camunda-optimize/pull/14835
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT and C7-3.15.0-SNAPSHOT

An exploratory testing was conducted and I didn't find any miss-matching between ES and OS ✅
