### ISSUE TITLE
Package 7: Front-End changes to Optimize due to OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23587]
### Context

This is a parent task for all Front-End changes that were made to Optimize and are related to OpenSearch

### Breakdown

```[tasklist]
- [ ] https://github.com/camunda/camunda-optimize/issues/14180
- [ ] https://github.com/camunda/camunda/issues/23585
- [ ] https://github.com/camunda/camunda/issues/23588
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
