### ISSUE TITLE
Rollback changes made to the Front-End for hiding non-implemented OpenSearch features

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23585]
Engineering DRI: @misiekhardcore

### Context

With https://github.com/camunda/camunda-optimize/issues/14180 we have performed Front-End changes to hide features that are not yet working with OpenSearch. We would like to roll-back those changes now so that Optimize displays its full feature set in C7 and C8 as well. It is [agreed with our PM](https://camunda.slack.com/archives/C05PL891Y2U/p1728996232648509) that in the upcoming alphas Optimize will display features that are not yet working with OpenSearch.
After our alpha 2 we will evaluate [with this task](https://github.com/camunda/camunda/issues/23588) whether we still need to hide any features for the upcoming minor and will act accordingly

### Acceptance Criteria

The changes from https://github.com/camunda/camunda-optimize/issues/14180 that hide unsupported features are rolled back in C7 and C8. The error display texts can stay as is

### Testing Notes

Optimize displays its full feature set and it is ok that some features are not yet working

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23644
- [ ] https://github.com/camunda/camunda-optimize/pull/14513
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by OmranAbazid** [comment]
@grlimacan do we any to do this on any maintenance/stable branch? or is it only for master/main?

**Comment by grlimacan** [comment]
> @grlimacan do we any to do this on any maintenance/stable branch? or is it only for master/main?

Hi @OmranAbazid , only on master/main, because the maintenance/stable branches will never offer these features

**Comment by RobertDorlan** [comment]
Tested agains C8-SNAPSHOT and C7-SNAPSHOT with Opensearch

Everything under the "Analysis Tab". successfully displayed ✅ 
C8
![image](https://github.com/user-attachments/assets/1b21f10f-33d1-4e7a-a615-d3b3d3e64dae)

C7
![image](https://github.com/user-attachments/assets/9cc8ab8b-8e20-4405-b3f1-e21a3be144a0)


Optimize Reports. Suggested action: Hide the 4 views below, successfully displayed ✅ 
Flow Nodes Reports (Reports -> View -> Flow Nodes)
User Task Reports (Reports -> View -> User Tasks)
Incident Reports (Reports -> View -> Incidents)
Variable Reports Reports (Reports -> View -> Variable)
(see note below for reporting specifics)

C8
![image](https://github.com/user-attachments/assets/264e5c92-7631-45f3-ba7b-3acecc0b1dd4)

C7
![image](https://github.com/user-attachments/assets/9b97ebfe-f306-4c01-9dbd-e02559e93ae5)




Combined Reports successfully displayed ✅ 
(see note below for reporting specifics)

C7
![image](https://github.com/user-attachments/assets/f70a4d5f-8414-4ef7-af69-e32f5b6c4535)


KPI reports successfully displayed ✅ 
(see note below for reporting specifics)
all report templates related to any of the above restricted options should be hidden

C8
![image](https://github.com/user-attachments/assets/15c1c4dd-d526-4019-8c05-082173f12c8b)


C7
![image](https://github.com/user-attachments/assets/aa6d7367-5dca-4bc6-aa34-7a2af31fddd0)


links to instant preview dashboard are hidden for OS successfully displayed ✅ 

C8
![image](https://github.com/user-attachments/assets/fa4a3f49-c29f-43d4-8ef2-23d8fdb43090)


C7
![image](https://github.com/user-attachments/assets/eb4ba7cf-f4ca-4d9c-89b7-35c42e30a1fd)
