### ISSUE TITLE
Missing functionality in windows c8run (compared to linux+mac)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda#23593]
**Describe the issue:**

This issue is to track the functionality that our Linux+Mac version of c8run has that the windows version does not currently support.

```[tasklist]
### Tasks
- [ ] Traps for situations like gracefully ending the program if a subprocess exits.
- [ ] windows version doesn't support --detached or --config flags
- [ ] windows version doesn't tail the logs  (it instead does --detached behavior by default with no attached option)
```

**Comment by hisImminence** [comment]
`--detached` is the default now. We can close this now.
