### ISSUE TITLE
Run Optimize upgrade tests CI also on Opensearch

### ISSUE THREAD

**Issue by PHWaechtler** [camunda/camunda#23602]
Engineering DRI: @grlimacan

### Context
When the upgrade CI step was first added these tests only ran on Elasticsearch. Now that we can also run them on opensearch lets add this to the Optimize upgrade CI workflow/

### Acceptance Criteria
Optimize upgrade CI runs on both ES and OS.

### Testing Notes
Observe upgrade CI running on both ES and OS.

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24407
- [ ] https://github.com/camunda/camunda/pull/24410
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
