### ISSUE TITLE
Move Optimize footer information to sidebar and remove footer component

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23630]
Engineering DRI: @misiekhardcore

### Context

Following other components Optimize needs to remove page footer and use info sidebar for the info displayed now in the footer

### Acceptance Criteria

- [x] move footer information into info sidebar (same as other components do)
- [x] remove footer component

### Testing Notes

- page footer is gone
- version information is displayed in user side bar

![Screenshot from 2024-10-16 15-21-00](https://github.com/user-attachments/assets/2164708d-ffec-4c8d-90b2-77af19980ef0)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23639
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT

 move footer information into info sidebar (same as other components do) ✅ 
 remove footer component ✅ 
![image](https://github.com/user-attachments/assets/1a9b49d1-05a1-4fe9-abbd-e7527d4c4c24)
