### ISSUE TITLE
Remove legacy Icon component

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23632]
Engineering DRI: @misiekhardcore

### Context

After replacing all icons with carbon equivalents, now we need to remove the old Icon component and clean up the codebase

### Acceptance Criteria

- [ ] remove Icon component
- [ ] clean up all other files related to the Icon component

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23635
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue
