### ISSUE TITLE
Implement Variable Reports for OS

### ISSUE THREAD

**Issue by oleksandr-kriuchenko-lohika** [camunda/camunda#23641]
Engineering DRI: @oleksandr-kriuchenko-lohika 

### Context

Implement Variable Reports for OS

### Acceptance Criteria

Variable Reports for OS work same way as for ES

### Testing Notes

- This is a parent ticket for the implementation of Variable reports. Please test the full functionality of Variable reports
- Should be be tested in C7 and C8

### Breakdown

```[tasklist]
### Breakdown
- [ ] https://github.com/camunda/camunda-optimize/issues/12887
- [ ] https://github.com/camunda/camunda-optimize/issues/12842
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
