### ISSUE TITLE
Implement Incident Reports for OS

### ISSUE THREAD

**Issue by oleksandr-kriuchenko-lohika** [camunda/camunda#23640]
Engineering DRI: @oleksandr-kriuchenko-lohika 

### Context

Implement Incident Reports for OS

### Acceptance Criteria

Incident Reports for OS work same way as for ES

### Testing Notes

- This is a parent ticket for the implementation of Incident reports. Please test the full functionality of Incident reports
- Should be be tested in C7 and C8

### Breakdown

```[tasklist]
### Breakdown
- [ ] https://github.com/camunda/camunda-optimize/issues/12918
- [ ] https://github.com/camunda/camunda-optimize/issues/12920
- [ ] https://github.com/camunda/camunda-optimize/issues/12839
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C7 3.15.0-SNAPSHOT

View = Incident
Measure = Count
Group by = Flow node
![image](https://github.com/user-attachments/assets/d7ca920c-bee7-4021-9c71-d3aca65481fc)

View = Incident
Measure = Count
Group by = Flow node
with the view of Raw data
![image](https://github.com/user-attachments/assets/bf4f57ab-38dc-4397-b6d5-823cd9e1bfd8)

View = Incident
Measure = Count
with the view of Raw data
![image](https://github.com/user-attachments/assets/215cb71d-2635-4230-9762-d8db4b2bc428)

View = Incident
Measure = Resolution duration
with the view of Raw data
![image](https://github.com/user-attachments/assets/4f40edfd-5b24-4156-a227-b946e18d6553)
