### ISSUE TITLE
Implement User Task Reports for OS

### ISSUE THREAD

**Issue by oleksandr-kriuchenko-lohika** [camunda/camunda#23643]
Engineering DRI: @oleksandr-kriuchenko-lohika

### Context

Implement User Task Reports for OS

### Acceptance Criteria

User Task Reports for OS work same way as for ES

### Testing Notes

- This is a parent ticket for the implementation of User Task reports. Please test the full functionality of User Task reports
- Should be be tested in C7 and C8

### Breakdown

```[tasklist]
- [ ] https://github.com/camunda/camunda-optimize/issues/12919
- [ ] https://github.com/camunda/camunda-optimize/issues/12921
- [ ] https://github.com/camunda/camunda-optimize/issues/12855
- [ ] https://github.com/camunda/camunda-optimize/issues/12841
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
For the Group by = Start date/End date that are not working this will be tested when the following ticket is completed --> https://github.com/camunda/camunda/issues/24690

**Comment by RobertDorlan** [comment]
This is now working and tested as part of the fix of https://github.com/camunda/camunda/issues/24690
