### ISSUE TITLE
Implement alerts for OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23653]
Engineering DRI: @grlimacan

### Context

Verify that alerts are working properly for OpenSearch. Required code is already implemented, however the functionality is still not working 100% (and also not all ITs are passing) due to pending implementation of reporting

### Acceptance Criteria

- All Alert related integration tests are working
- The functionality is validated for real use cases in C7 and C8

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains C7-3.15.0-SNAPSHOT**

All Alert related integration tests are working ✅ 
![image](https://github.com/user-attachments/assets/f430328b-a9cb-49fc-b1f0-c1742c0aa0e9)
![image](https://github.com/user-attachments/assets/2f619cca-4d71-43cf-8186-a46251346e25)


For now waiting for this ticket --> [ticket](https://github.com/camunda/camunda/issues/24186) to be resolve to test on C8
