### ISSUE TITLE
Migrate to ESLint v9

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23695]
Engineering DRI: @misiekhardcore

### Context

The eslint v8 is end of life from 5th October 2024 so we need to update

### Acceptance Criteria

- [x] ESLint is migrated to v9
- [x] there are no errors/warning in the codebase

### Links

- [convo](https://camunda.slack.com/archives/C01H4NG9XDY/p1726038280348729)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23711
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by misiekhardcore** [comment]
Nope, we can close this actually
