### ISSUE TITLE
[8.3] Fix E2E test: multiInstanceSelection.spec.ts › Multi Instance Flow Node Selection

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#23694]
### Description

This test is flaky on the `stable/8.3` branch of Operate.

Example failure: https://github.com/camunda/operate/actions/runs/11361362548/job/31600903444

```
 1) [chromium] › tests/multiInstanceSelection.spec.ts:59:7 › Multi Instance Flow Node Selection › expand multi instance flow nodes in instance history 

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 25
    Received: 20

    Call Log:
    - Test timeout of 30000ms exceeded

      23 |
      24 |   // wait until all flow nodes are in incident state
    > 25 |   await expect
         |   ^
      26 |     .poll(
      27 |       async () => {
      28 |         const response = await request.post(

        at /home/runner/work/operate/operate/client/e2e-playwright/tests/multiInstanceSelection.spec.ts:25:3
```

### TODO

- [ ] Verify if this test is flaky on stable/8.3 only
- [ ] Investigate if there were fixes for this test since stable/8.3
- [ ] Fix the test
- [ ] Run e2e tests multiple times to ensure it's not flaky anmore

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ⚠️ Mid |
| **When** | ⚠️ Soon |
| **Confidence** | 0.94 |

---

### 📝 Rationale

This is flaky E2E test maintenance, not incorrect product behavior; it improves CI reliability and developer workflow. The issue is within Core Features ownership because it concerns Operate web-application E2E coverage. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
