### ISSUE TITLE
Teach Task Listeners how to change user task data

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#23708]
Task Listeners must be able to change the data of the user task.

For example, an `assignment` task listener may want to re-assign another candidate if it sees that the assigning person is currently out of office.

To achieve this, the Task Listener must be able to pass this information along with the job completion.
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/24712
- [ ] https://github.com/camunda/camunda/issues/24756
- [ ] https://github.com/camunda/camunda/issues/24889
- [ ] https://github.com/camunda/camunda/issues/25447
- [ ] https://github.com/camunda/camunda/issues/25448
- [ ] https://github.com/camunda/camunda/issues/25449
- [ ] https://github.com/camunda/camunda/issues/26032
- [ ] https://github.com/camunda/camunda/issues/26206
```
