### ISSUE TITLE
Move archiver to camunda exporter

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#23721]
**Description**

The archiver should be integrated into the new architecture.  To achieve this we will move the existing archivers from Operate and Tasklist to camunda-exporter, while merging them according to the harmonized indices.

* The archiver will added to camunda-exporter module. `io.camunda.exporter.archiver`
* Archiver will run per partition. 
* Archiver runs on its own thread pool to avoid blocking exporter actor threads

- [ ] Implement ElasticsearchArchiverRepository
    * Use the Operate implementation as the basis and can be adpated later to include required functionailities for tasklist
- [ ] Implement OpensearchArchiverRepository
    * Use the Operate implementation as the basis and can be adpated later to include required functionailities for tasklist
- [ ] Move/Implement `Archiver`, `ArchiverJob`, `AbstractArchiverJob` from Operate
    * Archiver can take a list of `ArchiverJob`s and starts/stop them on demand
    * `ArchiverJob`s should archive in batches and schedule itself when one batch is completed.
- [ ] Move/Implement actual archiver jobs from Operate and Tasklist. Merge them as needed.
    * TBD
    * Start with existing Operate archiver jobs
    * Add or merge tasklist archivers later
- [ ] Integrate archiver with the exporter
    * Configure the archiver and archiver jobs in `DefaultExporterResourceProvider`. Note that the BatchProcessingArchiver should be only started on partition 1. Other archivers should start on all partitions and only archive data for the respective partitions. 
    * On exporter open start archiver
    * On exporter close stop archiver
- [ ] Ensure ILM policy is correctly assigned to the respective indices
- [ ] Add and document required configuration parameters to the exporter configuration. (Check existing ArchiverProperties in operate)
    
    
Reference:
* [Discussion doc](https://docs.google.com/document/d/184JfguLkLOp03zArBq5IX236CO9yFZY4hCh3L8Hv0-U/edit#heading=h.4r06t8r0ou3w)
* [Spike](https://github.com/camunda/camunda/pull/23687)
* Existing archiver code in [Operate](https://github.com/camunda/camunda/tree/dd-poc-archiver-in-exporter/operate/archiver/src/main/java/io/camunda/operate/archiver)
* Existing archiver code in [Tasklist](https://github.com/camunda/camunda/tree/dd-poc-archiver-in-exporter/tasklist/archiver/src/main/java/io/camunda/tasklist/archiver) 
```[tasklist]
### Basic archiving logic against a NOOP data store
- [ ] https://github.com/camunda/camunda/issues/24078
- [ ] https://github.com/camunda/camunda/issues/24079
- [ ] https://github.com/camunda/camunda/issues/24290
```

```[tasklist]
### Data store implementations
- [ ] https://github.com/camunda/camunda/issues/24093
- [ ] https://github.com/camunda/camunda/issues/24094
```

```[tasklist]
### Testing
- [ ] https://github.com/camunda/camunda/issues/24095
- [ ] https://github.com/camunda/camunda/issues/24096
```

```[tasklist]
### Follow ups/possible improvements
- [ ] https://github.com/camunda/camunda/issues/24382
- [ ] https://github.com/camunda/camunda/issues/24566
- [ ] https://github.com/camunda/camunda/issues/24747
```

**Comment by mustafadagher** [comment]
Hello team, 
As part of #18372, we will be moving the logic to complete operate operations to the exporter (relying on the operation reference sent from operate). 
But we have one issue (4th open question in this [comment](https://github.com/camunda/camunda/issues/18372#issuecomment-2435662446)):
> ❓ In operate, we also updated [BatchOperationEntity](https://github.com/camunda/camunda/blob/main/operate/schema/src/main/java/io/camunda/operate/entities/BatchOperationEntity.java) by decrementing total operations counts when completing an operation related to this batch, this won't be possible in the exporter since we have no knowledge about the batch operation id available during exporting, what should happen to that logic?

We thought this can be combined with the post-importer actions, and since those have been decided to be part of the archiver. I wanted to ask you if you think if you can also incorporate the batch operation completion logic to in the Archiver as well?

Let me know your thoughts!

**Comment by sdorokhova** [comment]
I created an issue for the batch operation problem: https://github.com/camunda/camunda/issues/24084

**Comment by npepinpe** [comment]
Question to figure out:
- For brown field deployments, would existing historic indices from that day have some existing ILM policy set? Would archiving new things (which sets the lifecycle policy) break anything?

**Comment by npepinpe** [comment]
Some more thoughts while I'm working through stuff:

- To make it easier to test, I would separate the scheduling behavior from the job behavior. That way I can test scheduling (e.g. always reschedule no matter what) separately from the jobs themselves.
- Since we have one repository per exporter, we can scope the API to the partition, so the jobs don't need to care about partition IDs. _This may change in the future of course, but it might make things simpler for now_.
- To properly stop execution and avoid unnecessary error handling/continuations, one way would be to ensure that _all_ asynchronous callbacks are executed on the same executor. That way, we can simply stop it, and it will stop the execution pipeline in its track. We can then safely clean up resources afterwards.
  - There's still an edge case of closing, say, the underlying ES client while a request is happening. While this will cause an error to be thrown, the `exceptionallyAsync` handler will not be executed to log and work with the error, since the executor will be shutdown first. So I think this should be OK.
  - This does mean we rely on people _always_ using the `async` variants for completable future, and _always_ passing the executor. This is somewhat brittle. Maybe a ArchUnit test?
  - The other option is having a switch in all the jobs which knows if the archiver is shutdown or not. And every callback then has to check that. The downside still applies: if someone forgets to check it, then you might do something wrong in the callback.
- I might also scope the repository instance to use the same executor for some of its callbacks, e.g. chaining reindex and delete for the `moveDocuments` method.

**Comment by npepinpe** [comment]
One thing to note: we'd like to block 2h to look into starting a small async client abstraction in the search client modules. We think it should be easy to do, as the types are generally the same (so we can reuse all query transformers), and we can start small and only support basic stuff: search, scroll, and bulk.

**Comment by ChrisKujawa** [comment]
@npepinpe you can add such improvements in https://github.com/camunda/camunda/issues/24328 

I will close this issue, as the general work on migrating the archiver has been done. To add more E2E, we have the referenced follow-up issue. This will be tackled in `Iteration 4: Stabilization` as part of [ Extend test coverage of Camunda Exporter](https://github.com/camunda/camunda/issues/25595 )
