### ISSUE TITLE
C8 API Variable value as free-form object

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#23724]
### Description

Currently the value of a variable is a JSON object encoded and stored as String value.

Example: 
```json
{
 "name": "person"
 "value" : "{\"name\":  \"Homer\"}"
}
```

The value should be an JSON object:

```json
{
 "name": "person"
 "value" : {"name":  "Homer"}
}
```

It is called `Free-Form Object` in [OpenAPI](https://swagger.io/docs/specification/v3_0/data-models/data-types/#objects)

The value can be used in search filter and for result items:

VariableFilter:
```
    VariableFilterRequest:
      description: Variable filter request.
      type: object
      properties:
        variableKey:
          description: The key for this variable.
          type: integer
          format: int64
       ...
        value:
          description: The value of the variable.
          type: object
```

VariableItem:
```yaml
    VariableItem:
      description: Variable search response item.
      type: object
      properties:
        variableKey:
        ...
        value:
          description: Value of this variable.
          type: object
```

### TODO

- [ ] How handle this internally in API. Storage in datastore is currently as string. Can this be stored as an object?
- [ ] How to implement this and where. In service layer or conversion in controller?
- [ ] Implement as result item
- [ ] Implement as filter

### Additional Information

Raised in [Slack thread](https://camunda.slack.com/archives/C06UKS51QV9/p1728977700713929)

**Comment by tmetzke** [comment]
@aleksander-dytko, this would be an improvement from the V1 variable search.
As far as I can see, this is straightforward to implement but still needs some time to implement.
I would like to put this into our last C8 API 8.7 increment (Nov 4 - Nov 24) to potentially make it to 8.7-alpha2.
It doesn't have the highest priority but it can also be tackled by anyone in the team actually, so an ideal candidate for a nice-to-have.

We can also deliver it with 8.8+ but the filter API for the variable, user task, and process instance search would need to be adjusted from `string` to `object` for the variable `value` attribute. 
This is a generalization (moving from a more specific to a more generic type), so it's backward-compatible regarding user input. However, it's not 100 percent compatible regarding generated REST API clients of all programming languages. But we can document it in a migration guide which should still be OK.

Overall, I'd like to treat this as a nice-to-have for 8.7 but we should be able to deliver it with 8.8+ as well.
@jonathanlukas, let me know if any of the above reasoning is wrong or if I overlooked anything.

**Comment by tmetzke** [comment]
One thing to consider here: can we and do we want to deserialize all values in the REST API that we receive from the data layer? At least in ES/OS, we store serialized and escaped JSON values. Job workers can set those values with specific business logic and serialization methods. We might a) not be able to deserialize and b) it might not be safe to simply deserialize everything.

Maybe it's not that much of a problem but I wanted to note this here so we at least think about this and make a conscious decision.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** No Status  
**To:** Inbox  

**Reason:** Queued for further analysis and triage.

**Comment by marcosgvieira** [comment]
🔄 **Assignee updated automatically (Core Features)**

**Reason:** As the label kind/feature-request is present this issue is being assigned to Product Manager
