### ISSUE TITLE
Issue verifying token signatures when JWKs use the ES256 algorithm

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#23727]
### Description

The context is IAM integration and validating user tokens (JWT) provided by the identity provider. When a JWT is returned, it may be signed (depending on the identity provider). The IAM client then needs to verify the signature against a set of JSON web keys (JWK) that the identity provider exposes.  See an [example JWKs response](https://stackoverflow.com/a/61200654).

Some identity providers (in the case leading to the ticket, it was a customized version of Ping Federate Identity Provider), provide JWKs without indicating the algorithm that was used to encode the keys (`alg` field missing in the response). Originally we assumed, that in that situation, the exception below gets raised in Operate's integration because Identity had already had similar (but not exactly the same) issue and they implemented [the workaround](https://github.com/camunda-cloud/identity/pull/3002). But Identity has their own implementation, whereas in Operate we would have had to adjust Spring Security or Nimbus behavior to work around this case as is part of Spring Security's `org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter`, which in turn uses the [Nimbus JOSE + JWT library](https://connect2id.com/products/nimbus-jose-jwt) for decoding and validating JWTs.

The exception is raised by Nimbus because it doesn't find a matching key for validating the JWT. In particular for Ping Federate and the originating case, the returned JWT is encoded with ES256 (which is different from default RSA). We found out while further investigating, that the empty algorithm field actually does *not* lead to the exception, but the nimbus decoder [by default only supports RS256](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-decoder-algorithm). Other trusted algorithms have to be added manually.

### Root cause

* ~~The identity provider's JWKS response misses the `alg` property. This is against the JWKS specification. However, we may have to tolerate that case since requesting to use a fixed identity provider may not be an option.~~
* The Nimbus decoder by default only supports the RS256 algorithm but in the use case where this error appears ES256 is used
* Here the exception is thrown by Nimbus when it cannot find a matching JWKS key for a token: https://bitbucket.org/connect2id/nimbus-jose-jwt/src/fa2cffe6b8ffccfcb44f6daa798c2c8ed7b671b5/src/main/java/com/nimbusds/jwt/proc/DefaultJWTProcessor.java#lines-393:395

### TODO

* Backport to 8.5 and 8.6

### Additional Information

* We configure the JWT decoder used by Spring here: https://github.com/camunda/camunda/blob/operate-8.5.6/operate/webapp/src/main/java/io/camunda/operate/webapp/security/oauth2/IdentityOAuth2WebConfigurer.java (note this is the code of 8.5.6, it has changed a bit on main)
* `io.camunda.operate.webapp.security.oauth2.JwtAuthenticationIT` or tests in the same package may be the right test classes and set up to reproduce/test this

Incident slack channel: https://camunda.slack.com/archives/C07RFJEMUU8
Support case: https://jira.camunda.com/browse/SUPPORT-23905
Operate version: 8.5.6

```[tasklist]
### PRs
- [x] main: https://github.com/camunda/camunda/pull/26471
- [x] 8.6: https://github.com/camunda/camunda/pull/26231
- [x] 8.5: https://github.com/camunda/camunda/pull/26497
```

**Comment by sdorokhova** [comment]
Exception: 
```
com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:357) ~[nimbus-jose-jwt-9.37.3.jar!/:9.37.3]
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:303) ~[nimbus-jose-jwt-9.37.3.jar!/:9.37.3]
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:158) ~[spring-security-oauth2-jose-6.2.5.jar!/:6.2.5]
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.decode(NimbusJwtDecoder.java:138) ~[spring-security-oauth2-jose-6.2.5.jar!/:6.2.5]
	at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.getJwt(JwtAuthenticationProvider.java:99) ~[spring-security-oauth2-resource-server-6.2.5.jar!/:6.2.5]
	at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:88) ~[spring-security-oauth2-resource-server-6.2.5.jar!/:6.2.5]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.2.5.jar!/:6.2.5]
	at org.springframework.security.authentication.ObservationAuthenticationManager.lambda$authenticate$1(ObservationAuthenticationManager.java:54) ~[spring-security-core-6.2.5.jar!/:6.2.5]
	at io.micrometer.observation.Observation.observe(Observation.java:565) ~[micrometer-observation-1.12.7.jar!/:1.12.7]
	at org.springframework.security.authentication.ObservationAuthenticationManager.authenticate(ObservationAuthenticationManager.java:53) ~[spring-security-core-6.2.5.jar!/:6.2.5]
	at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:137) ~[spring-security-oauth2-resource-server-6.2.5.jar!/:6.2.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.10.jar!/:6.1.10]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.2.5.jar!/:6.2.5]
	at io.camunda.operate.webapp.security.BaseWebConfigurer$1.doFilterInternal(BaseWebConfigurer.java:255) ~[!/:8.5.6]

```

**Comment by kristinkomschow** [comment]
Further explanations and helpful resources [WIP comment]:

JWTs consist of three Base64 encoded parts that are separated by a dot: [HEADER].[PAYLOAD].[SIGNATURE]
The signature is the part that is encrypted with the algorithm declared in the header.
Useful website to see the decoded JWT: https://jwt.io/

Documentation for generating a JWT with RSA signature: https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-signature
Documentation for JWK generation: https://connect2id.com/products/nimbus-jose-jwt/examples/jwk-generation

Workflow:

Reading the JWK from the auth server happens in `com.nimbusds.jose.jwk.source.RemoteJWKSet.updateJWKSetFromURL()`
[TODO]

Our goal for a fix:
Use an own JWEKeySelector that uses the default selector, but has a fallback in case that one fails (because of no alg field).

**Comment by kristinkomschow** [comment]
Test case showed that a missing algorithm field does not lead to this error. That is because the [JWKMatcher ](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/9.42.2/src/main/java/com/nimbusds/jose/jwk/JWKMatcher.java#lines-1118) always return null as a possible algorithm value for all RSA and EC algorithms, so the matcher passes that check for the key (and returns it as a candidate).

The error does, however, get thrown, when using the ES256 algorithm for the JWT/JWK. The [JWSVerificationKeySelector](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/src/main/java/com/nimbusds/jose/proc/JWSVerificationKeySelector.java#lines-142) then returns an empty list of keys because the only supported algorithm (`this.jwsAlgs`) is RSA256.

**Comment by kristinkomschow** [comment]
Adding supported algorithms via the decoder builder is described here: https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-decoder-builder

My plan now is to add all signature algorithms that are also supported by identity (RS256, RS384, RS512, ES256, ES384, ES512) as shown here:
https://github.com/camunda-cloud/identity/blob/aca3ff4d22e070ae1205514c80c7d4be8939e929/sdk-java/src/main/java/io/camunda/identity/sdk/authentication/AbstractAuthentication.java#L288-L304
