### ISSUE TITLE
[EPIC] Provide API migration guide content

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23736]
## Acceptance criteria

* An overview of changes users will face when moving from V1 component REST APIs to the V2 C8 REST API.
* A list of general changes (like general path, naming, and request/response structure).
* An endpoint-specific changeset list, outlining adjusted/removed attributes or functionality compared to V1

## Resources

* [Migration guide document](https://docs.google.com/document/d/1h1i2ZzHsrun7lyNVJn6I2Z-VBvAqYwRGcpiN-wmviwM) (🔒 internal)

## Breakdown

```[tasklist]
### Tasks
- [ ] Add general path changes (@tmetzke)
- [ ] Add general request/response structure changes (@tmetzke)
- [ ] Add general naming changes (@tmetzke)
- [ ] Add user task endpoints' changes (@nathansandi)
- [ ] Add process definition endpoints' changes
- [ ] Add process definition endpoints' changes
- [ ] Add process instance endpoints' changes
- [ ] Add decision definition endpoints' changes
- [ ] Add decision instance endpoints' changes
- [ ] Add decision requirement endpoints' changes
- [ ] Add flownode instance endpoints' changes
- [ ] Add incident endpoints' changes
- [ ] Add variable endpoints' changes
```

**Comment by tmetzke** [comment]
## Alignment with DevEx team (@akeller, @christinaausley, and @pepopowitz)

* Engineering provides content in the Google Doc
* DevEx team starts with creating the appropriate structures in `camunda-docs`, migrates existing content
* Engineering contributes to the camunda-docs directly afterward

=> We incrementally fill the migration guide publicly to get feedback early

**Comment by pepopowitz** [comment]
Not sure this is the right place, but I'm going to stick here a few examples of API migration guides I'm finding in other places.

* [Google](https://developers.google.com/people/contacts-api-migration) -- I think it actually lacks a lot of context other than the first couple paragraphs, but I do appreciate the table for direct mappings.
* [Primer](https://apiref.primer.io/docs/api-migration-guide) -- not a format I'd have thought of -- sample messages, v1 next to v2. It seems like we'd have way too many changes for this to be a reasonable approach, but it is interesting.

I'll add more as I find them. I also have a couple posts out in public Slack communities to gather examples from people, and I'll share them back here.

**Comment by christinaausley** [comment]
@tmetzke I've added your basic content into [this PR](https://github.com/camunda/camunda-docs/pull/4557) -- anyone can jump into this branch and make changes.

Note that I still plan to link to the guide in a handful of docs and incorporate some tabs/restructuring for clean reading once the content is closer to complete.

**Comment by akeller** [comment]
@christinaausley @tmetzke see my comment [here](https://github.com/camunda/product-hub/issues/2524#issuecomment-2462689054), regarding specific use cases for zbctl identified by the Support team.

This could warrant a separate guide entirely, transitioning from zbctl to the REST API. Can you please evaluate these use cases against your in-flight work and determine how you want to handle this feedback?

**Comment by tmetzke** [comment]
@akeller, I've added a comment to the parent issue regarding `zbctl`. Having a dedicated migration guide or section makes sense. I consider it out of the scope of this issue. Let's create a dedicated issue for that. It can still go into the API migration guide but has its own scope.

**Comment by tmetzke** [comment]
All V1 endpoints have a migration guide entry now, including changes to migrate to V2. Closing this as done.
Any follow-ups regarding UX and structural improvements should be tracked somewhere else.

**Comment by christinaausley** [comment]
Huge feat! Awesome work @tmetzke 🚀
