### ISSUE TITLE
Add process instance endpoints' changes

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23742]
## Description

Add the user-facing changes from V1 to V2 to the [API migration guide](https://github.com/camunda/camunda-docs/blob/main/docs/apis-tools/migration-manuals/migrate-to-camunda-api.md).

Suggested procedure:
* Compare the public reference documentation from V1 with the V2 documentation, e.g. the input and output parameters of endpoints, general structure of inputs and outputs, and potential behavioral changes.

```[tasklist]
### Tasks
- [ ] [Search process instances](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/search-1/) - `POST /v1/process-instances/search`
- [ ] [Get process instance by key](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/by-key-1/) - `GET /v1/process-instances/:key`
- [ ] [Delete process instance and all dependant data by key](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/delete/) - `DELETE /v1/process-instances/:key`
- [ ] [Get flow node statistic by process instance id](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/get-statistics/) - `GET /v1/process-instances/:key/statistics`
- [ ] [Get sequence flows of process instance by key](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/sequence-flows-by-key/) - `GET /v1/process-instances/:key/sequence-flows`
```
