### ISSUE TITLE
Add user task endpoints' changes

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23740]
## Description

Add the user-facing changes from V1 to V2 to the [API migration guide](https://github.com/camunda/camunda-docs/blob/main/docs/apis-tools/migration-manuals/migrate-to-camunda-api.md).

Suggested procedure:
* Compare the public reference documentation from V1 with the V2 documentation, e.g. the input and output parameters of endpoints, general structure of inputs and outputs, and potential behavioral changes.

```[tasklist]
### Tasks
- [x] [Get a form](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/get-form/) - `GET /v1/forms/:formId`
- [x] [Save draft variables](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/save-draft-task-variables/) - `POST /v1/tasks/:taskId/variables`
- [x] [Search task variables](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/search-task-variables/) - `POST /v1/tasks/:taskId/variables/search`
- [x] [Search tasks](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/search-tasks/) - `POST /v1/tasks/search`
- [ ] [Unassign a task](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/unassign-task/) - `PATCH /v1/tasks/:taskId/unassign`
- [ ] [Complete a task](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/complete-task/) - `PATCH /v1/tasks/:taskId/complete`
- [ ] [Assign Task](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/assign-task/) - `PATCH /v1/tasks/:taskId/assign`
- [ ] [Get a task](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/get-task-by-id/) - `GET /v1/tasks/:taskId`
```

**Comment by tmetzke** [comment]
@nathansandi, can we list ALL endpoints from https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/tasklist-rest-api/ and how they have been replaced in V2?

**Comment by nathansandi** [comment]
Hello @tmetzke 
Do you mean the 
- [Save draft variables](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/save-draft-task-variables/)
- [Will be covered on variable tickets] [Search task variables](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/search-task-variables/)
- [OK] [Search tasks](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/search-tasks/)

Other ones: 
- [Unassign a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/unassign-task/)
- [Complete a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/complete-task/)
- [Assign a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/assign-task/)
- [Get a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/get-task-by-id/)

**Comment by tmetzke** [comment]
> Hello @tmetzke
> 
> Totally, I am sorry, was not clear for me the final scope :)
> 
> I have updated here, as well as the document with the follow migration changes.
> 
> * [OK/Removed][Save draft variables](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/save-draft-task-variables/)
> * [Will be covered on **variable** tickets] [Search task variables](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/search-task-variables/)
> * [OK] [Search tasks](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/search-tasks/)
> * [OK] Get Form
> 
> Other ones:
> 
> I just included over the Migration Guide
> 
> * [Unassign a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/unassign-task/)
> * [Complete a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/complete-task/)
> * [Assign a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/assign-task/)
> * [Get a task](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/get-task-by-id/)

Yep, exactly, thanks for adding them all 👍

**Comment by tmetzke** [comment]
@nathansandi, can you create a PR for the changes in https://github.com/camunda/camunda-docs/?
The changes need to go into https://github.com/camunda/camunda-docs/blob/main/docs/apis-tools/migration-manuals/migrate-to-camunda-api.md.
Thank you!

**Comment by nathansandi** [comment]
The follow up Pull Request 
I was already working on this in a local branch 🥇 
https://github.com/camunda/camunda-docs/pull/4756
