### ISSUE TITLE
Add decision requirement endpoints' changes

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23745]
## Description

Add the user-facing changes from V1 to V2 to the [API migration guide](https://github.com/camunda/camunda-docs/blob/main/docs/apis-tools/migration-manuals/migrate-to-camunda-api.md).

Suggested procedure:
* Compare the public reference documentation from V1 with the V2 documentation, e.g. the input and output parameters of endpoints, general structure of inputs and outputs, and potential behavioral changes.

```[tasklist]
### Tasks
- [ ] [Search decision requirements](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/search-5/) - `/v1/drd/search`
- [ ] [Get decision requirements by key](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/by-key-5/) - `/v1/drd/:key`
- [ ] [Get decision requirements as XML by key](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/xml-by-key-1/) - `/v1/drd/:key/xml`
```

**Comment by nathansandi** [comment]
Pull Request for review
https://github.com/camunda/camunda-docs/pull/4796/files
