### ISSUE TITLE
Add variable endpoints' changes

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23748]
## Description

Add the user-facing changes from V1 to V2 to the [API migration guide](https://github.com/camunda/camunda-docs/blob/main/docs/apis-tools/migration-manuals/migrate-to-camunda-api.md).

Suggested procedure:
* Compare the public reference documentation from V1 with the V2 documentation, e.g. the input and output parameters of endpoints, general structure of inputs and outputs, and potential behavioral changes.

```[tasklist]
### Tasks
- [ ] [Get Task Variable](https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/specifications/get-variable-by-id/) - `GET /v1/variables/:variableId`
- [ ] [Search process instance variable](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/search/) - `POST /v1/variables/search`
- [ ] [Get variable by key](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/by-key/) - `GET /v1/variables/:key`
```

**Comment by tmetzke** [comment]
@nathansandi, let's add this to the [public migration guide](https://github.com/camunda/camunda-docs/blob/main/docs/apis-tools/migration-manuals/migrate-to-camunda-api.md) as well.

**Comment by nathansandi** [comment]
Same as Tasklist
I was working already on this in a local branch :D 
The follow up Pull Request 
https://github.com/camunda/camunda-docs/pull/4756

**Comment by tmetzke** [comment]
@nathansandi, there are two further variable endpoints we need to document besides the task variable endpoint. I added all 3 that I think are relevant to the issue description.
