### ISSUE TITLE
Fix Optimize e2e tests running in chrome

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23749]
Engineering DRI: @misiekhardcore

### Context

With chrome update to v130, `testcafe` no longer works, throwing web socket connection errors

### Acceptance Criteria

- [x] temporarily use older version of chrome browser

### Testing Notes

- [ ] e2e are passing

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23753
- [ ] https://github.com/camunda/camunda-optimize/pull/14525
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
