### ISSUE TITLE
Verify that all OpenSearch database settings are working as intended 

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23752]
### Context

<!-- Please, describe the context and need for this task.-->
In the [technical documentation](https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/system-configuration/) we describe all OpenSearch related settings that the user can configure for Optimize with OpenSearch.
Verify that all settings work as intended, here's the complete list:

#### Connection settings

| YAML path                                             | Confirmed? | Description                                                                                                                                                          |
| ----------------------------------------------------- | ------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| opensearch.connection.timeout                         | C7, C8         | Maximum time without connection to OpenSearch that Optimize should wait until a timeout triggers.                                                                    |
| opensearch.connection.responseConsumerBufferLimitInMb | No - [see this](https://github.com/camunda/camunda/issues/24083)           | Maximum size of the OpenSearch response consumer heap buffer. This can be increased to resolve errors from OpenSearch relating to the entity content being too long. |
| opensearch.connection.pathPrefix                      |        C7, C8       | The path prefix under which OpenSearch is available.                                                                                                                 |
| opensearch.connection.nodes[*].host                   | C7, C8     | The address/hostname under which the OpenSearch node is available.                                                                                                   |
| opensearch.connection.nodes[*].httpPort               | C7, C8          | A port number used by OpenSearch to accept HTTP connections.                                                                                                         |
| opensearch.connection.proxy.enabled                   | No - [see this](https://github.com/camunda/camunda-optimize/issues/10058)         | Whether an HTTP proxy should be used for requests to OpenSearch.                                                                                                     |
| opensearch.connection.proxy.host                      | No - [see this](https://github.com/camunda/camunda-optimize/issues/10058)          | The proxy host to use, must be set if `opensearch.connection.proxy.enabled = true`.                                                                                  |
| opensearch.connection.proxy.port                      | No - [see this](https://github.com/camunda/camunda-optimize/issues/10058)          | The proxy port to use, must be set if `opensearch.connection.proxy.enabled = true`.                                                                                  |
| opensearch.connection.proxy.sslEnabled                | No - [see this](https://github.com/camunda/camunda-optimize/issues/10058)         | Whether this proxy is using a secured connection (HTTPS).                                                                                                            |
| opensearch.connection.skipHostnameVerification        | C7, C8         | Determines whether the hostname verification should be skipped.                                                                                                      |

#### Index settings

| YAML path                                        | Confirmed? | Description                                                                                                                                                                                                                                                                                                                                                                                                            |
| ------------------------------------------------ | ------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| opensearch.settings.index.prefix                 | C7, C8      | The prefix prepended to all Optimize index and alias names. Custom values allow you to operate multiple isolated Optimize instances on one OpenSearch cluster. <br /><br />NOTE: Changing this after Optimize has already run will create new empty indexes.                                                                                                                                                           |
| opensearch.settings.index.number_of_replicas     | C7, C8             | How often data should be replicated to handle node failures.                                                                                                                                                                                                                                                                                                                                                           |
| opensearch.settings.index.number_of_shards       | C7, C8             | How many shards should be used in the cluster for process instance and decision instance indices. All other indices will be made up of a single shard. <br /><br />NOTE: This property only applies the first time Optimize is started and the schema/mapping is deployed on OpenSearch. If you want this property to take effect again, you need to delete all indices (and with that all data) and restart Optimize. |
| opensearch.settings.index.refresh_interval       | C7, C8            | How long OpenSearch waits until the documents are available for search. A positive value defines the duration in seconds. A value of -1 means a refresh needs to be done manually.                                                                                                                                                                                                                                     |
| opensearch.settings.index.nested_documents_limit | C7, [C8 (Yes but Bug)](https://github.com/camunda/camunda/issues/24059)         | Optimize uses nested documents to store list information such as activities or variables belonging to a process instance. This setting defines the maximum number of activities, variables, or incidents that a single process instance can contain. This limit helps to prevent out of memory errors and should be used with care. For more information, refer to the OpenSearch documentation on this topic.         |

#### OpenSearch security

Define a secured connection to be able to communicate with a secured OpenSearch instance.

| YAML path                                       | Confirmed? | Description                                                                                                                                                                                                                                                  |
| ----------------------------------------------- | ------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| opensearch.security.username                    |      C7, C8         | The basic authentication (x-pack) username.                                                                                                                                                                                                                  |
| opensearch.security.password                    |      C7, C8         | The basic authentication (x-pack) password.                                                                                                                                                                                                                  |
| opensearch.security.ssl.enabled                 |  C7, C8         | Used to enable or disable TLS/SSL for the HTTP connection.                                                                                                                                                                                                   |
| opensearch.security.ssl.certificate             |       C7, C8        | The path to a PEM encoded file containing the certificate (or certificate chain) that will be presented to clients when they connect.                                                                                                                        |
| opensearch.security.ssl.certificate_authorities | C7, C8        | A list of paths to PEM encoded CA certificate files that should be trusted, for example ['/path/to/ca.crt']. <br /><br />NOTE: if you are using a public CA that is already trusted by the Java runtime, you do not need to set the certificate_authorities. |
| opensearch.security.ssl.selfSigned              | C7, C8         | Used to specify that the certificate was self-signed.                                                                                                                                                                                                        |

### Acceptance Criteria

<!-- Please list the Acceptance Criteria. It will be used during Review -->

1. For each setting, either a confirmation that the setting is working as intended or the creation of a github issue in order to make that setting work

### Testing Notes

<!-- Any additional information that can be used for review should be provided here -->

### Links

<!-- Add links to related issues -->

### Breakdown

<!-- A breakdown of tasks that need to be completed in order for this to be ready for review. -->
<!--
- [ ] #123
- [ ] Step X
-->

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### Review

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by grlimacan** [comment]
Investigation completed. The results have been detailed [here](https://github.com/camunda/camunda/issues/23752#issue-2601896285) and new GitHub issues have been created where appropriate
