### ISSUE TITLE
Use latest version of chrome in Optimize e2e tests

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#23776]
### Context

Currently testcafe does not work wirh `chrome` >= `v130`. When there will be a patch or update to `testcafe`/`chrome` allowing testcafe` to work again with latest version of `chrome`, we need to do so and revert the temporary fix done in https://github.com/camunda/camunda/issues/23749

### Acceptance Criteria

- [ ] make e2e work with latest version of `chrome:headless` browser

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by OmranAbazid** [comment]
This issue seems to be outdated as we are now using chrome 1.40 for our e2e tests.
