### ISSUE TITLE
As a user I can define an optional prefix for indices stored in ES/OS

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#23807]
## Description

Previously we supported in Tasklist and Operate custom prefixes for indices (stored in ES or OS). They were separate configurations (it was possible to configure different prefixes), additionally they replaced the component prefix `tasklist-` or `operate-` from the index name.

In our recent work, we [harmonized indices to one schema](https://docs.google.com/document/d/1w1VzwyvvBzu0vnjCUj4UcLxTCVae8iMXAMA5_m6xs1s/edit#bookmark=id.vdvz69sho0gb). Component names need to still exist as part of the index names to avoid migration, but we still want to support custom prefixes but on a more global level.

```[tasklist]
### Global prefix
- [ ] #23638
- [ ] https://github.com/camunda/camunda/issues/23808
- [x] Optional prefix in migration application
- [ ] https://github.com/camunda/camunda/issues/23972
- [ ] https://github.com/camunda/camunda/issues/23973
- [ ] https://github.com/camunda/camunda-platform-helm/issues/2610
```

**Comment by Zelldon** [comment]
FOR 8.7 We decided to have no common config, but make use of Helm charts to abstract this away and have a "global" prefix. 

https://docs.google.com/document/d/1w1VzwyvvBzu0vnjCUj4UcLxTCVae8iMXAMA5_m6xs1s/edit?tab=t.0#bookmark=id.atzhmlt05x26

**Comment by ChrisKujawa** [comment]
Last task is about SM enabling global optional prefix. This is already provided https://github.com/camunda/camunda-platform-helm/pull/2643, so closing this
