### ISSUE TITLE
Implement tasklist data migration

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#23814]
Goal:
When updating from 8.6 to 8.7 data from existing `tasklist-process` index must be migrated to `operate-process` index. This is done by a migration app which is a separate application that will be deployed along with the core C8 components. Currently, there is already a migration app for identity `io.camunda.identity.migration.MigrationRunner`. Our goal is to add the tasklist migration logic to the same app, so that we have only one migration app. 

- [ ] Move migration app out of identity to a common module
- [ ] Allow MigrationRunner to run identity and tasklist data migration in parallel. 
    * Tasklist migration could be just a no-op at this point
    * MigrationRunner should run for ever until the application is stopped
- [ ] Add tasklist data migration logic
    * Support ElasticSearch
    * Migration of on process from `tasklist-process` is as follows
        * Migrate
            * tasklist-process.formId -> operate-process.formId
            * Set operate-process.isPublic from the process definition XML (see [ref](https://docs.google.com/document/d/1Y12848yrn3lcSFjHrgIFuhMJXrZxRxbR-Oec43uchoA/edit#bookmark=id.hqotxwa4weo))
        * Delete the process from `tasklist-process`
            * This is done so that if the migration app is restarted, it doesn't migrate already migrated processes again. 
- [ ] Allow configuring the source and target index names/prefix
        * This should be configurable because the users might have configured index prefix in the existing deployments. 
- [ ] Support OpenSearch
- [ ] Add tests 
    - [ ]  verify that existing data is migrated
    - [ ]  verify that newly imported data is also migrated

**Comment by panagiotisgts** [comment]
> Migration of on process from tasklist-process is as follows
Migrate
tasklist-process.formKey -> operate-process.formKey

Is changed to `tasklist-process.formId` -> `operate-process.formId` after discussion with @marcosgvieira  and the REST API team ([ref](https://camunda.slack.com/archives/C06UKS51QV9/p1729598526012179))

**Comment by Zelldon** [comment]
For transparency:

Discussed with @panagiotisgts and @sdorokhova the migration logic

* We decided against deleting user data. 
  * User can decide to delete index after successful migration
  * Allows to restore data, when something goes wrong
* We will keep track of the migration in the `operate-migration-repository` index. 
  * We will use as ID the `8.7.0` version, as no migration is planned for Operate
  * We should make sure to remove the migration repository from the Operate code base, as otherwise, we might run into conflicts (mistakenly detecting that there is a migration planned)
    * Should be possible to already delete the code
* Migration app will run parallel to the importer
  * Importer communicates via import-position that it is done #23913 
  * Side note: SchemaManager is still needed for 8.7 in Importer - so we can update the import-position schema!!! We can't remove it from the code base yet, but make it limited to only this index for example.

**Comment by ChrisKujawa** [comment]
The migration application has been implemented by @panagiotisgts
