### ISSUE TITLE
Remove the need for Optimize monitor and manage_index_templates privileges

### ISSUE THREAD

**Issue by RomanJRW** [camunda/camunda#23866]
Engineering DRI: @KarpovIvan 

### Context

Currently, it is known that Optimize requires [cluster level Elasticsearch privileges](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html). The same is true for OpenSearch. The reason for this includes, but is not necessarily limited to:
- Checking the status of tasks during upgrades
- Checking cluster health during start up
- Creating templated indices

We would like to provide the option for users to run Optimize without granting it the `monitor` privilege or `manage_index_templates` privilege. At a minimum, this will include providing the option for users to skip the cluster health check as part of the application health check (like Operate did [here](https://github.com/camunda/camunda/issues/22918)). If we identify other areas requiring this privilege, we should consider similar work arounds. We would also like Optimize to be able to run without the `manage_index_templates`, assuming that the indices are managed externally.

### Notes

- Templated index creation is necessary for the external variable feature. For this customer, we can simply tell them that this feature will not be available. It can be omitted from the scope of this issue
- The expectation is that an external script will be used for Optimize upgrades, so that can be ignored in the scope of this work.
- This feature should not be documented publicly, as it largely corresponds to the requirements of a single customer with a specific use case

### Acceptance Criteria

- Optimize can run with a user without `monitor` elasticsearch cluster privileges when the schema has been initialized elsewhere
- Optimize can run with a user without `manage_index_templates` elasticsearch cluster privileges when the schema has been initialized else where

### Testing Notes

Optimize can be started and run without it being granted the `monitor` privilege

### Links

[Operate issue](https://github.com/camunda/camunda/issues/22918)
[Slack thread](https://camunda.slack.com/archives/C55U06YRG/p1727998857494419)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24205
- [ ] https://github.com/camunda/camunda/pull/24492
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by KarpovIvan** [comment]
After discussion with @RomanJRW we summarize that project does not need solution for opensearch part, thats why we will go with implementation of solution for elasticsearch.

**Comment by KarpovIvan** [comment]
## How Test for QA
1. Run ES with security enable (xpack.security.enabled=true)
2. Auth with super user: elastic password provide by env ELASTIC_PASSWORD
3. Create Role without priveligions 'monitor' and 'manage_index_templates'.
POST http://localhost:9200/_security/role/my_test_role_7
```
{
    "cluster": [
        "cancel_task",
        "create_snapshot",
        "cross_cluster_replication",
        "cross_cluster_search",
        "grant_api_key",
        "read_ccr",
        "read_ilm",
        "read_pipeline",
        "read_slm",
        "read_security",
        "transport_client"
    ],
    "indices": [{
                "names": [
                    "*"
                ],
                "privileges": [
                    "maintenance",
                    "read",
                    "write",
                    "view_index_metadata"
                ],
                "allow_restricted_indices": false
            }],
    "applications": []
}
```
Create user with this role
http://localhost:9200/_security/user/test_77
```
{
  "password" : "test_test",
  "roles" : [ "my_test_role_7" ],
  "full_name" : "Jack Nicholson",
  "email" : "jacknich@example.com",
  "metadata" : {
    "intelligence" : 7
  }
}
```
5. First optimize run with super user elastic:ELASTIC_PASSWORD for init schema
6. Re run optimize with 
CAMUNDA_OPTIMIZE_ELASTICSEARCH_CLUSTER_TASK_CHECKING_ENABLED=false
CAMUNDA_OPTIMIZE_ELASTICSEARCH_INIT_SCHEMA_ENABLED=false
with user test_77 password test_test
7. Check that all good

**Comment by RomanJRW** [comment]
To give an update on progress here:

- Optimize requires the `manage_index_templates` privilege to create indices when using the external variables API feature, or when initializing schema
- Optimize requires the `monitor` privilege to check the status of cluster tasks during various async operations, as well as during upgrade

We are proceeding with the following plan based on the concept of schema initialization and upgrades being performed externally to Optimize:
- We are only considered Elasticsearch in scope, nothing is being changed for OpenSearch
- We will add a config option that allow schema initialization. When disabled (it is enabled by default), Optimize will not attempt to initialize schema.
- We will add a config option that allows checking the status of cluster tasks. When disabled (it is enabled by default), Optimize will not attempt to check cluster tasks. Some operations might take longer or Optimize may consume more memory in this case. The impact is expected to be minimal
- Upgrades will not be allowed on ES if either of these options are disabled
- We plan to backport this to the 8.6 stable branch to allow a patch release to contain this change
- We will not document this publicly, for consistency with Operate/Tasklist

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT


Optimize can run with a user without monitor elasticsearch cluster privileges when the schema has been initialized elsewhere ✅ 
Optimize can run with a user without manage_index_templates elasticsearch cluster privileges when the schema has been initialized else where ✅ 


<img width="1352" alt="image" src="https://github.com/user-attachments/assets/e729c620-35a0-437f-9d16-cf1448401623">

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/fcbaced0-de59-48bc-a0b9-18e80d071633">

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/80bb5435-728e-4637-9128-8ce6d9c272e4">

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/189089c0-025a-4113-bb62-af6b6c551819">

<img width="1698" alt="image" src="https://github.com/user-attachments/assets/4c5f243f-fc74-4709-9ca4-55e239ae8404">
