### ISSUE TITLE
Camunda exporter handler tests

### ISSUE THREAD

**Issue by EuroLew** [camunda/camunda#23888]
**Description**

Handlers in the camunda exporter supports a number of records, ensure that when records are exported, corresponding entities are written to the correct index.

```[tasklist]
### Tasks
- [x] IT for UserHandler
- [x] IT for AuthorizationHandler
- [x] IT for DecisionHandler
- [x] IT for ListViewProcessInstanceFromProcessInstanceHandler
- [x] IT for ListViewFlowNodeFromIncidentHandler
- [x] IT for ListViewFlowNodeFromJobHandler
- [x] IT for ListViewFlowNodeFromProcessInstanceHandler
- [x] IT for ListViewVariableFromVariableHandler
- [x] IT for VariableHandler
- [x] IT for DecisionRequirementsHandler
- [x] IT for PostImporterQueueFromIncidentHandler
- [x] IT for FlowNodeInstanceIncidentHandler
- [x] IT for FlowNodeInstanceProcessInstanceHandler
- [x] IT for IncidentHandler
- [x] IT for SequenceFlowHandler
- [x] IT for DecisionEvaluationHandler
- [x] IT for ProcessHandler
- [x] IT for MetricFromProcessInstanceHandler
- [x] IT for FormHandler
- [x] IT for EventFromIncidentHandler
- [x] IT from EventFromJobHandler
- [x] IT from EventFromProcessInstanceHandler
- [x] IT from EventFromProcessMessageSubscriptionHandler
```
