### ISSUE TITLE
Prepare Importer to run concurrent with Exporter

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#23915]
## Description

By introducing the Camunda Exporter we will replace the previously deployed Importer applications.

The applications still need to run for a bit, to import left-over data from Zeebe indices before they can turned off.

Importers shouldn't accidentally overwrite data that has been written from Exporter and vice-versa.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/22897
- [ ] https://github.com/camunda/camunda/issues/20191
- [ ] https://github.com/camunda/camunda/issues/22899
- [ ] https://github.com/camunda/camunda/issues/19388
- [x] Concurrency mode for Tasklist? Needs to be defined/decided https://docs.google.com/document/d/1_ptXAzDuoyEGMvVSZCXRGTVFQN6rNyifwXGj9k8RnFw/edit?tab=t.0#heading=h.dwqteb8vomp9
- [x] Disable Schema creation of Tasklist - here we might need to check with progress on V1 to V2 migration for Tasklist
```

**Comment by Zelldon** [comment]
We decided agains this and will run Importing/Exporter in sequence https://github.com/camunda/camunda/issues/24440
