### ISSUE TITLE
[EPIC] User Task Listeners in Operate

### ISSUE THREAD

**Issue by vitorwtavares** [camunda/camunda#23938]
### Description

This is the technical breakdown epic for User Task Listeners on Operate. 
- [PDP Issue](https://github.com/camunda/product-hub/issues/1821)
- [Figma design](https://www.figma.com/proto/zfOVIMNthZneqFiyUhWTP2/Listeners?page-id=925%3A34385&node-id=856-29596&node-type=frame&viewport=-986%2C-1810%2C0.08&t=MXwMMnjHSWn6Jqq6-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=856%3A29596)

Note this is being worked as one with the Zeebe team and the corresponding epics might still be merged.

#### Backend

- [ ] #23728 (will be worked using the same issue and branch between BE and FE)
- [ ] #23383 (bugfix for Execution Listeners that will be worked as part of this epic)
- [ ] #23942
- [ ] #23944
- [ ] #23945
- [ ] #23946

#### Frontend

- [ ] #23728 (will be worked using the same issue and branch between BE and FE)
- [ ] #23941
- [ ] #23943

### Additional Information

- Issue: https://github.com/camunda/product-hub/issues/1821
- Root epic: https://github.com/camunda/product-hub/issues/1316
- Relates to: https://github.com/camunda/product-hub/issues/1822

### Definition of Ready - Checklist

- [x] The epic is broken down into backend and frontend tasks/features - if applicable
- [x] It is clear what will be delivered in each increment/alpha release
- [ ] Edge cases and limitations are clear
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [x] Cross-team dependencies have been considered

### Acceptance Criteria

- [ ] All the TODO issues are done
