### ISSUE TITLE
Recreate Integration Tests previously running on C7

### ISSUE THREAD

**Issue by PHWaechtler** [camunda/camunda#23965]
### Context

With [OPT#22461](https://github.com/camunda/camunda-optimize/issues/14105) , we removed all IT that were running in C7 mode. To ensure sufficient test coverage we will need to recreate all those IT relevant to C8 as well.
The [removal PR](https://github.com/camunda/camunda/pull/23182/files#) can be used as a guideline to get an overview of what needs recreated.

### Acceptance Criteria

Removed C7 IT are recreated in C8 and ran in Optimize 8 CI.

### Breakdown
The following test groups have to be recreated:

```[tasklist]
### Sub tasks per IT grouping
- [ ] Rest IT
- [ ] Public API IT
- [ ] Service IT
- [ ] Report Evaluation IT
- [ ] Report Filter IT
- [ ] Branch analysis IT
- [ ] Outlier analysis IT
- [ ] Retrieval and conflict logic IT
- [ ] Variable IT
- [ ] Entity import and export IT
- [ ] Identity caching IT
- [ ] CSV export IT
- [ ] Data ingestion IT
- [ ] Import permutation IT
- [ ] Metadata IT
- [ ] Mixpanel IT
- [ ] Onboarding scheduling IT
- [ ] Process overview and owner IT
- [ ] Process digest IT
- [ ] Process KPI IT
- [ ] Index rollover IT
- [ ] Authentication and security IT
- [ ] Authorization IT
- [ ] Collection IT
- [ ] Sharing IT
```

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by PHWaechtler** [comment]
Closing as this is a duplicate - had already created the same in the c7 repo a while ago
