### ISSUE TITLE
Verify/Test Camunda Exporter MVP

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#23977]
## Description

![it1-mvp](https://github.com/user-attachments/assets/07eb5111-f5e2-44b7-9ec3-e190e92a5f02)

Iteration 1 - MVP of the Camunda Exporter comes to an end. MVP was targeting green field installations, containing the basic functionality (first breakthrough). This means it provides the Camunda Exporter with ported business logic from Tasklist and Operate Importer.

We should verify that it is providing basic functionality, without an Importer. It must not support all features fully yet, but it should generally work and can be seen as a breakthrough.

This means (basic checks):

 * Schemas are created
 * Data is aggregated and exported by new Exporter
 * Data should become visible to the Operate and Tasklist UI

```[tasklist]
### Tasks
- [x] Run Exporter in SM without Importer
- [x] Run Exporter in SaaS without Importer
- [x] Benchmark Exporter - without Importer
- [x] [Pair with QA on the Exporter changes](https://camunda.slack.com/archives/C063D123AMD/p1729512909916419?thread_ts=1729511188.093209&cid=C063D123AMD)
```

**Comment by Zelldon** [comment]
![operate-metrics-2](https://github.com/user-attachments/assets/ae4d0aea-508d-486f-80b1-dfac70007868)
![operate-metrics-compare](https://github.com/user-attachments/assets/be0c2f8a-ece8-4ad1-9ab0-30856ea9bd5e)
![es-indices](https://github.com/user-attachments/assets/c2f1dd65-f3eb-4900-b4bf-691e2921f6c1)
![es-documents](https://github.com/user-attachments/assets/ccb1f64c-35c4-438f-a910-bdab130734a0)
![es-system-compare](https://github.com/user-attachments/assets/da48bd1b-464f-43fb-bdff-64df40abeaab)
![es-cluster-act-compare](https://github.com/user-attachments/assets/b024580c-4d4b-4528-9b62-c4a1c424a7f2)
![cam-ex-flus](https://github.com/user-attachments/assets/176a7979-52bc-4e3e-b5c5-01cb31d06de8)
![cam-ex-compare](https://github.com/user-attachments/assets/a85b12a2-c184-4734-a161-229ea779477a)
![es-disk](https://github.com/user-attachments/assets/b64be83f-0474-44b7-84c6-f3f5b01ee521)
![ex-exporter-compare](https://github.com/user-attachments/assets/3ebca5fe-8963-4f46-be57-a6982b76d089)
![record-process-duration-comparison](https://github.com/user-attachments/assets/c0fa0d16-d32d-411e-a7e2-26b79753d7fd)
![latency-comparison](https://github.com/user-attachments/assets/664396f0-27cf-481a-acd3-00a7a6a33e2e)
![memory-comparison](https://github.com/user-attachments/assets/82c7cbbf-2676-46ed-9f27-5d2620faab07)
![cpu-comparison](https://github.com/user-attachments/assets/719a4606-3fdb-4682-834c-fb0dfa02f3a4)


# Benchmark
With https://zeebe-io.github.io/zeebe-chaos/2024/10/24/Camunda-Exporter-MVP/ I have set up a benchmark for the MVP and a base benchmark running without exporter (and importer enabled), to better compare the differences. 

I have run them over the weekend (~4 days now). In the following I will shortly try to describe the observations and compare them. On the left we always see metrics from the base and on the right always from the MVP benchmark.

## General

 In general, we can't see much of a difference. The benchmarks seem to perform quite similarly. 
![general-comparison](https://github.com/user-attachments/assets/7a9b4dfe-4d65-4436-8e38-38671341393d)

## Snapshot Issue

We can see that both benchmarks have a state issue, as reported by [others](https://camunda.slack.com/archives/C037RS2JHB8/p1730111585816089) already. It looks like jobs are created more then completed, causing leftovers in the state.

![snapshot-issue-benchmark](https://github.com/user-attachments/assets/471cc1d0-dda8-4c9b-93b0-44774a9afd21)

## Processing

**Comment by Zelldon** [comment]
Closing this as we did everything planned for the MVP verification. I plan to set up a regular benchmark, as part of the weekly benchmarks
