### ISSUE TITLE
Align Rdbms readers, writers and tests

### ISSUE THREAD

**Issue by stoerti** [camunda/camunda#24002]
After integrating the first searches for business entities in the RDBMS some refactorings should be done:

- [ ] sort test should not influence each other. Currently the sort tests have no filter and find *all* data. Leads to NPE sometimes
- [ ] create new Module rdbms-test containing fixtures for RDBMS entities [#27495](https://github.com/camunda/camunda/pull/27490)
- [ ] align using same fixtures in all tests (also in UnitTests in db/rdbms) [#27495](https://github.com/camunda/camunda/pull/27490)
- [x] align varchar column sizes [#27492](https://github.com/camunda/camunda/pull/27492)
- [x] move processInstance ITests into separate package
- [x] align integration tests between all entities. Rethink what to test just with H2 and what with all DBs. More tests for Operator-Filters?
- [x] check if generalisations and abstractions can be used between the search implementations ❓ 
- [x] move common utilities between both exporters to common module ❓
