### ISSUE TITLE
Create an `ExporterHandler` for each `OperationHandler` record type that marks the respective operation as complete

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#24029]
### Description

Some of the user operations must be marked as completed when the corresponding records are being exported. We can use `operationReference` from the record to correlate it with operation id.

Completion of operation by id means update of OperationEntity by id and setting following fields:
```
state = OperationState.COMPLETED
lockOwner = null
lockExpirationTime = null
completedDate = current timestamp
```

### TODO

- [x] Implement `OperationFromProcessInstanceHandler` to complete operations when `BpmnElementType=PROCESS` and intent is one of `[ELEMENT_MIGRATED, ELEMENT_TERMINATED]`. This will cover Migrate process instance and Cancel process instance operation
- [x] Implement `OperationFromVariableDocumentHandler` to complete operation on `UPDATED` intent. This will cover Update variable operation.
- [x] Implement `OperationFromIncidentHandler` to complete operation on `RESOLVED` intent. This will cover Resolve incident operation.
- [x] cleanup other export handlers which have operation related commented code, e.g. [here](https://github.com/camunda/camunda/blob/be8c71199bba138d3493543c7835f0e2c93da55a/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/ListViewProcessInstanceFromProcessInstanceHandler.java#L235)
