### ISSUE TITLE
When exporting the incident populate the tree path fields

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24061]
### Description

Within #16915 we started receiving in exported Zeebe records 3 new fields, that describe position of the incident and corresponding process and flow node instances in two hierarchies: "inter tree path" when parent process has call activity and child process has an incident and "intra tree path" when process instance scope contain some nested scopes (subprocess, multi-tenancy) and incident is fired in the nested scope.
We need to work through these fields and convert them to `treePath` values for different Operate entities so that all related Operate features continue working.

### TODO

- [ ] fill in "inter" `treePath` in process instance in `list-view` index: #24037
- [ ] fill in "inter" `treePath` in `incident` entity: #24511
- [ ] fill in "intra" `treePath` in flow node instances in `list-view` and `flow-node-instance` indices #24527 

### Additional information

* Related Zeebe changes with description of the new incident fields: https://github.com/camunda/camunda/issues/16915 and https://github.com/camunda/camunda/pull/20293
* document with description of Operate fields: https://docs.google.com/document/d/1Nh8Jln5_aWIS1O5NnC-SGRblijizDTSujG7zIfc-GOY/edit

**Comment by sdorokhova** [comment]
> fill in "inter" treePath in incident entity
This part of the issue is blocked by #21567, as for the incident we need to know `flowNodeId` (or `elementId`) of the node where incident occurred, but we get some error code instead.
Mode data also here: https://camunda.slack.com/archives/CSQ2E3BT4/p1730127004045349

**Comment by Zelldon** [comment]
@sdorokhova can we close #21567 ? As we now correctly set the incident elementId (which is what we need right?)
