### ISSUE TITLE
[EPIC] Resolve XML-based attributes in the REST API

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#24077]
## Introduction

The REST API needs to provide attributes in certain entities that are based on BPMN XML data that isn't present in the data layer.
To provide these attributes, the REST API needs to resolve them from the related process definition data itself.

An example of such an attribute is the `taskName` of user tasks. This is based on the name of the related flow node in the BPMN XML that describes the resulting user task instances.

## Concept

* Iteration 1: The REST API will fetch the required data (e.g. resolved from BPMN XMLs or ES/OS indexes directly) related to the entity instances a query yields to resolve the missing attributes.
* Iteration 2: The REST API will cache the resolved data needed from those to reduce the number of queries to the data layer as this is immutable data (can only be deleted at some point).

## Task Breakdown

```[tasklist]
### Iteration 1
- [x] Extract `processDefinitionKey` set from query results
- [x] Query for process data for all keys from the database
- [x] Extract data for each user query item
- [ ] https://github.com/camunda/camunda/issues/24893
```

```[tasklist]
### Iteration 2
- [x] Create cache for process data
- [x] Query cache for process data before querying the database
- [x] Only fetch missing entries and cache them
- [ ] https://github.com/camunda/camunda/issues/24894
```

## Discussions and Decisions

* The decision to go in this direction is explained in https://github.com/camunda/camunda/issues/22812#issuecomment-2435051652
* For `taskName` data for user task queries
  * The `flowNodeName` is needed.
  * This exists in the BPMN XML **and** also in the `flowNodes` document of each item from the `*-process` index.
  * Potentially, querying for a list of composite keys (tuples of `processDefinitionKey` and `flowNodeId`) could yield a list of names directly from ES/OS. This needs to be checked though for feasibility with ES/OS.
* The process cache could potentially just be a nested map structure, with the root-level key being `processDefinitionKey`, pointing to a map of `flowNodeId` -> `flowNodeName`.

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2243

**Comment by tmetzke** [comment]
Moved https://github.com/camunda/camunda/issues/25691 out of this issue as it's a toil/refactoring follow-up.
