### ISSUE TITLE
Rework how `BatchOperationEntity#operationsFinishedCount` is updated

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24084]
### Description

Currently we increment batch operation `operationsFinishedCount` field with every completed operation.

There're 2 problems with this:
* increment is not idempotent and we have issues when some ES queries are retried and numbers go out of sync. Related bug issue: 
* when completing operations from exporter we can't update batch operation as we don't have batchOperationId and we can't query it

### Solution

We will have background task (similar to archiver or incident update task) running in Camunda exporter that will go through active batch operations and update `operationsFinishedCount` values. In case all single operations included in batch operation are completed, the task will also set `endDate` on batch operate (= moment of task execution). 

### TODO

We will use the same background task mechanism as used for [archiver and incident post importer](https://github.com/camunda/camunda/tree/e8c0b759e01bdda422ad9d95b7ea8163e73c821d/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/tasks):
- [x] create batch operation update background task (iplementation of `BackgroundTask` interface): https://github.com/camunda/camunda/pull/25742
- [x] use repository pattern to abstract all interaction with Elasticsearch/Opensearch: https://github.com/camunda/camunda/pull/25743 and https://github.com/camunda/camunda/pull/26613
- [x] implementation should be asynchronous to make thread usage as efficient as possible: https://github.com/camunda/camunda/pull/26603
- [x] think through error processing. If some internal call (e.g. to ES/OS) fails, we must make sure that error is properly logged and task is retried (explained [here](https://github.com/camunda/camunda/pull/26603#issuecomment-2575206515) and also tested manually)

Currently there are failing E2E tests related to this: https://github.com/camunda/camunda/pull/25800
- [ ] Revert [this PR](https://github.com/camunda/camunda/pull/25800) to unskip the tests: https://github.com/camunda/camunda/pull/26672

**Comment by ThorbenLindhauer** [comment]
Note that the current Operate implementation suffers from a race condition described in https://github.com/camunda/camunda/issues/24906 that can result in batches not completing (because we are not counting all finished single operations). The root cause is that when we see the effect of a single operation, we query for the corresponding batch operation (or rather the index that contains it). If this happens within the refresh interval of the index (so by default: 1 second after the batch operation is created), this fails and the completed operation is not recorded.

**Comment by ThorbenLindhauer** [comment]
Note number two: The current Operate implementation suffers from https://github.com/camunda/operate/issues/6790 that may count completed operations twice if a bulk request fails partially.

**Comment by ChrisKujawa** [comment]
* Opensearch is not yet implemented
* we need to rework/refactor to async

**Comment by sdorokhova** [comment]
Information for QA **(work in progress)**:
* #24906

**Comment by ArezooAzar** [comment]
> Hi [@ArezooAzar](https://github.com/ArezooAzar) , this issue is ready to be tested on `main` branch (SNAPSHOT docker image). It affects how batch operations are marked as completed. Basically regression test(s) that you have on the topic should work. And also the bug [#24906](https://github.com/camunda/camunda/issues/24906) must be fixed. Other bug that must be fixed, but nor clear how to test it: [#26516](https://github.com/camunda/camunda/issues/26516).

@sdorokhova : I tested it works as expected 
I updated [this test](https://camunda.testrail.com/index.php?/cases/view/3651) case and put it as a regression test.

**Comment by ChrisKujawa** [comment]
@sdorokhova can we close this issue?

**Comment by ChrisKujawa** [comment]
After discussing with @sdorokhova we will close this

To quote:
> Yes, let's close it. We still have some problems with E2E tests. I will still continue with that
