### ISSUE TITLE
[EPIC] Migrate Operate V1 internal API to V2 C8 API

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#24169]
## Introduction

Our out-of-the-box Operate application depends on internal Operate V1 REST APIs that aren't available in the C8 V2 REST API.
To move our application to V2, we need to support the functionality.

## Concept

There are two ways to achieve this (and the final proposal can be a mixture of both):
1. Add the internal Operate V1 REST API to the C8 V2 REST API.
2. Build a more general (or no additional) API in the C8 V2 REST API and implement the required additional logic in the client application.

## Task Breakdown

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/21724
- [ ] https://github.com/camunda/camunda/issues/21720
- [ ] https://github.com/camunda/camunda/issues/21716
- [ ] https://github.com/camunda/camunda/issues/21717
- [ ] https://github.com/camunda/camunda/issues/21719
- [ ] https://github.com/camunda/camunda/issues/21721
- [ ] https://github.com/camunda/camunda/issues/20663
- [ ] https://github.com/camunda/camunda/issues/24148
- [ ] https://github.com/camunda/camunda/issues/22850
``` 

## Links

- Product Hub (internal): https://github.com/camunda/product-hub/issues/2243
