### ISSUE TITLE
Task Listener for `assign` operation (expansion)

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#24197]
In the same way that users want to respond to, correct, or even reject the user task `complete` operation in the form of a task listener, they'll also want a task listener for `assign` operations.

When `ASSIGNING` a user task, a job of `TASK_LISTENER` kind must be created. The job must have the assigning `assignee` available. **Should the job also have the currently assigned `assignee` available?**

The user task can be assigned both on creation ([by specifying the `assignee` property](https://docs.camunda.io/docs/next/components/modeler/bpmn/user-tasks/#assignments)) and while active (through the API [`POST /user-tasks/:userTaskKey/assignment`](https://docs.camunda.io/docs/next/apis-tools/camunda-api-rest/specifications/assign-user-task/), [`DELETE /user-tasks/:userTaskKey/assignment`](https://docs.camunda.io/docs/next/apis-tools/camunda-api-rest/specifications/unassign-user-task/), and through [Tasklist's UI](https://docs.camunda.io/docs/next/components/tasklist/userguide/managing-tasks/#assign-tasks)). Both the creation with `assignee` and the `assign` operation should trigger the `assignment` task listener.

**Approved or denied**
The task listener job can be completed to mark the user task as `ASSIGNED`. This updates the user task's `assignee` and moves the user task's lifecycle state to `CREATED` (note that there is no `ASSIGNED` lifecycle state).

**Corrections**
If the job is [completed with a correction](https://github.com/camunda/camunda/issues/23708) of the `assignee`, then this assignee must be persisted for the user task in the `ASSIGNED` event. The same goes for other corrections.

**Incidents**
If the job is failed and has no retries left, an incident must be raised that can be resolved when the job has retries again.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/24233
- [ ] https://github.com/camunda/camunda/issues/24235
- [x] (possibly) Don't set `assignee` in the `CREATED` event and don't provide it to task listener job
- [x] Test that we can resolve incidents for the `assignment` listener job
- [ ] (out of scope for 8.7) Provide the currently set and the assigning `assignee` to the task listener
```

**Comment by korthout** [comment]
I've moved the following issue out as delivered and moved this issue to the next iteration.
- #24232

**Comment by ce-dmelnych** [comment]
All subtask were implemented
