### ISSUE TITLE
Support a basic `assignment` task listener

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#24232]
```[tasklist]
### Tasks
- [ ] Move appending the `ASSIGNED` event to `onFinalizeCommand` for `UserTaskAssignProcessor`
- [ ] Allow multiple assignment listeners, i.e. Track assignment task listener index
- [ ] Store user task intermediate state on `ASSIGNING` event
- [ ] Cleanup user task intermediate state on `ASSIGNED` event
- [ ] Favor the user task intermediate state in the task listeners and finalizeCommand
- [ ] Testing
```
