### ISSUE TITLE
Optimize is part of the Single Application

### ISSUE THREAD

**Issue by buccarel** [camunda/camunda#24277]
### Context

Currently, Optimize can be launched used its own Main class, which does not use the common framework used by the other applications of the stack. The objective of this task is to make Optimize use such common infrastructure, as well as to make Optimize launchable with profiles, similarly to what the other applications are doing.

### Acceptance Criteria

- [ ] Is it possible to launch Optimize using the Single Application profiles (standalone or with the rest of the stack)
  - [ ] Object Mapper does not conflict other existing mappers (can be prefixed)
- [ ] Remove the hack in OptimizeIndexNameService#getShortIndexPrefix that returns CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX if set

### Links

* Part of https://github.com/camunda/product-hub/issues/2289

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
