### ISSUE TITLE
Add carbon breadcrumbs to reports/dashboards

### ISSUE THREAD

**Issue by OmranAbazid** [camunda/camunda#24275]
Engineering DRI: @OmranAbazid

### Context

See https://github.com/camunda/camunda-optimize/issues/6864

### Acceptance Criteria

For reports, there is a breadcrumb to back to, 
- collections home page
- Parent collection
- Parent dashboard

For dashboards, there is a breadcrumb to back to, 
- collections home page
- Parent collection

For instant dashboards and adoption dashboard reports, there is a breadcrumb to back to dashboards page 

### Testing Notes
- The description above should be sufficient

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24276
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
