### ISSUE TITLE
Migrate post-importer to archiver

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#24297]
# Description

The goal is to migrate the existing post-importer as a new background task to be executed inside the exporter, e.g. alongside the archiver jobs.

The post importer task should reschedule itself like the archiver jobs. For the first iteration, we can keep the hard coded delay between runs (3s), instead of making it configurable (like with the archiver task), as this is the current state of the post-importer.

To do this, we will refactor the existing archiver such that it becomes a `BackgroundTaskManager`, and the `ReschedulingTask` to accept more generic tasks. Every background task will now return as result how much work items they did, and pass to the rescheduling task what is the minimum expected amount of work to know whether or not to increase the backoff delay. For the post importer, we will keep this as 1, so we keep the same behavior as before.

```[tasklist]
### First iteration
- [ ] https://github.com/camunda/camunda/pull/24921
- [ ] https://github.com/camunda/camunda/pull/24922
- [ ] https://github.com/camunda/camunda/issues/24929
- [ ] https://github.com/camunda/camunda/pull/25067
- [ ] https://github.com/camunda/camunda/issues/24930
- [ ] https://github.com/camunda/camunda/issues/24931
- [ ] https://github.com/camunda/camunda/issues/24990
```

**Comment by Zelldon** [comment]
@npepinpe should we remove this issue from https://github.com/camunda/camunda/issues/23721 and make it a separate epci? So we can close the other one already

**Comment by npepinpe** [comment]
Yes, I will do that monday, had meetings all day. We still will not close this unt we have tests though (imo)

**Comment by npepinpe** [comment]
Moved for posterity, previous description:

```
- It fetches all new incident updates that have been imported, but not yet processed by the post-importer (up to a maximum) (see `Fetching the incident updates`)
- With the results, it then searches for the related process instances (see `Searching for related process instances`)
- Then it updates the related instances, as well as anything on the tree path, in order to mark incidents as created or resolved. (see `Updating related process instances`).

As you can see, this is quite coupled with the importing process. So there's a couple things we need to do:

1. We need to update the complete tree path for related process instances when an incident is created.
2. We need to update the complete tree path for related process instances when an incident is resolved.

At the moment, the exporter is not handling RESOLVED records, only creation. And since we don't have an importer or post-importer queue anymore, we need a new way to track what we've processed, and what we haven't, in order to avoid doing too much work.

There is also a risk (to be verified) that updating the list view index to flag/unflag incidents along the tree path in a background task could cause concurrency issues, as we are mutating the documents from different sources. Considering this was previously also the case, I'm assuming this is not a problem - but we should verify this.

## Current post-importer logic details

Here's a rundown of what I understood the current post-importer does, purely from reading the code.

### Fetching the incident updates
- Fetches the last post-importer position for incidents from the `import-position` index.
- It then fetches pending incidents - this is a search query over the `post-importer-queue` index, filtering by partition ID (and if you're on partition 1, you also look for...partition 0?), with the action type `INCIDENT`, and where the position is greater than the last post-importer position (what? how can this be?).
- The results are sorted by position, and then collected in a map, where the key is the incident key, and the value is the intent (with RESOLVED overriding any other intents for the same key).
- We then search for all incidents by filtering over the ID with the incident keys in the incident index (runtime only).
- We warn about keys which did not match imported incidents (since importing is asynchronous).

### Searching for related process instances

### Updating related process instances
```

**Comment by npepinpe** [comment]
Here's a more accurate description, with some questions answered by the Operate team:


- Fetch next batch based on position
- Fetch incidents based on these updates
  - This can fail if index is behind.
- Some incidents may not have a tree path yet; make sure to collect them.
  - This is not true in 8.7 anymore, but is still true for records imported from 8.6.
  - As there is no migration application, we must still handle this case.
  - If there is no tree path, then fetch the associated process instances for their tree path, and build it.
    - This can fail, again for same reasons.
    - If the `ignoreMissingData` flag is true, then we build a fake tree path based purely on the process instance key and flow node key given in the incident.
- Once all incidents have a tree path, collect all the FNIs and PIs part of these - their incident state may have to change.
  - To know if it has to change, we need to know if they are already affected by incidents. 
  - Since they can be in different indices, fetch the docs by ID and just save which index we'll have to save them in.
- Fetch all active incidents with a tree path containing any of the FNIs or PIs above.
  - Map every FNI to a set of active incidents by ID.
  - Map every PI to a set of active incidents by ID.
- Go through the incident updates:
  - For every PI in the incident tree path, add or remove the incident from the map of PI -> active incidents.
  - For every FNI in the incident tree path, add or remove the incident from the map of FNI -> active incidents.
  - Add to the bulk update the new incident state.
- For every PI:
  - If there is at least one incident remaining, and the PI was not already marked as having an incident, add it to the bulk update and mark it as with an incident.
  - If there are no more incidents, and the PI was marked as having an incident, then add it to the bulk update and remove the incident mark.
  - Make sure routing is set.
- For every FNI:
  - If there is at least one incident remaining, and the FNI was not already marked as having an incident, add it to the bulk update and mark it as with an incident.
  - If there are no more incidents, and the FNI was marked as having an incident, then add it to the bulk update and remove the incident mark.
- Execute the bulk update, wait for refresh.

**Comment by npepinpe** [comment]
Second iteration has been moved here: https://github.com/camunda/camunda/issues/24328
E2E/IT tests have been moved here: https://github.com/camunda/camunda/issues/25595

Once we've removed the old code, we can close this.
