### ISSUE TITLE
[EPIC]: Remove 8.7 importing

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#24441]
### Description 

We want to get rid of the 8.7 importing, as part of moving the data aggregation to the Camunda Exporter completely.

### This means:

 - Camunda Exporter will take care of 8.7 data
 - Importers will take care of importing the rest of the data from 8.6, which means we will keep 8.6 Importers

This is for multiple reasons necessary:

 * indices about authentication will only be supported by Camunda Exporter - soon BE's should be migrated to
 * Tasklist V1 will make use of harmonized indices - only available via Camunda Exporter

For context https://camunda.slack.com/archives/C06F0GLJNFM/p1730886411155929

### Pre-requisite:

 * Current IT relies on Importer
 * Integration tests need to be adjusted to make use of Camunda Exporter

 
```[tasklist]
### Tasks
- [x] Delete tests that verify specific logic of importing/exporting a record - Should be part of Exporter IT
- [ ] https://github.com/camunda/camunda/issues/24822
- [x] Delete tests that verify specific logic of importing/exporting a record - e.g data is trimmed on importing
- [x] Adjust/refactor tests that verify query/search API (we want to keep v1 APIs for now in tact) - make use of the exporter - https://github.com/camunda/camunda/pull/25188
- [x] Remove 8.7 importers https://github.com/camunda/camunda/pull/25259
- [ ] https://github.com/camunda/camunda/issues/23044
- [ ] https://github.com/camunda/camunda/pull/24620
- [ ] https://github.com/camunda/camunda/issues/25245
- [ ] https://github.com/camunda/camunda/pull/25188
- [x] Migrate Tasklist E2E to Camunda Exporter - after we fixed the user task search
- [ ] https://github.com/camunda/camunda/issues/23045
- [ ] https://github.com/camunda/camunda/issues/25798
- [x] Remove Takslist 8.7 Importer - after IT and E2E are migrated
- [ ] https://github.com/camunda/camunda/pull/26325
```

**Comment by ChrisKujawa** [comment]
Moved https://github.com/camunda/camunda/issues/22897 out of the epic, as we will keep it for the alpha3, and will remove it in January (or make one SchemaManager to resolve race conditions with REST API, need to be defined)

Context https://camunda.slack.com/archives/C06F0GLJNFM/p1733989369486779

**Comment by ChrisKujawa** [comment]
Everything done!
