### ISSUE TITLE
[EPIC]: Sequentialize Exporting with Importing

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#24440]
## Description

Based on the decision we made [here](https://camunda.slack.com/archives/C05QBRGMA9F/p1730902505772459?thread_ts=1730285918.203039&cid=C05QBRGMA9F).

> ### To recap:
> 
> - We have some challenges in running Importer and Exporter running together from the start.
> - As data can get corrupted (user tasks might be stuck in creation, containing old data, an assignment can be wrong, etc)
> - We need to either avoid corruption or make it possible to resolve corruption
> - Resolving corruption can’t be done in all cases
> - Avoiding corruption
>   - Was done partly in Operate already - but not fully
>   - We used a position check in the importer to verify whether we are able/allowed to update the document (involved extra queries, made it slower)
>   - Tasklist hadn’t yet a concept - it would involve work on Importer sides, extra patch releases, etc.
> 
> ### Decided solution:
> 
> - We will make the importing and exporting sequential
>   - Importing will happen for old data (8.6 records)
>   - Exporting will happen for new data (8.7 records)
>   - Exporting will be blocked until importing is done
> - We need to clearly communicate this in our update guides (especially regarding backlogs)
>   - We should highlight what to do when experiencing backlog, and how they could be overcome
> 
> ### Consequences (including accepted risks): 
> 
> - We will avoid any data corruption/conflicts, with our planned solution. We will reduce the risk of data corruption to zero
> - The effort of implementing has been reduced and is manageable in our project
> - We do not need extra patch releases to be rolled out and where users might need to update first
> - We make the user accountable for their backlog - they need to make sure that their exporting/importing backlog is reasonably low (not hours/days) before updating
> - We expect this to be a reasonable trade as users should be interested in as well that Tasklist nor Operate is lagging behind by too far.
>   - To overcome such backlogs they are able to properly configure their deployments (fex giving more resources to ES, etc.) or do such updates at a time when the load is small
>   - If there exists a huge backlog (during an update) this will cause as a consequence to grow the backlog (which already exists before) and might at some point affect general performance as exporting is blocked (involving backpressure, OOD, etc.). We accept this as we see the platform as a whole and expect that the system should be set up/configured properly so no (or only small) backlogs exist, otherwise part of the Platform was already not properly configured and usable.
> 

Next steps:

- We will fix the ES exporter to write into the right versioned Zeebe indices
- We will implement in the importers that they can communicate that the importing is done for a certain partition/value type
- We will remove 8.7 importing
- We will make sure that Camunda Exporter only runs for 8.7 records
- Camunda Exporter will react to the status updates (communicated via ES index) and start when importing is done
- Document the general sequence, etc.
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/24316
- [ ] https://github.com/camunda/camunda/issues/23913
- [ ] https://github.com/camunda/camunda/issues/24441
- [ ] https://github.com/camunda/camunda/issues/24907
- [ ] https://github.com/camunda/camunda/issues/24908
- [ ] https://github.com/camunda/camunda/pull/25616
```

-----

**AT (version update):**

 * Importer is running - gets updated to 8.7 
   * is running only for 8.6 records
   * **updates import-position schema to include is done flag**
 * Camunda exporter is enabled in Brokers
   * Open - update / validate schema (nothing worth to mention?)
   * skips exporting of 8.6 - allows ES exporter to make progress
   * When encountering 8.7 checks import state `import-position` index
   * When doesn't exist or import-position indicates importing done 
      * store state in memory (meta data?)
   * Export 8.7 records
   * Importer marks via metrics done - can be turned off 
   * Further (not part of this issue, but worth to know):
     * Migration app - can finish as well
     * Both applications can be taken down
     * Unused indices can be dropped

**Comment by ChrisKujawa** [comment]
Importer - Exporter are sequenced and 8.7 importers have been removed!
