### ISSUE TITLE
[EPIC]: Backups Implementation - 8.7

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24456]
### Description

As part of 8.7 we have now a single-application and harmonized indices on ES/OS. As a consequence the backups need to be revisited as at the current state each component has its own backup implementation and take backups of their own indices.

This needs to change, so we are now going to take backups of all the webapps together (Tasklist, Operate, Optimize, Identity) for ES/OS - Zeebe still has their own implementation

Decision document: https://docs.google.com/document/d/1vLatb2aOgp75IQVpREfqq7fxkYtUi0x47tRH7j26cnw/edit?tab=t.0#heading=h.v6u7hjfs53fz

```[tasklist]
### Breakdown
- [ ] #24457
- [ ] https://github.com/camunda/camunda/issues/24462
- [ ] https://github.com/camunda-cloud/camunda-operator/issues/2590
- [ ] https://github.com/camunda/camunda/issues/24842
- [ ] https://github.com/camunda/camunda/issues/24843
- [ ] Chris: Avoid old indices to be backed up
- [ ] https://github.com/camunda/camunda/issues/24850
- [ ] https://github.com/camunda/camunda/issues/24869
- [ ] https://github.com/camunda/camunda/issues/25162
- [ ] https://github.com/camunda/camunda/issues/24465
- [ ] https://github.com/camunda/camunda/issues/25410
- [ ] https://github.com/camunda/camunda/issues/24467
- [ ] https://github.com/camunda/camunda/issues/24474
- [ ] https://github.com/camunda/camunda/issues/24475
- [ ] https://github.com/camunda/camunda/issues/24464
- [ ] https://github.com/camunda/camunda/issues/24476
- [ ] https://github.com/camunda/camunda/issues/24477
- [ ] https://github.com/camunda/camunda/issues/24479
- [ ] https://github.com/camunda/camunda/issues/24480
- [ ] https://github.com/camunda/camunda/issues/25186
- [ ] https://github.com/camunda/camunda/issues/25481
- [ ] https://github.com/camunda/camunda/issues/25597
- [ ] https://github.com/camunda/camunda/issues/25676
- [ ] https://github.com/camunda/camunda/issues/25769
- [ ] https://github.com/camunda/camunda/issues/25848
- [ ] https://github.com/camunda/camunda/issues/25984
- [ ] https://github.com/camunda/camunda/issues/26111
- [ ] https://github.com/camunda/camunda/issues/26120
- [ ] https://github.com/camunda/camunda/issues/26489
- [ ] https://github.com/camunda/camunda/issues/26618
- [ ] https://github.com/camunda/camunda/issues/26758
- [ ] https://github.com/camunda/camunda/issues/26825
- [ ] https://github.com/camunda/camunda/issues/26826
```
