### ISSUE TITLE
Update backups documentation

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24480]
Document the new backup structure for 8.7

### Acceptance Criteria
- [ ] Remove specific backups details from all components
   - [ ] https://docs.camunda.io/docs/8.5/self-managed/operational-guides/backup-restore/operate-tasklist-backup/
   - [ ] https://docs.camunda.io/docs/8.5/self-managed/operational-guides/backup-restore/optimize-backup/ (double check if Optimize will make to be part of single application [#prj-optimize-as-part-of-single-application](https://camunda.slack.com/archives/C07MMF3MRPA)
- [ ] Update backup guide: https://docs.camunda.io/docs/8.5/self-managed/operational-guides/backup-restore/backup-and-restore/
```[tasklist]
### Tasks
- [ ] Add a note in "8.7 Announcements" page
```

**Comment by entangled90** [comment]
Yes

**Comment by RomanJRW** [comment]
Closing, as per the above comment
