### ISSUE TITLE
[Doc Handling] AWS S3 document store implementation

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda#24541]
**Description**

As part of the Document Handling capability, we need to provide the Self-Managed Camunda 8 users with a way to store their documents in a custom S3 bucket.

The store must implement all operations:
- Create/get/delete documents
- Generate public signed URLs
- Verify document hash

**Breakdown**

1. Implement a new [DocumentStore](https://github.com/camunda/camunda/blob/main/document/api/src/main/java/io/camunda/document/api/DocumentStore.java) for AWS S3
* [ ] Test setup: Create a static test bucket for testing & development @chillleader 
  * [ ] Permissions: Write objects, read objects, create pre-signed URLs, delete objects. No access to bucket parameters or lifecycle
  * [ ] Lifecycle policies need to be set
* [ ] Align with the Controller team to ensure we create a bucket in each cluster - this [happens for GCP](https://github.com/camunda-cloud/camunda-operator/issues/3089) but we will need to do the same for S3
* [ ] Implement the document store operations
  * [ ] Create/read/delete documents, create link
  * [ ] Consider lifecycle policies: Objects must have a default TTL and a per-object TTL should be possible, most likely as combination of bucket lifecycle policies and custom metadata
  * [ ] Consider [hash verification](https://github.com/camunda/camunda/issues/24284) support: calculate hash on creation and store in metadata
  * [ ] Consider native approach: https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html
* [ ] Cover the implementation with unit tests
* [ ] Include the new document store into the Camunda distribution package so that it's available in the Zeebe gateway
* [ ] Test the configuration logic and make sure it is possible to configure the S3 document store with environment variables (related: https://github.com/camunda/camunda/issues/24508)
* [ ] Documentation: How can customers configure their buckets to work with Camunda? Mainly lifecycle policies & permissions
* [ ] Align with the Distro team regarding configuration of this feature in Helm charts. How will authentication work? Default credentials chain must be supported @chillleader 

See [GCP DocumentStore](https://github.com/camunda/camunda/blob/0c5092aad641ebb1431dacb3239512e324733484/document/store/src/main/java/io/camunda/document/store/gcp/GcpDocumentStore.java) for reference
2. Align with QA to test the new store implementation
3. Document the new feature in https://github.com/camunda/camunda-docs
