### ISSUE TITLE
Build foundational test suite for Optimize 8

### ISSUE THREAD

**Issue by RomanJRW** [camunda/camunda#24657]
### Context

In Optimize 7, the codebase had a large number of ITs that gave a high level of confidence during development of new or changing features. However, with the move to C8, these tests were never rewritten for Optimize 8. The reasons for this include:
- Optimize 8 could not perform data import from Zeebe in a performant way
- There was no easy way to mock the identity integration to handle Optimize authentication/authorization
- Not all functionality was supported in Optimize 8 (although that gap has closed over time)

Given that the Optimize importer is planned to be extracted, and that Identity changes are happening, we acknowledge that a rewrite of these tests is no longer possible and we need to revisit the testing structure in from scratch.

Therefore, we would like to in this issue:
- Remove all of the existing test infrastructure from Optimize 8 that is not used
- Delete all of the IT classes that are commented out or disabled
- Identity the most important parts of the codebase and create unit tests for these classes

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24875
- [ ] https://github.com/camunda/camunda/pull/25485
- [ ] https://github.com/camunda/camunda/pull/25484
- [ ] https://github.com/camunda/camunda/pull/25536
- [ ] https://github.com/camunda/camunda/pull/25608
- [ ] https://github.com/camunda/camunda/pull/25651
- [ ] https://github.com/camunda/camunda/pull/25755
- [ ] https://github.com/camunda/camunda/pull/25832
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RomanJRW** [comment]
@KarpovIvan is moving focus to another project, so we have agreed to shift focus away from this. We will close this as complete, while understanding that the endeavour for increased test coverage will continue as we make changes to the codebase
