### ISSUE TITLE
Replace usage of tree path in POST /api/flow-node-instances

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24667]
### Description

As of 8.7, the flow node intra tree path is no longer available by default (only when an incident is raised). This API endpoint needs to change because it must correctly return the children of a flow node instance in all cases, if there is an incident or not.

### TODO

- [ ] fill in flowScopeKey when exporting flow node instance
- [ ] Instead of the tree path, accept a flow scope key as parameter
- [ ] When processing the query
  - for 8.7 data: use `flowScoperKey` to build the response
  - for pre 8.7 data: use the `treePath` as a fallback
- [ ] In the result, return only the flow scope key instead of the tree path

**Comment by sdorokhova** [comment]
Pausing implementation for now, as we're considering returning tree path from Zeebe.

**Comment by sdorokhova** [comment]
This change is not needed any more, as we continue having full treePath for process instance entities.
