### ISSUE TITLE
[EPIC]: Add missing pieces to Camunda Exporter/Importer/Webapps in Iteration 3

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#24724]
## Description

Collection of smaller missing pieces we should still add to the Camunda Exporter as part [of the Iteration 3.](https://docs.google.com/document/d/1w1VzwyvvBzu0vnjCUj4UcLxTCVae8iMXAMA5_m6xs1s/edit?tab=t.0#bookmark=id.3on0wj9gqozq)

Related to https://github.com/camunda/product-hub/issues/2128

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/22997
- [ ] https://github.com/camunda/camunda/issues/22747
- [x] Add missing metrics for Camunda Exporter (from Importer) - moved
- [ ] https://github.com/camunda/camunda/issues/24729
- [ ] https://github.com/camunda/camunda/issues/24667
- [ ] https://github.com/camunda/camunda/issues/24731
- [x] ~Add scopeKey in Exporter to build treePath~ - We will not do as we implemented treePath in engine
- [ ] https://github.com/camunda/camunda/issues/23891
```

**Comment by ChrisKujawa** [comment]
Everything is done for this EPIC
