### ISSUE TITLE
Operate UI: Process instance breadcrumb links only to parent and root process instance

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24729]
### Description

Within Camunda exporter implementation we got rid of full inter `treePath` for process instances. As a result we can't return full `callHierarchy`  and `rootInstanceId` in `api/process-instances/{id}` internal API endpoint. 

The only data that we will still provide is `parentInstanceId` and the root process instance key (via #25233). The proposal is to show only direct parent in breadcrumb, e.g.:
`root process / ... / parent process / current process`.

### TODO

* decide on design (in collaboration with design and/or PM team)
* adjust frontend to not use `callHierarchy` from `api/process-instances/{id}` response
* (optionally) clean up endpoint fields

### Acceptance Criteria

- [ ] breadcrumb is shown in new format

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
