### ISSUE TITLE
Operate modification UI does not use intra `treePath` 

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24731]
### Description

Within Camunda exporter implementation we got rid of full inter `treePath` for process instances. As a result we can't return full `treePath` and `level` from `/api/flow-node-instances` internal API endpoint.

### TODO

- [ ] adjust Modification UI to avoid using `treePath` field (and `level` in case also used)
- [ ] (optionally) clean up endpoint DTO object

### Acceptance Criteria

- [ ] Modification UI continues working without regression with the new backend not returning `treePath` and `level` fields

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by sdorokhova** [comment]
Information from @pedesen :
"We split the treePath at / (so that we get all parent instance keys). Then we check for for each parent instance if there are is a pending, cancel or move modification."
_Theoretically is it possible to avoid using the field in this case? You probably already have all parent nodes in memory already?_
"In this case we should have it in memory yes. It's about showing a cancel icon which is only visible if the parent instances are (expanded/fetched). I assume we can avoid parsing the treepath then."
![image](https://github.com/user-attachments/assets/6aa6a5ed-e7f9-4a43-8b6f-aad4985847d2)
