### ISSUE TITLE
[EPIC] Camunda supports RPA script deployments

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#24763]
## Introduction

To make RPA a first class citizen of Camunda, RPA files should be deployed to Zeebe and linked from the process.  File endings should be `.rpa`. Version resolution should be done by Zeebe. RPA files should be part of Process Applications.

For this, we will annotate the RPA files with metadata, such as version tags. The file structure can be a JSON file.

```JSON
{
  "id": "robot_123",
  "name": "my robot",
  "versionTag": "v123",
  "RPARuntimeVersion": "1.0"
  "CamundaVersion": "8.8",
  "robotScript": "<content of original .robot file"
}
```

On a Service Task, a robotFile can be linked using a new extension element:

```xml
<bpmn:serviceTask>
  <extensionElements>
    <linkedResource name="robotFile" resourceId="=foo" versionBinding="versionTag" versionStrategy="latest" />
  </extensionElemnts>
</bpmn:serviceTask>
```

Zeebe will resolve the resource to a resource key. With the key, the RPA runtime can then fetch the resource directly from zeebe. This allows us to cache results for certain keys and save on bandwidth and Zeebe resources for resource lookup.

## Task Breakdown

```[tasklist]
### Engine
- [ ] https://github.com/camunda/camunda/issues/24764
- [ ] https://github.com/camunda/camunda/issues/24765
- [ ] https://github.com/camunda/camunda/issues/24766
- [ ] https://github.com/camunda/camunda/issues/25277
- [ ] https://github.com/camunda/camunda/issues/24772
- [ ] https://github.com/camunda/camunda/issues/25278
- [ ] https://github.com/camunda/camunda/issues/25279
- [ ] https://github.com/camunda/camunda/issues/24773
- [ ] https://github.com/camunda/camunda/issues/28780
```

```[tasklist]
### REST API
- [ ] https://github.com/camunda/camunda/issues/25280
- [ ] https://github.com/camunda/camunda/issues/25281
```

```[tasklist]
### BPMN Model API
- [ ] https://github.com/camunda/camunda/issues/24774
```

## Links

- Main Epic issue:  https://github.com/camunda/rpa-runtime/issues/8
