### ISSUE TITLE
Allow corrections for the complete listener

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#24889]
```[tasklist]
### Tasks
- [x] Append the `CORRECTED` event when a task listener job is completed with corrections
- [x] Fill the `COMPLETED` event with the latest intermediate user task data
- [x] Possibly change the `COMPLETED` event applier to store the corrected data
```

**Comment by korthout** [comment]
Not necessary to adjust the COMPLETED event applier, because the user task is deleted when it is COMPLETED.
