### ISSUE TITLE
Group migration is supported

### ISSUE THREAD

**Issue by maryarm** [camunda/camunda#25075]
### Description
With this issue we want to  migrate existing groups of Management Identity to New Identity. In management identity we have groups stored locally for SaaS, and for SM with Keycloak, they are stored in Keycloak. For oidc, groups are not supported yet.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/25127
- [ ] https://github.com/camunda/camunda/issues/25128
- [ ] https://github.com/camunda/camunda/issues/24815
- [ ] https://github.com/camunda/camunda/issues/25125
- [ ] https://github.com/camunda/camunda/issues/25167
```
