### ISSUE TITLE
Migration for tenant membership of type Group is supported for SM Keycloak

### ISSUE THREAD

**Issue by maryarm** [camunda/camunda#25141]
### Description
With this issue group to a tenant should be retrieved from Management Identity and stored as a group for that tenant in Camunda.

### Tasks
- [ ] https://github.com/camunda/camunda/issues/25139
- [ ] https://github.com/camunda-cloud/identity/pull/3228
- [ ] https://github.com/camunda/camunda/pull/26278

**Comment by npepinpe** [comment]
Assuming this is done since all sub issues are closed.
