### ISSUE TITLE
🎯 List task attachments 

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#25236]
### Description

- https://github.com/camunda/product-hub/issues/2497

#### Frontend

* [x] https://github.com/camunda/camunda/issues/25239
* [x] https://github.com/camunda/camunda/issues/25241
* [x] https://github.com/camunda/camunda/issues/25242
* [ ] https://github.com/camunda/team-hto/issues/709

### Definition of Ready - Checklist

- [ ] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] Edge cases and limitations are clear

### Acceptance Criteria

- [ ] All the TODO issues are done
