### ISSUE TITLE
Add an attachments tab to the task

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#25239]
### Description

To further develop the document handling feature created via https://github.com/camunda/team-hto/issues/662 we want to add the options for users to preview the task files/attachments

### TODO

- [ ] Create a new attachments tab
  - [ ] The tab must visible only if the user has read permissions (Clarify resource based auth)
- [ ] Fetch files information from the new endpoint (This endpoint is still TBD)
- [ ] Render a list of files based on [the design mocks](https://www.figma.com/design/77VZ8co4S2STqwuyyzO7As/Document-handling?node-id=579-7796&node-type=frame&t=rAFUjWVEzUqnBBCY-0)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
