### ISSUE TITLE
Allow the user to download an attachment

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#25242]
### Description

To further develop the document handling feature created via https://github.com/camunda/team-hto/issues/662 we want to add the options for users to preview the task files/attachments

### TODO

- [ ] The user must be able to download the listed attachments (Clarify resource based auth)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
