### ISSUE TITLE
Process Migration Observability Metrics

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#25305]
## Description
Export relevant application metrics to the actuator

## Todo
- [ ] Processes Migrated `camunda.migration.processes.migrated.total` counter
- [ ] Migration rounds `camunda.migration.processes.rounds.total` counter
- [ ] Migration round duration `camunda.migration.processes.round.time` round number tag
- [ ] Single process migration duration (extract XML data) `camunda.migration.processes.single.process.time` timer
