### ISSUE TITLE
[EPIC] Return key attributes as string values in the C8 REST API by default

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#25424]
## Introduction

We change the C8 REST API default to `string`-based key attributes for content type `application/json` as proposed in https://github.com/camunda/camunda/issues/24805. This is a **breaking change** in the V2 API.

## Concept

* We introduce dedicated content types and DTOs to use in requests/responses to accept/return `int64` number-based or `string`-based key attributes for clients that need this. Upgrading clients can set the number content type if they need the old behavior.
* The content types are reflected at least in the 8.6 V2 GA endpoints (aka migrated Zeebe gRPC API) in the OpenAPI spec and reference documentation.
* Internally, in the REST API, key attributes remain as `long` values.
* The REST gateway transforms `long` values into `string` values or vice versa for requests and responses by default. Ideally, this happens generically in a Jackson (de-)serializer to avoid unnecessary code duplication in the controllers.
* We detect supported pre-8.7 clients via agent header and return/accept number-based key attributes if `application/json` is provided as the content type. 8.7 clients define the content type they need explicitly.
* The 8.6 V2 API receives the new content types as well to allow fixing existing client applications that need `string´-based keys. We don't change the default there to avoid breaking changes in a patch.

## Task Breakdown

```[tasklist]
### Gateway API 8.6 & 8.7
- [x] Add `string` and `int64`-based DTOs
- [x] Transform key attributes based on content type
- [x] Detect pre-8.7 clients via agent header
- [ ] https://github.com/camunda/camunda/issues/25760
- [ ] https://github.com/camunda/camunda/issues/26063
- [ ] https://github.com/camunda/camunda/issues/26653
- [ ] https://github.com/camunda/camunda/issues/26761
- [ ] https://github.com/camunda/camunda/issues/26251
```

```[tasklist]
### Gateway API 8.7
- [x] Make `string` keys the default
- [x] Decide on support for new content types for new 8.7 endpoints
- [ ] https://github.com/camunda/camunda/issues/26062
- [ ] https://github.com/camunda/camunda/issues/26465
- [ ] https://github.com/camunda/camunda/issues/27204
```

```[tasklist]
### Java SDK 8.7
- [x] Use string-based content type in Java SDK
```

```[tasklist]
### Documentation
- [x] Document key attribute changes in update guide
- [x] Document different content types and their purpose in OpenAPI spec and reference docs
- [x] Adjust 8.6 public reference specification
- [ ] https://github.com/camunda/camunda/issues/27741
```

## Discussions and Decisions

* Camunda-internal [discussion on Slack](https://camunda.slack.com/archives/C06UKS51QV9/p1732305476336959?thread_ts=1731429420.606829&cid=C06UKS51QV9)
* [API proposal](https://github.com/camunda/camunda/issues/24805) with an outline and more options

**Comment by tmetzke** [comment]
I will create a POC for job activation and one search endpoint to discover the dimensions of this.
@danielkelemen will drive the overall implementation in the API.

**Comment by tmetzke** [comment]
POC with discussions: https://github.com/camunda/camunda/pull/25464

**Comment by danielkelemen** [comment]
## Changes

### 8.6

Default key type stays Long but with header `application/vnd.camunda.api.keys.string+json` they are converted to String.

#### Which APIs support String Keys
- /v2/jobs
  - activation
- /v2/decision-definitions
  - evaluate
  - search
- /v2/decision-instances
  - search
- /v2/decision-requirements
  - search
- /v2/flownode-instances
  - search
- /v2/incidents
  - search
  - get
- /v2/process-instances
  - create
  - search
- /v2/deployments
- /v2/user-tasks
  - search

TODO:
- /v2/authorizations
  - search - `ownerKey`?
- /v2/messages
  - publication - `messageKey`?
  - correlation - `messageKey`?
- /v2/signals
  - broadcast - `signalKey`?

### 8.7 (or higher)

Default key is String but with header `application/vnd.camunda.api.keys.number+json` they are converted to Long.

#### Which APIs support String Keys
TODO

**Comment by tmetzke** [comment]
I added the task `Adjust 8.6 public reference specification`. The public reference in 8.6 docs has to be adjusted manually. You can still generate the files, I think, and copy them accordingly to the versioned docs. @pepopowitz can support here if necessary, as can I. Let us know if you need any support on that.

**Comment by pepopowitz** [comment]
> I added the task `Adjust 8.6 public reference specification`. The public reference in 8.6 docs has to be adjusted manually. You can still generate the files, I think, and copy them accordingly to the versioned docs. @pepopowitz can support here if necessary, as can I. Let us know if you need any support on that.

I am working on this! I have in-flight work to add the ability to generate non-next versions of API docs directly, instead of the workaround you described, in https://github.com/camunda/camunda-docs/pull/4799. I hope to land that PR soon, but it's realistically a couple weeks away. If you do a lot of updating of the 8.6 schema and the current state of generation gets in your way, let me know, and I can try to get that specific bit merged sooner.
