### ISSUE TITLE
Add `corrections` to complete job REST endpoint

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#25447]
Add corrections to complete job REST endpoint.
```[tasklist]
### Tasks
- [x] Update rest-api.yaml
- [x] Add `corrections` to RequestMapper
- [x] Add relevant tests to `JobControllerTest`
- [x] Add relevant tests to Complete Job Test
- [x] Add support for `correctedAttributes`
```
