### ISSUE TITLE
Support completing job with corrections in java client

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#25449]
```[tasklist]
### Tasks
- [x] Add `corrections` to CompleteJobCommand
- [x] Set `corrections` in CompleteJobCommandImpl
- [x] Update `CompleteJobTest` in the client
- [x] Update `CompleteJobRestTest` in the client
- [x] Update `UserTaskListenersTest`
```
