### ISSUE TITLE
[EPIC] Complete user task variable-related API

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#25455]
## Introduction

User task variables in the C8 REST API can be accessed in two ways:
* Fetching user task variables via `POST /v2/user-tasks/:key/variables/search`
* Filtering user tasks by variables via `filter` attributes in `POST /v2/user-tasks/search`

The scopes considered in those endpoints are different for performance reasons and required use cases.

## Concept

Fetching user task variables yields ALL variables visible from a user task. This includes the following scopes:
* The variables local to the element instance the user task is related to via `elementInstanceKey`
* The variables local to any parent scopes of the user task's element instance, e.g., a surrounding parent subprocess. This hierarchically proceeds up the tree until the process instance's scope is reached.
* The variables in the scope of the process instance.

Filtering user tasks by variables considers the following scopes:
* The variables available anywhere in the process instance, no matter in which scope. This can be local to the user task's element instance, a sibling element instance, a parent element instance, or the process instance itself.
* The variables available locally at a user task's element instance (linked to via `elementInstanceKey`).

The different variable scopes in filtering user tasks can be expressed explicitly in the user task search request, e.g. by different filter attributes `processVariables` and `localVariables`.

### Gateway API

- [x] Adjust user task variable fetching endpoint to `POST /v2/user-tasks/:key/variables/search` - https://github.com/camunda/camunda/issues/25490 
- [x] Fetch variables from all parent scopes listed in the `treePath` of the user task's element instance (aka flow node instance) - The current implementation already covers that.
- [x] Replace `variables` filter attribute in user task search endpoint with `processInstanceVariables` and `localVariables`
- [x] Filter by all variables anywhere in the process instance as defined in `processInstanceVariables`, as described in https://github.com/camunda/camunda/issues/25291
- [x] Filter by all variables local to the user task's element instance as defined in `localVariables`, as described in https://github.com/camunda/camunda/issues/25292

### Clients

- [x] Adjust user task variable fetching endpoint to `POST /v2/user-tasks/:key/variables/search` - https://github.com/camunda/camunda/issues/25490 
- [x] Replace `variables` filter attribute in user task search command with `processInstanceVariables` and `localVariables`

### Testing

- [x] Integration tests for fetching user task variables from all parent scopes (including intermediate subprocess scopes) - https://github.com/camunda/camunda/issues/25491
- [x] Integration tests for filtering user tasks based on process variables, local variables, and combinations of them

### Dependencies

This issue depends on the following tasks to be completed:
* The `treePath` is filled for all flow node instances in the exporters
* The global and local user task variables can be queried from the user task index/table in user task queries
