### ISSUE TITLE
[EPIC]: Build treePath in Engine and add respecitive properties on record(s)

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#25474]
## Description

In the early stages of the Camunda Exporter Project, we assumed that the treePath was only really necessary for incidents, and for most other cases it was not useful and could be avoided.

We [realized](https://camunda.slack.com/archives/C05QBRGMA9F/p1732562391807879) that the treePath is used in many more places. 

Operate uses it in several places, and the effort to change these based on our previous decision was rather intensive. This is especially an issue looking at our current timeline (release end of Dez).

This is the reason why we ran some POC’s one for [building the treePath in the Exporter](https://github.com/camunda/camunda/pull/25310) and one [in the Engine](https://github.com/camunda/camunda/pull/25352). We have implemented the POCs and benchmarked them intensively at the RSG (Hamburg 2024).

### Details on the benchmarking and decision

Based on the benchmarks and results, and intensive discussions with stakeholders and peers we [decided](https://camunda.slack.com/archives/C05QBRGMA9F/p1732872462881639) to go in the direction of implementing the treePath in the engine.

### Details on TreePath

There is a difference between inter and intra TreePath. The inter treePath goes over process definitions, including call activities and is used for showing incidents in Operate.

The intra treePath is just inside a process instance, and will/can be used to have a possibility to resolve existing variable scopes and understand the hierarchy in the PI.

We need both versions of treePaths, to support all current features!

> [!Important]
>
> Maxim:
> 
>  * internet - global -> inter treePath - global over multiple process instances
>  * intranet - local -> intra treePath - local on current process instance
> 

### Breakdown

```[tasklist]
### Engine
- [x] Adjust TreePathBuilder to accept flowScopeKey and RecordValue - avoiding look up of ElementInstance (that might not exist in ACTIVATING case)
- [x] Add inter treePath properties (similar to IncidentRecord) to ProcessInstanceRecord - ignore JSON output
- [ ] Use new compressed array property - provided by Lena
- [x] Find a place to calculate and add treePath properties to ProcessInstanceRecordValue - Activating intent
- [x] Make sure that properties are cleared for follow up events like ACTIVATED
- [x] Write a test to verify properties are correctly set - without CallActivity, with CallActivity, with multiple Callactivities
- [ ] Handle edge case with deep nesting - create incident for example (early, as otherwise Incident also runs into this issue)
- [x] Write tests that verify that on other intents properties are not set
```

```[tasklist]
### Exporter
- [ ] Consume new properties for FlowNodeInstance index - intra tree path (FlowNodeInstanceFromProcessInstanceHandler)
- [ ] Consume new properties for ListViewPI index - inter tree path (ListViewProcessInstanceFromProcessInstanceHandler)
- [ ] Migrate root QA/IT tests to Camunda Exporter (allows to validate that treePath works as expected)
- [ ] Fix bug - exporter should consume all treePath from all call activities - right now it is only the first one
```
