### ISSUE TITLE
Add documentation on User Task Listeners

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#25502]
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/26339
- [ ] https://github.com/camunda/camunda/issues/26338
- [ ] https://github.com/camunda/camunda/issues/26345
- [x] Update complete job restapi documentation
- [ ] https://github.com/camunda/camunda/issues/26342
- [ ] https://github.com/camunda/camunda/issues/26344
- [ ] https://github.com/camunda/camunda/issues/26343
- [ ] https://github.com/camunda/camunda/issues/26346
```

**Comment by ce-dmelnych** [comment]
Closing this issue as all sub-tasks have been completed.
