### ISSUE TITLE
[EPIC]: Extend test coverage of Camunda Exporter

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#25595]
## Description

With finalizing the Camunda Exporter business logic ([Iteration 3](https://github.com/camunda/product-hub/issues/2128)), we should as part of Iteration 4 stabilize the current implementation. While we want to spent time on manual and chaos testing and benchmarking.

We should also need to spent some time to extend the general test coverage with automated tests.
```[tasklist]
### Extend Test coverage
- [ ] https://github.com/camunda/camunda/issues/26896
- [ ] https://github.com/camunda/camunda/issues/27906
- [ ] We should analyze the current existing E2E and IT and validate whether we lack some coverage
- [ ] https://github.com/camunda/camunda/issues/24095
- [ ] https://github.com/camunda/camunda/issues/24932
- [ ] https://github.com/camunda/camunda/issues/28166
- [ ] https://github.com/camunda/camunda/issues/25935
- [x] [Extend Root IT Testing for Opensearch](https://camunda.slack.com/archives/C06F0GLJNFM/p1733393579736399)
- [ ] https://github.com/camunda/camunda/issues/27079
- [ ] Check long running importer tests (Operate) https://camunda.slack.com/archives/C05QBRGMA9F/p1740486440302079
- [ ] https://github.com/camunda/camunda/issues/29912
- [ ] https://github.com/camunda/camunda/issues/29915
```

**Comment by RomanJRW** [comment]
I will close this as done, as all subtasks are complete, or are tracked elsewhere
