### ISSUE TITLE
Remove the optimize-distro distribution directory from Optimize

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#25621]
### Context

With https://github.com/camunda/camunda/issues/22271 we have made Optimize part of the unified release process. As a failsafe for 8.7.0 we have kept `optimize-distro` distribution directory, so that we are also able to release Optimize in case something goes wrong with the unified release process. After a successful 8.7.0 from the unified release process, we can safely remove the distribution path `optimize-distro`

### Acceptance Criteria

- [ ] Remove all the build steps that generate data into `optimize-distro`
- [ ] Remove `optimize-distro` altogether as a distribution path

### Testing Notes

This is a purely technical issue and there's nothing to be tested from an end-user perspective

### Links

https://github.com/camunda/camunda/issues/22271

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
