### ISSUE TITLE
[Optimize] Support ad-hoc subprocesses

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#25639]
Engineering DRI: @abremard 

### Context

With Camunda 8.7, we will support a new BPMN element: the ad-hoc subprocess. For Optimize, we may write tests to ensure that data from such elements can be imported and used for report evaluation.

### Acceptance Criteria

- [ ] I can see the data from an ad-hoc subprocess

### Testing Notes

Example process:

![Screenshot from 2024-12-05 10-10-03](https://github.com/user-attachments/assets/963c4cd3-24a6-4b66-8713-5cea7393fe02)

### Links

Part of https://github.com/camunda/product-hub/issues/2546.

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/27968
- [ ] https://github.com/camunda/camunda/pull/28233
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by abremard** [comment]
I've checked regarding single app release with Mattia (see [comment](https://github.com/camunda/camunda/pull/28233#discussion_r1958987246))
