### ISSUE TITLE
[EPIC]: Support Incident notification with Camunda Exporter

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#25767]
## Description

We have a feature in SaaS, to alert on new incidents, which we need to keep up for 8.7, when replacing the Importers with the Camunda Exporters.

We planning to integrate the functionality, into the Camunda Exporter, see [decision](https://camunda.slack.com/archives/C05QBRGMA9F/p1733752653971549).

```[tasklist]
### Tasks
- [ ] Start with a POC, to make sure it is feasible
- [ ] We need to despringify the IncidentNotifier
- [ ] Bring notifier to Exporter
- [ ] Support configuration for notifier (incl. webhook, auth, etc.)
- [ ] Integrate notifier in Exporter, such that on new incident it can be triggered (ideally async)
- [ ] Provide dependencies to notifier:  process cache, M2M token provider,  HTTP client
```
