### ISSUE TITLE
I can use the profile `auth-ldap` to enable LDAP based authentication

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#25781]
### Description
LDAP is currently supported in the web applications. This support should be present and functioning in the `camunda-authentication` module

### Tasks
- [ ] A LDAP focused web security configuration exists
  - [ ] hint: we can heavily reference/use the Operate implementations [here](https://github.com/camunda/camunda/tree/main/operate/webapp/src/main/java/io/camunda/operate/webapp/security/ldap) 
- [ ] An LDAP user details service exists extending the `CamundaUserDetails` class
  - [ ] hint: the basic authentication user details class offers suggestions on getting application access from services, here we need to use mapping rules
- [ ] Accessing the `/v2/authentication/me` endpoint returns the expected data for LDAP

**Comment by npepinpe** [comment]
AFAIK we will go for a more plugin-based approach, so closing.
