### ISSUE TITLE
I can use the profile `auth-oidc` to enable OIDC based authentication

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#25780]
### Description
OIDC is currently supported in the web applications and is how we offer support for connecting to external providers. This support should be present and functioning in the `camunda-authentication` module

### Tasks
- [x] A OIDC focused web security configuration exists
- [ ] I can configure the OIDC connection using Camunda abstracted properties i.e. `camunda.auth.oidc.issuer-url`
- [ ] An OIDC user details service exists extending the `CamundaUserDetails` class
  - [ ] hint: the basic authentication user details class offers suggestions on getting application access from services, here we need to use mapping rules
- [ ] When in a SAAS context, the organization of the deployment is checked against the organizations on the users token
  - [ ] The orgs are in the claim `https://camunda.com/orgs` for a user token and `https://camunda.com/clusterId` for a M2M token
  - [ ] The organization ID of the cluster is passed into the single application via configuration in the property `camunda.security.organizationId` (proposal) (https://github.com/camunda-cloud/camunda-operator/issues/3571)
- [ ] Accessing the `/v2/authentication/me` endpoint returns the expected data for OIDC

**Comment by romansmirnov** [comment]
> The organization ID of the cluster is passed into the single application via configuration in the property camunda.environmnent.organizationId (proposal) 

I propose having this property as part of the security configuration unless the organization id must be used somewhere else as well.

**Comment by Ben-Sheppard** [comment]
> > The organization ID of the cluster is passed into the single application via configuration in the property camunda.environmnent.organizationId (proposal)
> 
> I propose having this property as part of the security configuration unless the organization id must be used somewhere else as well.

I agree that makes sense @romansmirnov - updated
