### ISSUE TITLE
Migrate Tasklist IT to Camunda Exporter

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#25798]
We are harmonizing the indices, and will replace the Operate/Tasklist Importer with the Camunda Exporter.

In order to do that, we have to migrate the Tasklist IT to the Camunda Exporter, so we can remove the 8.7 Importer.
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/pull/25500
- [x] Remove GraphQL It https://github.com/camunda/camunda/pull/25797
- [ ] https://github.com/camunda/camunda/pull/25758
- [ ] https://github.com/camunda/camunda/pull/26309
- [ ] https://github.com/camunda/camunda/pull/26308
- [ ] https://github.com/camunda/camunda/pull/26310
```

**Comment by ChrisKujawa** [comment]
Tasklist integration tests have been migrated 🎉
