### ISSUE TITLE
Allow corrections for the assigning listener

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#26032]
Similar to:
- https://github.com/camunda/camunda/issues/24889

```[tasklist]
### Tasks
- [x] Append the `CORRECTED` event when a task listener job is completed with corrections
- [x] Fill the `ASSIGNED` event with the latest intermediate user task data
- [x] Possibly change the `ASSIGNED` event applier to store the corrected data
```
