### ISSUE TITLE
[EPIC]: Camunda Exporter list of known bugs found in stabilization phase

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#26058]
## Description

This issue should be seen as a reference to discovered bugs in the stabilization phase, which need to be fixed until the release.

### Alpha3 Blockers
- [ ] https://github.com/camunda/camunda/issues/26046
- [ ] https://github.com/camunda/camunda/issues/26047
- [ ] https://github.com/camunda/camunda/issues/25968
- [ ] https://github.com/camunda/camunda/issues/26056
- [ ] https://github.com/camunda/camunda/issues/26066

### Blocking
- [ ] https://github.com/camunda/camunda/issues/26093
- [ ] https://github.com/camunda/camunda/issues/26048
- [ ] https://github.com/camunda/camunda/issues/26120
- [ ] https://github.com/camunda/camunda/issues/26701
- [ ] https://github.com/camunda/camunda/issues/26966
- [ ] https://github.com/camunda/camunda/pull/26067
- [ ] https://github.com/camunda/camunda/pull/28011
- [ ] https://github.com/camunda/camunda/pull/28154
- [ ] https://github.com/camunda/camunda/issues/28111
- [ ] https://github.com/camunda/camunda/pull/28140
- [ ] https://github.com/camunda/camunda/pull/28377
- [ ] https://github.com/camunda/camunda/issues/29114
- [ ] https://github.com/camunda/camunda/issues/29132

### High severity
- [ ] https://github.com/camunda/camunda/issues/26094
- [ ] https://github.com/camunda/camunda/issues/26755
- [ ] https://github.com/camunda/camunda/issues/24084
- [x] Export is not respecting batch limit, and continues consuming records https://camunda.slack.com/archives/C05QBRGMA9F/p1739194828715149

### Mid severity
- [ ] https://github.com/camunda/camunda/issues/25539
- [ ] https://github.com/camunda/camunda/issues/30877

### Low severity
- [ ] https://github.com/camunda/camunda/issues/24243
- [ ] https://github.com/camunda/camunda/issues/28173

### Easy picks/noise
- [ ] https://github.com/camunda/camunda/issues/25810
- [ ] https://github.com/camunda/camunda/issues/25811
- [ ] https://github.com/camunda/camunda/issues/25812
- [ ] https://github.com/camunda/camunda/issues/25814
- [ ] https://github.com/camunda/camunda/issues/25991
- [ ] https://github.com/camunda/camunda/issues/25631
- [ ] https://github.com/camunda/camunda/issues/28464
- [ ] https://github.com/camunda/camunda/issues/28039
- [ ] https://github.com/camunda/camunda/issues/29953
- [ ] https://github.com/camunda/camunda/issues/29954
- [ ] https://github.com/camunda/camunda/issues/29684

**Comment by RomanJRW** [comment]
All subtasks of this epic are now complete, closing as done
