### ISSUE TITLE
Opensearch schema manager false negative during index validation

### ISSUE THREAD

**Issue by EuroLew** [camunda/camunda#26056]
**Description**

The opensearch index validator will return a false negative when comparing a schema .json file and the index that was created with that .json file, this is due to certain fields not appearing in the mappings of a serialised return object. In the given example the `eager_global_ordinals` field is not returned as part of the `join` field. This issue seems to be unique to opensearch and not elastic

![image](https://github.com/user-attachments/assets/9dbd1660-9b74-4d6a-93a0-0b09b21e5fa0)
![image](https://github.com/user-attachments/assets/ccf5bf85-97f6-4e26-9648-d388a8544ecf)

Success Criteria:
- [ ] Indices created by a schema file will not trigger an index validation error which comparing against the schema file
- [ ] Add a test to catch the issue of schema files clashing against their created indices.
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/26085
```

**Comment by EuroLew** [comment]
The issue is already fixed by opensearch on Nov 13 https://github.com/Xtansia/opensearch-java/blob/0e386f4b508b995bdfc14780ea1f2a955ad41596/java-client/src/generated/java/org/opensearch/client/opensearch/_types/mapping/JoinProperty.java, they added eager_global_ordinals to the join serialisation. The only issue is that they haven't added to a release which they appear to do every 2-3 weeks.

For now to fix the breaking issue the field will be removed from affected schemas and when an `opensearch-java` client version is released with the fix we can add the `eager_global_ordinals` option back with the updated client

**Comment by ChrisKujawa** [comment]
@EuroLew can this be closed?
