### ISSUE TITLE
Update camunda-operator to set the stackdriver service name variable

### ISSUE THREAD

**Issue by buccarel** [camunda/camunda#26264]
### Context

With the change from logback to log4j2, we are using an environment variables to configure stackdriver. These variables should hold a value for optimize so that the logging related to optimize is routed correctly.

Sample optimize config file:
https://github.com/camunda/camunda/blob/dc8d434ed030e13e0319878ed58fcc723e528814/optimize/backend/src/main/resources/log4j2.xml

Sample commit to update camunda-operator:
https://github.com/camunda-cloud/camunda-operator/commit/12aed0d27391a82ca51f94de9d697afe058b868e

### Acceptance Criteria

[ ] Optimize logging is routed correctly in SaaS
[ ] OPTIMIZE_LOG_STACKDRIVER_SERVICEVERSION is also assigned the correct value

### Links

* Part of https://github.com/camunda/product-hub/issues/2289

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda-cloud/camunda-operator/pull/3631
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue
