### ISSUE TITLE
Remove the Optimize DB compatibility check on startup

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda#26311]
Engineering DRI: @RomanJRW

### Context

Some customers require to run on older ES versions (at own risk). No other components do a compatibility check. This is in some ways a legacy piece of functionality from Optimize in C7, that we continued supporting as it provided value. In the mono repo, this is less useful as a singular component check does not make sense.

We should remove this check for consistency, and to remove complexity too. Currently Optimize has to _know_ the minimum supported DB, removing this check also removes that dependency.

### Acceptance Criteria

- [x] Optimize starts even if older ES versions (compare https://docs.camunda.io/docs/next/reference/supported-environments/) is used
- [x] Build for 8.6.x +. Should be released as 8.6.x patch (and also for 8.7)

### Links

https://camunda.slack.com/archives/C044Q1241GC/p1733995696972009

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/26592
- [ ] https://github.com/camunda/camunda/pull/26743
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Hey @grlimacan I Tested agains 8.7.0-SNAPSHOT


Optimize started and seems to be working fine but when the app can't be reached 
I'm using ES --> 8.11.2
I'm getting the following error --> **Whitelabel Error Page**

![Image](https://github.com/user-attachments/assets/4394d414-7d29-4d4a-bb4a-a7dd86093e1f)

![Image](https://github.com/user-attachments/assets/2cffdfbe-ac25-4f18-b1c2-87aec87375e3)

**Comment by grlimacan** [comment]
> [@RomanJRW](https://github.com/RomanJRW) Thanks for the clarification
> 
> Successfully tested agains 8.7.0-SNAPSHOT
> 
> ![Image](https://github.com/user-attachments/assets/391f470b-9254-4cac-b5af-f16baa42374b)
> 
> [logs.txt](https://github.com/user-attachments/files/18426936/logs.txt)

@RobertDorlan The log that you attached in the message above is very problematic, as it contains the message

`Caused by: io.camunda.optimize.service.exceptions.OptimizeRuntimeException: 8.11.2 version of Database is not supported by Optimize`

Therefore this is not a successful test. If you built the Snapshot yourself this would be a definite qa reject. If you're taking the publicly available snapshot this behaviour is to be expected, since we currently have a problem with `main` where we are not pushing snapshot images.... Please let me know how this test went

**Comment by RobertDorlan** [comment]
@grlimacan 

sorry wrong file for the logs

[logs.txt](https://github.com/user-attachments/files/18427542/logs.txt)

**Comment by grlimacan** [comment]
> [@grlimacan](https://github.com/grlimacan)
> 
> sorry wrong file for the logs file, also updated on the comment above
> 
> [logs.txt](https://github.com/user-attachments/files/18427542/logs.txt)

@RobertDorlan Thanks, this one looks good :-)

**Comment by grlimacan** [comment]
FYI no changes needed on helm charts, as they set the port explicitly: https://github.com/camunda/camunda-platform-helm/blob/0baf80a2c439d307d50956febd9aeb1cbdd3b619/charts/camunda-platform-8.6/templates/optimize/deployment.yaml#L63
cc @RomanJRW

**Comment by RomanJRW** [comment]
Updating the version to alpha5, as Optimize does not intend to release a version 8.7.0-alpha4

**Comment by RomanJRW** [comment]
And back again to alpha4, given the changes to the release plans (branching from 8.6)
