### ISSUE TITLE
Add Spring SDK Testing support that was present in community Spring SDK 

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#26423]
**Is your feature request related to a problem? Please describe.**
Spring test support for the Camudna Spring SDK was previously introduced to a 8.6 alpha with https://github.com/camunda/camunda/issues/17343 but got eventually removed again with https://github.com/camunda/camunda/pull/18360 before the release.

As of now Camunda Spring SDK users have no way to make use of a spring test integration as also documented [here](https://github.com/camunda/zeebe-process-test/pull/1281/files).

**Describe the solution you'd like**
Provide 8.6 spring test modules compatible with the official Camunda Spring SDK

**Describe alternatives you've considered**
The alternative, being Camunda Process Test and it's spring support, are not suffice yet as it lacks feature parity with the [ZPT](https://github.com/camunda/zeebe-process-test) engine used in the former test integration.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/26424
- [ ] https://github.com/camunda/camunda/issues/26429
- [ ] https://github.com/camunda/camunda/issues/26598
- [ ] https://github.com/camunda/camunda/issues/26599
- [ ] https://github.com/camunda/camunda/issues/26600
```

Related support tickets:
https://jira.camunda.com/browse/SUPPORT-24723
https://jira.camunda.com/browse/SUPPORT-24975
https://jira.camunda.com/browse/SUPPORT-24844

**Comment by megglos** [comment]
To be decided:
Do we want to forward-port this to 8.7? Will likely result in a better migration experience as you could first just update to 8.7 and then migrate to the CPT based setup.

Wdyt @aleksander-dytko @saig0 ?

**Comment by aleksander-dytko** [comment]
@megglos I believe it makes sense to port it to 8.7 to provide a smother migration journey

**Comment by megglos** [comment]
Let's forward port this to `main` too then.

**Comment by alexcorremans** [comment]
Support tickets: 
https://jira.camunda.com/browse/SUPPORT-24723
https://jira.camunda.com/browse/SUPPORT-24975
https://jira.camunda.com/browse/SUPPORT-24844

**Comment by megglos** [comment]
Docs are due to make this addition to 8.6.7 transparent.
@mesellings @akeller Will provide the dcos PRs shortly so we can cross this off.
