### ISSUE TITLE
Handle requests in BatchRequest with index of `null`

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#32804]
### Description

Under some conditions it can happen that requests with index of `null` will be added to BatchRequest.
Before executing the request an exception is thrown, which means the index was set to `null`.

This can block executing all requests stored in current BulkRequest.

```
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: index is missing;

at org.elasticsearch.action.bulk.BulkRequest.validate ( org/elasticsearch.action.bulk/BulkRequest.java:486 )
at org.elasticsearch.client.RestHighLevelClient.performRequest ( org/elasticsearch.client/RestHighLevelClient.java:2133 )
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity ( org/elasticsearch.client/RestHighLevelClient.java:2105 )
at org.elasticsearch.client.RestHighLevelClient.bulk ( org/elasticsearch.client/RestHighLevelClient.java:620 )
at io.camunda.operate.util.ElasticsearchUtil.processLimitedBulkRequest ( io/camunda.operate.util/ElasticsearchUtil.java:336 )
at io.camunda.operate.util.ElasticsearchUtil.processBulkRequest ( io/camunda.operate.util/ElasticsearchUtil.java:291 )
at io.camunda.operate.util.ElasticsearchUtil.processBulkRequest ( io/camunda.operate.util/ElasticsearchUtil.java:284 )
at io.camunda.operate.store.elasticsearch.ElasticsearchBatchRequest.execute ( io/camunda.operate.store.elasticsearch/ElasticsearchBatchRequest.java:169 )
at io.camunda.operate.util.OperationsManager.completeOperation ( io/camunda.operate.util/OperationsManager.java:107 )
at io.camunda.operate.util.OperationsManager.completeOperation ( io/camunda.operate.util/OperationsManager.java:97 )
...
```

Seen in [incident](https://jira.camunda.com/browse/SUPPORT-20897) and [Stackdriver](https://console.cloud.google.com/errors/detail/CKGnxZ2xgJrzeA;service=operate;time=P7D?project=camunda-saas-prod)

### TODO

- [ ] Filter out requests with index of `null` 
- [ ] Log a warn message with details of what should be added/updated/deleted
- [ ] Looking for other occurrences of creating requests as in 
[ElasticsearchOperationStore](https://github.com/camunda/zeebe/blob/26e652384a9cf057142bafec0847eb7eed3d73fc/operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchOperationStore.java#L170-L170)
### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
