### ISSUE TITLE
Add js package files to docker image in order to enable vulnerability scanning

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#32811]
### Description
In order to enable vulnerability scanning for js files we need to change the docker image.
Details in [Security Meeting document](https://docs.google.com/document/d/1bz6vAy5wN5Q5OgdErC7qsFAdFh4ZtmIAbUd_vP5v04o/edit#heading=h.pzq3goh3g7fv)

These files needs to be in the filesystem on top level:

* yarn.lock
* package.json
---
* See also [Identity PR](https://github.com/camunda-cloud/identity/pull/2598/files)
### TODO

- [ ] Provide files for copying into docker image
- [ ] Place the files in docker image at top level

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
