### ISSUE TITLE
Upgrade OpenSearch Java client to 2.8.x and check if workarounds are still needed.

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#32814]
### Description

Operate uses workarounds where OpenSearch Java client can't communicate with OpenSearch 2.5.+ server. 

### TODO

- [ ] Upgrade Java client to version 2.8.x
- [ ] Evaluate if we still need the workaround (`ExtendedOpenSearchClient`)
- [ ] Decide how to proceed 

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered
