### ISSUE TITLE
Migrate from CRA to vite

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#32844]
### Description

Operate is using CRA ([Create React App](https://github.com/facebook/create-react-app)), which is not actively maintained anymore and discouraged by the React team. We need to migrate to an alternative.

After some research the most sustainable solution is to replace CRA by [vite](https://vitejs.dev/).

With vite we should use vitest for testing, which works a bit differently, especially in regards to (fake) timers. The biggest challenge here is to refactor all tests to make them work with vitest, which will take some time to finish.

### TODO

- [x] Add vite dependencies
- [x] Add vite configuration
- [x] Refactor tests using vitest (general)
- [x] Refactor tests (fake timers)
- [x] Check e2e tests
- [x] Check visual regression tests
- [x] Check screenshot generator

### Additional Information

Tasklist has [migrated successfully to vite](https://github.com/camunda/tasklist/pull/3639).

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by pedesen** [comment]
Fixed with https://github.com/camunda/camunda/pull/35050
