### ISSUE TITLE
Provide access to endpoints internally (same cluster) in SaaS without auth0 token

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#32886]
### Description
Currently connectors need to create tokens to access public API.
Due to the fact that connectors running on same cluster in SaaS it is not necessary to create (and pay for it) tokens.

See also [Product hub issue](https://github.com/camunda/product-hub/issues/1262)

### Solutions
1. Provide public API with API key which is only used in SaaS.
   * The key could be exchanged between client (connector) and server (Operate) via environment variable.
2. Operate routes every traffic which comes from the same cluster without any authentication checks
   * How to define "same cluster" ?
     * Same IP in request? [Blog post](https://www.baeldung.com/spring-security-whitelist-ip-range)

### TODO
- [ ] Evaluate possible solutions (like the ones above)
- [ ] Align with other teams: connectors, sre
- [ ] Implement solution
- [ ] Tests

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)
