### ISSUE TITLE
Use Carbon Tooltips

### ISSUE THREAD

**Issue by huygur** [camunda/camunda#32902]
### Description
Carbon tooltips were overridden for Operation Buttons. We will remove these overrides, and also add a Tooltip wrapper for the Link item that has a title. (We will also remove the browser titles from these components, in order not to have 2 different tooltips)

### TODO

- [ ] Remove tooltip override from Operation Buttons (processes list, incidents list), along with removing browser titles
- [ ] Add tooltip wrapper to Link component in processes table, along with removing browser title

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ℹ️ Low |
| **When** | ℹ️ Later |
| **Confidence** | 0.97 |

---

### 📝 Rationale

Narrow UI cleanup to standardize Carbon tooltips, remove duplicate browser titles, and add a tooltip wrapper; it introduces no new capability and is a small, deferrable quality-of-life task.  It falls within Core Features’ web-application ownership. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
