### ISSUE TITLE
Reindex get stuck during migration due to insufficient ELS memory

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#32909]
### Description
During fixing an issue in a [support case](https://jira.camunda.com/browse/SUPPORT-16649) the reindex of variables indices got stuck due to insufficient Elasticsearch memory.

In `/.tasks/<id>` document for the reindex task was an error message:
```json
 "error": {
        "type": "es_rejected_execution_exception",
        "reason": "rejected execution of coordinating operation [coordinating_and_primary_bytes=0, replica_bytes=0, all_bytes=0, coordinating_operation_bytes=421267155, max_coordinating_and_primary_bytes=322122547]"
      }
```
### TODO

- [ ] Evaluate reindex options for batching the reindex
- [ ] Implement backoff strategy or raise exception for insufficient resources

### Additional Information
* [Index pressure memory limit](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-indexing-pressure.html)
* [Support case](https://jira.camunda.com/browse/SUPPORT-16649)

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
