### ISSUE TITLE
Show different decision deletion warnings based on scenario

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#32911]
Related to https://github.com/camunda/camunda/issues/32931

### Description

In the decision definition deletion dialog there will be two different scenarios with a different warning text each. 

- [ ] Scenario 1: The definition is only part of one DRD (see designs)
- [ ] Scenario 2: The definition is part of multiple DRDs or is part of a DRD which contains another decision which is part of multiple DRDs (see designs)

To check the type of definition, we need to introduce a new API endpoint.

### TODO

* [ ] Determine which is the current scenario
* [ ] Change warning text accordingly 

### Additional Information

Designs: https://www.figma.com/file/S0VWipy5r3KlZ0H1zR1mkb/Delete-Definition?node-id=126-1816&t=KqqB2AZEHtj7irrf-0

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
