### ISSUE TITLE
Provide better feedback for no permission to see a process

### ISSUE THREAD

**Issue by huygur** [camunda/camunda#32910]
### Description
When we try to open Operate with a URL that contains an invalid process name, the behavior is to poll until that process is available (in case it was newly created). If process is not available until the 3rd poll (which should be around 15 seconds in total) we then redirect to processes page with initial filters, followed by showing an error notification 'Process could not be found'.

With the resource based permissions, users can experience this behavior when they try to open Operate with a URL that contains a process name that they don't have READ permissions for. 

### TODO

- [ ] Decide on what to do differently for permissions, to improve user experience by giving better feedback
- [ ] Implement the discussed behavior

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | NEEDS_INFO |
| **Severity** | N/A |
| **Likelihood** | N/A |
| **Confidence** | 0.98 |

---

### 📝 Rationale

The issue concerns Operate, which is within Core Features ownership, but the intended permission-specific behavior is undecided and the acceptance criteria are not testable. The triage guidance requires clear expected behavior and sufficient reproduction details, and says to stop triage when information is missing. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
