### ISSUE TITLE
🎯 Frontend enhancements for Delete Definition

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#32931]
### Description

This epic will enable the user to check the details of referenced definitions of Process or Decision definition version that is about to be deleted.

* [ ] Product Hub: https://github.com/camunda/product-hub/issues/620
* [ ] Design: https://www.figma.com/file/S0VWipy5r3KlZ0H1zR1mkb/Delete-Definition?node-id=126%3A1816&t=ciu0kXyhdprV5N9u-1

### Use Cases

```Gherkin
Scenario: As an Operate user
    When I plan to delete a process definition which is a child of a parent process 
    Then I can see which parent process(es) are affected
    Then I can see that the parent process(es) will not be terminated nor deleted
    Then I can see that an incident will be created in the parent process(es)  
```

```Gherkin
Scenario: As an Operate user
    When I plan to delete a process definition which has child processes (call activities / business rule tasks)
    Then I can see which child processes and decisions are affected
    Then I can see that all instances of these children will be terminated and deleted
    Then I can see that the process definitions of these children will not be deleted 
```

#### Frontend
* [ ] camunda/camunda#32927 
* [ ] camunda/camunda#32925
* [ ] https://github.com/camunda/camunda/issues/32921
* [ ] https://github.com/camunda/camunda/issues/32920
* [x] https://github.com/camunda/operate/issues/4141
* [ ] https://github.com/camunda/camunda/issues/32919
* [x] https://github.com/camunda/camunda/issues/32917
* [ ] camunda/camunda#32926
* [ ] camunda/camunda#32911
* [ ] https://github.com/camunda/camunda/issues/32918
* [ ] https://github.com/camunda/camunda/issues/32915
* [ ] https://github.com/camunda/camunda/issues/32914
* [x] https://github.com/camunda/operate/issues/5267

### Additional Information

This is iteration 4/4 of the Delete Process and Decision Definition topic:

1. https://github.com/camunda/operate/issues/3972
2. https://github.com/camunda/operate/issues/3971
3. https://github.com/camunda/camunda/issues/32932
4. :arrow_right: https://github.com/camunda/camunda/issues/32931

### Definition of Ready - Checklist

- [ ] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] Edge cases and limitations are clear

### Acceptance Criteria

- [ ] All the TODO issues are done
