### ISSUE TITLE
🎯 Delete Process and Decision definition via API

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#32932]
### Description

Delete Process and Decision Definitions via Operate Public API

* [ ] Product Hub: https://github.com/camunda/product-hub/issues/619
* [ ] Zeebe: https://github.com/camunda/zeebe/issues/9576

### Additional Information

This is iteration 3/4 of the Delete Process and Decision Definition topic:

1. https://github.com/camunda/operate/issues/3972
2. https://github.com/camunda/operate/issues/3971
3. :arrow_right: https://github.com/camunda/camunda/issues/32932
4. https://github.com/camunda/operate/issues/3974

### Definition of Ready - Checklist

- [ ] The epic is broken down into backend and frontend tasks/features - if applicable
- [ ] Edge cases and limitations are clear

### Acceptance Criteria

- [ ] All the TODO issues are done
