### ISSUE TITLE
Centralize common mocks into `modules/` folder

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#32951]
### Description

On our unit/integration tests we have mocks spread around all over the project (localized in the tests, inside the modules folder, etc). To avoid repetition and bugs we should centralize these mocks into reusable location inside the `modules/` folder.

### TODO
- [ ] Map all possible reusable mocks
- [ ] Propose a structure
- [ ] Split it into smaller tasks if necessary

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
