### ISSUE TITLE
Fix error state in the UI for decision instance details page

### ISSUE THREAD

**Issue by huygur** [camunda/camunda#32962]
### Describe the bug

(Enable/add visual regression test after this bug is fixed)
If we navigate to decision instance detail page with an invalid id like this: https://stage.operate.camunda.cloud/decisions/9798789234 , we see a broken UI like in the screenshot:

![Screenshot 2022-09-16 at 10 34 06](https://user-images.githubusercontent.com/45518829/190594895-649ca0d2-392d-4d00-bd98-d5fa796c96f7.png)

###  To Reproduce
1. Go to decision instance detail page
2. Change the id at the end of the url to a random number

### Expected behavior
When user enters an invalid decision id, then they will see loading indicators and skeletons in the instance details page, similar to what we have in process instance details page. 
<img width="400" alt="Screenshot 2022-10-14 at 10 51 20" src="https://user-images.githubusercontent.com/16151298/195805250-c0079136-df99-460d-8b8d-d745e5d4163e.png">

- Use skeleton for Instance header and Inputs/Outputs areas
- Use loading spinner for Decision table and Results areas
- Keep DRD panel closed
- When Operate finds out, the id is not found then return to the Decision list view and show toast notification.
<img width="400" alt="Screenshot 2022-10-14 at 11 20 39" src="https://user-images.githubusercontent.com/16151298/195811403-43035063-b597-4614-bc4a-40da23e6e91d.png">

### TODO

- unskip test: `e2e-playwright/visual/decisionInstance.spec.ts`  > `error page`

### Environment

 - OS: MacOS
 - Browser: Chrome
 - Operate Version: 8.1.0-alpha5

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

**Comment by huygur** [comment]
Carbon update:
DRD Panel is completely if an error occurs when fetching `api/decision-instances/:id/drd-data`
<img width="1044" alt="Screenshot 2023-08-28 at 14 21 44" src="https://github.com/camunda/camunda/assets/45518829/6fc4a0d5-1bf0-4b45-bdb1-b3c8eb142324">

Page breaks if an error occurs when fetching `/api/decision-instances/:id`

<img width="1151" alt="Screenshot 2023-08-28 at 14 23 32" src="https://github.com/camunda/camunda/assets/45518829/dfa8442d-134b-441f-8c38-8d789cf43a5e">

**Comment by eppdot** [comment]
@huygur  is this still a relevant issue? (I am trying to clean up some stuff) 🧹

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** No Status  
**To:** Inbox  

**Reason:** Queued for further analysis and triage.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | ⚠️ Mid |
| **Confidence** | 0.95 |

---

### 📝 Rationale

The issue describes incorrect UI behavior when navigating to a decision instance detail page with an invalid ID in Operate, which is a released product. The expected behavior is clearly stated, and the bug is reproducible. The impact is noticeable (broken UI, user confusion), but does not cause data loss or block core functionality, so severity is MID. The likelihood is MID, as it can occur whenever a user enters an invalid ID, but is not a default path. The issue is in scope for Core Features per team boundaries.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.

**Comment by marcosgvieira** [comment]
🔄 **Iteration updated automatically (Core Features)**

**From:** Mar M1 (8.9)  
**To:** Mar M2 (8.9)  

**Reason:** The issue is In Progress, so it should be part of the current iteration.

**Comment by marcosgvieira** [comment]
🔄 **Iteration updated automatically (Core Features)**

**From:** Mar M2 (8.9)  
**To:** Iteration 8  

**Reason:** The issue is In Progress, so it should be part of the current iteration.

**Comment by marcosgvieira** [comment]
🔄 **Iteration updated automatically (Core Features)**

**From:** Apr - M1  
**To:** Apr - M2  

**Reason:** The issue is In Progress, so it should be part of the current iteration.
