### ISSUE TITLE
🎯 Refactor of diagram popover in Process Instance Details page

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#32970]
### Description

- [x] camunda/product-design#15

#### Frontend
* [x] camunda/operate#3124
* [x] camunda/operate#3125
#### Backend
* [ ] camunda/camunda#32965
* [ ] camunda/camunda#32964

### Definition of Ready - Checklist

- [x] The epic is broken down into backend and frontend tasks/features - if applicable
- [x] Edge cases and limitations are clear

### Acceptance Criteria

- [ ] All the TODO issues are done
