### ISSUE TITLE
🎯 Align terminology in Operate with API and consistency

### ISSUE THREAD

**Issue by santanaluiz** [camunda/camunda#32981]
## Description

Make sure a consistent terminology is used throughout the UI and the codebase.

## TODO

* [x] Rename UI labels https://github.com/camunda/operate/pull/2867
* [ ] Rename variables in frontend code
* [ ] Rename variables in backend code
* [ ] Rename internal API endpoints and parameters

### Dashboard
Rename
* _Instances_ -> _Process Instances_
* Error messages to "Data could not be fetched"

### Process Instances List
Rename
* _Instances_ -> _Process Instances_
* _Instance Id_ -> _Process Instance Key_
* _Start/End Time_ -> _Start/End Date_
* Versions inside filter dropdown:  _Version 1_ -> _1_ etc.

### Process Instance View
Rename
*  _Instance Id_ -> _Process Instance Key_
*  _End Time_ -> _End Date_
*  _FlowNodeInstanceId_ -> _FlowNodeInstanceKey_

### Decision Instances List
Rename
* _id_ -> _key_
* _Evaluation Time_ -> _Evaluation Date_

Please see miro board for all changes: https://miro.com/app/board/uXjVOPZgc-o=/?invite_link_id=672294558823
