### ISSUE TITLE
E2E Tests for Decisions

### ISSUE THREAD

**Issue by huygur** [camunda/camunda#32997]
## TODO

- [ ] https://github.com/camunda-cloud/operate/issues/2478
- [ ] https://github.com/camunda-cloud/operate/issues/2487
- [ ] https://github.com/camunda-cloud/operate/issues/2488
- [ ] https://github.com/camunda-cloud/operate/issues/2489
- [x] https://github.com/camunda-cloud/operate/issues/2490

**Comment by pedesen** [comment]
Will be part of [Orchestration cluster E2E test suite](https://github.com/camunda/camunda/blob/main/qa/c8-orchestration-cluster-e2e-test-suite/README.md).
