### ISSUE TITLE
The variable scope for a boundary event is the activity that it is attached to

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#4799]
**Describe the bug**
If a boundary event is attached to an activity then the variables of the boundary event expression (i.e. timer expression) are accessed from the scope of the activity instead of its flow scope activity (e.g. the workflow instance scope).  

If the activity has an input variable mapping that overlaps a variable that is used by a boundary event expression then it accesses the value of the local variable of the activity. This may lead to an incorrect event subscription or an incident.

This happens for all boundary event expressions except the message correlation-key expressions. 

**To Reproduce**
* deploy a workflow with
  * a service task with the input mapping
    * source: `="foo"` target: `x`
  * a timer boundary attached to the service task with 
    * a duration expression `=x`
* create an instance of this workflow with variable `{"x": "PT1M"}`
* verify that an incident is created  (`Expected result of the expression 'x' to be parsed to a duration, but was 'foo'`)

Try the same for message correlation key, and notice that it behaves differently.

**Expected behavior**

We want the same behavior for message correlation key expression evaluation when subscribing an activity to a message boundary event. Evaluate the expression in the context of the activity that is subscribing to the event.

**Root cause**

We explicitly use the flow scope instead of the element instance, but we shouldn't.

https://github.com/camunda/camunda/blob/89fd3db77ece80b872cc0631f82f425fb4a8f0fc/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java#L290-L293

Notice how the scope key for the message name expression is always just element instance key:

https://github.com/camunda/camunda/blob/89fd3db77ece80b872cc0631f82f425fb4a8f0fc/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java#L270

**Log/Stacktrace**

No.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.0, 0.24.0-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

**Comment by saig0** [comment]
Currently, the variable scope of the boundary event (i.e. the message correlation-key) is not documented. We need to clarify for the users when the variable mapping is applied and when the event subscriptions are opened.

**Comment by npepinpe** [comment]
What does the spec say regarding this?

**Comment by saig0** [comment]
In Camunda BPM, the behavior is the same as described in **Expected behavior**.

**Comment by Zelldon** [comment]
But is this also the same as in the spec ? :sweat_smile:

**Comment by saig0** [comment]
I looked into the spec but didn't found anything about it. 

If we don't see a reason why this is a bad idea then I would adopt the behavior of Camunda BPM.

**Comment by npepinpe** [comment]
The expected behaviour is more intuitive from my pov, and actually how I thought we had implemented it :sweat_smile:

**Comment by korthout** [comment]
Sev should be high, since there is no known workaround.

**Comment by korthout** [comment]
>**Expected behavior**
> The variables of the expressions are accessed from the scope of the activity that the boundary event is attached to.

@saig0 I just reread this, and I think the expected behavior section is incorrect. Could you please clarify this for me?

I think the expected behavior should be that only the variables visible from the scope of the boundary event can be accessed. 

I.e., the following scopes should be visible to expressions on the boundary event:
- variables at the boundary event
- variables at the root process instance

And the following scopes should **not** be visible to expressions on the boundary event:
- variables at the activity

**Comment by saig0** [comment]
> the following scopes should be visible to expressions on the boundary event:
> - variables at the boundary event
> - variables at the root process instance
>
> And the following scopes should not be visible to expressions on the boundary event:
> - variables at the activity

Correct. :+1: 

The issue should describe precisely this behavior. But the wording is probably not very clear. :sweat_smile:

**Comment by korthout** [comment]
Thanks, I've updated the expected behavior in the issue.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | 🔥 HIGH |
| **Likelihood** | 🔥 High |
| **Confidence** | 0.95 |

---

### 📝 Rationale

The issue describes incorrect variable scoping for boundary events, leading to incidents and incorrect event subscriptions, with no known workaround. The report is clear, includes expected vs actual behavior, and reproduction steps. Team Boundaries confirm this is in Core Features scope. Severity is HIGH due to the lack of workaround and production impact; likelihood is HIGH as it affects all boundary event expressions except message correlation-key expressions and is not an edge case.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by marcosgvieira** [comment]
@korthout this seems to be an old issue from 2020 - can you help to understand if it's still valid?

**Comment by korthout** [comment]
The core concepts have not changed. I think the issue is still valid. 

Reading back my conversation with Philipp, I actually think that both of us made a mistake (due to me not understanding the issue well enough at the time):
- the reproducer clearly shows that we want task-scoped variables to be visible from the attached boundary event
- my clarification [here](https://github.com/camunda/camunda/issues/4799#issuecomment-1434666760) was to say the opposite: task-scoped variables are **not visible** from the attached boundary event
- and philipp agreed to it [here](https://github.com/camunda/camunda/issues/4799#issuecomment-1436689587)

But after thinking about it more, I've realized that the description is simply not clear.

We don't always evaluate expressions in the same way. For example, a timer boundary event's timer expression would be evaluated when we are activating the activity that the timer boundary event is attached to. That makes sense, because the activity is subscribing to the timer boundary event and so we want to access the activity's variables. 

But we also have the expressions of an output mapping, which are evaluated when we complete the boundary event (after triggering). These are evaluated at a different time, and from the boundary event's scope. And that makes sense as well, because the boundary event is now completing and so we want to access any of its variables.

Now, this bug is actually describing how timer event expressions and message event expressions are treated differently. We evaluate the message correlation key expression of a message boundary event in the scope of the element containing the attached element (e.g. the process instance itself, or a sub-process that contains them). You can see that defined in these lines:

https://github.com/camunda/camunda/blob/89fd3db77ece80b872cc0631f82f425fb4a8f0fc/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java#L290-L293

Why is that strange? Well it means that we can't resolve an incident on an activity with a message boundary event caused by a missing variable.

<img width="750" height="479" alt="Image" src="https://github.com/user-attachments/assets/8a277718-944f-4ec0-bed2-b410f827f17c" />

Example:
- I have a process instance where a task A was completed with some variables
- These are supposed to include a variable `foo` that is used in an input mapping to create the variable `bar`
- The variable `bar is used to specify a property of the boundary event, e.g. message correlation key `= bar`
- But on this particular process instance, the previous task was completed without this `foo` variable
- On activating the task B (the one with attached boundary event), foo does not exist so `bar` is created with the value `null` **and** an incident is raised because `bar` is null which is not an allowed value for correlation key
- To resolve the incident, we can set a variable at B, and retry

The alternative, that I initially proposed would not have allowed such a use case. The boundary event could only look at process-level variables.

@saig0 I'll adjust the Expected behavior again to clarify what we truly want

**Comment by korthout** [comment]
Note that fixing this bug, requires changing existing behavior. However, the chance that it breaks user space is very small.

It requires an input mapping that hides an existing variable at a higher scope that is used in the correlation key expression:
- `foo` exists at the process instance scope as `"x"`
- An input mapping creates a task-scoped variable `foo` with the value `"y"`
- The correlation key expression uses `foo`
- Previously it would subscribe to `"x"
- After the change it subscribes to `"y"`

I believe this is a highly uncommon case.

Still, we could argue, that we only roll this out in a new minor rather releasing it in patches. This would allow mentioning the breaking change in the update guide.

**Comment by marcosgvieira** [comment]
Thanks @korthout, with that plus the fact that this is open since 2020, do you think that severity/high and likelihood/high are the correct labels for this issue?

**Comment by korthout** [comment]
>do you think that severity/high and likelihood/high are the correct labels for this issue?

- Severity high makes sense because there's no workaround.
- Likelihood high makes sense because it always happens. However, if you consider likelihood as how many customers do we expect to encounter this, then I'd say low.

Please correct me if you disagree.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.

**Comment by koevskinikola** [comment]
## Implementation plan

The fix is gated behind a new engine feature flag, **`evaluateBoundaryEventCorrelationKeyInActivityScope`**, defaulting to **on**. It can be disabled (`zeebe.broker.experimental.features.evaluateBoundaryEventCorrelationKeyInActivityScope: false`) as a kill-switch to restore the previous behavior without a code change.

### Root cause

`evaluateCorrelationKey` is the only boundary-event subscription expression that evaluates against the **flow scope** instead of the **element instance** the event is attached to. Timer, message-name, and signal-name expressions all use the element instance.

https://github.com/camunda/camunda/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java#L298-L301

```java
final long scopeKey =
    event.getElementType() == BpmnElementType.BOUNDARY_EVENT
        ? context.getFlowScopeKey()
        : context.getElementInstanceKey();
```

This breaks two things:
1. **Variable resolution** — the correlation key can't see the activity's input-mapped variables.
2. **Incident placement** — `scopeKey` is also threaded into the `Failure`, so a failing correlation key raises the incident on the flow scope, which can't be resolved by setting a variable on the activity.

### The fix (flag-gated)

```java
final long scopeKey =
    (!evaluateBoundaryEventCorrelationKeyInActivityScope
            && event.getElementType() == BpmnElementType.BOUNDARY_EVENT)
        ? context.getFlowScopeKey()
        : context.getElementInstanceKey();
```

With the flag **on** (default) the correlation key resolves against the element instance — the same scope timer and message-name expressions already use. With the flag **off**, behavior is byte-for-byte the legacy behavior.

### Feature flag plumbing

- `FeatureFlags` (zeebe/util): new property `evaluateBoundaryEventCorrelationKeyInActivityScope`, default `true` (also `true` in `createDefaultForTests`). **Note:** this deviates from the documented default-false convention because the flag gates a bug fix we're confident in (kill-switch), not a gradual rollout.
- `FeatureFlagsCfg` (zeebe/broker): field + accessors + `toFeatureFlags()`, surfaced under `zeebe.broker.experimental.features.*`.
- Wiring: `EngineProcessors.createBehaviors` → `BpmnBehaviorsImpl` → `CatchEventBehavior` constructor (`featureFlags` is already in scope in `EngineProcessors`; both `BpmnBehaviorsImpl` and `CatchEventBehavior` have a single caller each).
- Config/unit tests: `FeatureFlagsTest`, `FeatureFlagsCfgTest`, `feature-flags-cfg.yaml`.
- The new 7th `FeatureFlags` constructor arg also requires updating the one direct caller: `PartitionManagerStepTest.java:220-221` (append a 7th boolean to both `new FeatureFlags(...)` calls), else `zeebe/broker` test sources won't compile.

### Behavioral change (breaking, low-risk, reversible)

With the flag on, the resolved value changes only when the correlation-key expression references a variable that is shadowed by an input mapping on the activity, or local to a sub-process / call activity the boundary is attached to. **Rollout: target the next minor, do not backport.** Add an update-guide note documenting the flag.

### Tests

Two existing tests in `zeebe/engine/.../bpmn/boundary/BoundaryEventTest.java` deliberately assert the **old** behavior and must be inverted (the engine test default has the flag on):

1. **`shouldUseScopeToExtractCorrelationKeys`** (lines 316-351) is purpose-built to lock in the bug. Rewrite to assert the opened subscription correlates on the activity-local value `"2"`:

```java
@Test
public void shouldEvaluateCorrelationKeyInActivityScope() {
  // given
  final String processId = "boundaryCorrelationScope";
  final BpmnModelInstance process =
      Bpmn.createExecutableProcess(processId)
          .startEvent()
          .serviceTask("task", c -> c.zeebeJobType("type").zeebeInputExpression("bar", "foo"))
          .boundaryEvent(
              "event", b -> b.message(m -> m.zeebeCorrelationKeyExpression("foo").name("message")))
          .endEvent()
          .moveToActivity("task")
          .endEvent()
          .done();
  ENGINE.deployment().withXmlResource(process).deploy();

  // when
  final long processInstanceKey =
      ENGINE.processInstance().ofBpmnProcessId(processId)
          .withVariables("{'foo':1,'bar':2}").create();

  // then -- input mapping creates foo=2 in the task scope; before the fix this was foo=1
  final Record<MessageSubscriptionRecordValue> subscription =
      RecordingExporter.messageSubscriptionRecords(MessageSubscriptionIntent.CREATED)
          .withProcessInstanceKey(processInstanceKey)
          .getFirst();
  assertThat(subscription.getValue().getCorrelationKey()).isEqualTo("2");
}
```

2. **`shouldHaveScopeKeyIfBoundaryEvent`** (lines 353-392): change `.hasVariableScopeKey(processInstanceKey)` (line 391) to `.hasVariableScopeKey(failureEvent.getKey())`.

3. **Sub-process coverage** — a boundary on an embedded sub-process, with a sub-process-scoped variable shadowing a process-level one, asserting the correlation key resolves to the sub-process value.

4. **Flag-off legacy test** (new class) — start an `EngineRule` with `.withFeatureFlags(ff -> ff.setEvaluateBoundaryEventCorrelationKeyInActivityScope(false))` and assert the legacy flow-scope behavior (correlation key `"1"`, incident `variableScopeKey == processInstanceKey`) is preserved.

### Verified facts (no need to re-investigate)

- **Processing-path only.** `subscribeToEvents` is called exclusively from processors/behaviors; no `*Applier` references `CatchEventBehavior`. The correlation key is written into the subscription record, so replay replays the recorded value — no re-evaluation. **No event-applier version change and no `NoChangesTest` golden-file change required.**
- **Feature-flag determinism.** The flag is read at engine construction; the value it influences is recorded, not recomputed on replay. Toggling cannot corrupt existing subscriptions or cause leader/follower divergence. All brokers in a cluster must use the same value; changing it requires a restart.
- **Migration is unaffected** — `ProcessInstanceMigrationCatchEventBehavior` re-uses the existing correlation-key buffer rather than re-evaluating.
- **Ordering is safe.** Input mappings are applied (writing to the element-instance scope) before subscriptions are opened.
- A missing correlation variable yields `ErrorType.EXTRACT_VALUE_ERROR` → incident (event), not an exception. Pre-fix the incident's `variableScopeKey` is the PI, flag-on it is the activity.
- `MessageCatchElementTest` does **not** regress (boundary processes use no input mapping; correlation variable is at PI scope and resolves identically either way).

### Acceptance criteria

- [ ] `evaluateBoundaryEventCorrelationKeyInActivityScope` flag added to `FeatureFlags` (default `true`) and `FeatureFlagsCfg`, with unit + config tests.
- [ ] `CatchEventBehavior.evaluateCorrelationKey` uses the element-instance scope when the flag is on, flow scope when off; flag threaded via `EngineProcessors` → `BpmnBehaviorsImpl`.
- [ ] `BoundaryEventTest` tests inverted to assert activity-scope behavior, plus a sub-process case.
- [ ] New flag-off test preserves the legacy flow-scope behavior.
- [ ] `BoundaryEventTest`, `BoundaryEventLegacyCorrelationKeyScopeTest`, `MessageCatchElementTest`, `MessageCorrelationTest`, `CorrelateMessageTest`, `EventSubscriptionIncidentTest`, `FeatureFlagsTest`, `FeatureFlagsCfgTest` all pass.
- [ ] Update-guide note added (next-minor breaking change; documents the flag).
- [ ] No `backport stable/*` labels — minor only.

### Local verification

```bash
./mvnw verify -pl zeebe/util   -Dtest=FeatureFlagsTest    -DskipTests=false -DskipITs -Dquickly -T1C
./mvnw verify -pl zeebe/broker -Dtest=FeatureFlagsCfgTest -DskipTests=false -DskipITs -Dquickly -T1C
./mvnw verify -pl zeebe/engine \
  -Dtest='BoundaryEventTest,BoundaryEventLegacyCorrelationKeyScopeTest,MessageCatchElementTest,EventSubscriptionIncidentTest' \
  -DskipTests=false -DskipITs -Dquickly -T1C
./mvnw install -Dquickly -T1C   # repo still compiles (cross-module constructor changes)
```
